# DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
# Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
"""String catalogue and locale resolution for generated reports.

Every word a generated report put in front of a reader used to be an English
literal: the section headings, the field labels, the metadata line, the
"no data" notice, the AI-narrative caution, ``Yes`` / ``No``, and the
``<html lang="en">`` attribute. The module carried a locale-aware toolkit
(:mod:`app.modules.reporting.intl`) but nothing on the render or export path
called it, so a reader who set the interface to German still downloaded an
English PDF. This file is the catalogue those two paths now read.

* **Self-contained per-package bundle**, the same shape
  :mod:`app.modules.daily_diary.pdf_translations` and
  :mod:`app.modules.einvoice.pdf_translations` use: the strings live next to
  the code that renders them and no global catalogue is touched.
* **Shared resolution**, from :mod:`app.core.document_locale`: an explicit
  ``?locale=`` query parameter wins, otherwise the first ``Accept-Language``
  tag whose primary subtag this table has, otherwise English. The
  middleware's context locale is deliberately not reused, so a report's
  language depends only on what this table can actually render.
* **English is byte-for-byte what the module shipped before.** Every English
  value here is the literal it replaced, including the two that read wrong
  (``Open Rfis``, ``Cpi``): fixing those is a change to the English document
  and belongs in its own commit, not hidden inside a localization one.

Because this table is narrower than the interface's locale list, a reader can
ask for a language it does not hold. The routes serving a report therefore
declare the language they actually rendered in ``Content-Language`` - see
:mod:`app.core.document_locale`.

Adding a language is adding a column to the three tables below and a code to
:data:`SUPPORTED_REPORT_LOCALES`; no call site changes.
"""

from __future__ import annotations

from typing import Any

from app.core.document_locale import (
    normalize_document_locale,
    resolve_document_locale,
    translate,
)

__all__ = [
    "DEFAULT_REPORT_LOCALE",
    "SUPPORTED_REPORT_LOCALES",
    "field_label",
    "normalize_report_locale",
    "resolve_report_locale",
    "section_title",
    "tr",
]

DEFAULT_REPORT_LOCALE = "en"

#: Languages a generated report can be rendered in. The same three
#: :mod:`app.modules.reporting.intl` already declares, so the module answers
#: with one voice about what it can write.
SUPPORTED_REPORT_LOCALES: tuple[str, ...] = ("en", "de", "ru")

# ── Report chrome ─────────────────────────────────────────────────────────
#
# Everything the renderer and the exporters emit that is not a section title
# or a field label: the header metadata line, the table column headers, the
# empty-snapshot notice, the footer, the AI-narrative block.

_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "meta_report": "Report",
        "meta_project": "Project",
        "meta_type": "Type",
        "meta_generated": "Generated",
        "meta_currency": "Currency",
        "field_column": "Field",
        "value_column": "Value",
        "yes": "Yes",
        "no": "No",
        "no_data_heading": "No data available",
        # ``no_data_body`` and ``no_data_body_short`` say the same thing and
        # differ only by the parenthetical list of source modules. That is
        # deliberate and matches the pre-catalogue wording: the HTML page had
        # room for the examples and the PDF paragraph did not. Keep the two in
        # step when either is reworded, or the same report explains itself
        # differently depending on which format the reader opened.
        "no_data_body": (
            "This report was generated with an empty data snapshot. "
            "Verify that the source modules (finance, schedule, safety, etc.) "
            "returned data for the selected project."
        ),
        "no_data_body_short": (
            "This report was generated with an empty data snapshot. "
            "Verify that the source modules returned data for the selected project."
        ),
        "footer_generated_by": "Generated by OpenConstructionERP at {timestamp}.",
        "worksheet_name": "Report",
        "pdf_subject": "Project Report",
        "overall_progress": "Overall Progress",
        "as_of": "As Of",
        "recorded_by": "Recorded By",
        "period": "Period",
        "entries_suffix": "({count} entries)",
        "site_photo_alt": "Site photo",
        "ai_summary_heading": "Summary",
        "ai_badge": "AI-generated",
        "ai_note": "Generated by AI from the project data below.",
        "ai_note_confidence": "Generated by AI from the project data below (confidence {confidence}).",
        "ai_note_review": "Review before sharing with the client.",
    },
    "de": {
        "meta_report": "Bericht",
        "meta_project": "Projekt",
        "meta_type": "Typ",
        "meta_generated": "Erstellt",
        "meta_currency": "Währung",
        "field_column": "Feld",
        "value_column": "Wert",
        "yes": "Ja",
        "no": "Nein",
        "no_data_heading": "Keine Daten verfügbar",
        "no_data_body": (
            "Dieser Bericht wurde mit einem leeren Daten-Snapshot erstellt. "
            "Prüfen Sie, ob die Quellmodule (Finanzen, Terminplanung, "
            "Arbeitssicherheit usw.) Daten für das gewählte Projekt geliefert haben."
        ),
        "no_data_body_short": (
            "Dieser Bericht wurde mit einem leeren Daten-Snapshot erstellt. "
            "Prüfen Sie, ob die Quellmodule Daten für das gewählte Projekt geliefert haben."
        ),
        "footer_generated_by": "Erstellt von OpenConstructionERP am {timestamp}.",
        "worksheet_name": "Bericht",
        "pdf_subject": "Projektbericht",
        "overall_progress": "Gesamtfortschritt",
        "as_of": "Stand",
        "recorded_by": "Erfasst von",
        "period": "Zeitraum",
        "entries_suffix": "({count} Einträge)",
        "site_photo_alt": "Baustellenfoto",
        "ai_summary_heading": "Zusammenfassung",
        "ai_badge": "KI-generiert",
        "ai_note": "Von der KI aus den unten stehenden Projektdaten erstellt.",
        "ai_note_confidence": ("Von der KI aus den unten stehenden Projektdaten erstellt (Konfidenz {confidence})."),
        "ai_note_review": "Vor der Weitergabe an den Auftraggeber prüfen.",
    },
    "ru": {
        "meta_report": "Отчет",
        "meta_project": "Проект",
        "meta_type": "Тип",
        "meta_generated": "Создан",
        "meta_currency": "Валюта",
        "field_column": "Поле",
        "value_column": "Значение",
        "yes": "Да",
        "no": "Нет",
        "no_data_heading": "Нет данных",
        "no_data_body": (
            "Отчет сформирован на пустом снимке данных. Проверьте, вернули ли "
            "исходные модули (финансы, календарный план, охрана труда и т. д.) "
            "данные по выбранному проекту."
        ),
        "no_data_body_short": (
            "Отчет сформирован на пустом снимке данных. Проверьте, вернули ли "
            "исходные модули данные по выбранному проекту."
        ),
        "footer_generated_by": "Сформировано в OpenConstructionERP {timestamp}.",
        "worksheet_name": "Отчет",
        "pdf_subject": "Отчет по проекту",
        "overall_progress": "Общий прогресс",
        "as_of": "На дату",
        "recorded_by": "Кто внес",
        "period": "Период",
        "entries_suffix": "(записей: {count})",
        "site_photo_alt": "Фото со стройплощадки",
        "ai_summary_heading": "Сводка",
        "ai_badge": "Сформировано ИИ",
        "ai_note": "Сформировано ИИ по приведенным ниже данным проекта.",
        "ai_note_confidence": ("Сформировано ИИ по приведенным ниже данным проекта (достоверность {confidence})."),
        "ai_note_review": "Проверьте перед отправкой заказчику.",
    },
}

# ── Section titles ────────────────────────────────────────────────────────
#
# Keyed by the English title rather than by the section id, because the id
# alone does not determine the heading: ``kpi`` is "Key Performance
# Indicators" in a project-status report and "Safety KPIs" in a safety one,
# and ``risk`` is "Risk Summary" in one and "Top Risks" in another.
#
# The English string is also the only thing available at render time for a
# report bound to a template, because ``SYSTEM_TEMPLATES`` seeds these exact
# headings into ``ReportTemplate.template_data`` as rows in the database.
# Looking them up by their own text localizes the seeded templates and the
# renderer's built-in defaults through one table, and it is what makes
# :func:`section_title` leave a user's own heading alone: a title that is not
# one of ours is not in this table and renders verbatim.

_SECTION_TITLES: dict[str, dict[str, str]] = {
    "en": {},  # Filled below: the key is the English string.
    "de": {
        "Project Overview": "Projektübersicht",
        "Key Performance Indicators": "Wesentliche Leistungskennzahlen",
        "Schedule Status": "Terminplanstatus",
        "Risk Summary": "Risikoübersicht",
        "Open Issues": "Offene Punkte",
        "Cost Summary": "Kostenübersicht",
        "Cost Breakdown": "Kostenaufschlüsselung",
        "Change Orders": "Nachträge",
        "Cash Flow": "Zahlungsfluss",
        "Schedule Overview": "Terminplanübersicht",
        "Milestone Status": "Meilensteinstatus",
        "Critical Path": "Kritischer Pfad",
        "3-Week Lookahead": "3-Wochen-Vorschau",
        "Safety KPIs": "Arbeitssicherheits-KPIs",
        "Incident Log": "Unfallprotokoll",
        "Near-Miss Reports": "Beinaheunfall-Meldungen",
        "Safety Training": "Sicherheitsunterweisungen",
        "Inspection Summary": "Prüfübersicht",
        "By Inspection Type": "Nach Prüfart",
        "Punch List Status": "Status der Mängelliste",
        "Recent Inspections": "Letzte Prüfungen",
        "Portfolio Overview": "Portfolioübersicht",
        "Project Statuses": "Projektstatus",
        "KPI Comparison": "KPI-Vergleich",
        "Portfolio Risks": "Portfoliorisiken",
        "Field Progress": "Baufortschritt",
        "Top Risks": "Wesentliche Risiken",
        "Site Photos": "Baustellenfotos",
        "Summary": "Zusammenfassung",
    },
    "ru": {
        "Project Overview": "Обзор проекта",
        "Key Performance Indicators": "Ключевые показатели",
        "Schedule Status": "Статус календарного плана",
        "Risk Summary": "Сводка по рискам",
        "Open Issues": "Открытые вопросы",
        "Cost Summary": "Сводка затрат",
        "Cost Breakdown": "Разбивка затрат",
        "Change Orders": "Изменения к договору",
        "Cash Flow": "Движение денежных средств",
        "Schedule Overview": "Обзор календарного плана",
        "Milestone Status": "Статус вех",
        "Critical Path": "Критический путь",
        "3-Week Lookahead": "План на три недели",
        "Safety KPIs": "Показатели охраны труда",
        "Incident Log": "Журнал происшествий",
        "Near-Miss Reports": "Сообщения о предпосылках к происшествиям",
        "Safety Training": "Обучение по охране труда",
        "Inspection Summary": "Сводка по проверкам",
        "By Inspection Type": "По типам проверок",
        "Punch List Status": "Статус списка недоделок",
        "Recent Inspections": "Последние проверки",
        "Portfolio Overview": "Обзор портфеля",
        "Project Statuses": "Статусы проектов",
        "KPI Comparison": "Сравнение KPI",
        "Portfolio Risks": "Риски портфеля",
        "Field Progress": "Ход работ на объекте",
        "Top Risks": "Основные риски",
        "Site Photos": "Фотографии с объекта",
        "Summary": "Сводка",
    },
}

# The English table is the identity map over the keys the translated tables
# hold, so a lookup in any locale answers from the same key set and English
# can never drift away from the strings the other languages were written
# against.
_SECTION_TITLES["en"] = {title: title for title in _SECTION_TITLES["de"]}

# ── Field labels ──────────────────────────────────────────────────────────
#
# Keyed by the snapshot key, which is a stable token the service layer emits
# rather than prose. Only the keys ``ReportingService._build_default_snapshot``
# produces are listed: a caller-supplied snapshot may carry any keys at all,
# and those keep falling through to the Title-Cased fallback the renderer and
# the exporters already used.
#
# The English column reproduces that fallback exactly, ``Open Rfis`` and
# ``Cpi`` included. They read wrong, and correcting them changes the English
# document, which is a separate change from being able to write a German one.

_FIELD_LABELS: dict[str, dict[str, str]] = {
    "en": {
        "name": "Name",
        "status": "Status",
        "phase": "Phase",
        "planned_start": "Planned Start",
        "planned_end": "Planned End",
        "schedule_progress_pct": "Schedule Progress Pct",
        "cpi": "Cpi",
        "spi": "Spi",
        "budget_consumed_pct": "Budget Consumed Pct",
        "as_of": "As Of",
        "progress_pct": "Progress Pct",
        "risk_score_avg": "Risk Score Avg",
        "open_rfis": "Open Rfis",
        "open_submittals": "Open Submittals",
        "open_defects": "Open Defects",
        "open_observations": "Open Observations",
        "budget": "Budget",
        "committed": "Committed",
        "actual": "Actual",
        "payable": "Payable",
        "receivable": "Receivable",
        "net_cash_flow": "Net Cash Flow",
    },
    "de": {
        "name": "Name",
        "status": "Status",
        "phase": "Phase",
        "planned_start": "Geplanter Beginn",
        "planned_end": "Geplantes Ende",
        "schedule_progress_pct": "Terminfortschritt (%)",
        "cpi": "CPI",
        "spi": "SPI",
        "budget_consumed_pct": "Budgetverbrauch (%)",
        "as_of": "Stand",
        "progress_pct": "Fortschritt (%)",
        "risk_score_avg": "Durchschnittlicher Risikowert",
        "open_rfis": "Offene RFIs",
        "open_submittals": "Offene Freigaben",
        "open_defects": "Offene Mängel",
        "open_observations": "Offene Beobachtungen",
        "budget": "Budget",
        "committed": "Gebunden",
        "actual": "Ist",
        "payable": "Verbindlichkeiten",
        "receivable": "Forderungen",
        "net_cash_flow": "Netto-Zahlungsfluss",
    },
    "ru": {
        "name": "Наименование",
        "status": "Статус",
        "phase": "Фаза",
        "planned_start": "Плановое начало",
        "planned_end": "Плановое окончание",
        "schedule_progress_pct": "Выполнение плана, %",
        "cpi": "CPI",
        "spi": "SPI",
        "budget_consumed_pct": "Освоение бюджета, %",
        "as_of": "На дату",
        "progress_pct": "Выполнение, %",
        "risk_score_avg": "Средний балл риска",
        "open_rfis": "Открытые запросы (RFI)",
        "open_submittals": "Открытые согласования",
        "open_defects": "Открытые дефекты",
        "open_observations": "Открытые замечания",
        "budget": "Бюджет",
        "committed": "Законтрактовано",
        "actual": "Факт",
        "payable": "Кредиторская задолженность",
        "receivable": "Дебиторская задолженность",
        "net_cash_flow": "Чистый денежный поток",
    },
}


# ── Locale resolution ─────────────────────────────────────────────────────


def normalize_report_locale(value: str | None) -> str:
    """Reduce a locale-ish value to a language this catalogue can render.

    Args:
        value: A locale code such as ``"de"``, ``"de-DE"`` or ``"DE"``.

    Returns:
        A member of :data:`SUPPORTED_REPORT_LOCALES`.
    """
    return normalize_document_locale(value, SUPPORTED_REPORT_LOCALES, DEFAULT_REPORT_LOCALE)


def resolve_report_locale(locale_param: str | None, accept_language: str | None) -> str:
    """Pick the language of a report for one HTTP request.

    Args:
        locale_param: Explicit ``?locale=`` query value, if any.
        accept_language: Raw ``Accept-Language`` header value, if any.

    Returns:
        A member of :data:`SUPPORTED_REPORT_LOCALES`. When it is
        :data:`DEFAULT_REPORT_LOCALE` but the caller asked for something
        else, the document is a fallback and the route must say so in
        ``Content-Language``.
    """
    return resolve_document_locale(
        locale_param,
        accept_language,
        SUPPORTED_REPORT_LOCALES,
        DEFAULT_REPORT_LOCALE,
    )


# ── Lookups ───────────────────────────────────────────────────────────────


def tr(locale: str, key: str, **params: Any) -> str:
    """Resolve a report-chrome string, falling back to English then the key.

    Args:
        locale: A member of :data:`SUPPORTED_REPORT_LOCALES`; anything else
            reads the English table.
        key: Catalogue key, e.g. ``"no_data_heading"``.
        **params: ``str.format`` interpolation values.

    Returns:
        The resolved, formatted string.
    """
    return translate(_STRINGS, locale, key, DEFAULT_REPORT_LOCALE, **params)


def section_title(title: str, locale: str) -> str:
    """Localize a section heading, leaving a caller's own heading untouched.

    *title* is looked up as itself. The platform's own headings - the
    renderer's ``_DEFAULT_SECTIONS`` and the ``SYSTEM_TEMPLATES`` rows seeded
    into the database - are in the table and come back translated. A heading
    a user wrote into their own template is not, and comes back unchanged,
    which is the point: translating it would mean overwriting their text with
    ours whenever it happened to collide.

    Args:
        title: The section heading as the template or the default list holds it.
        locale: A member of :data:`SUPPORTED_REPORT_LOCALES`.

    Returns:
        The localized heading, or *title* verbatim when it is not ours.
    """
    table = _SECTION_TITLES.get(locale) or _SECTION_TITLES[DEFAULT_REPORT_LOCALE]
    return table.get(title) or _SECTION_TITLES[DEFAULT_REPORT_LOCALE].get(title) or title


def field_label(key: Any, locale: str) -> str:
    """Localize a snapshot key into a row label.

    Falls back to the Title-Cased key the renderer and the exporters used
    before this catalogue existed, so a caller-supplied snapshot carrying
    keys the platform never emits still labels its rows readably.

    Args:
        key: A snapshot key, e.g. ``"net_cash_flow"``.
        locale: A member of :data:`SUPPORTED_REPORT_LOCALES`.

    Returns:
        The localized label, or the Title-Cased key.
    """
    text = str(key)
    table = _FIELD_LABELS.get(locale) or _FIELD_LABELS[DEFAULT_REPORT_LOCALE]
    return table.get(text) or _FIELD_LABELS[DEFAULT_REPORT_LOCALE].get(text) or text.replace("_", " ").title()
