# DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
# Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
"""Render a validated :class:`~app.modules.module_builder.spec.ModuleSpec` into files.

Deterministic and total: the same spec renders the same bytes, and a spec that
validated always renders. No assistant is involved at this layer, which is why
what lands on a user's server is reviewable in the ordinary way.

What is rendered is a real module by the platform's own conventions -
manifest, models, schemas, repository, service, router, permissions,
validators, locales and tests - so the loader, the permission registry and the
validation engine pick it up with no special case for having been generated.

The user interface is deliberately not a React page. The frontend is a
compiled bundle, so a module installed at runtime cannot add a compiled screen
without a rebuild, and pretending otherwise would ship half a module. Instead
every generated module serves its own spec at ``<url_prefix>/ui-spec`` and the
core frontend renders list, detail and form from it. One generic screen that is
always in step beats a generated one that cannot be installed.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from app.modules.module_builder.spec import FieldSpec, ModuleSpec

HEADER = """\
# DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
# Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
"""

# Marks a file as machine-written, so a person reading it in a diff knows where
# it came from and that editing it by hand is a decision rather than an
# accident. Deliberately not a timestamp: a regenerated file that differs only
# by the second it was written would show up as a change in every review.
GENERATED_NOTE = (
    "# Generated by the OpenConstructionERP module builder from a module\n"
    "# specification. Edits are kept: the builder never overwrites a module it\n"
    "# did not just create. To change the shape, change the spec and generate\n"
    "# a new version.\n"
)

# SQLAlchemy column type per field type, and the Python annotation that goes
# with it. Money is Numeric, never float: a rate that loses cents is a defect
# the user finds in an invoice.
COLUMN_TYPES: dict[str, tuple[str, str]] = {
    "text": ("String(255)", "str"),
    "long_text": ("Text", "str"),
    "integer": ("Integer", "int"),
    "number": ("MoneyType(18, 4)", "Decimal"),
    "money": ("MoneyType(18, 2)", "Decimal"),
    "date": ("Date", "date"),
    "datetime": ("DateTime(timezone=True)", "datetime"),
    "boolean": ("Boolean", "bool"),
    "select": ("String(64)", "str"),
}

# Where each column type is imported from. Computed rather than emitted as a
# fixed block: a spec with no dates and no numbers would otherwise render
# imports nothing uses, and ruff refuses the module the builder just wrote.
_SQLALCHEMY_NAMES = {"String", "Text", "Integer", "Date", "DateTime", "Boolean"}


@dataclass(frozen=True)
class GeneratedFile:
    """One rendered file, relative to the module directory."""

    path: str
    content: str

    @property
    def lines(self) -> int:
        return self.content.count("\n")


def render(spec: ModuleSpec) -> list[GeneratedFile]:
    """Render the whole module. Order is stable so diffs are readable."""
    return [
        GeneratedFile("__init__.py", _init(spec)),
        GeneratedFile("manifest.py", _manifest(spec)),
        GeneratedFile("spec.json", _spec_json(spec)),
        GeneratedFile("models.py", _models(spec)),
        GeneratedFile("schema.py", _schema(spec)),
        GeneratedFile("schemas.py", _schemas(spec)),
        GeneratedFile("validators.py", _validators(spec)),
        GeneratedFile("permissions.py", _permissions(spec)),
        GeneratedFile("repository.py", _repository(spec)),
        GeneratedFile("service.py", _service(spec)),
        GeneratedFile("router.py", _router(spec)),
        GeneratedFile("locales/en.json", _locale(spec)),
        GeneratedFile("tests/__init__.py", ""),
        GeneratedFile("tests/conftest.py", _tests_conftest()),
        GeneratedFile(f"tests/test_{spec.key}.py", _tests(spec)),
        GeneratedFile("README.md", _readme(spec)),
    ]


def write(spec: ModuleSpec, root: Path) -> list[Path]:
    """Render and write into ``root/<key>/``. Refuses to overwrite.

    A module directory that already exists is never written into. Overwriting
    is how a user loses the edits they made to a generated module, and the
    builder has no way to tell its own output from work done since.
    """
    target = root / spec.key
    if target.exists():
        raise FileExistsError(
            f"{target} already exists. Uninstall the module or choose another key; "
            "the builder does not overwrite a directory it did not just create."
        )
    written: list[Path] = []
    try:
        for item in render(spec):
            path = target / item.path
            path.parent.mkdir(parents=True, exist_ok=True)
            # newline="\n" on purpose. The default translates to CRLF on
            # Windows, and a module generated on one operating system would
            # then differ byte for byte from the same spec generated on
            # another - which turns every cross-platform diff into noise.
            path.write_text(item.content, encoding="utf-8", newline="\n")
            written.append(path)
    except Exception:
        # A half-written module is worse than none: the loader would import
        # what landed and fail somewhere unrelated to the cause.
        import shutil

        shutil.rmtree(target, ignore_errors=True)
        raise
    return written


# ── renderers ───────────────────────────────────────────────────────────────


def _init(spec: ModuleSpec) -> str:
    """The package, and the startup hook the loader calls after importing it.

    Two things have to happen once the module is loaded and neither can happen
    at import time. Permissions must be registered, because a permission the
    registry has never heard of is denied to everyone except an administrator,
    and the module would then appear to work for whoever tested it and for
    nobody else. And the table has to exist, because a module installed at
    runtime has no migration to create it.
    """
    return f'''{HEADER}"""{spec.display_name}.

{spec.description or "Generated by the OpenConstructionERP module builder."}

Generated from a module specification. ``spec.json`` beside this file is the
description the code came from, and is what the interface renders the module's
screens out of.
"""

import logging

logger = logging.getLogger(__name__)


async def on_startup() -> None:
    """Register permissions and make sure the module's table is there.

    Called by the module loader once the package has been imported.
    """
    from app.database import engine
    from app.modules.{spec.key}.permissions import register_{spec.key}_permissions
    from app.modules.{spec.key}.schema import ensure_table

    register_{spec.key}_permissions()

    # A module installed at runtime lives outside the repository and therefore
    # outside Alembic, so nothing else will ever create this table. Checked
    # first, so this is a no-op on every start after the first.
    await ensure_table(engine)
    logger.info("{spec.module_name}: table %s is present", {spec.table_name!r})
'''


def _manifest(spec: ModuleSpec) -> str:
    return f'''{HEADER}"""{spec.display_name} module manifest."""

{GENERATED_NOTE}
from app.core.module_loader import ModuleManifest

manifest = ModuleManifest(
    name={spec.module_name!r},
    version={spec.version!r},
    display_name={spec.display_name!r},
    description={spec.description!r},
    author={(spec.author or "Built with the OpenConstructionERP module builder")!r},
    category={spec.category!r},
    depends={["oe_projects"] if spec.entity.project_scoped else []!r},
    auto_install=False,
    enabled=True,
)
'''


def _spec_json(spec: ModuleSpec) -> str:
    """The spec, kept beside the code that came from it.

    This is what the generic frontend renders from and what a later version of
    the builder reads to regenerate. Without it the module is only readable as
    Python, and the screen would have to be inferred from the ORM.
    """
    payload = spec.model_dump(mode="json")
    payload["generated_at"] = datetime.now(UTC).isoformat()
    payload["generator"] = "openconstructionerp.module_builder/1"
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _models(spec: ModuleSpec) -> str:
    entity = spec.entity
    columns = {COLUMN_TYPES[f.type][0].split("(")[0] for f in entity.fields}
    annotations = {COLUMN_TYPES[f.type][1] for f in entity.fields}

    # Always present: the row carries created_at and updated_at whatever the
    # spec says, and both of those need DateTime, func and datetime.
    sqlalchemy_names = {"DateTime", "Index", "func"} | (columns & _SQLALCHEMY_NAMES)
    if entity.project_scoped:
        sqlalchemy_names.add("ForeignKey")
    stdlib_datetime = {"datetime"} | (annotations & {"date"})

    lines = [
        HEADER,
        f'"""{spec.display_name} ORM model.\n\nTable:\n    {spec.table_name}\n"""\n',
        GENERATED_NOTE,
        "import uuid",
        f"from datetime import {', '.join(sorted(stdlib_datetime))}",
    ]
    if "Decimal" in annotations:
        lines.append("from decimal import Decimal")
    lines += [
        "",
        f"from sqlalchemy import {', '.join(sorted(sqlalchemy_names))}",
        "from sqlalchemy.orm import Mapped, mapped_column",
        "",
    ]
    if "MoneyType" in columns:
        # The house decimal column. Plain Numeric hands back a float on some
        # backends, and a rate that arrives as 1450.7499999 is a defect the
        # user finds in an invoice rather than in a test.
        lines.append("from app.core.db_types import MoneyType")
    lines += [
        "from app.database import GUID, Base",
        "",
        "",
        f"class {spec.class_name}(Base):",
        f'    """{entity.display_name}."""',
        "",
        f"    __tablename__ = {spec.table_name!r}",
        "",
        "    id: Mapped[uuid.UUID] = mapped_column(GUID(), primary_key=True, default=uuid.uuid4)",
    ]
    if entity.project_scoped:
        lines.append(
            "    project_id: Mapped[uuid.UUID] = mapped_column(\n"
            '        GUID(), ForeignKey("oe_projects_project.id", ondelete="CASCADE"), nullable=False\n'
            "    )"
        )
    for field in entity.fields:
        column, annotation = COLUMN_TYPES[field.type]
        optional = "" if field.required else " | None"
        default = "" if field.required else ", default=None"
        lines.append(
            f"    {field.name}: Mapped[{annotation}{optional}] = mapped_column("
            f"{column}, nullable={not field.required}{default})"
        )
    lines += [
        "    created_at: Mapped[datetime] = mapped_column(",
        "        DateTime(timezone=True), server_default=func.now(), nullable=False",
        "    )",
        "    updated_at: Mapped[datetime] = mapped_column(",
        "        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False",
        "    )",
        "",
        "    __table_args__ = (",
    ]
    if entity.project_scoped:
        lines.append(f'        Index("ix_{spec.table_name}_project", "project_id"),')
    lines += [
        f'        Index("ix_{spec.table_name}_created", "created_at"),',
        "    )",
        "",
    ]
    return "\n".join(lines)


def _schema(spec: ModuleSpec) -> str:
    """The module creates its own table.

    A module installed at runtime lives outside the repository, so it cannot
    carry an Alembic revision: a revision file in the instance's data directory
    is either invisible to ``alembic upgrade`` or, once it is made visible,
    collides with the repository's own head on the next platform upgrade. Both
    failures land on the user, and the second one lands on every user at once.

    So the table is created from the same model the code reads, scoped to that
    one table and checked first. That is idempotent across restarts and across
    reinstalls, and it touches nothing the platform owns.
    """
    return f'''{HEADER}"""Physical table for {spec.display_name}.

Table:
    {spec.table_name}

A generated module is installed outside the repository and therefore outside
Alembic's history, so it creates its own table rather than carrying a revision
that would collide with the platform's head on the next upgrade. Creation is
scoped to this one table and checked first, which makes it safe to call on
every start.

The scoping goes through ``Table.create`` and ``Table.drop`` rather than
``MetaData.create_all(tables=[...])``. The ``tables`` argument filters tables
and nothing else: standalone sequences declared anywhere on the shared
metadata are still visited, so dropping this module's table that way would
take a sequence belonging to another module with it.
"""

{GENERATED_NOTE}
from typing import Any

from sqlalchemy import Table

from app.modules.{spec.key}.models import {spec.class_name}


def table() -> Table:
    """The one table this module owns."""
    return {spec.class_name}.__table__


def create_table(bind: Any) -> None:
    """Create the table on a synchronous connection or engine, if absent."""
    table().create(bind, checkfirst=True)


def drop_table(bind: Any) -> None:
    """Drop the table on a synchronous connection or engine, if present.

    Only the uninstall path calls this, and only when the operator asked for
    the data to go too. Uninstalling a module leaves its rows alone by default.
    """
    table().drop(bind, checkfirst=True)


async def ensure_table(engine: Any) -> None:
    """Create the table through an async engine. Safe to call repeatedly."""
    async with engine.begin() as connection:
        await connection.run_sync(create_table)


async def remove_table(engine: Any) -> None:
    """Drop the table through an async engine. Destroys the module's data."""
    async with engine.begin() as connection:
        await connection.run_sync(drop_table)
'''


def _pydantic_type(field: FieldSpec) -> str:
    _, annotation = COLUMN_TYPES[field.type]
    return annotation if field.required else f"{annotation} | None"


def _schemas(spec: ModuleSpec) -> str:
    entity = spec.entity
    create_fields = []
    read_fields = []
    update_fields = []
    for field in entity.fields:
        annotation = _pydantic_type(field)
        default = "" if field.required else " = None"
        create_fields.append(f"    {field.name}: {annotation}{default}")
        read_fields.append(f"    {field.name}: {annotation}")
        _, base = COLUMN_TYPES[field.type]
        update_fields.append(f"    {field.name}: {base} | None = None")

    project_create = "    project_id: uuid.UUID\n" if entity.project_scoped else ""
    project_read = "    project_id: uuid.UUID\n" if entity.project_scoped else ""

    return f'''{HEADER}"""{spec.display_name} request and response schemas."""

{GENERATED_NOTE}
import uuid
from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401

from pydantic import BaseModel, ConfigDict


class {spec.class_name}Create(BaseModel):
    """Payload for creating one {entity.display_name.lower()}."""

    model_config = ConfigDict(extra="forbid")

{project_create}{chr(10).join(create_fields)}


class {spec.class_name}Update(BaseModel):
    """Partial update. Every field is optional; absent means unchanged."""

    model_config = ConfigDict(extra="forbid")

{chr(10).join(update_fields)}


class {spec.class_name}Read(BaseModel):
    """One {entity.display_name.lower()} as the API returns it."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
{project_read}{chr(10).join(read_fields)}
    created_at: datetime
    updated_at: datetime


class {spec.class_name}List(BaseModel):
    """A page of {entity.plural_name.lower()}."""

    items: list[{spec.class_name}Read]
    total: int
'''


def _validators(spec: ModuleSpec) -> str:
    checks = []
    for rule in spec.rules:
        field = rule.field
        if rule.kind == "required":
            condition = f"value.{field} is None or (isinstance(value.{field}, str) and not value.{field}.strip())"
        elif rule.kind == "positive":
            condition = f"value.{field} is not None and value.{field} <= 0"
        elif rule.kind == "not_future":
            condition = f"value.{field} is not None and _is_future(value.{field})"
        elif rule.kind == "range":
            parts = []
            if rule.min_value is not None:
                parts.append(f"value.{field} < {rule.min_value}")
            if rule.max_value is not None:
                parts.append(f"value.{field} > {rule.max_value}")
            condition = f"value.{field} is not None and ({' or '.join(parts)})"
        elif rule.kind == "one_of":
            options = [f.options for f in spec.entity.fields if f.name == field][0]
            condition = f"value.{field} is not None and value.{field} not in {options!r}"
        else:  # order
            condition = (
                f"value.{field} is not None and value.{rule.other_field} is not None "
                f"and value.{field} > value.{rule.other_field}"
            )
        checks.append(
            f"    if {condition}:\n"
            f"        findings.append(\n"
            f"            Finding(\n"
            f"                code={rule.code!r},\n"
            f"                message={rule.message!r},\n"
            f"                field={field!r},\n"
            f"                severity={rule.severity!r},\n"
            f"            )\n"
            f"        )"
        )

    return f'''{HEADER}"""{spec.display_name} validation rules.

Validation is part of the workflow rather than an option, so these run on
every write and their findings travel with the response.
"""

{GENERATED_NOTE}
from dataclasses import dataclass
from datetime import date, datetime
from typing import Any


@dataclass(frozen=True)
class Finding:
    """One rule that did not hold."""

    code: str
    message: str
    field: str
    severity: str = "error"


def _is_future(value: Any) -> bool:
    """Whether a date or datetime is after now, comparing like with like."""
    if isinstance(value, datetime):
        from datetime import UTC

        now = datetime.now(UTC)
        # A naive datetime cannot be compared with an aware one, and which of
        # the two arrives depends on the client rather than on this module.
        if value.tzinfo is None:
            value = value.replace(tzinfo=UTC)
        return value > now
    if isinstance(value, date):
        from datetime import UTC

        return value > datetime.now(UTC).date()
    return False


def validate(value: Any) -> list[Finding]:
    """Run every rule. Returns findings; an empty list means the record is sound."""
    findings: list[Finding] = []
{chr(10).join(checks)}
    return findings


def blocking(findings: list[Finding]) -> list[Finding]:
    """The findings that must stop a write, as opposed to warn about it."""
    return [f for f in findings if f.severity == "error"]
'''


def _permissions(spec: ModuleSpec) -> str:
    return f'''{HEADER}"""{spec.display_name} permissions.

Registered rather than merely referenced: a permission the registry has never
heard of is denied to everyone except an administrator, and a test run as an
administrator cannot see the difference.
"""

{GENERATED_NOTE}
from app.core.permissions import Role, permission_registry

{spec.key.upper()}_PERMISSIONS: dict[str, Role] = {{
    "{spec.key}.read": Role.VIEWER,
    "{spec.key}.write": Role.EDITOR,
    "{spec.key}.delete": Role.MANAGER,
}}


def register_{spec.key}_permissions() -> None:
    """Register this module's permissions with the platform registry.

    Called from ``on_startup`` in this package's ``__init__``, which is the
    hook the module loader runs once the module is loaded.
    """
    permission_registry.register_module_permissions({spec.key!r}, {spec.key.upper()}_PERMISSIONS)
'''


def _repository(spec: ModuleSpec) -> str:
    entity = spec.entity
    scope = (
        "        if project_id is not None:\n"
        f"            stmt = stmt.where({spec.class_name}.project_id == project_id)\n"
        if entity.project_scoped
        else ""
    )
    return f'''{HEADER}"""{spec.display_name} data access."""

{GENERATED_NOTE}
import uuid

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.modules.{spec.key}.models import {spec.class_name}


class {spec.class_name}Repository:
    """Reads and writes for {spec.table_name}."""

    def __init__(self, session: AsyncSession) -> None:
        self.session = session

    async def list_page(
        self,
        project_id: uuid.UUID | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> tuple[list[{spec.class_name}], int]:
        """One page, plus the total the page was taken from.

        The total is counted rather than inferred from the page length, so a
        caller can tell a short last page from an empty result.
        """
        stmt = select({spec.class_name})
{scope}        count_stmt = select(func.count()).select_from(stmt.subquery())
        total = int((await self.session.execute(count_stmt)).scalar_one())
        stmt = stmt.order_by({spec.class_name}.created_at.desc()).limit(limit).offset(offset)
        rows = list((await self.session.execute(stmt)).scalars().all())
        return rows, total

    async def get(self, record_id: uuid.UUID) -> {spec.class_name} | None:
        return await self.session.get({spec.class_name}, record_id)

    async def add(self, record: {spec.class_name}) -> {spec.class_name}:
        self.session.add(record)
        await self.session.flush()
        return record

    async def delete(self, record: {spec.class_name}) -> None:
        await self.session.delete(record)
        await self.session.flush()
'''


def _service(spec: ModuleSpec) -> str:
    entity = spec.entity
    return f'''{HEADER}"""{spec.display_name} business logic."""

{GENERATED_NOTE}
import uuid

from sqlalchemy.ext.asyncio import AsyncSession

from app.modules.{spec.key}.models import {spec.class_name}
from app.modules.{spec.key}.repository import {spec.class_name}Repository
from app.modules.{spec.key}.schemas import {spec.class_name}Create, {spec.class_name}Update
from app.modules.{spec.key}.validators import Finding, blocking, validate


class ValidationRefused(Exception):
    """A write that the module's own rules will not allow."""

    def __init__(self, findings: list[Finding]) -> None:
        self.findings = findings
        super().__init__("; ".join(f"{{f.code}}: {{f.message}}" for f in findings))


class {spec.class_name}Service:
    """The operations the router exposes, with validation attached to writes."""

    def __init__(self, session: AsyncSession) -> None:
        self.repo = {spec.class_name}Repository(session)

    async def list_page(
        self, project_id: uuid.UUID | None = None, limit: int = 100, offset: int = 0
    ) -> tuple[list[{spec.class_name}], int]:
        return await self.repo.list_page(project_id=project_id, limit=limit, offset=offset)

    async def get(self, record_id: uuid.UUID) -> {spec.class_name} | None:
        return await self.repo.get(record_id)

    async def create(self, payload: {spec.class_name}Create) -> tuple[{spec.class_name}, list[Finding]]:
        findings = validate(payload)
        if blocking(findings):
            raise ValidationRefused(blocking(findings))
        record = {spec.class_name}(**payload.model_dump())
        await self.repo.add(record)
        return record, findings

    async def update(
        self, record: {spec.class_name}, payload: {spec.class_name}Update
    ) -> tuple[{spec.class_name}, list[Finding]]:
        # Validate the record as it will be, not the patch on its own: a rule
        # about two fields cannot be judged from whichever one was sent.
        changes = payload.model_dump(exclude_unset=True)
        merged = _Merged(record, changes)
        findings = validate(merged)
        if blocking(findings):
            raise ValidationRefused(blocking(findings))
        for key, value in changes.items():
            setattr(record, key, value)
        return record, findings

    async def delete(self, record: {spec.class_name}) -> None:
        await self.repo.delete(record)


class _Merged:
    """A read-only view of a record with pending changes applied.

    Used to validate an update before it is written, so a refused update leaves
    the row untouched rather than needing a rollback.
    """

    def __init__(self, record: object, changes: dict[str, object]) -> None:
        self._record = record
        self._changes = changes

    def __getattr__(self, name: str) -> object:
        if name in self._changes:
            return self._changes[name]
        return getattr(self._record, name)
'''


def _router(spec: ModuleSpec) -> str:
    entity = spec.entity
    project_query = (
        '    project_id: uuid.UUID | None = Query(None, description="Restrict to one project"),\n'
        if entity.project_scoped
        else ""
    )
    project_arg = "project_id=project_id, " if entity.project_scoped else ""
    return f'''{HEADER}"""{spec.display_name} HTTP API."""

{GENERATED_NOTE}
import json
import uuid
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Query, status

from app.dependencies import RequirePermission, SessionDep
from app.modules.{spec.key}.schemas import (
    {spec.class_name}Create,
    {spec.class_name}List,
    {spec.class_name}Read,
    {spec.class_name}Update,
)
from app.modules.{spec.key}.service import {", ".join(sorted([f"{spec.class_name}Service", "ValidationRefused"]))}

router = APIRouter()


@router.get("/ui-spec", summary="The screen description this module renders from")
async def ui_spec() -> dict:
    """Return the module specification.

    The frontend is a compiled bundle, so a module installed at runtime cannot
    ship a screen of its own. It ships this instead, and the platform renders
    the list, the detail and the form from it.
    """
    path = Path(__file__).parent / "spec.json"
    if not path.is_file():
        raise HTTPException(status.HTTP_404_NOT_FOUND, "this module carries no ui spec")
    return json.loads(path.read_text(encoding="utf-8"))


@router.get("", response_model={spec.class_name}List, summary="List {entity.plural_name.lower()}")
async def list_records(
    db: SessionDep,
{project_query}    limit: int = Query(100, ge=1, le=500),
    offset: int = Query(0, ge=0),
    _perm: None = Depends(RequirePermission("{spec.key}.read")),
) -> {spec.class_name}List:
    rows, total = await {spec.class_name}Service(db).list_page({project_arg}limit=limit, offset=offset)
    return {spec.class_name}List(items=[{spec.class_name}Read.model_validate(r) for r in rows], total=total)


@router.get("/{{record_id}}", response_model={spec.class_name}Read, summary="One {entity.display_name.lower()}")
async def get_record(
    record_id: uuid.UUID,
    db: SessionDep,
    _perm: None = Depends(RequirePermission("{spec.key}.read")),
) -> {spec.class_name}Read:
    record = await {spec.class_name}Service(db).get(record_id)
    if record is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "not found")
    return {spec.class_name}Read.model_validate(record)


@router.post("", response_model={spec.class_name}Read, status_code=status.HTTP_201_CREATED)
async def create_record(
    payload: {spec.class_name}Create,
    db: SessionDep,
    _perm: None = Depends(RequirePermission("{spec.key}.write")),
) -> {spec.class_name}Read:
    try:
        record, _findings = await {spec.class_name}Service(db).create(payload)
    except ValidationRefused as exc:
        raise HTTPException(
            status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=[{{"code": f.code, "message": f.message, "field": f.field}} for f in exc.findings],
        ) from exc
    await db.commit()
    await db.refresh(record)
    return {spec.class_name}Read.model_validate(record)


@router.patch("/{{record_id}}", response_model={spec.class_name}Read)
async def update_record(
    record_id: uuid.UUID,
    payload: {spec.class_name}Update,
    db: SessionDep,
    _perm: None = Depends(RequirePermission("{spec.key}.write")),
) -> {spec.class_name}Read:
    service = {spec.class_name}Service(db)
    record = await service.get(record_id)
    if record is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "not found")
    try:
        record, _findings = await service.update(record, payload)
    except ValidationRefused as exc:
        raise HTTPException(
            status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=[{{"code": f.code, "message": f.message, "field": f.field}} for f in exc.findings],
        ) from exc
    await db.commit()
    await db.refresh(record)
    return {spec.class_name}Read.model_validate(record)


@router.delete("/{{record_id}}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_record(
    record_id: uuid.UUID,
    db: SessionDep,
    # Deleting is a manager's action, as it is everywhere else in the platform.
    # Whoever may correct a record is not automatically whoever may remove it.
    _perm: None = Depends(RequirePermission("{spec.key}.delete")),
) -> None:
    service = {spec.class_name}Service(db)
    record = await service.get(record_id)
    if record is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "not found")
    await service.delete(record)
    await db.commit()
'''


def _locale(spec: ModuleSpec) -> str:
    """English strings for the generated screen.

    English only, on purpose. The platform ships 29 locales and a machine
    translation nobody read is worse than an untranslated string: the reader
    cannot tell it was never checked. The generated screen falls back to
    English until a person translates it.
    """
    payload = {
        spec.key: {
            "title": spec.display_name,
            "description": spec.description,
            "entity": spec.entity.display_name,
            "entityPlural": spec.entity.plural_name,
            "fields": {f.name: f.label for f in spec.entity.fields},
            "help": {f.name: f.help_text for f in spec.entity.fields if f.help_text},
            "rules": {r.code: r.message for r in spec.rules},
        }
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _tests_conftest() -> str:
    """Let the generated tests run on their own, outside platform startup.

    The module lives in the instance's runtime module root, which is only on
    the import path once the platform has attached it. A developer running
    ``pytest`` against the module directory has not been through startup, so
    the tests attach the root themselves.
    """
    return f'''{HEADER}"""Make this module importable when its tests run on their own."""

{GENERATED_NOTE}
from pathlib import Path

# tests/ -> <module>/ -> the runtime module root that holds it.
RUNTIME_ROOT = Path(__file__).resolve().parents[2]


def pytest_configure() -> None:
    from app.core.module_runtime_root import attach_runtime_root

    attach_runtime_root(RUNTIME_ROOT, create=False)
'''


def _tests(spec: ModuleSpec) -> str:
    """Tests that come with the module, exercising its own rules.

    Generated from the same rules the validator was generated from, so they
    check the rendering rather than restating it: each one builds a record that
    breaks exactly one rule and asserts that rule fires.
    """
    cases = []
    for rule in spec.rules:
        cases.append(
            f"    def test_{rule.code.lower()}_fires(self) -> None:\n"
            f"        findings = validate(_breaking({rule.code!r}))\n"
            f"        assert {rule.code!r} in [f.code for f in findings]\n"
        )
    field_defaults = ", ".join(f"{f.name}={_sample_source(f)}" for f in spec.entity.fields)
    return f'''{HEADER}"""Tests for {spec.display_name}."""

{GENERATED_NOTE}
from datetime import UTC, datetime, timedelta  # noqa: F401
from types import SimpleNamespace

from app.modules.{spec.key}.validators import validate

RULES = {[r.model_dump(mode="json") for r in spec.rules]!r}


def _sound() -> SimpleNamespace:
    """A record every rule accepts."""
    return SimpleNamespace({field_defaults})


def _breaking(code: str) -> SimpleNamespace:
    """A sound record with exactly one rule broken."""
    record = _sound()
    rule = next(r for r in RULES if r["code"] == code)
    field, kind = rule["field"], rule["kind"]
    if kind == "required":
        setattr(record, field, None)
    elif kind in {{"positive"}}:
        setattr(record, field, -1)
    elif kind == "range":
        low, high = rule.get("min_value"), rule.get("max_value")
        setattr(record, field, (low - 1) if low is not None else (high + 1))
    elif kind == "one_of":
        setattr(record, field, "definitely-not-an-option")
    elif kind == "not_future":
        # No local import here. Binding datetime names inside one branch makes
        # them local to the whole function, and the order branch below then
        # raises UnboundLocalError on a name the module already imported.
        current = getattr(record, field)
        ahead = datetime.now(UTC) + timedelta(days=365)
        setattr(record, field, ahead if isinstance(current, datetime) else ahead.date())
    elif kind == "order":
        # One day past the field it must not exceed.
        setattr(record, field, getattr(record, rule["other_field"]) + timedelta(days=1))
    return record


class TestRules:
    def test_a_sound_record_passes_every_rule(self) -> None:
        assert validate(_sound()) == []

{chr(10).join(cases)}
    def test_every_rule_is_covered(self) -> None:
        """The count is the point: a rule with no test looks the same as one that passes."""
        tested = {{name.removeprefix("test_").removesuffix("_fires").upper() for name in dir(TestRules) if name.endswith("_fires")}}
        assert tested == {{r["code"] for r in RULES}}
'''


def _sample_source(field: FieldSpec) -> str:
    """Python source for a value every rule accepts.

    Source rather than a value: a date has no literal form that ``repr`` can
    put in a generated file, and a placeholder string in its place would give
    the generated tests a record that fails on a type error rather than on the
    rule under test.

    Numbers start at 1 so a ``positive`` rule holds; a ``range`` rule can still
    exclude 1, which the range case in ``_breaking`` accounts for by moving
    outside the bound rather than assuming the sound value is inside it.
    """
    if field.type == "integer":
        return "1"
    if field.type in {"number", "money"}:
        return "1"
    if field.type == "boolean":
        return "True"
    # Yesterday, not today: it satisfies ``not_future`` without depending on
    # the clock crossing midnight mid-run, and leaves room for an ``order``
    # rule to place a later field after it.
    if field.type == "date":
        return "(datetime.now(UTC) - timedelta(days=2)).date()"
    if field.type == "datetime":
        return "datetime.now(UTC) - timedelta(days=2)"
    if field.type == "select":
        return repr(field.options[0])
    if field.type == "long_text":
        return repr(f"About {field.label.lower()}")
    return repr(field.label)


def _readme(spec: ModuleSpec) -> str:
    rows = "\n".join(
        f"| `{f.name}` | {f.label} | {f.type} | {'yes' if f.required else 'no'} |" for f in spec.entity.fields
    )
    rules = "\n".join(f"- `{r.code}` ({r.severity}): {r.message}" for r in spec.rules)
    return f"""# {spec.display_name}

{spec.description or "Generated with the OpenConstructionERP module builder."}

This module was generated from a specification rather than written by hand.
`spec.json` beside this file is that specification, and it is also what the
platform renders the screen from.

## Record: {spec.entity.display_name}

| Field | Label | Type | Required |
|---|---|---|---|
{rows}

## Rules

{rules}

## API

Mounted at `{spec.url_prefix}`.

- `GET /ui-spec` the screen description
- `GET /` list, `GET /{{id}}` one
- `POST /` create, `PATCH /{{id}}` update, `DELETE /{{id}}` remove

Reading needs `{spec.key}.read`, writing needs `{spec.key}.write`.
"""
