// DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
// Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
//
// GENERATED by scripts/build_video_catalog.py from the video production
// registries and scripts/video_catalog/editorial.json. Do not edit by hand:
// change a source and re-run the script.

import type { AcademyCatalog } from './academyTypes';

export const ACADEMY_CATALOG: AcademyCatalog = {
  "channelId": "UCQ3IWLMLnBFwNeG5VBxXQ5Q",
  "channelName": "OpenConstruction Academy",
  "series": [
    {
      "id": "getting-started",
      "title": "Getting started",
      "titleKey": "videos.series.getting_started",
      "language": "en",
      "market": null,
      "channel": "academy"
    },
    {
      "id": "landshut-de",
      "title": "OpenConstructionERP auf Deutsch: Lernprojekt Landshut",
      "language": "de",
      "market": "DE",
      "channel": "academy"
    },
    {
      "id": "playbook-getting-started",
      "title": "Builder's Playbook: Getting Started",
      "language": "en",
      "market": null,
      "channel": "academy"
    },
    {
      "id": "playbook-canada-ontario",
      "title": "Builder's Playbook Canada: Ontario Construction",
      "language": "en",
      "market": "CA",
      "channel": "academy"
    },
    {
      "id": "playbook-quebec",
      "title": "Builder's Playbook Québec : la construction en français",
      "language": "fr",
      "market": "CA",
      "channel": "academy"
    },
    {
      "id": "playbook-chantier-fr",
      "title": "Builder's Playbook : gestion de chantier en français",
      "language": "fr",
      "market": null,
      "channel": "academy"
    },
    {
      "id": "ddc-walkthroughs",
      "title": "Product walkthroughs and talks",
      "titleKey": "videos.series.walkthroughs",
      "language": "en",
      "market": null,
      "channel": "ddc"
    }
  ],
  "videos": [
    {
      "id": "Setup_EN",
      "youtubeId": "WjDK-uk9b1w",
      "status": "published",
      "channel": "academy",
      "language": "en",
      "series": "getting-started",
      "seriesOrder": 1,
      "startHere": true,
      "stage": "define",
      "roles": [],
      "cases": [
        "set-up-a-new-project",
        "project-end-to-end"
      ],
      "routes": [
        "/projects/new",
        "/boq",
        "/schedule",
        "/daily-diary",
        "/closeout"
      ],
      "title": "How to Install OpenConstructionERP | Windows Setup & First Project",
      "description": "Install OpenConstructionERP on Windows and set up your first construction project. This beginner's guide covers the desktop app, installation with Python/pip, workspace settings and team access.",
      "recordedOn": "17.7",
      "duration": 281,
      "cover": "https://i.ytimg.com/vi/WjDK-uk9b1w/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Why use a construction ERP?"
        },
        {
          "t": 24,
          "title": "What OpenConstructionERP does"
        },
        {
          "t": 51,
          "title": "Desktop app, Python or Docker?"
        },
        {
          "t": 67,
          "title": "Download the installer"
        },
        {
          "t": 91,
          "title": "Install on Windows"
        },
        {
          "t": 108,
          "title": "Install with Python/pip"
        },
        {
          "t": 119,
          "title": "First launch and sample data"
        },
        {
          "t": 131,
          "title": "Language, profile and regional settings"
        },
        {
          "t": 150,
          "title": "Select your modules"
        },
        {
          "t": 162,
          "title": "Add users and set permissions"
        },
        {
          "t": 187,
          "title": "Set up access for your team"
        },
        {
          "t": 205,
          "title": "Create your first project"
        },
        {
          "t": 228,
          "title": "Configure regional data"
        },
        {
          "t": 240,
          "title": "Explore the platform"
        },
        {
          "t": 262,
          "title": "Get started"
        }
      ]
    },
    {
      "id": "V01",
      "youtubeId": "IM9hK6kCZCs",
      "status": "published",
      "channel": "academy",
      "language": "de",
      "series": "landshut-de",
      "seriesOrder": 1,
      "stage": "define",
      "roles": [
        "project-manager",
        "estimator",
        "quantity-surveyor"
      ],
      "cases": [
        "set-up-a-new-project",
        "feasibility-budget-before-design",
        "write-the-basis-of-estimate"
      ],
      "caseStarts": {
        "write-the-basis-of-estimate": 279
      },
      "routes": [
        "/projects/new",
        "/boq",
        "/schedule",
        "/cost-explorer",
        "/reports",
        "/estimate-basis"
      ],
      "result": "cost",
      "title": "Projekt und Verantwortung klären",
      "titleEn": "Set up the project and who decides",
      "description": "Ein Projekt aufbauen, Beteiligte zuordnen und Budgetentscheidungen nachvollziehen.",
      "produces": "A project record with two comparable variants, budget scope, reserve and named owners",
      "duration": 438,
      "cover": "https://i.ytimg.com/vi/IM9hK6kCZCs/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Sechs Wohnungen. Ein gemeinsamer Projektstart."
        },
        {
          "t": 19,
          "title": "Unser Lernprojekt in Landshut"
        },
        {
          "t": 36,
          "title": "Ein neues Projekt anlegen"
        },
        {
          "t": 47,
          "title": "Name und Projektcode"
        },
        {
          "t": 62,
          "title": "Region, Währung und Sprache"
        },
        {
          "t": 79,
          "title": "Standort: Landshut"
        },
        {
          "t": 84,
          "title": "Auftraggeber und Aufgaben trennen"
        },
        {
          "t": 97,
          "title": "Speichern und das Ziel prüfen"
        },
        {
          "t": 114,
          "title": "Die gemeinsame Ausgangsbasis ablegen"
        },
        {
          "t": 132,
          "title": "Zielwerte sind noch keine geprüften Flächen"
        },
        {
          "t": 149,
          "title": "Eine Entscheidung hat einen Verantwortlichen"
        },
        {
          "t": 168,
          "title": "Zwei Varianten vergleichbar halten"
        },
        {
          "t": 185,
          "title": "Variante A anlegen"
        },
        {
          "t": 199,
          "title": "Variante B als echte Alternative"
        },
        {
          "t": 212,
          "title": "Warum wir vorläufig ohne Keller planen"
        },
        {
          "t": 228,
          "title": "Die Arbeitsgrundlage sichtbar setzen"
        },
        {
          "t": 242,
          "title": "Budget und Reserve auf einen Blick"
        },
        {
          "t": 279,
          "title": "Die Kalkulationsgrundlage öffnen"
        },
        {
          "t": 292,
          "title": "Den Umfang der Budgetvorgabe festhalten"
        },
        {
          "t": 312,
          "title": "Allgemeine Ausschlüsse an den Auftrag anpassen"
        },
        {
          "t": 325,
          "title": "Preisstand und Reserve begründen"
        },
        {
          "t": 340,
          "title": "Annahmen und Ausschlüsse prüfen"
        },
        {
          "t": 357,
          "title": "Speichern und wieder öffnen"
        },
        {
          "t": 371,
          "title": "Offene Fragen brauchen einen nächsten Schritt"
        },
        {
          "t": 390,
          "title": "Das Projekt als gemeinsamen Ausgangspunkt prüfen"
        },
        {
          "t": 405,
          "title": "Ihre kurze Projektprüfung"
        },
        {
          "t": 420,
          "title": "Eine belastbare Grundlage für den nächsten Schritt"
        }
      ]
    },
    {
      "id": "V02",
      "youtubeId": "LP-CZOhu6OA",
      "status": "published",
      "channel": "academy",
      "language": "de",
      "series": "landshut-de",
      "seriesOrder": 2,
      "stage": "design",
      "roles": [
        "document-controller",
        "project-manager",
        "design-lead"
      ],
      "cases": [
        "answer-an-rfi",
        "issue-a-controlled-drawing-revision",
        "get-a-key-document-signed-off",
        "set-up-the-common-data-environment",
        "reconcile-a-drawing-issue-against-the-index"
      ],
      "caseStarts": {
        "answer-an-rfi": 69,
        "set-up-the-common-data-environment": 227,
        "reconcile-a-drawing-issue-against-the-index": 279
      },
      "routes": [
        "/rfi",
        "/correspondence",
        "/files",
        "/inspections",
        "/signing",
        "/cde",
        "/governance",
        "/coordination",
        "/plan-room",
        "/files/transmittals"
      ],
      "title": "Dokumente und Entscheidungen sichern",
      "titleEn": "Keep documents and decisions under control",
      "description": "Planstände, Rückfragen und Freigaben mit klaren Verantwortlichen verbinden.",
      "produces": "Drawing revisions, queries and approvals tied to the person responsible",
      "duration": 360,
      "cover": "https://i.ytimg.com/vi/LP-CZOhu6OA/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Ein Problem vor der Ausführung erkennen"
        },
        {
          "t": 11,
          "title": "Wer übernimmt welchen Schritt?"
        },
        {
          "t": 23,
          "title": "Den richtigen Projektkontext öffnen"
        },
        {
          "t": 38,
          "title": "Den Plan eindeutig erkennen"
        },
        {
          "t": 55,
          "title": "Dasselbe Detail in beiden Disziplinen ansehen"
        },
        {
          "t": 69,
          "title": "Eine klare Planungsfrage anlegen"
        },
        {
          "t": 84,
          "title": "Die Quellen mitgeben"
        },
        {
          "t": 97,
          "title": "Verantwortlichen und Termin festlegen"
        },
        {
          "t": 112,
          "title": "Den gespeicherten Auftrag prüfen"
        },
        {
          "t": 126,
          "title": "Die Fachprüfung sichtbar machen"
        },
        {
          "t": 140,
          "title": "Die Antwort dokumentieren"
        },
        {
          "t": 155,
          "title": "Revision B als neue Fassung ablegen"
        },
        {
          "t": 171,
          "title": "Die Änderung und den Plankopf prüfen"
        },
        {
          "t": 188,
          "title": "Den richtigen Stand zur Prüfung vorlegen"
        },
        {
          "t": 203,
          "title": "Die Entscheidung mit ihrem Umfang lesen"
        },
        {
          "t": 227,
          "title": "Aktuellen Stand und Historie auseinanderhalten"
        },
        {
          "t": 243,
          "title": "Zwei unterschiedliche Freigaben"
        },
        {
          "t": 254,
          "title": "Die externe Vorbereitung anhand der Unterlagen prüfen"
        },
        {
          "t": 265,
          "title": "Fehlende Unterlagen sichtbar lassen"
        },
        {
          "t": 279,
          "title": "Die richtige Datei herunterladen"
        },
        {
          "t": 290,
          "title": "Das Ergebnis nach erneutem Öffnen prüfen"
        },
        {
          "t": 309,
          "title": "Die Verantwortung weitergeben"
        },
        {
          "t": 320,
          "title": "Selbst prüfen"
        },
        {
          "t": 335,
          "title": "Die Antwort erklären"
        },
        {
          "t": 346,
          "title": "Anschluss an V03"
        }
      ]
    },
    {
      "id": "V03",
      "youtubeId": "YEk8F3W28po",
      "status": "published",
      "channel": "academy",
      "language": "de",
      "series": "landshut-de",
      "seriesOrder": 3,
      "stage": "estimate",
      "roles": [
        "estimator",
        "quantity-surveyor"
      ],
      "cases": [
        "takeoff-quantities-from-a-pdf-plan",
        "takeoff-from-dwg"
      ],
      "routes": [
        "/files",
        "/takeoff",
        "/quantities",
        "/boq",
        "/dwg-takeoff"
      ],
      "result": "qty",
      "title": "Mengen aus PDF und DWG ermitteln",
      "titleEn": "Quantities from PDF and DWG plans",
      "description": "Fläche, Sockellänge und Fensterzahl mit Quelle und Gegenprüfung sichern.",
      "produces": "Floor area, skirting length and window count, each with its source and a cross-check",
      "duration": 355,
      "cover": "https://i.ytimg.com/vi/YEk8F3W28po/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Mengen nachvollziehbar ermitteln"
        },
        {
          "t": 11,
          "title": "Wer liefert, misst und prüft?"
        },
        {
          "t": 25,
          "title": "Den freigegebenen Plan verwenden"
        },
        {
          "t": 44,
          "title": "Ein Plan braucht einen Maßbezug"
        },
        {
          "t": 55,
          "title": "Am bekannten Abstand kalibrieren"
        },
        {
          "t": 71,
          "title": "Mit einer zweiten Strecke prüfen"
        },
        {
          "t": 85,
          "title": "Die richtige Fläche abgrenzen"
        },
        {
          "t": 101,
          "title": "Den ersten Flächenwert sichern"
        },
        {
          "t": 114,
          "title": "Den Abzug nachvollziehbar erfassen"
        },
        {
          "t": 134,
          "title": "Ausgangsfläche minus Abzug"
        },
        {
          "t": 146,
          "title": "Eine Länge nach derselben Regel messen"
        },
        {
          "t": 164,
          "title": "Messungen wiederfinden"
        },
        {
          "t": 181,
          "title": "Ein klar begrenzter Umfang"
        },
        {
          "t": 195,
          "title": "Denselben Plan als DWG öffnen"
        },
        {
          "t": 211,
          "title": "Einheiten und Ebenen kontrollieren"
        },
        {
          "t": 226,
          "title": "Fenster im vereinbarten Bereich zählen"
        },
        {
          "t": 242,
          "title": "Mit Plan und Liste vergleichen"
        },
        {
          "t": 268,
          "title": "Eine prüfbare Mengenbasis sichern"
        },
        {
          "t": 286,
          "title": "Die Grundlage gezielt weitergeben"
        },
        {
          "t": 300,
          "title": "Einen anderen Raum selbst prüfen"
        },
        {
          "t": 323,
          "title": "Die Kontrolle begründen"
        },
        {
          "t": 338,
          "title": "Mit derselben Grundlage weiterarbeiten"
        }
      ]
    },
    {
      "id": "BIM01",
      "youtubeId": "KI6e3s7XScY",
      "status": "published",
      "channel": "academy",
      "language": "de",
      "series": "landshut-de",
      "seriesOrder": 4,
      "stage": "design",
      "roles": [
        "bim-coordinator",
        "estimator",
        "quantity-surveyor"
      ],
      "cases": [
        "quantities-from-bim"
      ],
      "routes": [
        "/bim",
        "/boq",
        "/validation"
      ],
      "result": "qty",
      "title": "BIM-Modelle verstehen und nutzen",
      "titleEn": "Read and use BIM models",
      "description": "IFC und vorbereitetes RVT erkunden, Bauteile auswählen und die heruntergeladene CSV-Tabelle prüfen.",
      "produces": "Selected IFC and RVT elements grouped by storey, checked in the exported CSV",
      "duration": 341,
      "cover": "https://i.ytimg.com/vi/KI6e3s7XScY/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "BIM-Modelle verstehen und nutzen"
        },
        {
          "t": 15,
          "title": "Verschiedene Formate. Ein klarer Ablauf."
        },
        {
          "t": 35,
          "title": "Die IFC im BIM-Aufmaß öffnen"
        },
        {
          "t": 54,
          "title": "Zuerst das ganze Gebäude verstehen"
        },
        {
          "t": 73,
          "title": "Ein Geschoss nach dem anderen"
        },
        {
          "t": 93,
          "title": "Vom Geschoss zur Bauteilgruppe"
        },
        {
          "t": 116,
          "title": "Ein kurzer Blick auf die Eigenschaften"
        },
        {
          "t": 134,
          "title": "So genau wie nötig"
        },
        {
          "t": 156,
          "title": "Das vorbereitete RVT-Modell"
        },
        {
          "t": 178,
          "title": "Die Geometrie räumlich erkunden"
        },
        {
          "t": 197,
          "title": "Die gleichen Werkzeuge weiterverwenden"
        },
        {
          "t": 218,
          "title": "Eine Auswahl, die andere verstehen"
        },
        {
          "t": 238,
          "title": "Die ausgewählten Elemente exportieren"
        },
        {
          "t": 257,
          "title": "Die heruntergeladene Tabelle lesen"
        },
        {
          "t": 279,
          "title": "Die Arbeit wieder aufnehmen"
        },
        {
          "t": 299,
          "title": "Klar übergeben, gezielt weiterarbeiten"
        },
        {
          "t": 322,
          "title": "Vom Modell zur nächsten Aufgabe"
        }
      ]
    },
    {
      "id": "LV01",
      "youtubeId": "tZEdPehNE6Q",
      "status": "published",
      "channel": "academy",
      "language": "de",
      "market": "DE",
      "series": "landshut-de",
      "seriesOrder": 5,
      "stage": "estimate",
      "roles": [
        "estimator",
        "quantity-surveyor"
      ],
      "cases": [],
      "routes": [],
      "result": "bill",
      "title": "Ein Leistungsverzeichnis aufbauen",
      "titleEn": "Build a Leistungsverzeichnis",
      "description": "Aus einer geprüften Mengenbasis acht eindeutig beschriebene Leistungen erstellen.",
      "produces": "Eight unambiguously described bill items built on a checked quantity base",
      "duration": 302,
      "cover": "https://i.ytimg.com/vi/tZEdPehNE6Q/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Aus Mengen wird ein Leistungsverzeichnis"
        },
        {
          "t": 17,
          "title": "Wer beschreibt, prüft und kalkuliert?"
        },
        {
          "t": 37,
          "title": "Die Leistungsgrundlage öffnen"
        },
        {
          "t": 56,
          "title": "Ein eigenes LV anlegen"
        },
        {
          "t": 76,
          "title": "Drei Abschnitte, acht Leistungen"
        },
        {
          "t": 95,
          "title": "Den ersten Abschnitt erstellen"
        },
        {
          "t": 116,
          "title": "Eine Leistung eindeutig beschreiben"
        },
        {
          "t": 137,
          "title": "Einheit und genaue Menge eintragen"
        },
        {
          "t": 156,
          "title": "Arbeitsfläche und Materialbedarf unterscheiden"
        },
        {
          "t": 174,
          "title": "Den vollständigen Umfang lesen"
        },
        {
          "t": 195,
          "title": "Eine bestimmte Position wiederfinden"
        },
        {
          "t": 212,
          "title": "Vollständig beschrieben ist noch nicht bepreist"
        },
        {
          "t": 230,
          "title": "Den gespeicherten Stand kontrollieren"
        },
        {
          "t": 248,
          "title": "Welche Positionen ändern sich?"
        },
        {
          "t": 268,
          "title": "Nur die betroffenen Mengen fortschreiben"
        },
        {
          "t": 285,
          "title": "Die Grundlage für einen nachvollziehbaren Preis"
        }
      ]
    },
    {
      "id": "KALK01",
      "youtubeId": "qFGKRIXHM8w",
      "status": "published",
      "channel": "academy",
      "language": "de",
      "series": "landshut-de",
      "seriesOrder": 6,
      "stage": "estimate",
      "roles": [
        "estimator",
        "quantity-surveyor"
      ],
      "cases": [
        "build-an-assembly-recipe-rate",
        "calculate-with-your-own-efb-rates"
      ],
      "routes": [
        "/cost-explorer",
        "/assemblies",
        "/boq",
        "/labor-rates",
        "/catalog",
        "/resource-summary"
      ],
      "result": "rate",
      "title": "Einheitspreise und Kosten nachvollziehen",
      "titleEn": "Unit rates you can trace",
      "description": "Parkett und Gipskarton kalkulieren, Arbeitsrezepte aus dem Katalog verwenden und eine Kostenänderung über den Zeitbedarf begründen.",
      "produces": "Parquet and drywall rates from catalogue recipes, with a price change argued through labour time",
      "duration": 396,
      "cover": "https://i.ytimg.com/vi/qFGKRIXHM8w/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Einheitspreise und Kosten nachvollziehen"
        },
        {
          "t": 18,
          "title": "Der Katalog ist Ihr Rezeptbuch"
        },
        {
          "t": 38,
          "title": "Die beiden Arbeitsrezepte finden"
        },
        {
          "t": 58,
          "title": "Das Parkettrezept aufklappen"
        },
        {
          "t": 78,
          "title": "Arbeitsmenge und Verbrauch trennen"
        },
        {
          "t": 103,
          "title": "Das Rezept für die Trennwand lesen"
        },
        {
          "t": 126,
          "title": "Eine Wandfläche, zwei Plattenseiten"
        },
        {
          "t": 150,
          "title": "Beide Rezepte in das eigene LV übernehmen"
        },
        {
          "t": 172,
          "title": "Die fertigen Arbeitsmengen einsetzen"
        },
        {
          "t": 192,
          "title": "Den Parkettpreis bis zur Ressource verfolgen"
        },
        {
          "t": 216,
          "title": "Auch die Trennwand vollständig prüfen"
        },
        {
          "t": 239,
          "title": "Was diese Kostenbasis enthält"
        },
        {
          "t": 266,
          "title": "Mehr Arbeitszeit gezielt berücksichtigen"
        },
        {
          "t": 291,
          "title": "Eine Änderung mit sichtbarer Wirkung"
        },
        {
          "t": 310,
          "title": "Den gespeicherten Ansatz wieder prüfen"
        },
        {
          "t": 334,
          "title": "Das Ausgangsrezept bleibt verfügbar"
        },
        {
          "t": 353,
          "title": "Ansatz, Begründung und Prüfung zusammengeben"
        },
        {
          "t": 374,
          "title": "Ein Rezept wird zu Ihrer Kalkulation"
        }
      ]
    },
    {
      "id": "GAEB01",
      "youtubeId": "T3FBggAeFJ4",
      "status": "published",
      "channel": "academy",
      "language": "de",
      "market": "DE",
      "series": "landshut-de",
      "seriesOrder": 7,
      "stage": "procure",
      "roles": [
        "estimator",
        "quantity-surveyor",
        "procurement-buyer"
      ],
      "cases": [
        "import-a-gaeb-tender-into-a-priced-boq",
        "answer-a-gaeb-inquiry-as-a-subcontractor",
        "win-a-gaeb-tender-from-lv-to-angebot"
      ],
      "routes": [
        "/files",
        "/boq",
        "/catalog",
        "/validation",
        "/gaeb-exchange",
        "/bid-management",
        "/costs",
        "/files/transmittals"
      ],
      "result": "gaeb",
      "title": "GAEB-Dateien kontrolliert austauschen",
      "titleEn": "Exchange GAEB files under control",
      "description": "X83 und X84 über geprüfte Wege ausgeben, Dateien prüfen und den Import kontrollieren.",
      "produces": "X83 and X84 exported by checked routes, then re-imported and verified",
      "duration": 334,
      "cover": "https://i.ytimg.com/vi/T3FBggAeFJ4/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "GAEB-Dateien kontrolliert austauschen"
        },
        {
          "t": 19,
          "title": "Anfrage und Angebot haben verschiedene Phasen"
        },
        {
          "t": 39,
          "title": "Den richtigen Ausgangsstand wählen"
        },
        {
          "t": 58,
          "title": "X83 aus dem LV-Editor exportieren"
        },
        {
          "t": 78,
          "title": "Die Anfrage unabhängig prüfen"
        },
        {
          "t": 98,
          "title": "Den GAEB-Import öffnen"
        },
        {
          "t": 117,
          "title": "In ein getrenntes LV importieren"
        },
        {
          "t": 135,
          "title": "Das gespeicherte Ergebnis vergleichen"
        },
        {
          "t": 153,
          "title": "Text und Struktur gehören zur Prüfung"
        },
        {
          "t": 174,
          "title": "Den bepreisten Stand auswählen"
        },
        {
          "t": 194,
          "title": "X84 über GAEB-Austausch ausgeben"
        },
        {
          "t": 214,
          "title": "Acht Preise und die richtige Bezugsdatei"
        },
        {
          "t": 234,
          "title": "Die Grenze beim Preisrücklauf erkennen"
        },
        {
          "t": 253,
          "title": "Was funktioniert und was bleibt offen?"
        },
        {
          "t": 276,
          "title": "Drei Dateien, welche ist die passende Antwort?"
        },
        {
          "t": 293,
          "title": "Vollständigkeit ist der Anfang der Prüfung"
        },
        {
          "t": 315,
          "title": "Austausch mit einer nachvollziehbaren Prüfkette"
        }
      ]
    },
    {
      "id": "VERGABE01",
      "youtubeId": "75sjLEjXiBc",
      "status": "published",
      "channel": "academy",
      "language": "de",
      "market": "DE",
      "series": "landshut-de",
      "seriesOrder": 8,
      "stage": "procure",
      "roles": [
        "procurement-buyer",
        "estimator",
        "commercial-manager"
      ],
      "cases": [
        "build-a-preisspiegel-and-award",
        "level-bids-to-a-common-scope",
        "compare-bids-and-award"
      ],
      "routes": [
        "/tendering",
        "/subcontractors",
        "/procurement",
        "/reports",
        "/bid-management"
      ],
      "result": "award",
      "title": "Angebote prüfen und Vergabe vorbereiten",
      "titleEn": "Check bids and prepare the award",
      "description": "Vollständige Leistungen vergleichen, einen automatischen Ansatz prüfen und eine vorläufige Begründung speichern.",
      "produces": "A like-for-like bid comparison with a saved, provisional award rationale",
      "duration": 184,
      "cover": "https://i.ytimg.com/vi/75sjLEjXiBc/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Günstigster Preis — vollständige Leistung?"
        },
        {
          "t": 12,
          "title": "Prüfen · begründen · entscheiden"
        },
        {
          "t": 25,
          "title": "Das Vergabepaket öffnen"
        },
        {
          "t": 39,
          "title": "Acht Positionen, gleicher Mengenstand"
        },
        {
          "t": 51,
          "title": "Angebotssummen lesen"
        },
        {
          "t": 61,
          "title": "Bei A fehlt Position 03.20"
        },
        {
          "t": 71,
          "title": "Den automatischen Ansatz prüfen"
        },
        {
          "t": 86,
          "title": "Ein transparenter Vergleichsansatz"
        },
        {
          "t": 99,
          "title": "Angebot und Vergleich getrennt halten"
        },
        {
          "t": 111,
          "title": "Preis plus Ausführungsbedingungen"
        },
        {
          "t": 122,
          "title": "Die Begründung festhalten"
        },
        {
          "t": 139,
          "title": "Den gespeicherten Stand prüfen"
        },
        {
          "t": 153,
          "title": "Der Vorschlag ist noch kein Zuschlag"
        },
        {
          "t": 168,
          "title": "Ihre Kontrolle vor der Auswahl"
        }
      ]
    },
    {
      "id": "TERMIN01",
      "youtubeId": "bGUpude30wc",
      "status": "published",
      "channel": "academy",
      "language": "de",
      "series": "landshut-de",
      "seriesOrder": 9,
      "stage": "plan",
      "roles": [
        "planner",
        "site-manager",
        "project-manager"
      ],
      "cases": [
        "protect-the-programme-from-a-long-lead-item",
        "crew-and-plant-lookahead-balance",
        "schedule-and-track",
        "build-the-baseline-programme",
        "update-the-programme-and-reforecast",
        "produce-a-short-interval-lookahead"
      ],
      "caseStarts": {
        "protect-the-programme-from-a-long-lead-item": 68,
        "schedule-and-track": 35,
        "build-the-baseline-programme": 52,
        "update-the-programme-and-reforecast": 103,
        "produce-a-short-interval-lookahead": 121
      },
      "routes": [
        "/procurement",
        "/schedule-advanced",
        "/reports",
        "/field-time",
        "/schedule",
        "/boq",
        "/change-intelligence"
      ],
      "result": "programme",
      "title": "Abhängigkeiten und Ressourceneinsatz planen",
      "titleEn": "Plan dependencies and crews",
      "description": "Eine Lieferänderung durch den Ablauf verfolgen und die Zuordnung des Bodenteams nach erneutem Öffnen prüfen.",
      "produces": "A delivery change traced through the programme, with the crew assignment checked after reopening",
      "duration": 271,
      "cover": "https://i.ytimg.com/vi/bGUpude30wc/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Wenn die Fenster später kommen"
        },
        {
          "t": 16,
          "title": "Wer stimmt den Ablauf ab?"
        },
        {
          "t": 35,
          "title": "Den vorbereiteten Terminplan öffnen"
        },
        {
          "t": 52,
          "title": "Abhängigkeit mit einer klaren Bedeutung"
        },
        {
          "t": 68,
          "title": "Lieferung und Montage verbinden"
        },
        {
          "t": 87,
          "title": "Planzeit ersetzt keine Freigabe"
        },
        {
          "t": 103,
          "title": "Die Lieferänderung übernehmen"
        },
        {
          "t": 121,
          "title": "Was verschiebt sich durch die Lieferung?"
        },
        {
          "t": 139,
          "title": "Ressourcen und Personal finden"
        },
        {
          "t": 157,
          "title": "Das Bodenteam zur Aktivität zuordnen"
        },
        {
          "t": 176,
          "title": "Vorgeschlagen und bestätigt unterscheiden"
        },
        {
          "t": 195,
          "title": "Die Zuteilung bestätigen und erneut prüfen"
        },
        {
          "t": 215,
          "title": "Den gespeicherten Ablauf wieder öffnen"
        },
        {
          "t": 238,
          "title": "Ihre Prüfung vor der nächsten Zusage"
        },
        {
          "t": 254,
          "title": "Vom Terminplan zur Materiallieferung"
        }
      ]
    },
    {
      "id": "EINKAUF01",
      "youtubeId": "G0a5pEiXaS4",
      "status": "published",
      "channel": "academy",
      "language": "de",
      "series": "landshut-de",
      "seriesOrder": 10,
      "stage": "procure",
      "roles": [
        "procurement-buyer",
        "site-manager"
      ],
      "cases": [
        "procure-from-boq",
        "receive-and-reconcile-material-deliveries",
        "run-a-three-way-match-before-paying-a-supplier"
      ],
      "caseStarts": {
        "run-a-three-way-match-before-paying-a-supplier": 359
      },
      "routes": [
        "/boq",
        "/procurement",
        "/site-inventory",
        "/reconciliation",
        "/finance"
      ],
      "result": "order",
      "title": "Material und Teillieferung verfolgen",
      "titleEn": "Track materials and part deliveries",
      "description": "Materialbedarf, Bestellung, geprüfte Teilmenge und offenen Lieferrest unterscheiden.",
      "produces": "Demand, order, checked part delivery and open remainder kept apart",
      "duration": 421,
      "cover": "https://i.ytimg.com/vi/G0a5pEiXaS4/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Bestellt ist noch nicht auf Lager"
        },
        {
          "t": 17,
          "title": "Wer prüft welche Grundlage?"
        },
        {
          "t": 36,
          "title": "Von der Bodenfläche zum Materialbedarf"
        },
        {
          "t": 57,
          "title": "Das Lieferformat begründet die Bestellung"
        },
        {
          "t": 76,
          "title": "Beschaffung im richtigen Projekt öffnen"
        },
        {
          "t": 92,
          "title": "Material, Menge und Preis eintragen"
        },
        {
          "t": 113,
          "title": "Lernbestellung nachvollziehbar speichern"
        },
        {
          "t": 132,
          "title": "Was bedeuten die 440 Euro?"
        },
        {
          "t": 156,
          "title": "Den abgestimmten Auftrag freigeben"
        },
        {
          "t": 180,
          "title": "Die erste Lieferung erfassen"
        },
        {
          "t": 196,
          "title": "Nur die tatsächliche Menge übernehmen"
        },
        {
          "t": 216,
          "title": "Die Teilannahme bestätigen und nachlesen"
        },
        {
          "t": 238,
          "title": "Wareneingang und Lager getrennt prüfen"
        },
        {
          "t": 255,
          "title": "Baustellenbestand und Stammdaten finden"
        },
        {
          "t": 275,
          "title": "Zwölf Quadratmeter dem Lager zuordnen"
        },
        {
          "t": 296,
          "title": "Die Belegreferenz im Zugang festhalten"
        },
        {
          "t": 317,
          "title": "Den gespeicherten Bestand nachweisen"
        },
        {
          "t": 338,
          "title": "Drei Mengen mit verschiedenen Aussagen"
        },
        {
          "t": 359,
          "title": "Bestellung und Lieferbeleg erneut abgleichen"
        },
        {
          "t": 379,
          "title": "Ihre Prüfung vor der Restlieferung"
        },
        {
          "t": 400,
          "title": "Bedarf, Bestellung und Bestand belegen"
        }
      ]
    },
    {
      "id": "KOSTENDB01",
      "youtubeId": "uBhNqXw2dm0",
      "status": "published",
      "channel": "academy",
      "language": "de",
      "series": "landshut-de",
      "seriesOrder": 11,
      "stage": "estimate",
      "roles": [
        "estimator",
        "quantity-surveyor"
      ],
      "cases": [
        "estimate-from-cost-database",
        "build-the-resource-library-and-rates",
        "localize-an-estimate-to-a-region",
        "calculate-with-your-own-efb-rates",
        "build-an-all-in-labour-rate"
      ],
      "caseStarts": {
        "calculate-with-your-own-efb-rates": 261,
        "build-an-all-in-labour-rate": 303
      },
      "routes": [
        "/cost-explorer",
        "/boq",
        "/assemblies",
        "/validation",
        "/resources",
        "/schedule-advanced",
        "/labor-rates",
        "/catalog",
        "/resource-summary"
      ],
      "result": "rate",
      "title": "Kostenquellen und Ressourcen anpassen",
      "titleEn": "Adapt cost sources and resources",
      "description": "Parkettrezept als Katalogreferenz prüfen, Ressourcen ins LV übernehmen und eigene Preisansätze nachvollziehbar anpassen.",
      "produces": "Catalogue resources taken into the bill, with your own price assumptions traceable",
      "duration": 455,
      "cover": "https://i.ytimg.com/vi/uBhNqXw2dm0/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Kostenquellen und Ressourcen anpassen"
        },
        {
          "t": 20,
          "title": "Ein Rezeptbuch für Ihre Bauarbeiten"
        },
        {
          "t": 42,
          "title": "Die Herkunft der Datenbank öffnen"
        },
        {
          "t": 63,
          "title": "Quelle, Sprache und Zielmarkt trennen"
        },
        {
          "t": 84,
          "title": "Die Parkettarbeit wiederfinden"
        },
        {
          "t": 102,
          "title": "Ein kurzer Quellenpass bleibt dabei"
        },
        {
          "t": 124,
          "title": "Sechs Ressourcen erzählen die Leistung"
        },
        {
          "t": 146,
          "title": "Was gehört zum Parkettrezept?"
        },
        {
          "t": 170,
          "title": "Übersetzen und Preise anpassen"
        },
        {
          "t": 195,
          "title": "Gleiche Kostenbasis vergleichen"
        },
        {
          "t": 220,
          "title": "Das Rezept in Ihr LV übernehmen"
        },
        {
          "t": 241,
          "title": "Vierzig Quadratmeter fertigen Boden ansetzen"
        },
        {
          "t": 261,
          "title": "Eine eigene Preisfassung anlegen"
        },
        {
          "t": 280,
          "title": "Eigene Preise brauchen eine Begründung"
        },
        {
          "t": 303,
          "title": "Die beiden Stundenpreise ändern"
        },
        {
          "t": 324,
          "title": "Auch den Gerätesatz anpassen"
        },
        {
          "t": 345,
          "title": "Den gespeicherten Ansatz prüfen"
        },
        {
          "t": 364,
          "title": "Was die Anpassung für die Fläche bedeutet"
        },
        {
          "t": 388,
          "title": "Das ursprüngliche Rezept bleibt erhalten"
        },
        {
          "t": 408,
          "title": "Quelle und Entscheidung gemeinsam weitergeben"
        },
        {
          "t": 430,
          "title": "Vom Katalogrezept zu Ihrem Projektansatz"
        }
      ]
    },
    {
      "id": "V04",
      "youtubeId": "OJ1FMzwY3FM",
      "status": "published",
      "channel": "academy",
      "language": "de",
      "market": "DE",
      "series": "landshut-de",
      "seriesOrder": 12,
      "stage": "estimate",
      "roles": [
        "estimator",
        "quantity-surveyor",
        "project-manager"
      ],
      "cases": [
        "validate-estimate",
        "din-276-cost-plan-for-the-client",
        "control-cost-against-budget"
      ],
      "routes": [
        "/boq",
        "/validation",
        "/reports",
        "/rom-estimate",
        "/5d",
        "/estimate-basis",
        "/finance"
      ],
      "result": "cost",
      "title": "Vom vollständigen LV zur Kostenbasis",
      "titleEn": "From a complete bill to the cost base",
      "description": "50 Arbeiten, Mengen und Ressourcen prüfen, die Quellenfassung sichern und das vollständige Budget nachvollziehen.",
      "produces": "50 items with quantities and resources checked, the source version saved and the full budget traced",
      "duration": 615,
      "cover": "https://i.ytimg.com/vi/OJ1FMzwY3FM/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Vom Aufmaß zur Kostenbasis"
        },
        {
          "t": 19,
          "title": "Welche Kosten gehören zu dieser Summe?"
        },
        {
          "t": 44,
          "title": "Das vorbereitete LV öffnen"
        },
        {
          "t": 68,
          "title": "Die Menge am richtigen Blatt prüfen"
        },
        {
          "t": 92,
          "title": "Die genaue Arbeitsmenge erhalten"
        },
        {
          "t": 112,
          "title": "Den vollständigen Umfang durchgehen"
        },
        {
          "t": 131,
          "title": "Acht Abschnitte ergeben einen Kostenstand"
        },
        {
          "t": 161,
          "title": "Einen Abschnitt bis zur Leistung lesen"
        },
        {
          "t": 183,
          "title": "Den Einheitspreis aufklappen"
        },
        {
          "t": 209,
          "title": "Vier Bestandteile werden zu 34,00 Euro"
        },
        {
          "t": 231,
          "title": "Fläche und Materialverbrauch trennen"
        },
        {
          "t": 252,
          "title": "Zwölf Südfenster bleiben rückverfolgbar"
        },
        {
          "t": 272,
          "title": "HP-01 mit klaren Schnittstellen führen"
        },
        {
          "t": 297,
          "title": "Den Kostenstand in DIN 276 gliedern"
        },
        {
          "t": 318,
          "title": "Prüfung und fachliche Freigabe unterscheiden"
        },
        {
          "t": 349,
          "title": "Einen Cent nachvollziehbar erklären"
        },
        {
          "t": 369,
          "title": "Die Ausgangsfassung aufbewahren"
        },
        {
          "t": 391,
          "title": "Prüfen, entscheiden, festhalten"
        },
        {
          "t": 416,
          "title": "Aus dem fixierten LV ein Budget erzeugen"
        },
        {
          "t": 437,
          "title": "Ursprüngliches und aktuelles Budget abgleichen"
        },
        {
          "t": 462,
          "title": "Drei Ansichten, eine überprüfte Grundlage"
        },
        {
          "t": 482,
          "title": "Das Kostengerüst am richtigen Projekt prüfen"
        },
        {
          "t": 507,
          "title": "Eine Teilansicht ist kein Projektbudget"
        },
        {
          "t": 528,
          "title": "Budgetgrenze und Reserve richtig einordnen"
        },
        {
          "t": 552,
          "title": "Wo wurde der Verlust zweimal angesetzt?"
        },
        {
          "t": 571,
          "title": "Den Verlust im Verbrauch belassen"
        },
        {
          "t": 589,
          "title": "Eine nachvollziehbare Basis für die Vergabe"
        }
      ]
    },
    {
      "id": "EP02_L1",
      "youtubeId": "kEN-F92hNZc",
      "status": "published",
      "channel": "academy",
      "language": "en",
      "series": "playbook-getting-started",
      "seriesOrder": 1,
      "stage": "estimate",
      "roles": [
        "estimator",
        "quantity-surveyor"
      ],
      "cases": [
        "estimate-from-cost-database",
        "build-the-resource-library-and-rates",
        "build-an-assembly-recipe-rate",
        "localize-an-estimate-to-a-region",
        "sense-check-an-estimate-with-benchmarks"
      ],
      "caseStarts": {
        "sense-check-an-estimate-with-benchmarks": 117
      },
      "routes": [
        "/cost-explorer",
        "/boq",
        "/assemblies",
        "/validation",
        "/resources",
        "/schedule-advanced"
      ],
      "result": "rate",
      "title": "Construction Cost Database: Check a Unit Rate",
      "example": {
        "country": "US"
      },
      "description": "Every number in an estimate comes from somewhere. Find a unit rate in a construction cost database, see what it is made of, and adjust it to your market before it goes into a bid.",
      "duration": 242,
      "cover": "https://i.ytimg.com/vi/kEN-F92hNZc/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Cost databases"
        },
        {
          "t": 61,
          "title": "Find a rate"
        },
        {
          "t": 117,
          "title": "Check it"
        },
        {
          "t": 179,
          "title": "Assemblies & more"
        }
      ]
    },
    {
      "id": "EP02_L2",
      "youtubeId": "zGgfX19b3gc",
      "status": "published",
      "channel": "academy",
      "language": "en",
      "series": "playbook-getting-started",
      "seriesOrder": 2,
      "stage": "estimate",
      "roles": [
        "estimator",
        "quantity-surveyor"
      ],
      "cases": [
        "estimate-from-cost-database",
        "estimate-with-your-own-crew-rates",
        "validate-estimate",
        "build-an-all-in-labour-rate"
      ],
      "caseStarts": {
        "build-an-all-in-labour-rate": 171
      },
      "routes": [
        "/cost-explorer",
        "/boq",
        "/assemblies",
        "/validation",
        "/labor-rates",
        "/costs",
        "/waste-factors",
        "/price-index",
        "/reports"
      ],
      "result": "bill",
      "title": "Build a Construction Estimate Step by Step",
      "example": {
        "place": "Denver",
        "country": "US"
      },
      "description": "Build a priced construction estimate from an empty page. A Denver duplex, ten positions in five sections, and every rate traced back to where it came from.",
      "duration": 288,
      "cover": "https://i.ytimg.com/vi/zGgfX19b3gc/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Set up"
        },
        {
          "t": 103,
          "title": "From the database"
        },
        {
          "t": 171,
          "title": "Your own"
        },
        {
          "t": 233,
          "title": "Read it"
        }
      ]
    },
    {
      "id": "EP02_L3",
      "youtubeId": "FRI5_7CsZT0",
      "status": "published",
      "channel": "academy",
      "language": "en",
      "series": "playbook-getting-started",
      "seriesOrder": 3,
      "stage": "estimate",
      "roles": [
        "estimator",
        "commercial-manager"
      ],
      "cases": [
        "cost-risk-and-contingency",
        "validate-estimate"
      ],
      "routes": [
        "/boq",
        "/risks",
        "/reports",
        "/validation"
      ],
      "result": "bill",
      "title": "Construction Pricing: Overhead, Profit & Contingency",
      "example": {
        "country": "US"
      },
      "description": "The estimate says what the job costs. The price says what you charge. Turn a direct cost into a bid price with overhead, profit and contingency, then check it, save a version and export it.",
      "duration": 234,
      "cover": "https://i.ytimg.com/vi/FRI5_7CsZT0/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Markups"
        },
        {
          "t": 88,
          "title": "Checks"
        },
        {
          "t": 130,
          "title": "Versions"
        },
        {
          "t": 166,
          "title": "Export"
        }
      ]
    },
    {
      "id": "CA02",
      "youtubeId": "LejLQ4skfvM",
      "status": "published",
      "channel": "academy",
      "language": "en",
      "market": "CA",
      "series": "playbook-canada-ontario",
      "seriesOrder": 2,
      "stage": "estimate",
      "roles": [
        "estimator",
        "quantity-surveyor"
      ],
      "cases": [
        "walk-the-estimate-from-class-d-to-class-a",
        "take-off-in-metric-and-buy-in-imperial"
      ],
      "routes": [
        "/estimate-basis",
        "/allowances",
        "/boq",
        "/price-index",
        "/reports",
        "/takeoff",
        "/quantities",
        "/validation"
      ],
      "result": "bill",
      "title": "Price a Construction Job",
      "example": {
        "place": "Toronto",
        "country": "CA"
      },
      "description": "Every bid on a Toronto job comes down to one number: your contract price, in Canadian dollars, with markups and bond, before HST. Price six stacked townhomes and turn their cost into that number.",
      "duration": 289,
      "cover": "https://i.ytimg.com/vi/LejLQ4skfvM/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "The price"
        },
        {
          "t": 51,
          "title": "The take-off"
        },
        {
          "t": 125,
          "title": "The markups"
        },
        {
          "t": 211,
          "title": "Class and PDF"
        }
      ]
    },
    {
      "id": "CA03",
      "youtubeId": "7u7Ur3ZFe94",
      "status": "published",
      "channel": "academy",
      "language": "en",
      "market": "CA",
      "series": "playbook-canada-ontario",
      "seriesOrder": 3,
      "stage": "procure",
      "roles": [
        "estimator",
        "procurement-buyer",
        "commercial-manager"
      ],
      "cases": [
        "level-subcontract-bids-and-flow-the-terms-down",
        "compare-bids-and-award",
        "level-bids-to-a-common-scope",
        "tender-from-boq",
        "issue-a-procurement-and-buying-schedule",
        "raise-a-subcontract-order-from-the-award"
      ],
      "caseStarts": {
        "tender-from-boq": 92,
        "issue-a-procurement-and-buying-schedule": 92,
        "raise-a-subcontract-order-from-the-award": 215
      },
      "routes": [
        "/tendering",
        "/subcontractors",
        "/contracts",
        "/reports",
        "/bid-management",
        "/boq",
        "/procurement"
      ],
      "result": "award",
      "title": "Tender Work to Subcontractors",
      "example": {
        "place": "Toronto",
        "country": "CA"
      },
      "description": "Three drywall subtrades priced your townhomes, and one came in more than a fifth lower. In Canada, carry the wrong sub's price in your bid and you may be held to it.",
      "duration": 263,
      "cover": "https://i.ytimg.com/vi/7u7Ur3ZFe94/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "The rules"
        },
        {
          "t": 92,
          "title": "Package and quotes"
        },
        {
          "t": 145,
          "title": "Compare and check"
        },
        {
          "t": 215,
          "title": "Award"
        }
      ]
    },
    {
      "id": "CA04",
      "youtubeId": "b-qv_emcDwc",
      "status": "published",
      "channel": "academy",
      "language": "en",
      "market": "CA",
      "series": "playbook-canada-ontario",
      "seriesOrder": 4,
      "stage": "build",
      "roles": [
        "quantity-surveyor",
        "accountant",
        "contract-administrator",
        "commercial-manager"
      ],
      "cases": [
        "bill-the-monthly-draw-with-holdback-and-a-declaration",
        "prepare-an-interim-payment-application",
        "manage-retention-across-the-supply-chain"
      ],
      "routes": [
        "/boq",
        "/finance",
        "/contracts",
        "/subcontractors",
        "/reports",
        "/value",
        "/reconciliation"
      ],
      "result": "invoice",
      "title": "CCDC 2 Monthly Progress Draw",
      "example": {
        "place": "Ontario",
        "country": "CA"
      },
      "description": "Once a month on a CCDC 2 job you bill the owner for the work in place, and Ontario law makes the owner hold back 10%. Set up the contract, bill a $184,300 draw, and see what stays on your own calendar.",
      "duration": 298,
      "cover": "https://i.ytimg.com/vi/b-qv_emcDwc/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "The rules"
        },
        {
          "t": 99,
          "title": "The contract"
        },
        {
          "t": 182,
          "title": "The draw"
        },
        {
          "t": 256,
          "title": "What stays with you"
        }
      ]
    },
    {
      "id": "CA05",
      "youtubeId": "aQlkuS7ShCM",
      "status": "published",
      "channel": "academy",
      "language": "en",
      "market": "CA",
      "series": "playbook-canada-ontario",
      "seriesOrder": 5,
      "stage": "build",
      "roles": [
        "accountant",
        "finance-manager",
        "commercial-manager",
        "contract-administrator"
      ],
      "cases": [
        "run-the-ontario-prompt-payment-clock-down-the-chain"
      ],
      "routes": [
        "/finance",
        "/payment-clock",
        "/deadlines",
        "/contracts",
        "/correspondence",
        "/reports"
      ],
      "result": "invoice",
      "title": "The Construction Payment Clock",
      "example": {
        "place": "Ontario",
        "country": "CA"
      },
      "description": "In Ontario, an owner has 28 days to pay a proper invoice, and a contract cannot push that back. Start the payment clock on this month's invoice and see every date that matters.",
      "duration": 275,
      "cover": "https://i.ytimg.com/vi/aQlkuS7ShCM/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "The rule"
        },
        {
          "t": 124,
          "title": "Start the clock"
        },
        {
          "t": 172,
          "title": "Read the deadlines"
        },
        {
          "t": 200,
          "title": "When no notice comes"
        }
      ]
    },
    {
      "id": "CA06",
      "youtubeId": "tj7McUl37X0",
      "status": "published",
      "channel": "academy",
      "language": "en",
      "market": "CA",
      "series": "playbook-canada-ontario",
      "seriesOrder": 6,
      "stage": "build",
      "roles": [
        "project-manager",
        "contract-administrator",
        "quantity-surveyor",
        "commercial-manager"
      ],
      "cases": [
        "record-a-change-under-a-ccdc-family-contract",
        "assess-and-price-a-variation",
        "change-to-paid-variation"
      ],
      "routes": [
        "/correspondence",
        "/variations",
        "/changeorders",
        "/contracts",
        "/reports",
        "/boq",
        "/value"
      ],
      "result": "change",
      "title": "Manage Construction Change Orders",
      "example": {
        "country": "CA"
      },
      "description": "Your crew hits rock the soils report never showed, and the work, the price and the finish date all change. See how CCDC 2 handles it, then record the change order, price it against your estimate and get it approved.",
      "duration": 285,
      "cover": "https://i.ytimg.com/vi/tj7McUl37X0/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "The contract"
        },
        {
          "t": 112,
          "title": "Raise and price it"
        },
        {
          "t": 185,
          "title": "Approve it"
        },
        {
          "t": 212,
          "title": "Where it lands"
        }
      ]
    },
    {
      "id": "CA07",
      "youtubeId": "fKGh2e6pJqc",
      "status": "published",
      "channel": "academy",
      "language": "en",
      "market": "CA",
      "series": "playbook-canada-ontario",
      "seriesOrder": 7,
      "stage": "handover",
      "roles": [
        "project-manager",
        "contract-administrator",
        "site-manager",
        "planner"
      ],
      "cases": [
        "close-out-from-substantial-performance-to-the-final-account",
        "clear-the-snag-list-before-handover",
        "schedule-and-track",
        "handover-and-closeout"
      ],
      "caseStarts": {
        "handover-and-closeout": 187
      },
      "routes": [
        "/construction-control",
        "/deadlines",
        "/punchlist",
        "/contracts",
        "/finance",
        "/reports",
        "/inspections",
        "/closeout",
        "/schedule",
        "/schedule-advanced",
        "/field-time",
        "/files"
      ],
      "result": "handover",
      "title": "Schedule to Substantial Performance",
      "example": {
        "country": "CA"
      },
      "description": "On an Ontario job, the day that matters most for your money is the day the work is substantially performed. Take a townhome project from the schedule to that finish line, and see how it starts the holdback clock.",
      "duration": 289,
      "cover": "https://i.ytimg.com/vi/fKGh2e6pJqc/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "The plan"
        },
        {
          "t": 48,
          "title": "The schedule"
        },
        {
          "t": 126,
          "title": "The site record"
        },
        {
          "t": 187,
          "title": "The finish line"
        }
      ]
    },
    {
      "id": "QC01",
      "youtubeId": "CMuMMej0zwM",
      "status": "published",
      "channel": "academy",
      "language": "fr",
      "market": "CA",
      "series": "playbook-quebec",
      "seriesOrder": 1,
      "stage": "define",
      "roles": [
        "project-manager",
        "estimator"
      ],
      "cases": [
        "set-up-a-new-project",
        "price-one-bill-for-hst-pst-and-qst"
      ],
      "caseStarts": {
        "price-one-bill-for-hst-pst-and-qst": 138
      },
      "routes": [
        "/projects/new",
        "/boq",
        "/schedule",
        "/costs",
        "/catalog",
        "/estimate-basis",
        "/reports"
      ],
      "title": "Démarrer avec OpenConstructionERP en français",
      "example": {
        "place": "Québec",
        "country": "CA"
      },
      "description": "L'application s'affiche en français, mais c'est le français de France. Passez votre logiciel de construction en français et faites le lien entre ses mots et ceux d'un chantier québécois.",
      "duration": 226,
      "cover": "https://i.ytimg.com/vi/CMuMMej0zwM/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Pourquoi en français"
        },
        {
          "t": 55,
          "title": "La langue"
        },
        {
          "t": 113,
          "title": "Le projet"
        },
        {
          "t": 138,
          "title": "Les taxes"
        },
        {
          "t": 186,
          "title": "À vous"
        }
      ]
    },
    {
      "id": "QC02",
      "youtubeId": "7eT4lg1ggQY",
      "status": "published",
      "channel": "academy",
      "language": "fr",
      "market": "CA",
      "series": "playbook-quebec",
      "seriesOrder": 2,
      "stage": "estimate",
      "roles": [
        "estimator",
        "quantity-surveyor"
      ],
      "cases": [
        "check-the-rbq-subclass-and-price-gst-and-qst",
        "price-one-bill-for-hst-pst-and-qst",
        "walk-the-estimate-from-class-d-to-class-a"
      ],
      "routes": [
        "/subcontractors",
        "/boq",
        "/reports",
        "/costs",
        "/catalog",
        "/estimate-basis",
        "/allowances",
        "/price-index"
      ],
      "result": "bill",
      "title": "Estimer un projet de construction",
      "example": {
        "place": "Montréal",
        "country": "CA"
      },
      "description": "Toute soumission se résume à un montant : le prix du contrat, avant taxes. Estimez un immeuble locatif à Montréal, ajoutez vos majorations et établissez ce prix.",
      "duration": 258,
      "cover": "https://i.ytimg.com/vi/7eT4lg1ggQY/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Un seul prix"
        },
        {
          "t": 47,
          "title": "Le bordereau"
        },
        {
          "t": 102,
          "title": "Les majorations"
        },
        {
          "t": 165,
          "title": "Taxes, forfait et RBQ"
        },
        {
          "t": 236,
          "title": "Prêt à soumissionner"
        }
      ]
    },
    {
      "id": "QC03",
      "youtubeId": "gmg2h1JcuGI",
      "status": "published",
      "channel": "academy",
      "language": "fr",
      "market": "CA",
      "series": "playbook-quebec",
      "seriesOrder": 3,
      "stage": "procure",
      "roles": [
        "estimator",
        "procurement-buyer",
        "commercial-manager"
      ],
      "cases": [
        "level-subcontract-bids-and-flow-the-terms-down",
        "compare-bids-and-award"
      ],
      "routes": [
        "/tendering",
        "/subcontractors",
        "/contracts",
        "/reports",
        "/bid-management"
      ],
      "result": "award",
      "title": "Soumissions et BSDQ",
      "example": {
        "place": "Québec",
        "country": "CA"
      },
      "description": "Trois sous-traitants ont soumissionné par le BSDQ, et la plus basse soumission est arrivée sans la garantie exigée. Voyez pourquoi vous ne pouvez pas l'accepter, même si l'application la recommande.",
      "duration": 271,
      "cover": "https://i.ytimg.com/vi/gmg2h1JcuGI/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Pourquoi et quoi"
        },
        {
          "t": 31,
          "title": "Les règles du BSDQ"
        },
        {
          "t": 74,
          "title": "Le lot et les soumissions"
        },
        {
          "t": 133,
          "title": "Comparer et appliquer la règle"
        },
        {
          "t": 202,
          "title": "L’attribution"
        },
        {
          "t": 233,
          "title": "À vous"
        }
      ]
    },
    {
      "id": "QC04",
      "youtubeId": "4LTXS0QEkzY",
      "status": "published",
      "channel": "academy",
      "language": "fr",
      "market": "CA",
      "series": "playbook-quebec",
      "seriesOrder": 4,
      "stage": "build",
      "roles": [
        "quantity-surveyor",
        "accountant",
        "contract-administrator"
      ],
      "cases": [
        "bill-the-monthly-draw-with-holdback-and-a-declaration",
        "prepare-an-interim-payment-application",
        "manage-retention-across-the-supply-chain"
      ],
      "routes": [
        "/boq",
        "/finance",
        "/contracts",
        "/subcontractors",
        "/reports",
        "/value",
        "/reconciliation"
      ],
      "result": "invoice",
      "title": "Facturation, retenue et hypothèque légale",
      "example": {
        "place": "Québec",
        "country": "CA"
      },
      "description": "Votre première demande de paiement s'élève à 184 300 $, avec une retenue de 10 % prévue au contrat. Préparez-la, puis voyez comment conserver votre hypothèque légale au Québec.",
      "duration": 277,
      "cover": "https://i.ytimg.com/vi/4LTXS0QEkzY/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Votre première demande"
        },
        {
          "t": 24,
          "title": "Les règles de paiement"
        },
        {
          "t": 66,
          "title": "Le contrat"
        },
        {
          "t": 133,
          "title": "La demande de paiement"
        },
        {
          "t": 169,
          "title": "L’hypothèque légale"
        },
        {
          "t": 240,
          "title": "À vous"
        }
      ]
    },
    {
      "id": "QC05",
      "youtubeId": "IWjtAujWPAA",
      "status": "published",
      "channel": "academy",
      "language": "fr",
      "market": "CA",
      "series": "playbook-quebec",
      "seriesOrder": 5,
      "stage": "handover",
      "roles": [
        "project-manager",
        "site-manager",
        "contract-administrator"
      ],
      "cases": [
        "clear-the-snag-list-before-handover",
        "run-a-handover-acceptance-inspection",
        "close-out-from-substantial-performance-to-the-final-account",
        "handover-and-closeout",
        "defects-liability-period-tracking"
      ],
      "caseStarts": {
        "clear-the-snag-list-before-handover": 79,
        "handover-and-closeout": 79,
        "defects-liability-period-tracking": 135
      },
      "routes": [
        "/punchlist",
        "/inspections",
        "/closeout",
        "/construction-control",
        "/deadlines",
        "/contracts",
        "/finance",
        "/reports",
        "/files"
      ],
      "result": "handover",
      "title": "Réception des travaux et déficiences",
      "example": {
        "place": "Québec",
        "country": "CA"
      },
      "description": "À la fin d'un chantier au Québec, le jour qui compte le plus pour votre argent, c'est la réception des travaux. Suivez vos déficiences jusqu'à leur vérification et voyez ce que la réception déclenche.",
      "duration": 224,
      "cover": "https://i.ytimg.com/vi/IWjtAujWPAA/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Pourquoi la réception"
        },
        {
          "t": 55,
          "title": "La loi"
        },
        {
          "t": 79,
          "title": "La liste des déficiences"
        },
        {
          "t": 135,
          "title": "Retenue et délais"
        },
        {
          "t": 179,
          "title": "À vous"
        }
      ]
    },
    {
      "id": "Budget",
      "youtubeId": "L1DUikMF04Y",
      "status": "published",
      "channel": "academy",
      "language": "fr",
      "series": "playbook-chantier-fr",
      "seriesOrder": 1,
      "stage": "estimate",
      "roles": [
        "estimator",
        "project-manager",
        "commercial-manager"
      ],
      "cases": [
        "control-cost-against-budget",
        "estimate-from-cost-database",
        "write-the-basis-of-estimate"
      ],
      "routes": [
        "/boq",
        "/finance",
        "/reports",
        "/cost-explorer",
        "/assemblies",
        "/validation",
        "/estimate-basis"
      ],
      "result": "cost",
      "title": "Budget de chantier : justifier chaque coût",
      "description": "240 000 USD de budget : pouvez-vous expliquer chaque poste ? Ce tutoriel montre comment relier les quantités, les prix et leurs sources dans OpenConstructionERP.",
      "duration": 306,
      "cover": "https://i.ytimg.com/vi/L1DUikMF04Y/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Comprendre"
        },
        {
          "t": 80,
          "title": "Décomposer"
        },
        {
          "t": 125,
          "title": "Vérifier"
        },
        {
          "t": 195,
          "title": "Revoir"
        },
        {
          "t": 238,
          "title": "Décider"
        }
      ]
    },
    {
      "id": "Achats_Stock",
      "youtubeId": "ZXbWsG_Syuo",
      "status": "published",
      "channel": "academy",
      "language": "fr",
      "series": "playbook-chantier-fr",
      "seriesOrder": 2,
      "stage": "procure",
      "roles": [
        "procurement-buyer",
        "site-manager"
      ],
      "cases": [
        "procure-from-boq",
        "receive-and-reconcile-material-deliveries"
      ],
      "routes": [
        "/boq",
        "/procurement",
        "/site-inventory"
      ],
      "result": "order",
      "title": "Achats et stock : suivre les quantités",
      "description": "1 000 sacs de ciment commandés, 600 encore en stock : comment expliquer l’écart ? Suivez une commande, une réception et une consommation dans OpenConstructionERP.",
      "duration": 277,
      "cover": "https://i.ytimg.com/vi/ZXbWsG_Syuo/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Comprendre"
        },
        {
          "t": 65,
          "title": "Commander"
        },
        {
          "t": 101,
          "title": "Réceptionner"
        },
        {
          "t": 159,
          "title": "Suivre le stock"
        },
        {
          "t": 202,
          "title": "Décider"
        }
      ]
    },
    {
      "id": "Terrain",
      "youtubeId": "5utorRM1fhY",
      "status": "published",
      "channel": "academy",
      "language": "fr",
      "series": "playbook-chantier-fr",
      "seriesOrder": 3,
      "stage": "build",
      "roles": [
        "site-manager",
        "foreman"
      ],
      "cases": [
        "turn-field-time-into-payroll-and-labour-cost",
        "capture-daywork-and-time-and-materials",
        "manage-the-plant-and-equipment-register",
        "run-the-site-day"
      ],
      "caseStarts": {
        "manage-the-plant-and-equipment-register": 85,
        "run-the-site-day": 85
      },
      "routes": [
        "/field-time",
        "/payroll",
        "/finance",
        "/daily-diary",
        "/contracts",
        "/equipment",
        "/reports",
        "/files",
        "/safety"
      ],
      "result": "site",
      "title": "Chantier : suivre les heures et le matériel",
      "description": "64 heures-personnes : quel travail a été réalisé ? Ce tutoriel relie le pointage de l’équipe, un volume mesuré séparément et l’utilisation du matériel dans OpenConstructionERP.",
      "duration": 323,
      "cover": "https://i.ytimg.com/vi/5utorRM1fhY/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Comprendre"
        },
        {
          "t": 85,
          "title": "Relever"
        },
        {
          "t": 131,
          "title": "Approuver"
        },
        {
          "t": 205,
          "title": "Expliquer"
        },
        {
          "t": 251,
          "title": "Agir"
        }
      ]
    },
    {
      "id": "Paiement",
      "youtubeId": "ViuB-ONl5Lk",
      "status": "published",
      "channel": "academy",
      "language": "fr",
      "series": "playbook-chantier-fr",
      "seriesOrder": 4,
      "stage": "build",
      "roles": [
        "accountant",
        "commercial-manager",
        "quantity-surveyor"
      ],
      "cases": [
        "payment-application-and-reconciliation",
        "prepare-an-interim-payment-application",
        "issue-an-electronic-invoice"
      ],
      "routes": [
        "/contracts",
        "/finance",
        "/reconciliation",
        "/boq",
        "/value",
        "/reports"
      ],
      "result": "invoice",
      "title": "Facture et paiement : comprendre le solde",
      "description": "30 000 USD facturés, 18 000 USD reçus : pourquoi reste-t-il 12 000 USD à recevoir ? Suivez les étapes du contrat au règlement dans OpenConstructionERP.",
      "duration": 339,
      "cover": "https://i.ytimg.com/vi/ViuB-ONl5Lk/maxresdefault.jpg",
      "chapters": [
        {
          "t": 0,
          "title": "Comprendre"
        },
        {
          "t": 95,
          "title": "Mesurer"
        },
        {
          "t": 137,
          "title": "Certifier"
        },
        {
          "t": 206,
          "title": "Facturer"
        },
        {
          "t": 248,
          "title": "Suivre"
        }
      ]
    },
    {
      "id": "ddc-walkthrough-v15",
      "youtubeId": "vENnh7bBVVM",
      "status": "published",
      "channel": "ddc",
      "language": "en",
      "series": "ddc-walkthroughs",
      "seriesOrder": 1,
      "stage": "define",
      "roles": [],
      "cases": [
        "project-end-to-end"
      ],
      "routes": [
        "/projects/new",
        "/boq",
        "/schedule",
        "/daily-diary",
        "/closeout"
      ],
      "title": "From a drawing to a priced tender",
      "description": "The whole chain in one take: a drawing becomes a takeoff, the takeoff becomes a bill, the bill carries its markups and the job is inspected on site. One data model underneath all of it.",
      "recordedOn": "15.0",
      "cover": "https://i.ytimg.com/vi/vENnh7bBVVM/maxresdefault.jpg",
      "chapters": []
    },
    {
      "id": "ddc-walkthrough-full",
      "youtubeId": "X06cIaroAeI",
      "status": "published",
      "channel": "ddc",
      "language": "en",
      "series": "ddc-walkthroughs",
      "seriesOrder": 2,
      "stage": "define",
      "roles": [],
      "cases": [
        "project-end-to-end",
        "estimate-from-cost-database"
      ],
      "routes": [
        "/projects/new",
        "/boq",
        "/schedule",
        "/daily-diary",
        "/closeout",
        "/cost-explorer",
        "/assemblies",
        "/validation"
      ],
      "title": "Full product walkthrough",
      "description": "Onboarding, a new project, the bill of quantities, BIM linking, DWG and PDF takeoff, the AI estimate and the portfolio dashboard, in the order you would use them.",
      "recordedOn": "2.0",
      "duration": 720,
      "cover": "https://i.ytimg.com/vi/X06cIaroAeI/maxresdefault.jpg",
      "chapters": []
    },
    {
      "id": "ddc-eth-talk",
      "youtubeId": "R_PQQHXY-rQ",
      "status": "published",
      "channel": "ddc",
      "language": "en",
      "series": "ddc-walkthroughs",
      "seriesOrder": 3,
      "stage": "define",
      "roles": [],
      "cases": [],
      "routes": [],
      "title": "The uberization of construction (ETH Zürich)",
      "description": "A talk at ETH Zürich on how drawings and models turn into quantities, why cost data stays locked up, and what open formats and AI agents change.",
      "duration": 862,
      "cover": "https://i.ytimg.com/vi/R_PQQHXY-rQ/maxresdefault.jpg",
      "chapters": []
    }
  ],
  "cases": {
    "answer-a-gaeb-inquiry-as-a-subcontractor": {
      "titleKey": "cases.answer_a_gaeb_inquiry_as_a_subcontractor.title",
      "titleDefault": "Answer a GAEB inquiry as a subcontractor",
      "region": "DE",
      "stage": "procure",
      "routes": [
        "/bid-management",
        "/gaeb-exchange",
        "/boq",
        "/catalog",
        "/validation"
      ]
    },
    "answer-an-rfi": {
      "titleKey": "cases.answer_an_rfi.title",
      "titleDefault": "Answer an RFI",
      "region": null,
      "stage": "build",
      "routes": [
        "/rfi",
        "/correspondence",
        "/files"
      ]
    },
    "assess-and-price-a-variation": {
      "titleKey": "cases.assess_and_price_a_variation.title",
      "titleDefault": "Assess and price a variation",
      "region": null,
      "stage": "build",
      "routes": [
        "/changeorders",
        "/boq",
        "/value",
        "/contracts",
        "/reports"
      ]
    },
    "bill-the-monthly-draw-with-holdback-and-a-declaration": {
      "titleKey": "cases.bill_the_monthly_draw_with_holdback_and_a_declaration.title",
      "titleDefault": "Bill the monthly draw with holdback and a declaration",
      "region": "CA",
      "stage": "build",
      "routes": [
        "/boq",
        "/finance",
        "/contracts",
        "/subcontractors",
        "/reports"
      ]
    },
    "build-a-preisspiegel-and-award": {
      "titleKey": "cases.build_a_preisspiegel_and_award.title",
      "titleDefault": "Build a Preisspiegel and award",
      "region": "DE",
      "stage": "procure",
      "routes": [
        "/tendering",
        "/subcontractors",
        "/procurement",
        "/reports"
      ]
    },
    "build-an-all-in-labour-rate": {
      "titleKey": "cases.build_an_all_in_labour_rate.title",
      "titleDefault": "Build an all-in labour rate",
      "region": null,
      "stage": "estimate",
      "routes": [
        "/labor-rates",
        "/assemblies"
      ]
    },
    "build-an-assembly-recipe-rate": {
      "titleKey": "cases.build_an_assembly_recipe_rate.title",
      "titleDefault": "Build an assembly (recipe rate)",
      "region": null,
      "stage": "estimate",
      "routes": [
        "/cost-explorer",
        "/assemblies",
        "/boq"
      ]
    },
    "build-the-baseline-programme": {
      "titleKey": "cases.build_the_baseline_programme.title",
      "titleDefault": "Build the baseline programme",
      "region": null,
      "stage": "plan",
      "routes": [
        "/boq",
        "/schedule",
        "/schedule-advanced",
        "/reports"
      ]
    },
    "build-the-resource-library-and-rates": {
      "titleKey": "cases.build_the_resource_library_and_rates.title",
      "titleDefault": "Build the resource library and rates",
      "region": null,
      "stage": "estimate",
      "routes": [
        "/resources",
        "/assemblies",
        "/schedule-advanced"
      ]
    },
    "calculate-with-your-own-efb-rates": {
      "titleKey": "cases.calculate_with_your_own_efb_rates.title",
      "titleDefault": "Calculate with your own rates for the EFB price sheets",
      "region": "DE",
      "stage": "estimate",
      "routes": [
        "/labor-rates",
        "/catalog",
        "/assemblies",
        "/boq",
        "/resource-summary"
      ]
    },
    "capture-daywork-and-time-and-materials": {
      "titleKey": "cases.capture_daywork_and_time_and_materials.title",
      "titleDefault": "Capture daywork and time and materials",
      "region": null,
      "stage": "build",
      "routes": [
        "/field-time",
        "/daily-diary",
        "/contracts"
      ]
    },
    "change-to-paid-variation": {
      "titleKey": "cases.change_to_paid_variation.title",
      "titleDefault": "Turn a change into a paid variation",
      "region": null,
      "stage": "build",
      "routes": [
        "/changeorders",
        "/contracts"
      ]
    },
    "check-the-rbq-subclass-and-price-gst-and-qst": {
      "titleKey": "cases.check_the_rbq_subclass_and_price_gst_and_qst.title",
      "titleDefault": "Check the RBQ subclass and price GST and QST in parallel",
      "region": "CA",
      "stage": "procure",
      "routes": [
        "/subcontractors",
        "/boq",
        "/reports"
      ]
    },
    "clear-the-snag-list-before-handover": {
      "titleKey": "cases.clear_the_snag_list_before_handover.title",
      "titleDefault": "Clear the snag list before handover",
      "region": null,
      "stage": "handover",
      "routes": [
        "/punchlist",
        "/inspections",
        "/closeout"
      ]
    },
    "close-out-from-substantial-performance-to-the-final-account": {
      "titleKey": "cases.close_out_from_substantial_performance_to_the_final_account.title",
      "titleDefault": "Close out from substantial performance to the final account",
      "region": "CA",
      "stage": "handover",
      "routes": [
        "/construction-control",
        "/deadlines",
        "/punchlist",
        "/contracts",
        "/finance",
        "/reports"
      ]
    },
    "compare-bids-and-award": {
      "titleKey": "cases.compare_bids_and_award.title",
      "titleDefault": "Compare bids and award",
      "region": null,
      "stage": "procure",
      "routes": [
        "/tendering",
        "/bid-management",
        "/reports"
      ]
    },
    "control-cost-against-budget": {
      "titleKey": "cases.control_cost_against_budget.title",
      "titleDefault": "Control cost against budget",
      "region": null,
      "stage": "build",
      "routes": [
        "/boq",
        "/finance",
        "/reports"
      ]
    },
    "cost-risk-and-contingency": {
      "titleKey": "cases.cost_risk_and_contingency.title",
      "titleDefault": "Set contingency from cost risk",
      "region": null,
      "stage": "estimate",
      "routes": [
        "/boq",
        "/risks",
        "/reports"
      ]
    },
    "crew-and-plant-lookahead-balance": {
      "titleKey": "cases.crew_and_plant_lookahead_balance.title",
      "titleDefault": "Balance crews and plant across the programme",
      "region": null,
      "stage": "plan",
      "routes": [
        "/schedule-advanced",
        "/field-time",
        "/reports"
      ]
    },
    "defects-liability-period-tracking": {
      "titleKey": "cases.defects_liability_period_tracking.title",
      "titleDefault": "Manage the defects liability period after occupation",
      "region": null,
      "stage": "operate",
      "routes": [
        "/punchlist",
        "/closeout"
      ]
    },
    "din-276-cost-plan-for-the-client": {
      "titleKey": "cases.din_276_cost_plan_for_the_client.title",
      "titleDefault": "Report a DIN 276 cost plan to the client",
      "region": "DE",
      "stage": "estimate",
      "routes": [
        "/rom-estimate",
        "/boq",
        "/5d",
        "/validation",
        "/estimate-basis",
        "/reports"
      ]
    },
    "estimate-from-cost-database": {
      "titleKey": "cases.estimate_from_cost_database.title",
      "titleDefault": "Estimate from a cost database",
      "region": null,
      "stage": "estimate",
      "routes": [
        "/cost-explorer",
        "/boq",
        "/assemblies",
        "/validation"
      ]
    },
    "estimate-with-your-own-crew-rates": {
      "titleKey": "cases.estimate_with_your_own_crew_rates.title",
      "titleDefault": "Estimate with your own crew rates",
      "region": "US",
      "stage": "estimate",
      "routes": [
        "/labor-rates",
        "/costs",
        "/waste-factors",
        "/assemblies",
        "/price-index"
      ]
    },
    "feasibility-budget-before-design": {
      "titleKey": "cases.feasibility_budget_before_design.title",
      "titleDefault": "Estimate a feasibility budget before design",
      "region": null,
      "stage": "define",
      "routes": [
        "/cost-explorer",
        "/boq",
        "/reports"
      ]
    },
    "get-a-key-document-signed-off": {
      "titleKey": "cases.get_a_key_document_signed_off.title",
      "titleDefault": "Get a key document signed off",
      "region": null,
      "stage": "handover",
      "routes": [
        "/files",
        "/signing"
      ]
    },
    "handover-and-closeout": {
      "titleKey": "cases.handover_and_closeout.title",
      "titleDefault": "Hand over and close out",
      "region": null,
      "stage": "handover",
      "routes": [
        "/punchlist",
        "/inspections",
        "/files",
        "/closeout"
      ]
    },
    "import-a-gaeb-tender-into-a-priced-boq": {
      "titleKey": "cases.import_a_gaeb_tender_into_a_priced_boq.title",
      "titleDefault": "Import a GAEB tender into a priced BOQ",
      "region": "DE",
      "stage": "estimate",
      "routes": [
        "/files",
        "/boq",
        "/catalog",
        "/validation",
        "/gaeb-exchange"
      ]
    },
    "issue-a-controlled-drawing-revision": {
      "titleKey": "cases.issue_a_controlled_drawing_revision.title",
      "titleDefault": "Issue a controlled drawing revision",
      "region": null,
      "stage": "build",
      "routes": [
        "/files",
        "/correspondence",
        "/inspections"
      ]
    },
    "issue-a-procurement-and-buying-schedule": {
      "titleKey": "cases.issue_a_procurement_and_buying_schedule.title",
      "titleDefault": "Issue a procurement and buying schedule",
      "region": null,
      "stage": "procure",
      "routes": [
        "/boq",
        "/procurement",
        "/tendering",
        "/subcontractors",
        "/reports"
      ]
    },
    "issue-an-electronic-invoice": {
      "titleKey": "cases.issue_an_electronic_invoice.title",
      "titleDefault": "Issue an electronic invoice",
      "region": null,
      "stage": "build",
      "routes": [
        "/contracts",
        "/finance",
        "/reconciliation"
      ]
    },
    "level-bids-to-a-common-scope": {
      "titleKey": "cases.level_bids_to_a_common_scope.title",
      "titleDefault": "Level bids to a common scope",
      "region": null,
      "stage": "procure",
      "routes": [
        "/bid-management",
        "/tendering"
      ]
    },
    "level-subcontract-bids-and-flow-the-terms-down": {
      "titleKey": "cases.level_subcontract_bids_and_flow_the_terms_down.title",
      "titleDefault": "Level subcontract bids and flow the terms down",
      "region": "CA",
      "stage": "procure",
      "routes": [
        "/tendering",
        "/subcontractors",
        "/contracts",
        "/reports"
      ]
    },
    "localize-an-estimate-to-a-region": {
      "titleKey": "cases.localize_an_estimate_to_a_region.title",
      "titleDefault": "Localize an estimate to a region",
      "region": null,
      "stage": "estimate",
      "routes": [
        "/cost-explorer",
        "/boq",
        "/validation"
      ]
    },
    "manage-retention-across-the-supply-chain": {
      "titleKey": "cases.manage_retention_across_the_supply_chain.title",
      "titleDefault": "Manage retention across the supply chain",
      "region": null,
      "stage": "build",
      "routes": [
        "/contracts",
        "/subcontractors",
        "/finance",
        "/reconciliation"
      ]
    },
    "manage-the-plant-and-equipment-register": {
      "titleKey": "cases.manage_the_plant_and_equipment_register.title",
      "titleDefault": "Manage the plant and equipment register",
      "region": null,
      "stage": "build",
      "routes": [
        "/equipment",
        "/field-time",
        "/reports"
      ]
    },
    "payment-application-and-reconciliation": {
      "titleKey": "cases.payment_application_and_reconciliation.title",
      "titleDefault": "Payment application and reconciliation",
      "region": null,
      "stage": "build",
      "routes": [
        "/contracts",
        "/finance",
        "/reconciliation"
      ]
    },
    "prepare-an-interim-payment-application": {
      "titleKey": "cases.prepare_an_interim_payment_application.title",
      "titleDefault": "Prepare an interim payment application",
      "region": null,
      "stage": "build",
      "routes": [
        "/boq",
        "/value",
        "/finance",
        "/reports",
        "/reconciliation"
      ]
    },
    "price-one-bill-for-hst-pst-and-qst": {
      "titleKey": "cases.price_one_bill_for_hst_pst_and_qst.title",
      "titleDefault": "Price one bill for HST, PST and QST",
      "region": "CA",
      "stage": "estimate",
      "routes": [
        "/costs",
        "/catalog",
        "/boq",
        "/estimate-basis",
        "/reports"
      ]
    },
    "procure-from-boq": {
      "titleKey": "cases.procure_from_boq.title",
      "titleDefault": "Procure materials from the BOQ",
      "region": null,
      "stage": "procure",
      "routes": [
        "/boq",
        "/procurement"
      ]
    },
    "produce-a-short-interval-lookahead": {
      "titleKey": "cases.produce_a_short_interval_lookahead.title",
      "titleDefault": "Produce a short-interval lookahead",
      "region": null,
      "stage": "plan",
      "routes": [
        "/schedule",
        "/schedule-advanced",
        "/reports"
      ]
    },
    "project-end-to-end": {
      "titleKey": "cases.project_end_to_end.title",
      "titleDefault": "Set up a project and hand it over",
      "region": null,
      "stage": "plan",
      "routes": [
        "/projects/new",
        "/boq",
        "/schedule",
        "/daily-diary",
        "/closeout"
      ]
    },
    "protect-the-programme-from-a-long-lead-item": {
      "titleKey": "cases.protect_the_programme_from_a_long_lead_item.title",
      "titleDefault": "Protect the programme from a long-lead item",
      "region": null,
      "stage": "plan",
      "routes": [
        "/procurement",
        "/schedule-advanced",
        "/reports"
      ]
    },
    "quantities-from-bim": {
      "titleKey": "cases.quantities_from_bim.title",
      "titleDefault": "Get quantities from a BIM model",
      "region": null,
      "stage": "design",
      "routes": [
        "/bim",
        "/boq",
        "/validation"
      ]
    },
    "raise-a-subcontract-order-from-the-award": {
      "titleKey": "cases.raise_a_subcontract_order_from_the_award.title",
      "titleDefault": "Raise a subcontract order from the award",
      "region": null,
      "stage": "procure",
      "routes": [
        "/bid-management",
        "/procurement",
        "/subcontractors",
        "/contracts"
      ]
    },
    "receive-and-reconcile-material-deliveries": {
      "titleKey": "cases.receive_and_reconcile_material_deliveries.title",
      "titleDefault": "Receive and reconcile material deliveries",
      "region": null,
      "stage": "build",
      "routes": [
        "/site-inventory",
        "/procurement"
      ]
    },
    "reconcile-a-drawing-issue-against-the-index": {
      "titleKey": "cases.reconcile_a_drawing_issue_against_the_index.title",
      "titleDefault": "Reconcile a drawing issue against the index",
      "region": null,
      "stage": "build",
      "routes": [
        "/files",
        "/plan-room",
        "/files/transmittals"
      ]
    },
    "record-a-change-under-a-ccdc-family-contract": {
      "titleKey": "cases.record_a_change_under_a_ccdc_family_contract.title",
      "titleDefault": "Record a change under a CCDC-family contract",
      "region": "CA",
      "stage": "build",
      "routes": [
        "/correspondence",
        "/variations",
        "/changeorders",
        "/contracts",
        "/reports"
      ]
    },
    "run-a-handover-acceptance-inspection": {
      "titleKey": "cases.run_a_handover_acceptance_inspection.title",
      "titleDefault": "Run a handover acceptance inspection",
      "region": null,
      "stage": "handover",
      "routes": [
        "/inspections",
        "/punchlist",
        "/closeout"
      ]
    },
    "run-a-three-way-match-before-paying-a-supplier": {
      "titleKey": "cases.run_a_three_way_match_before_paying_a_supplier.title",
      "titleDefault": "Run a three-way match before paying a supplier",
      "region": null,
      "stage": "build",
      "routes": [
        "/procurement",
        "/reconciliation",
        "/finance"
      ]
    },
    "run-the-ontario-prompt-payment-clock-down-the-chain": {
      "titleKey": "cases.run_the_ontario_prompt_payment_clock_down_the_chain.title",
      "titleDefault": "Run the Ontario prompt-payment clock down the chain",
      "region": "CA",
      "stage": "build",
      "routes": [
        "/finance",
        "/payment-clock",
        "/deadlines",
        "/contracts",
        "/correspondence",
        "/reports"
      ]
    },
    "run-the-site-day": {
      "titleKey": "cases.run_the_site_day.title",
      "titleDefault": "Run the site day",
      "region": null,
      "stage": "build",
      "routes": [
        "/daily-diary",
        "/field-time",
        "/files",
        "/safety"
      ]
    },
    "schedule-and-track": {
      "titleKey": "cases.schedule_and_track.title",
      "titleDefault": "Build a baseline and track progress",
      "region": null,
      "stage": "plan",
      "routes": [
        "/schedule",
        "/schedule-advanced",
        "/field-time"
      ]
    },
    "sense-check-an-estimate-with-benchmarks": {
      "titleKey": "cases.sense_check_an_estimate_with_benchmarks.title",
      "titleDefault": "Sense-check an estimate against benchmarks",
      "region": null,
      "stage": "estimate",
      "routes": [
        "/boq",
        "/cost-explorer",
        "/validation"
      ]
    },
    "set-up-a-new-project": {
      "titleKey": "cases.set_up_a_new_project.title",
      "titleDefault": "Set up a new project",
      "region": null,
      "stage": "define",
      "routes": [
        "/projects/new",
        "/boq",
        "/schedule"
      ]
    },
    "set-up-the-common-data-environment": {
      "titleKey": "cases.set_up_the_common_data_environment.title",
      "titleDefault": "Set up the common data environment",
      "region": null,
      "stage": "design",
      "routes": [
        "/cde",
        "/files",
        "/governance",
        "/coordination"
      ]
    },
    "take-off-in-metric-and-buy-in-imperial": {
      "titleKey": "cases.take_off_in_metric_and_buy_in_imperial.title",
      "titleDefault": "Take off in metric and buy in imperial",
      "region": "CA",
      "stage": "estimate",
      "routes": [
        "/takeoff",
        "/quantities",
        "/boq",
        "/validation",
        "/reports"
      ]
    },
    "takeoff-from-dwg": {
      "titleKey": "cases.takeoff_from_dwg.title",
      "titleDefault": "Measure quantities from a DWG",
      "region": null,
      "stage": "design",
      "routes": [
        "/dwg-takeoff",
        "/takeoff",
        "/boq"
      ]
    },
    "takeoff-quantities-from-a-pdf-plan": {
      "titleKey": "cases.takeoff_quantities_from_a_pdf_plan.title",
      "titleDefault": "Take off quantities from a PDF plan",
      "region": "DE",
      "stage": "estimate",
      "routes": [
        "/files",
        "/takeoff",
        "/quantities",
        "/boq"
      ]
    },
    "tender-from-boq": {
      "titleKey": "cases.tender_from_boq.title",
      "titleDefault": "Run a tender from a BOQ",
      "region": null,
      "stage": "procure",
      "routes": [
        "/boq",
        "/tendering"
      ]
    },
    "turn-field-time-into-payroll-and-labour-cost": {
      "titleKey": "cases.turn_field_time_into_payroll_and_labour_cost.title",
      "titleDefault": "Turn field time into payroll and labour cost",
      "region": null,
      "stage": "build",
      "routes": [
        "/field-time",
        "/payroll",
        "/finance"
      ]
    },
    "update-the-programme-and-reforecast": {
      "titleKey": "cases.update_the_programme_and_reforecast.title",
      "titleDefault": "Update the programme and reforecast",
      "region": null,
      "stage": "plan",
      "routes": [
        "/field-time",
        "/schedule",
        "/schedule-advanced",
        "/change-intelligence",
        "/reports"
      ]
    },
    "validate-estimate": {
      "titleKey": "cases.validate_estimate.title",
      "titleDefault": "Check an estimate before you send it",
      "region": null,
      "stage": "estimate",
      "routes": [
        "/boq",
        "/validation",
        "/reports"
      ]
    },
    "walk-the-estimate-from-class-d-to-class-a": {
      "titleKey": "cases.walk_the_estimate_from_class_d_to_class_a.title",
      "titleDefault": "Walk the estimate from Class D to Class A",
      "region": "CA",
      "stage": "estimate",
      "routes": [
        "/estimate-basis",
        "/allowances",
        "/boq",
        "/price-index",
        "/reports"
      ]
    },
    "win-a-gaeb-tender-from-lv-to-angebot": {
      "titleKey": "cases.win_a_gaeb_tender_from_lv_to_angebot.title",
      "titleDefault": "Win a GAEB tender, from the LV to the Angebot",
      "region": "DE",
      "stage": "procure",
      "routes": [
        "/files",
        "/gaeb-exchange",
        "/costs",
        "/boq",
        "/validation",
        "/files/transmittals"
      ]
    },
    "write-the-basis-of-estimate": {
      "titleKey": "cases.write_the_basis_of_estimate.title",
      "titleDefault": "Write the basis of estimate",
      "region": null,
      "stage": "estimate",
      "routes": [
        "/estimate-basis",
        "/boq",
        "/reports"
      ]
    }
  }
};
