# DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
# Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
"""A generated report reads in the language it was asked for.

Every word the reporting module put in front of a reader used to be an
English literal - section headings, field labels, the metadata line, the
"no data" notice, ``Yes`` / ``No``, the ``lang`` attribute - so a reader who
set the interface to German downloaded an English PDF. These tests pin the
three things that can quietly undo the fix:

* the English document did not move, so a locale nobody asked for changed
  nothing;
* a German document actually differs from the English one, rather than
  merely rendering without error;
* the catalogue covers every heading the platform itself emits, so a new
  section added to ``SYSTEM_TEMPLATES`` or ``_DEFAULT_SECTIONS`` without a
  translation fails here instead of shipping as an English island.

Pure unit tests: no DB, no app boot. The renderer, the exporters and the
catalogue all import cleanly on their own; the two service-level tests build
the service with ``object.__new__`` and mock repositories, the way
``test_reporting_error_logging`` does.
"""

from __future__ import annotations

import io
import uuid
from typing import Any
from unittest.mock import AsyncMock, MagicMock

import pytest

from app.modules.reporting import report_translations as cat
from app.modules.reporting.exporters import export_report
from app.modules.reporting.renderer import _DEFAULT_SECTIONS, ReportRenderer
from app.modules.reporting.service import SYSTEM_TEMPLATES, ReportingService

REPORT_TYPES = tuple(_DEFAULT_SECTIONS)

SNAPSHOT: dict[str, Any] = {
    "header": {
        "name": "Skyline Tower",
        "status": "active",
        "planned_start": "2026-01-01",
        "on_track": True,
    },
    "overview": {"name": "Skyline Tower", "schedule_progress_pct": "41%"},
    "kpi": {"cpi": "1.02", "spi": "0.97", "budget_consumed_pct": "38%"},
    "schedule": {"progress_pct": "41%"},
    "risk": {"risk_score_avg": "3.4"},
    "issues": {"open_rfis": 4, "open_defects": 7},
    "summary": {"budget": "1000 EUR", "committed": "800 EUR", "actual": "600 EUR"},
    "cashflow": {"payable": "10 EUR", "receivable": "20 EUR", "net_cash_flow": "10 EUR"},
    "breakdown": [{"name": "Concrete", "budget": "5 EUR", "committed": True}],
    "progress": {
        "overall_pct": 41.0,
        "as_of_date": "2026-08-01",
        "recorded_by": "Field Team",
        "milestone_status": [{"period": "2026-W31", "percent": 41.0, "entry_count": 3}],
    },
    "photos": {"photo_gallery": ["https://example.invalid/p.jpg"]},
    "ai_narrative": {"text": "Work is on track.", "confidence": 0.8},
    "currency": "EUR",
}

_META = {
    "title": "Q3 Report",
    "project_name": "Skyline Tower",
    "generated_at": "2026-08-29T10:00:00",
}


def _html(locale: str | None = None, snapshot: Any = SNAPSHOT, report_type: str = "project_status") -> str:
    kwargs = {} if locale is None else {"locale": locale}
    return ReportRenderer().render_html(
        report_type=report_type,
        template_data=None,
        data_snapshot=snapshot,
        **_META,
        **kwargs,
    )


def _export(fmt: str, locale: str, report_type: str = "project_status") -> bytes:
    _, _, blob = export_report(
        fmt=fmt,
        report_type=report_type,
        currency="EUR",
        template_data=None,
        data_snapshot=SNAPSHOT,
        locale=locale,
        **_META,
    )
    return blob


# ── The English document did not move ─────────────────────────────────────


@pytest.mark.parametrize("report_type", REPORT_TYPES)
def test_the_default_render_is_the_english_render(report_type: str) -> None:
    """Omitting the locale and asking for English produce the same bytes.

    The point of the default is that every existing caller - the cron
    worker, ``generate_report``, the older tests - keeps getting exactly
    what it got before the catalogue existed.
    """
    assert _html(None, report_type=report_type) == _html("en", report_type=report_type)


def test_the_english_document_still_carries_the_literals_it_shipped_with() -> None:
    """A spot check that the English values were copied, not rewritten.

    Byte equality with the default (above) cannot catch a catalogue whose
    English column drifted, because both sides read the same drifted value.
    These are the strings as they stood before the catalogue.
    """
    doc = _html("en")
    for literal in (
        '<html lang="en">',
        "Project: <strong>Skyline Tower</strong>",
        "&middot; Type: project_status",
        "&middot; Generated: 2026-08-29T10:00:00",
        "<h2>Key Performance Indicators</h2>",
        "<th>Open Rfis</th>",
        "<th>Cpi</th>",
        "Generated by OpenConstructionERP at 2026-08-29T10:00:00.",
        "Review before sharing with the client.",
    ):
        assert literal in doc, literal

    empty = _html("en", snapshot={})
    assert "<h2>No data available</h2>" in empty
    assert "Verify that the source modules (finance, schedule, safety, etc.)" in empty


# ── A German document is a different document ─────────────────────────────


@pytest.mark.parametrize("report_type", REPORT_TYPES)
def test_a_german_report_is_not_the_english_one(report_type: str) -> None:
    """Two locales that render equal would mean the locale never arrived.

    Asserting only that a German render succeeds proves nothing: the old
    code succeeded too, in English. The inequality is the finding.
    """
    assert _html("de", report_type=report_type) != _html("en", report_type=report_type)


def test_german_reaches_the_chrome_the_labels_and_the_lang_attribute() -> None:
    doc = _html("de")
    assert '<html lang="de">' in doc
    assert "Projekt: <strong>Skyline Tower</strong>" in doc
    assert "<h2>Wesentliche Leistungskennzahlen</h2>" in doc
    assert "<th>Offene RFIs</th>" in doc
    assert "Erstellt von OpenConstructionERP am" in doc
    assert "Vor der Weitergabe an den Auftraggeber prüfen." in doc
    # Booleans are chrome too, and they used to read Yes / No in every
    # language because the renderer returned the literal directly.
    assert "<td>Ja</td>" in doc


def test_russian_empty_snapshot_notice_is_russian() -> None:
    doc = _html("ru", snapshot={})
    assert '<html lang="ru">' in doc
    assert "Нет данных" in doc
    assert "No data available" not in doc


@pytest.mark.parametrize("fmt", ["csv", "xlsx"])
def test_every_download_format_carries_the_language(fmt: str) -> None:
    """The exporters read the same catalogue, so a download is not an
    English island next to a translated on-screen view.

    PDF is asserted separately: its bytes carry a creation timestamp, so two
    PDFs are never equal and inequality would pass without the locale ever
    arriving.
    """
    assert _export(fmt, "de") != _export(fmt, "en")


def test_the_csv_preamble_and_column_headers_are_translated() -> None:
    text = _export("csv", "de").decode("utf-8-sig")
    assert "Projekt,Skyline Tower" in text
    assert "Feld,Wert" in text
    assert "Field,Value" not in text
    # evidence_header has always taken a locale; reporting never passed one.
    assert "Erstellt," in text


def test_the_xlsx_worksheet_and_headers_are_translated() -> None:
    from openpyxl import load_workbook

    ws = load_workbook(io.BytesIO(_export("xlsx", "de"))).active
    assert ws.title == "Bericht"
    values = {str(c.value) for row in ws.iter_rows() for c in row if c.value is not None}
    assert "Feld" in values
    assert "Wert" in values
    assert "Field" not in values


def test_the_pdf_document_metadata_names_the_language_it_was_written_in() -> None:
    """The PDF subject is the one string in that file the reader's own tools
    surface, and reportlab writes it into the document info dict where it is
    findable in the raw bytes."""
    assert b"Projektbericht" in _export("pdf", "de")
    assert b"Project Report" in _export("pdf", "en")


# ── Fallback behaviour ────────────────────────────────────────────────────


def test_a_language_the_catalogue_does_not_hold_falls_back_to_english() -> None:
    """Japanese is a supported interface language and not a supported
    report language, which is exactly why the routes must declare what
    they produced rather than what was asked for."""
    assert cat.resolve_report_locale("ja", None) == "en"
    assert _html("ja") == _html("en")


def test_a_regional_code_resolves_through_its_base_language() -> None:
    assert cat.resolve_report_locale("de-AT", None) == "de"
    assert cat.normalize_report_locale("DE") == "de"


def test_the_query_parameter_outranks_the_header() -> None:
    assert cat.resolve_report_locale("ru", "de,en;q=0.5") == "ru"
    assert cat.resolve_report_locale(None, "de,en;q=0.5") == "de"
    assert cat.resolve_report_locale(None, "ja,ru;q=0.5") == "ru"


# ── Catalogue integrity ───────────────────────────────────────────────────


@pytest.mark.parametrize(
    "table_name",
    ["_STRINGS", "_SECTION_TITLES", "_FIELD_LABELS"],
)
def test_every_supported_language_holds_every_key(table_name: str) -> None:
    """A missing key silently serves English inside an otherwise translated
    document, which reads as a half-finished translation rather than as a
    fallback."""
    table: dict[str, dict[str, str]] = getattr(cat, table_name)
    assert set(table) == set(cat.SUPPORTED_REPORT_LOCALES)
    english = set(table["en"])
    for locale in cat.SUPPORTED_REPORT_LOCALES:
        assert set(table[locale]) == english, f"{table_name}[{locale}]"


def test_no_translated_value_is_left_as_the_english_one() -> None:
    """A copied English value is the usual shape of an unfinished locale.

    A handful legitimately match across languages - ``Name``, ``Status``,
    ``Budget``, ``Phase``, the two acronyms - so the assertion is on the
    bulk, not on every cell.
    """
    for table_name in ("_STRINGS", "_SECTION_TITLES", "_FIELD_LABELS"):
        table: dict[str, dict[str, str]] = getattr(cat, table_name)
        for locale in cat.SUPPORTED_REPORT_LOCALES:
            if locale == "en":
                continue
            copied = [k for k, v in table[locale].items() if v == table["en"][k]]
            assert len(copied) <= 6, f"{table_name}[{locale}] copies English for {copied}"


def test_every_heading_the_platform_emits_is_translatable() -> None:
    """The gate that catches a new section shipped without a translation.

    Both sources of a heading are checked: the renderer's built-in defaults
    and the ``SYSTEM_TEMPLATES`` rows, which are seeded into the database as
    data and therefore reach the renderer as English strings rather than as
    ids.
    """
    headings = {s["title"] for sections in _DEFAULT_SECTIONS.values() for s in sections}
    headings.update(s["title"] for tmpl in SYSTEM_TEMPLATES for s in tmpl["template_data"]["sections"] if "title" in s)
    headings.add("Summary")  # the generic fallback in _resolve_sections

    untranslated = [h for h in sorted(headings) if cat.section_title(h, "de") == h]
    assert untranslated == []


def test_a_heading_a_user_wrote_is_left_alone() -> None:
    """Localizing by the English text must not mean overwriting text that
    was never ours."""
    custom = "Weekly walkthrough - Block C"
    assert cat.section_title(custom, "de") == custom

    doc = ReportRenderer().render_html(
        report_type="project_status",
        template_data={"sections": [{"id": "kpi", "title": custom}]},
        data_snapshot=SNAPSHOT,
        locale="de",
        **_META,
    )
    assert custom in doc


def test_an_unknown_field_key_still_gets_a_readable_label() -> None:
    """A caller-supplied snapshot may carry any keys at all; those keep the
    Title-Cased fallback the renderer used before the catalogue."""
    assert cat.field_label("some_custom_metric", "de") == "Some Custom Metric"
    assert cat.field_label("net_cash_flow", "de") == "Netto-Zahlungsfluss"


# ── The stored body must not be served under another language ─────────────


def _report_row() -> MagicMock:
    report = MagicMock()
    report.id = uuid.uuid4()
    report.project_id = uuid.uuid4()
    report.template_id = None
    report.report_type = "project_status"
    report.title = "Q3 Report"
    report.generated_at = "2026-08-29T10:00:00"
    report.currency = "EUR"
    report.data_snapshot = SNAPSHOT
    report.storage_key = "reports/x/y.html"
    return report


def _service(report: MagicMock) -> ReportingService:
    svc = object.__new__(ReportingService)
    svc.session = MagicMock()
    svc.kpi_repo = MagicMock()
    svc.template_repo = MagicMock()
    svc.report_repo = MagicMock()
    svc.report_repo.get_by_id = AsyncMock(return_value=report)
    return svc


async def test_a_german_body_is_re_rendered_not_read_back_from_storage() -> None:
    """The stored HTML is written once, in English, at generation time.

    Handing it back for a German request would put a German
    ``Content-Language`` on an English body - the mislabelling
    ``app.core.document_locale`` exists to prevent. The storage backend is
    not stubbed here on purpose: reaching it at all would raise.
    """
    svc = _service(_report_row())

    _, body = await svc.get_report_content(uuid.uuid4(), locale="de")

    assert '<html lang="de">' in body
    assert "Wesentliche Leistungskennzahlen" in body


async def test_an_html_download_in_another_language_does_not_reuse_the_stored_body() -> None:
    """``export_report_file`` short-circuits ``fmt=html`` to the stored
    blob. That short-circuit is correct only for the language the blob was
    written in."""
    svc = _service(_report_row())

    _, _, blob = await svc.export_report_file(uuid.uuid4(), "html", locale="de")

    assert b'<html lang="de">' in blob
