# DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
# Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
from __future__ import annotations

from app.core.demo_projects import DemoTemplate

# ---------------------------------------------------------------------------
# Flagship demo pack: India / CPWD-style rates - IT Park / Software Campus,
# Bengaluru (Whitefield, ORR tech corridor), Karnataka.
# ---------------------------------------------------------------------------
# A privately developed, multi-tower commercial Grade-A IT / software campus
# (warm-shell office space for SEZ / IT-ITeS tenants) - distinct from the
# Government Office Complex demo for New Delhi. Costing follows a CPWD DSR
# 2021 sub-head structure adapted to Bengaluru 2026 market rates; item
# references carry CPWD DSR clause numbers in the classification dict
# (key "cpwd"), with a MasterFormat division supplied as the platform
# fallback standard. Rates are GST-exclusive (GST 18% carried as a separate
# markup line). Design intent conforms to IS 456 (RCC), IS 1893:2016
# (seismic - Zone II), IS 13920 (ductile detailing), IS 875 (loads),
# IS 800 (structural steel), NBC 2016 and the Karnataka (BBMP / KMBR)
# building bye-laws. IGBC Green Rating (LEED v4 BD+C: Core & Shell aligned).
# ---------------------------------------------------------------------------

TEMPLATE = DemoTemplate(
    demo_id="it-park-bangalore",
    project_name="IT Park Campus - Bengaluru (Whitefield)",
    project_description=(
        "Development of a Grade-A IT / software campus on the Whitefield "
        "technology corridor, Bengaluru, comprising two 2B+G+12 office "
        "towers, a shared amenity block (food court, gym, daycare, "
        "experience centre) and a two-level common basement for car and "
        "two-wheeler parking, utilities and services. Leasable area approx. "
        "13.5 lakh sq ft (~125,400 m2 GFA) of warm-shell office floor plates "
        "with an additional ~3.2 lakh sq ft (~29,700 m2) of basement. RCC "
        "special moment-resisting framed structure (SMRF) on a raft "
        "foundation, designed to IS 456 and IS 1893:2016 for Seismic Zone II "
        "(importance factor 1.2, response reduction R=5) with ductile "
        "detailing to IS 13920. Double-glazed unitised curtain-wall envelope "
        "with ACP and terracotta accents; AAC-block infill. IGBC Green "
        "(LEED v4 BD+C: Core & Shell aligned), ECBC 2017 envelope, ~1.2 MWp "
        "rooftop solar and a campus STP for 100% wastewater reuse. Executed "
        "on CPWD DSR 2021 rates trued-up to the Bengaluru 2026 price level. "
        "Headline construction cost approx. INR 612 crore (6.12 billion)."
    ),
    region="IN",
    classification_standard="masterformat",
    currency="INR",
    locale="en-IN",
    address={
        "street": "EPIP Zone, Whitefield Main Road",
        "city": "Bengaluru",
        "postcode": "560066",
        "country": "India",
        "lat": 12.9852,
        "lng": 77.7266,
    },
    validation_rule_sets=["masterformat", "boq_quality", "project_completeness"],
    boq_name="Bill of Quantities - CPWD DSR 2021 (Bengaluru Civil & Services)",
    boq_description=(
        "Detailed BoQ prepared on a CPWD Delhi Schedule of Rates 2021 "
        "sub-head structure trued-up to Bengaluru 2026 rates, covering all "
        "trades from earthwork to external development across both towers, "
        "amenity block and common basement. Quantities to IS 1200 mode of "
        "measurement; rates GST-exclusive."
    ),
    boq_metadata={
        "standard": "CPWD DSR 2021 (Bengaluru-adjusted)",
        "phase": "Detailed Estimate / GMP Tender BoQ",
        "base_date": "2026-Q1",
        "price_level": "Bengaluru 2026",
    },
    sections=[
        # ── 1. Earthwork, Excavation & Site Preparation (CPWD Sub-head 1/2) ─
        (
            "1",
            "Earthwork, Excavation & Site Preparation",
            {"masterformat": "31 00 00", "cpwd": "DSR-2"},
            [
                (
                    "1.1",
                    "Site clearance, grubbing & dismantling of existing structures (sthal saphai)",
                    "m2",
                    24000,
                    72.00,
                    {"masterformat": "31 11 00", "cpwd": "1.1"},
                ),
                (
                    "1.2",
                    "Bulk earthwork in excavation in ordinary / dense soil for basement, 0-1.5 m",
                    "m3",
                    62000,
                    265.00,
                    {"masterformat": "31 23 16", "cpwd": "2.6"},
                ),
                (
                    "1.3",
                    "Extra for excavation in soft / disintegrated rock beyond 1.5 m depth",
                    "m3",
                    28500,
                    485.00,
                    {"masterformat": "31 23 16", "cpwd": "2.8"},
                ),
                (
                    "1.4",
                    "Excavation in hard granite rock by controlled chiselling / breaking (Bengaluru gneiss)",
                    "m3",
                    9200,
                    985.00,
                    {"masterformat": "31 23 16", "cpwd": "2.10"},
                ),
                (
                    "1.5",
                    "Soldier-pile & shotcrete shoring to deep basement perimeter, IS 9527",
                    "m2",
                    8600,
                    2650.00,
                    {"masterformat": "31 50 00", "cpwd": "2.40"},
                ),
                (
                    "1.6",
                    "Soil-nail / rock-anchor support to basement cut slopes, grouted",
                    "each",
                    420,
                    4850.00,
                    {"masterformat": "31 51 00", "cpwd": "2.45"},
                ),
                (
                    "1.7",
                    "Disposal of surplus excavated material, lead up to 10 km (mitti hatana)",
                    "m3",
                    74000,
                    285.00,
                    {"masterformat": "31 23 23", "cpwd": "2.31"},
                ),
                (
                    "1.8",
                    "Filling in plinth & podium with selected earth in 20 cm layers, watered & rammed",
                    "m3",
                    18500,
                    225.00,
                    {"masterformat": "31 23 23", "cpwd": "2.25"},
                ),
                (
                    "1.9",
                    "Granular sub-base / consolidated sand filling under raft & floors",
                    "m3",
                    4200,
                    1950.00,
                    {"masterformat": "31 23 23", "cpwd": "2.27"},
                ),
                (
                    "1.10",
                    "Pre-construction anti-termite soil treatment conforming to IS 6313",
                    "m2",
                    24000,
                    82.00,
                    {"masterformat": "31 31 16", "cpwd": "8.1"},
                ),
                (
                    "1.11",
                    "Dewatering of basement excavation with well-points during construction",
                    "lsum",
                    1,
                    3850000.00,
                    {"masterformat": "31 23 19", "cpwd": "2.9"},
                ),
                (
                    "1.12",
                    "Geotechnical investigation, boreholes & SBC report (mitti jaanch)",
                    "lsum",
                    1,
                    1850000.00,
                    {"masterformat": "31 00 00", "cpwd": "2.1"},
                ),
            ],
        ),
        # ── 2. RCC Substructure - Raft & Basement (CPWD Sub-head 4 & 5) ─────
        (
            "2",
            "RCC Substructure - Raft, Footings & Basement",
            {"masterformat": "03 30 00", "cpwd": "DSR-5"},
            [
                (
                    "2.1",
                    "PCC 1:4:8 levelling course in foundation & under raft (lean concrete)",
                    "m3",
                    1850,
                    7250.00,
                    {"masterformat": "03 30 00", "cpwd": "4.1.4"},
                ),
                (
                    "2.2",
                    "RCC M35 design mix in raft foundation, 1.2 m thick, incl. shuttering, IS 456",
                    "m3",
                    9800,
                    9950.00,
                    {"masterformat": "03 30 00", "cpwd": "5.9.2"},
                ),
                (
                    "2.3",
                    "RCC M35 in basement retaining / shear walls, water-tight, incl. shuttering",
                    "m3",
                    6400,
                    11650.00,
                    {"masterformat": "03 30 00", "cpwd": "5.9.6"},
                ),
                (
                    "2.4",
                    "RCC M40 in basement columns & cores, incl. IS 13920 ductile detailing",
                    "m3",
                    3200,
                    12450.00,
                    {"masterformat": "03 30 00", "cpwd": "5.9.3"},
                ),
                (
                    "2.5",
                    "RCC M30 in basement & podium slabs incl. beams, up to 5 m height",
                    "m3",
                    8200,
                    10650.00,
                    {"masterformat": "03 30 00", "cpwd": "5.9.5"},
                ),
                (
                    "2.6",
                    "TMT reinforcement Fe 500D, cut bent & placed in substructure, IS 1786",
                    "MT",
                    4850,
                    79500.00,
                    {"masterformat": "03 21 00", "cpwd": "5.22.6"},
                ),
                (
                    "2.7",
                    "Integral crystalline water-proofing admixture dosed in basement RCC",
                    "kg",
                    96000,
                    44.00,
                    {"masterformat": "07 16 00", "cpwd": "5.3"},
                ),
                (
                    "2.8",
                    "PVC water-stop 230 mm at basement construction & expansion joints",
                    "rm",
                    3800,
                    485.00,
                    {"masterformat": "03 15 13", "cpwd": "5.14"},
                ),
            ],
        ),
        # ── 3. RCC Superstructure - Towers & Amenity (CPWD Sub-head 5) ──────
        (
            "3",
            "RCC Superstructure - Towers & Amenity Block",
            {"masterformat": "03 30 00", "cpwd": "DSR-5"},
            [
                (
                    "3.1",
                    "RCC M40 in superstructure columns to IS 13920 ductile detail, incl. shuttering",
                    "m3",
                    7600,
                    12850.00,
                    {"masterformat": "03 30 00", "cpwd": "5.9.3"},
                ),
                (
                    "3.2",
                    "RCC M35 in shear-wall cores (lift & stair) incl. jump-form shuttering",
                    "m3",
                    5400,
                    12150.00,
                    {"masterformat": "03 30 00", "cpwd": "5.9.3"},
                ),
                (
                    "3.3",
                    "RCC M35 in beams incl. centering & shuttering (sariya & shuttering)",
                    "m3",
                    8900,
                    11050.00,
                    {"masterformat": "03 30 00", "cpwd": "5.9.4"},
                ),
                (
                    "3.4",
                    "RCC M35 in post-tensioned / conventional suspended slabs, large spans",
                    "m3",
                    16800,
                    10850.00,
                    {"masterformat": "03 30 00", "cpwd": "5.9.5"},
                ),
                (
                    "3.5",
                    "RCC M30 in staircases incl. landings, waist slab & risers (seedhi)",
                    "m3",
                    980,
                    12150.00,
                    {"masterformat": "03 30 00", "cpwd": "5.9.7"},
                ),
                (
                    "3.6",
                    "Unbonded post-tensioning system in slabs, mono-strand, supplied & stressed",
                    "kg",
                    285000,
                    225.00,
                    {"masterformat": "03 38 00", "cpwd": "5.30"},
                ),
                (
                    "3.7",
                    "TMT reinforcement Fe 500D in superstructure, cut bent & placed, IS 1786",
                    "MT",
                    9650,
                    80500.00,
                    {"masterformat": "03 21 00", "cpwd": "5.22.6"},
                ),
                (
                    "3.8",
                    "RCC precast chajja / sunshade & parapet coping incl. reinforcement",
                    "m2",
                    3800,
                    1650.00,
                    {"masterformat": "03 41 00", "cpwd": "5.11"},
                ),
                (
                    "3.9",
                    "Non-shrink micro-concrete / grout for column-slab repairs & pockets",
                    "m3",
                    180,
                    18500.00,
                    {"masterformat": "03 60 00", "cpwd": "5.40"},
                ),
            ],
        ),
        # ── 4. Masonry & Blockwork (CPWD Sub-head 6) ───────────────────────
        (
            "4",
            "Masonry & Blockwork",
            {"masterformat": "04 22 00", "cpwd": "DSR-6"},
            [
                (
                    "4.1",
                    "AAC block masonry 200 mm in external infill walls, polymer mortar (halka block)",
                    "m3",
                    9800,
                    6650.00,
                    {"masterformat": "04 22 00", "cpwd": "6.4"},
                ),
                (
                    "4.2",
                    "AAC block masonry 100 mm in internal partitions, polymer mortar",
                    "m2",
                    42000,
                    985.00,
                    {"masterformat": "04 22 00", "cpwd": "6.13.2"},
                ),
                (
                    "4.3",
                    "Solid concrete block 150 mm in basement & service walls, CM 1:6 (chinai)",
                    "m3",
                    2400,
                    6250.00,
                    {"masterformat": "04 22 00", "cpwd": "6.1.2"},
                ),
                (
                    "4.4",
                    "RCC band / lintel band at sill & lintel level for crack control (IS 4326)",
                    "rm",
                    18500,
                    525.00,
                    {"masterformat": "04 05 23", "cpwd": "6.30"},
                ),
                (
                    "4.5",
                    "Chicken-mesh reinforcement at RCC-masonry junctions to arrest cracking",
                    "m2",
                    14500,
                    95.00,
                    {"masterformat": "04 05 23", "cpwd": "6.32"},
                ),
                (
                    "4.6",
                    "Damp-proof course 50 mm CC 1:2:4 with integral water-proofing at plinth (DPC)",
                    "m2",
                    1850,
                    725.00,
                    {"masterformat": "07 16 00", "cpwd": "4.2"},
                ),
            ],
        ),
        # ── 5. Waterproofing (CPWD Sub-head 22) ────────────────────────────
        (
            "5",
            "Waterproofing",
            {"masterformat": "07 00 00", "cpwd": "DSR-22"},
            [
                (
                    "5.1",
                    "Crystalline water-proofing to basement raft & retaining walls (negative side)",
                    "m2",
                    18500,
                    525.00,
                    {"masterformat": "07 16 00", "cpwd": "22.20"},
                ),
                (
                    "5.2",
                    "APP-modified bitumen membrane water-proofing on terraces, 4 mm (chhat seal)",
                    "m2",
                    11800,
                    725.00,
                    {"masterformat": "07 52 00", "cpwd": "22.10"},
                ),
                (
                    "5.3",
                    "Box-type water-proofing in toilets, pantries & wet areas with brick-bat coba",
                    "m2",
                    8600,
                    1050.00,
                    {"masterformat": "07 14 00", "cpwd": "22.5"},
                ),
                (
                    "5.4",
                    "Polyurethane (PU) liquid-applied water-proofing to podium & landscape decks",
                    "m2",
                    6400,
                    885.00,
                    {"masterformat": "07 18 00", "cpwd": "22.25"},
                ),
                (
                    "5.5",
                    "Heat-reflective cool-roof / china-mosaic finish over terrace screed",
                    "m2",
                    11800,
                    425.00,
                    {"masterformat": "07 50 00", "cpwd": "22.30"},
                ),
                (
                    "5.6",
                    "Terrace insulation EPS + protective screed layer over membrane",
                    "m2",
                    11800,
                    585.00,
                    {"masterformat": "07 22 00", "cpwd": "22.35"},
                ),
            ],
        ),
        # ── 6. Façade & Glazing (Envelope) ─────────────────────────────────
        (
            "6",
            "Façade & Glazing",
            {"masterformat": "08 44 00", "cpwd": "DSR-FACADE"},
            [
                (
                    "6.1",
                    "Unitised curtain-wall DGU 6-12-6 low-E, thermal-break aluminium (kaanch deewar)",
                    "m2",
                    36500,
                    9450.00,
                    {"masterformat": "08 44 13", "cpwd": "F-1.1"},
                ),
                (
                    "6.2",
                    "Semi-unitised / capped glazing to amenity block & lobbies, DGU",
                    "m2",
                    6800,
                    7850.00,
                    {"masterformat": "08 44 13", "cpwd": "F-1.2"},
                ),
                (
                    "6.3",
                    "ACP cladding 4 mm FR-grade on aluminium sub-frame (ACP cladding)",
                    "m2",
                    14500,
                    3950.00,
                    {"masterformat": "07 42 13", "cpwd": "F-3.1"},
                ),
                (
                    "6.4",
                    "Terracotta rain-screen cladding on aluminium carrier system, accent bands",
                    "m2",
                    4200,
                    6850.00,
                    {"masterformat": "07 42 43", "cpwd": "F-3.2"},
                ),
                (
                    "6.5",
                    "Structural spider glazing at entrance atrium, 19 mm toughened low-iron",
                    "m2",
                    1850,
                    11850.00,
                    {"masterformat": "08 44 26", "cpwd": "F-4.1"},
                ),
                (
                    "6.6",
                    "Aluminium openable windows & vents, anodised, DGU, IS 1948 (khidki)",
                    "m2",
                    2400,
                    6450.00,
                    {"masterformat": "08 51 13", "cpwd": "F-2.1"},
                ),
                (
                    "6.7",
                    "Aluminium horizontal fins / louvres for solar shading on south & west",
                    "m2",
                    3800,
                    4450.00,
                    {"masterformat": "10 71 13", "cpwd": "F-5.1"},
                ),
                (
                    "6.8",
                    "Façade access - building maintenance unit (BMU) / monorail davits per tower",
                    "each",
                    2,
                    8500000.00,
                    {"masterformat": "11 24 00", "cpwd": "F-6.1"},
                ),
            ],
        ),
        # ── 7. Internal Finishes - Flooring, Plaster, Paint, Ceiling ───────
        (
            "7",
            "Internal Finishes - Flooring, Plaster, Paint & Ceiling",
            {"masterformat": "09 00 00", "cpwd": "DSR-11"},
            [
                (
                    "7.1",
                    "Cement plaster 12 mm in CM 1:4 on internal walls (andar plaster)",
                    "m2",
                    96000,
                    275.00,
                    {"masterformat": "09 24 00", "cpwd": "13.1"},
                ),
                (
                    "7.2",
                    "Acrylic emulsion paint two coats over putty base on walls & soffits (rang)",
                    "m2",
                    128000,
                    118.00,
                    {"masterformat": "09 91 23", "cpwd": "13.61"},
                ),
                (
                    "7.3",
                    "Vitrified tile flooring 800x800 mm in lobbies & common areas, on CM bed",
                    "m2",
                    18500,
                    1750.00,
                    {"masterformat": "09 30 13", "cpwd": "11.42"},
                ),
                (
                    "7.4",
                    "Polished granite flooring 18 mm in ground-floor lobbies & lift cores",
                    "m2",
                    4200,
                    3150.00,
                    {"masterformat": "09 63 40", "cpwd": "11.21"},
                ),
                (
                    "7.5",
                    "Power-floated VDF concrete flooring with hardener in office warm-shell",
                    "m2",
                    96000,
                    685.00,
                    {"masterformat": "03 35 00", "cpwd": "11.3"},
                ),
                (
                    "7.6",
                    "Ceramic anti-skid floor & glazed wall dado in toilets & wet areas",
                    "m2",
                    16500,
                    1250.00,
                    {"masterformat": "09 30 13", "cpwd": "11.45"},
                ),
                (
                    "7.7",
                    "Epoxy self-levelling floor coating in MEP plant rooms & UPS rooms, 3 mm",
                    "m2",
                    8600,
                    1450.00,
                    {"masterformat": "09 67 00", "cpwd": "11.60"},
                ),
                (
                    "7.8",
                    "Mineral-fibre acoustic tile ceiling 600x600 mm in lobbies & amenity",
                    "m2",
                    14500,
                    1250.00,
                    {"masterformat": "09 51 13", "cpwd": "13.93"},
                ),
                (
                    "7.9",
                    "Gypsum board false ceiling on GI framing, taped & jointed (chhat)",
                    "m2",
                    9800,
                    1050.00,
                    {"masterformat": "09 51 00", "cpwd": "13.91"},
                ),
                (
                    "7.10",
                    "Flush door shutters 35 mm BWP grade with hardwood frame & hardware (darwaza)",
                    "m2",
                    3200,
                    4450.00,
                    {"masterformat": "08 14 00", "cpwd": "9.21"},
                ),
                (
                    "7.11",
                    "Two-hour fire-rated steel door with vision panel & panic bar, IS 3614",
                    "each",
                    180,
                    42500.00,
                    {"masterformat": "08 16 13", "cpwd": "9.95"},
                ),
                (
                    "7.12",
                    "Granite kitchen / pantry platform 18 mm with SS sink cut-outs (slab)",
                    "rm",
                    420,
                    3850.00,
                    {"masterformat": "12 36 00", "cpwd": "11.70"},
                ),
            ],
        ),
        # ── 8. Plumbing & Firefighting (CPWD Sub-head 17 & 18) ─────────────
        (
            "8",
            "Plumbing & Firefighting",
            {"masterformat": "22 00 00", "cpwd": "DSR-18"},
            [
                (
                    "8.1",
                    "CPVC water-supply piping 25-65 mm, concealed, with fittings (paani ki line)",
                    "rm",
                    28000,
                    425.00,
                    {"masterformat": "22 11 00", "cpwd": "18.12"},
                ),
                (
                    "8.2",
                    "PVC-U soil, waste & vent piping 110 mm, SWR system, with fittings (nikasi)",
                    "rm",
                    22000,
                    525.00,
                    {"masterformat": "22 13 00", "cpwd": "17.5"},
                ),
                (
                    "8.3",
                    "Dual-flush water-closet vitreous china with concealed cistern (shauchalay)",
                    "each",
                    640,
                    9250.00,
                    {"masterformat": "22 41 00", "cpwd": "17.10"},
                ),
                (
                    "8.4",
                    "Wash-basin vitreous china with sensor CP mixer & waste (washbasin)",
                    "each",
                    520,
                    6850.00,
                    {"masterformat": "22 41 00", "cpwd": "17.20"},
                ),
                (
                    "8.5",
                    "RCC underground raw & domestic water tanks 1500 kL total, water-proofed",
                    "lsum",
                    1,
                    9850000.00,
                    {"masterformat": "22 12 00", "cpwd": "17.50"},
                ),
                (
                    "8.6",
                    "Hydro-pneumatic pumping systems with VFD & pressure vessels, per tower",
                    "each",
                    2,
                    3850000.00,
                    {"masterformat": "22 11 23", "cpwd": "18.40"},
                ),
                (
                    "8.7",
                    "Packaged sewage treatment plant 600 KLD (MBBR) with tertiary reuse (STP)",
                    "lsum",
                    1,
                    24500000.00,
                    {"masterformat": "22 13 00", "cpwd": "18.60"},
                ),
                (
                    "8.8",
                    "Rainwater harvesting recharge wells & storm network, KSPCB / CGWB norms",
                    "lsum",
                    1,
                    6850000.00,
                    {"masterformat": "33 40 00", "cpwd": "18.70"},
                ),
                (
                    "8.9",
                    "Wet-riser & hydrant system MS pipework with landing valves, IS 3844",
                    "rm",
                    6800,
                    1650.00,
                    {"masterformat": "21 12 00", "cpwd": "FF-1.1"},
                ),
                (
                    "8.10",
                    "Automatic sprinkler system throughout basements & floors, NBC 2016",
                    "m2",
                    155000,
                    285.00,
                    {"masterformat": "21 13 00", "cpwd": "FF-2.1"},
                ),
                (
                    "8.11",
                    "Electric & diesel fire-pump house with jockey pump & controls, IS 12469",
                    "lsum",
                    1,
                    12500000.00,
                    {"masterformat": "21 30 00", "cpwd": "FF-3.1"},
                ),
                (
                    "8.12",
                    "Clean-agent (NOVEC / FK-5-1-12) suppression for server & UPS rooms",
                    "lsum",
                    1,
                    8500000.00,
                    {"masterformat": "21 22 00", "cpwd": "FF-4.1"},
                ),
            ],
        ),
        # ── 9. HVAC & Ventilation (CPWD HVAC DSR) ──────────────────────────
        (
            "9",
            "HVAC & Ventilation",
            {"masterformat": "23 00 00", "cpwd": "DSR-HVAC"},
            [
                (
                    "9.1",
                    "Water-cooled centrifugal chillers 750 TR each with VFD (chiller plant)",
                    "each",
                    6,
                    18500000.00,
                    {"masterformat": "23 64 00", "cpwd": "H-1.1"},
                ),
                (
                    "9.2",
                    "Cooling towers FRP induced-draft with basins & make-up, per chiller",
                    "each",
                    6,
                    2850000.00,
                    {"masterformat": "23 65 00", "cpwd": "H-1.2"},
                ),
                (
                    "9.3",
                    "Primary / secondary chilled-water pumps with VFD & headers",
                    "lsum",
                    1,
                    14500000.00,
                    {"masterformat": "23 21 23", "cpwd": "H-1.3"},
                ),
                (
                    "9.4",
                    "Air-handling units with AHU, EC plug fans & MERV-13 filtration (warm-shell)",
                    "each",
                    96,
                    685000.00,
                    {"masterformat": "23 73 00", "cpwd": "H-1.4"},
                ),
                (
                    "9.5",
                    "Chilled-water MS piping with PUF insulation & cladding, 50-450 mm",
                    "rm",
                    18500,
                    2450.00,
                    {"masterformat": "23 21 13", "cpwd": "H-1.5"},
                ),
                (
                    "9.6",
                    "Pre-insulated GI / factory-fabricated ductwork with diffusers & VAV boxes",
                    "kg",
                    285000,
                    385.00,
                    {"masterformat": "23 31 00", "cpwd": "H-1.6"},
                ),
                (
                    "9.7",
                    "Basement & toilet mechanical ventilation with jet fans & CO sensors, NBC 2016",
                    "lsum",
                    1,
                    18500000.00,
                    {"masterformat": "23 34 00", "cpwd": "H-2.1"},
                ),
                (
                    "9.8",
                    "Stairwell pressurisation & smoke-extraction fans with dampers, NBC 2016",
                    "lsum",
                    1,
                    12500000.00,
                    {"masterformat": "23 37 00", "cpwd": "H-2.2"},
                ),
                (
                    "9.9",
                    "Testing, adjusting & balancing (TAB) and commissioning of HVAC systems",
                    "lsum",
                    1,
                    6850000.00,
                    {"masterformat": "23 05 93", "cpwd": "H-5.1"},
                ),
            ],
        ),
        # ── 10. Electrical, ELV & BMS (CPWD Electrical DSR) ────────────────
        (
            "10",
            "Electrical, ELV & BMS",
            {"masterformat": "26 00 00", "cpwd": "DSR-ELEC"},
            [
                (
                    "10.1",
                    "11 kV HT panel, RMU & ring main with metering cubicle, BESCOM compliant",
                    "lsum",
                    1,
                    18500000.00,
                    {"masterformat": "26 11 00", "cpwd": "E-1.1"},
                ),
                (
                    "10.2",
                    "Package substation 2000 kVA cast-resin transformers with LT switchgear",
                    "each",
                    6,
                    8850000.00,
                    {"masterformat": "26 12 00", "cpwd": "E-1.2"},
                ),
                (
                    "10.3",
                    "DG set 1500 kVA acoustic enclosure with AMF panel & day tank (generator)",
                    "each",
                    4,
                    11500000.00,
                    {"masterformat": "26 32 13", "cpwd": "E-2.1"},
                ),
                (
                    "10.4",
                    "Main LT panels, bus-ducts & floor distribution boards, IS 8623, wired",
                    "lsum",
                    1,
                    42500000.00,
                    {"masterformat": "26 24 00", "cpwd": "E-3.1"},
                ),
                (
                    "10.5",
                    "Sandwich bus-bar trunking risers per tower, 1600-2500 A",
                    "rm",
                    1800,
                    18500.00,
                    {"masterformat": "26 25 00", "cpwd": "E-3.2"},
                ),
                (
                    "10.6",
                    "XLPE armoured power cable 3.5C up to 400 sqmm, laid & terminated",
                    "rm",
                    42000,
                    1450.00,
                    {"masterformat": "26 05 19", "cpwd": "E-7.1"},
                ),
                (
                    "10.7",
                    "GI perforated cable tray 150-900 mm with covers, supports & earthing",
                    "rm",
                    28000,
                    825.00,
                    {"masterformat": "26 05 36", "cpwd": "E-6.1"},
                ),
                (
                    "10.8",
                    "LED luminaires for common areas, basements & landscape, BIS-marked (LED batti)",
                    "each",
                    12500,
                    1950.00,
                    {"masterformat": "26 51 00", "cpwd": "E-5.1"},
                ),
                (
                    "10.9",
                    "Maintenance-free earthing stations & equipotential bonding, IS 3043",
                    "each",
                    180,
                    19500.00,
                    {"masterformat": "26 05 26", "cpwd": "E-8.1"},
                ),
                (
                    "10.10",
                    "Lightning protection system, conventional air-termination, IS/IEC 62305",
                    "lsum",
                    1,
                    4850000.00,
                    {"masterformat": "26 41 00", "cpwd": "E-9.1"},
                ),
                (
                    "10.11",
                    "Addressable fire-detection & PA / voice-evacuation system, IS 2189 (NBC 2016)",
                    "lsum",
                    1,
                    28500000.00,
                    {"masterformat": "28 31 00", "cpwd": "E-10.1"},
                ),
                (
                    "10.12",
                    "Structured cabling Cat-6A backbone, data racks & OFC riser per tower",
                    "lsum",
                    1,
                    22500000.00,
                    {"masterformat": "27 10 00", "cpwd": "E-11.1"},
                ),
                (
                    "10.13",
                    "IP CCTV, access-control & boom barriers with NVR & command centre",
                    "lsum",
                    1,
                    24500000.00,
                    {"masterformat": "28 23 00", "cpwd": "E-12.1"},
                ),
                (
                    "10.14",
                    "Integrated building management system (IBMS) - HVAC, electrical, fire, ELV",
                    "lsum",
                    1,
                    18500000.00,
                    {"masterformat": "25 50 00", "cpwd": "H-4.1"},
                ),
            ],
        ),
        # ── 11. Vertical Transportation - Lifts & Escalators ───────────────
        (
            "11",
            "Vertical Transportation - Lifts & Escalators",
            {"masterformat": "14 20 00", "cpwd": "DSR-LIFT"},
            [
                (
                    "11.1",
                    "High-speed passenger lift 1800 kg, 2.5 m/s, MRL gearless, 15 stops, IS 14665 (lift)",
                    "each",
                    16,
                    8850000.00,
                    {"masterformat": "14 21 00", "cpwd": "H-3.1"},
                ),
                (
                    "11.2",
                    "Service / firemen's lift 2000 kg, 15 stops, with auto-rescue device (ARD)",
                    "each",
                    4,
                    9650000.00,
                    {"masterformat": "14 21 00", "cpwd": "H-3.2"},
                ),
                (
                    "11.3",
                    "Heavy-duty escalators 30 deg in amenity block & ground lobbies",
                    "each",
                    6,
                    6850000.00,
                    {"masterformat": "14 31 00", "cpwd": "H-3.3"},
                ),
                (
                    "11.4",
                    "Destination-control dispatch & lift lobby integration with access control",
                    "lsum",
                    1,
                    4850000.00,
                    {"masterformat": "14 28 00", "cpwd": "H-3.4"},
                ),
            ],
        ),
        # ── 12. External Development & Infrastructure (CPWD Sub-head 16) ───
        (
            "12",
            "External Development & Infrastructure",
            {"masterformat": "32 00 00", "cpwd": "DSR-16"},
            [
                (
                    "12.1",
                    "Bituminous flexible pavement (GSB + WMM + DBM + BC) on internal campus roads",
                    "m2",
                    14500,
                    1750.00,
                    {"masterformat": "32 12 16", "cpwd": "16.50"},
                ),
                (
                    "12.2",
                    "Interlocking concrete-block paving 80 mm in walkways & surface parking (paver)",
                    "m2",
                    9800,
                    1050.00,
                    {"masterformat": "32 14 13", "cpwd": "16.60"},
                ),
                (
                    "12.3",
                    "RCC compound boundary wall 2.7 m high with coping & MS palisade (chardiwari)",
                    "rm",
                    1200,
                    5250.00,
                    {"masterformat": "32 31 00", "cpwd": "16.30"},
                ),
                (
                    "12.4",
                    "Motorised cantilever entrance gates with boom barriers & guard kiosks",
                    "lsum",
                    1,
                    4850000.00,
                    {"masterformat": "32 31 13", "cpwd": "16.35"},
                ),
                (
                    "12.5",
                    "Soft landscaping - lawn, native shrubs, trees & drip irrigation (bagwani)",
                    "m2",
                    18500,
                    525.00,
                    {"masterformat": "32 90 00", "cpwd": "16.80"},
                ),
                (
                    "12.6",
                    "Hardscape - granite seating, water bodies & feature plaza at campus core",
                    "lsum",
                    1,
                    18500000.00,
                    {"masterformat": "32 84 00", "cpwd": "16.82"},
                ),
                (
                    "12.7",
                    "Storm-water RCC drains with gratings & oil-water separators along roads",
                    "rm",
                    4200,
                    2450.00,
                    {"masterformat": "33 40 00", "cpwd": "16.70"},
                ),
                (
                    "12.8",
                    "Rooftop grid-tied solar PV 1.2 MWp with net-metering (MNRE / BESCOM)",
                    "lsum",
                    1,
                    66500000.00,
                    {"masterformat": "48 14 00", "cpwd": "16.90"},
                ),
                (
                    "12.9",
                    "External area & street lighting on poles, LED, with feeder pillars (bahar batti)",
                    "each",
                    220,
                    34500.00,
                    {"masterformat": "26 56 00", "cpwd": "16.85"},
                ),
                (
                    "12.10",
                    "EV charging infrastructure - AC & DC fast chargers in basement & surface",
                    "each",
                    60,
                    285000.00,
                    {"masterformat": "26 27 00", "cpwd": "16.95"},
                ),
            ],
        ),
    ],
    # CPWD-style markups: contractor overheads & profit above DSR; design
    # contingency, BOCW cess and GST carried as separate lines.
    #
    # The cess is filed "other" rather than "tax" for the reason written out in
    # full over the same line in ``govt-building-delhi.py``: it is a levy on
    # the cost of construction, not a consumption tax, and a reader asking this
    # bill for its tax rate takes the first markup filed "tax" and stops.
    markups=[
        ("Contractor Overheads & Profit (CP&OH)", 14.0, "overhead", "direct_cost"),
        ("Design & Estimation Contingency", 4.0, "contingency", "direct_cost"),
        ("Building & Other Construction Workers Cess (1%)", 1.0, "other", "direct_cost"),
        ("Goods & Services Tax (GST 18%)", 18.0, "tax", "cumulative"),
    ],
    total_months=32,
    tender_name="Main Civil & MEP Contract (GMP, Composite)",
    tender_companies=[
        ("Vaidhan Infra Construction", "tenders@vaidhaninfra.example", 0.98),
        ("Kesharji Balvani & Co. Ltd.", "bids@kesharji.example", 1.05),
        ("Amrivan Projects Ltd.", "tenders@amrivan.example", 1.01),
        ("Vareda Ltd.", "contracts@vareda.example", 1.03),
    ],
    project_metadata={
        "address": "EPIP Zone, Whitefield Main Road, Bengaluru 560066, Karnataka",
        "client": "Sunveda IT Park Developers LLP (private SPV)",
        "architect": "MVK Design Consultants (India) Pvt. Ltd.",
        "structural_consultant": "Ravdeep Engineering Consultancy Services",
        "mep_consultant": "Trenholme India Pvt. Ltd.",
        "leasable_area_sqft": "approx. 13.5 lakh sq ft (warm-shell offices)",
        "gfa_m2": 125400,
        "basement_gfa_m2": 29700,
        "towers": 2,
        "storeys": "2B + G + 12 per tower, plus amenity block",
        "basement_levels": 2,
        "car_parks": 2400,
        "structure_system": "RCC special moment-resisting frame (SMRF) on raft, PT slabs",
        "seismic_zone": "Zone II (IS 1893:2016, Z=0.10, I=1.2, R=5)",
        "design_codes": "IS 456, IS 1893:2016, IS 13920, IS 875, IS 800, NBC 2016",
        "schedule_of_rates": "CPWD DSR 2021 trued-up to Bengaluru 2026 market rates",
        "measurement_standard": "IS 1200 (mode of measurement)",
        "local_byelaws": "Karnataka (BBMP) Building Bye-laws / KMBR; BMRDA & BESCOM clearances",
        "sustainability": "IGBC Green / LEED v4 BD+C: Core & Shell aligned; ECBC 2017 envelope; 1.2 MWp rooftop solar; 600 KLD STP with 100% reuse; RWH per KSPCB/CGWB",
        "tax_note": "All BoQ rates are GST-exclusive; GST at 18% (works contract HSN 9954) applied as a separate line; BOCW cess 1% applies; TDS as per Income-tax Act",
        "statutory": "Karnataka RERA registration (commercial); fire NOC per Karnataka Fire Force / NBC 2016 Part 4; KSPCB consent; structural safety certificate per BBMP bye-laws",
        "labour_compliance": "BOCW Act 1996; CLRA Act 1970; Karnataka minimum wages; ESI & EPF",
        "headline_cost_inr": "approx. 612 crore (6,120 million INR)",
    },
    tender_packages=[
        (
            "Civil & Structure (Towers + Amenity + Basement)",
            "Earthwork, shoring, RCC substructure & superstructure, PT slabs, masonry",
            "evaluating",
            [
                ("Vaidhan Infra Construction", "tenders@vaidhaninfra.example", 0.98),
                ("Kesharji Balvani & Co. Ltd.", "bids@kesharji.example", 1.05),
                ("Amrivan Projects Ltd.", "tenders@amrivan.example", 1.01),
            ],
        ),
        (
            "Façade & Glazing (Envelope)",
            "Unitised curtain-wall, ACP & terracotta cladding, spider glazing, BMU",
            "evaluating",
            [
                ("Vitrasan Industries (India) Pvt. Ltd.", "estimation@vitrasan.example", 0.99),
                ("Alucrest India Pvt. Ltd.", "bids@alucrest.example", 1.04),
                ("Kavyan Glass Industries Pvt. Ltd.", "tenders@kavyanglass.example", 1.02),
            ],
        ),
        (
            "MEP - HVAC, Electrical, Plumbing & Firefighting",
            "Chiller plant, AHUs, ductwork, HT/LT, DG, ELV, plumbing, fire systems",
            "evaluating",
            [
                ("Thermoya Ltd.", "projects@thermoya.example", 0.99),
                ("Nilvara Engineering & Electronics Ltd.", "bids@nilvara.example", 1.05),
                ("Sarveen Electric Pvt. Ltd.", "tenders@sarveen.example", 1.02),
            ],
        ),
        (
            "Vertical Transportation (Lifts & Escalators)",
            "High-speed passenger & service lifts, escalators, destination dispatch",
            "evaluating",
            [
                ("Elvantis Elevator Company (India) Ltd.", "india.tenders@elvantis.example", 1.00),
                ("Orvenda Elevator India Pvt. Ltd.", "bids@orvenda.example", 1.03),
                ("Belventa India Pvt. Ltd.", "tenders@belventa-in.example", 1.02),
            ],
        ),
        (
            "Internal Finishes & Joinery",
            "Plaster, paint, flooring, false ceilings, doors, toilet & pantry fit-out",
            "evaluating",
            [
                ("Vareda Ltd.", "contracts@vareda.example", 0.97),
                ("Sunveda Enterprises Ltd.", "tenders@sunveda.example", 1.03),
                ("Bhandroy Contracts (India) Ltd.", "bids@bhandroy.example", 1.01),
            ],
        ),
        (
            "External Development & Infrastructure",
            "Roads, paving, boundary, landscape, storm-water, solar PV, EV charging",
            "evaluating",
            [
                ("Amrivan Projects Ltd.", "tenders@amrivan.example", 0.99),
                ("Nagaralay Ltd.", "bids@nagaralay.example", 1.04),
            ],
        ),
    ],
    budget_boq_name="Bill of Quantities - CPWD DSR 2021 (Bengaluru Civil & Services)",
    planned_budget=6_120_000_000.0,
    actual_spend_ratio=0.42,
    spi_override=0.97,
    cpi_override=1.02,
)
