# DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
# Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
from __future__ import annotations

from app.core.demo_projects import DemoTemplate

# ---------------------------------------------------------------------------
# Partner pack: south-africa - Mixed-Use Development, Sandton, Johannesburg
# ---------------------------------------------------------------------------
# Flagship South African demo authored as a quantity surveyor would prepare a
# priced bill of quantities for tender. Programme: a mixed-use development on
# Rivonia Road in Sandton (Johannesburg, Gauteng) comprising a two-level
# basement parkade, a double-volume retail and lobby podium, a 14-storey
# P-grade office tower and a residential wing of sectional-title apartments.
# Reinforced-concrete frame with post-tensioned suspended slabs to the tower,
# unitised solar-control curtain walling, and a backup standby-generator and
# borehole installation as is standard for Johannesburg given grid (Eskom /
# City Power load-shedding) and municipal water constraints.
#
# Measurement: ASAQS Standard System of Measuring Building Work (the South
# African building standard) with the platform classification carried as CSI
# MasterFormat 2018 - the recognised standard the demo harness understands -
# and the ASAQS trade reference kept in each classification dict under the
# "asaqs" key. Rates are Johannesburg 2026 market rates in South African Rand
# (ZAR), exclusive of VAT (15% carried as a separate markup line) and CIDB /
# preliminaries which are priced as their own section. Terminology follows
# common South African site usage (parkade, brickforce, screed, geyser,
# Corobrik facebrick, shutter/formwork, rebar to SANS).
# ---------------------------------------------------------------------------

TEMPLATE = DemoTemplate(
    demo_id="mixed-use-johannesburg",
    project_name="Rivonia Quarter - Mixed-Use Development, Sandton",
    project_description=(
        "New mixed-use development on Rivonia Road, Sandton, Johannesburg. A "
        "two-level basement parkade, a double-volume retail and lobby podium, "
        "a 14-storey P-grade office tower and a residential wing of 88 "
        "sectional-title apartments. Reinforced-concrete framed structure with "
        "post-tensioned flat slabs to the tower, designed to SANS 10100 "
        "(structural concrete) and SANS 10160 (loading) for a non-seismic "
        "region. Unitised solar-control curtain walling and Corobrik facebrick "
        "infill, with a 4-Star Green Star SA target, standby diesel generators "
        "and a borehole and water-storage installation for grid and municipal "
        "resilience. Site area approx. 3,200 m2, gross floor area approx. "
        "24,000 m2. Measured on the ASAQS standard system; estimated direct "
        "construction cost approx. ZAR 520 million, before VAT and overheads."
    ),
    region="ZA",
    classification_standard="masterformat",
    currency="ZAR",
    locale="en-ZA",
    address={
        "street": "120 Rivonia Road, Sandton",
        "city": "Johannesburg",
        "postcode": "2196",
        "country": "South Africa",
        "lat": -26.1076,
        "lng": 28.0567,
    },
    validation_rule_sets=["masterformat", "boq_quality", "project_completeness"],
    boq_name="Bill of Quantities - ASAQS Standard System of Measuring Building Work",
    boq_description=(
        "Detailed bill of quantities measured on the ASAQS Standard System of "
        "Measuring Building Work, all trades from Preliminaries and Earthworks "
        "to External Works. Rates exclusive of VAT; Johannesburg 2026 price "
        "level (ZAR)."
    ),
    boq_metadata={
        "standard": "ASAQS Standard System of Measuring Building Work + division-based classification",
        "phase": "Detailed Estimate / Tender BoQ",
        "base_date": "2026-Q1",
        "price_level": "Johannesburg 2026 (ZAR, excl. VAT)",
        "cidb_grade": "9GB (General Building)",
    },
    sections=[
        # ── A - Preliminaries & General (ASAQS Preliminaries) ────────────
        (
            "A",
            "A - Preliminaries & General (Site establishment & management)",
            {"masterformat": "01", "asaqs": "Preliminaries"},
            [
                (
                    "A.01",
                    "Site establishment, site offices, sheds & ablutions (Site setup)",
                    "lsum",
                    1,
                    3850000.00,
                    {"masterformat": "01 50 00", "asaqs": "Prelim"},
                ),
                (
                    "A.02",
                    "Tower crane supply, erection & dismantling (Tower crane)",
                    "month",
                    22,
                    285000.00,
                    {"masterformat": "01 54 00", "asaqs": "Plant"},
                ),
                (
                    "A.03",
                    "Materials & passenger hoist (Hoist)",
                    "month",
                    16,
                    95000.00,
                    {"masterformat": "01 54 00", "asaqs": "Plant"},
                ),
                (
                    "A.04",
                    "Perimeter hoarding, gates & site fencing (Hoarding)",
                    "m",
                    240,
                    1450.00,
                    {"masterformat": "01 56 00", "asaqs": "Prelim"},
                ),
                (
                    "A.05",
                    "Temporary electricity, water & telecoms (Temp services)",
                    "lsum",
                    1,
                    1250000.00,
                    {"masterformat": "01 51 00", "asaqs": "Prelim"},
                ),
                (
                    "A.06",
                    "Contracts manager, site agent & supervision (Site staff)",
                    "month",
                    24,
                    420000.00,
                    {"masterformat": "01 31 00", "asaqs": "Prelim"},
                ),
                (
                    "A.07",
                    "Occupational health & safety, OHS Act compliance (Health & safety)",
                    "lsum",
                    1,
                    1850000.00,
                    {"masterformat": "01 35 29", "asaqs": "Prelim"},
                ),
                (
                    "A.08",
                    "Site survey, setting-out & dilapidation surveys (Survey)",
                    "lsum",
                    1,
                    685000.00,
                    {"masterformat": "01 71 23", "asaqs": "Prelim"},
                ),
                (
                    "A.09",
                    "Contractor's all-risk insurance & guarantees (Insurance)",
                    "lsum",
                    1,
                    4200000.00,
                    {"masterformat": "01 21 00", "asaqs": "Prelim"},
                ),
                (
                    "A.10",
                    "Progressive & final cleaning, builder's clean (Cleaning)",
                    "lsum",
                    1,
                    950000.00,
                    {"masterformat": "01 74 00", "asaqs": "Prelim"},
                ),
            ],
        ),
        # ── B - Earthworks & Site Clearance (SANS 1200 D) ────────────────
        (
            "B",
            "B - Earthworks & Site Clearance",
            {"masterformat": "31", "asaqs": "Earthworks"},
            [
                (
                    "B.01",
                    "Site clearance, grubbing & strip topsoil (Site clearance)",
                    "m2",
                    3200,
                    65.00,
                    {"masterformat": "31 11 00", "asaqs": "Earthworks"},
                ),
                (
                    "B.02",
                    "Geotechnical investigation & soils report (Geotech)",
                    "lsum",
                    1,
                    420000.00,
                    {"masterformat": "02 32 00", "asaqs": "Earthworks"},
                ),
                (
                    "B.03",
                    "Bulk excavation in soft material to spoil, parkade (Bulk dig)",
                    "m3",
                    96000,
                    145.00,
                    {"masterformat": "31 23 16", "asaqs": "Earthworks"},
                ),
                (
                    "B.04",
                    "Extra over bulk excavation for intermediate rock (Rock excavation)",
                    "m3",
                    14000,
                    285.00,
                    {"masterformat": "31 23 16", "asaqs": "Earthworks"},
                ),
                (
                    "B.05",
                    "Cart away surplus material to licensed spoil site (Cart away)",
                    "m3",
                    88000,
                    165.00,
                    {"masterformat": "31 23 23", "asaqs": "Earthworks"},
                ),
                (
                    "B.06",
                    "Lateral support, soil nails & shotcrete to faces (Lateral support)",
                    "m2",
                    7200,
                    1250.00,
                    {"masterformat": "31 50 00", "asaqs": "Earthworks"},
                ),
                (
                    "B.07",
                    "Construction dewatering & groundwater control (Dewatering)",
                    "lsum",
                    1,
                    980000.00,
                    {"masterformat": "31 23 19", "asaqs": "Earthworks"},
                ),
                (
                    "B.08",
                    "Engineered backfill, imported G7 compacted in layers (Backfill)",
                    "m3",
                    12500,
                    285.00,
                    {"masterformat": "31 23 23", "asaqs": "Earthworks"},
                ),
                (
                    "B.09",
                    "Compaction of bulk earthworks layerworks to 93% MOD (Compaction)",
                    "m2",
                    3200,
                    48.00,
                    {"masterformat": "31 23 23", "asaqs": "Earthworks"},
                ),
                (
                    "B.10",
                    "Soil poisoning, anti-termite treatment SANS 10124 (Soil poisoning)",
                    "m2",
                    3200,
                    38.00,
                    {"masterformat": "31 31 16", "asaqs": "Earthworks"},
                ),
            ],
        ),
        # ── C - Piling & Concrete Substructure (SANS 10100) ──────────────
        (
            "C",
            "C - Piling & Concrete Substructure",
            {"masterformat": "03", "asaqs": "Concrete"},
            [
                (
                    "C.01",
                    "Bored cast-in-situ piles, 750mm diameter (Bored piles)",
                    "m",
                    4800,
                    2850.00,
                    {"masterformat": "31 63 29", "asaqs": "Piling"},
                ),
                (
                    "C.02",
                    "Pile load testing, static & integrity (Pile testing)",
                    "lsum",
                    1,
                    680000.00,
                    {"masterformat": "31 09 00", "asaqs": "Piling"},
                ),
                (
                    "C.03",
                    "Blinding concrete 50mm, 15 MPa under bases (Blinding)",
                    "m2",
                    3400,
                    145.00,
                    {"masterformat": "03 30 00", "asaqs": "Concrete"},
                ),
                (
                    "C.04",
                    "Reinforced concrete pile caps & ground beams 40 MPa (Pile caps)",
                    "m3",
                    1850,
                    3450.00,
                    {"masterformat": "03 31 00", "asaqs": "Concrete"},
                ),
                (
                    "C.05",
                    "Reinforced concrete raft & ground-floor slab 40 MPa (Raft slab)",
                    "m3",
                    4200,
                    2950.00,
                    {"masterformat": "03 31 00", "asaqs": "Concrete"},
                ),
                (
                    "C.06",
                    "Reinforced concrete basement retaining walls 40 MPa (Basement walls)",
                    "m3",
                    2800,
                    3650.00,
                    {"masterformat": "03 30 00", "asaqs": "Concrete"},
                ),
                (
                    "C.07",
                    "High-yield reinforcement to substructure, SANS 920 (Substructure rebar)",
                    "t",
                    1450,
                    23500.00,
                    {"masterformat": "03 21 00", "asaqs": "Concrete"},
                ),
                (
                    "C.08",
                    "Formwork (shutter) to pile caps, beams & walls (Substructure shutter)",
                    "m2",
                    9800,
                    385.00,
                    {"masterformat": "03 11 00", "asaqs": "Concrete"},
                ),
                (
                    "C.09",
                    "Tanking & waterproof membrane to basement, below ground (Tanking)",
                    "m2",
                    6800,
                    685.00,
                    {"masterformat": "07 13 00", "asaqs": "Waterproofing"},
                ),
                (
                    "C.10",
                    "Subsoil agricultural drainage & filter layer (Subsoil drainage)",
                    "m",
                    820,
                    545.00,
                    {"masterformat": "33 46 00", "asaqs": "Earthworks"},
                ),
            ],
        ),
        # ── D - Concrete Superstructure (SANS 10100) ─────────────────────
        (
            "D",
            "D - Reinforced Concrete Superstructure",
            {"masterformat": "03", "asaqs": "Concrete"},
            [
                (
                    "D.01",
                    "Reinforced concrete columns 40 MPa, basement & podium (Columns lower)",
                    "m3",
                    1650,
                    4250.00,
                    {"masterformat": "03 30 00", "asaqs": "Concrete"},
                ),
                (
                    "D.02",
                    "Reinforced concrete columns 40 MPa, typical tower (Columns upper)",
                    "m3",
                    1980,
                    3950.00,
                    {"masterformat": "03 30 00", "asaqs": "Concrete"},
                ),
                (
                    "D.03",
                    "Reinforced concrete core & shear walls 40 MPa (Core walls)",
                    "m3",
                    3200,
                    3850.00,
                    {"masterformat": "03 30 00", "asaqs": "Concrete"},
                ),
                (
                    "D.04",
                    "Post-tensioned suspended flat slabs 40 MPa, tower (PT slabs)",
                    "m3",
                    7800,
                    4150.00,
                    {"masterformat": "03 38 00", "asaqs": "Concrete"},
                ),
                (
                    "D.05",
                    "Reinforced concrete suspended slabs & beams 40 MPa, podium (RC slabs)",
                    "m3",
                    5600,
                    3650.00,
                    {"masterformat": "03 30 00", "asaqs": "Concrete"},
                ),
                (
                    "D.06",
                    "Reinforced concrete transfer beams over podium 50 MPa (Transfer beams)",
                    "m3",
                    680,
                    5200.00,
                    {"masterformat": "03 30 00", "asaqs": "Concrete"},
                ),
                (
                    "D.07",
                    "Precast concrete stair flights & landings (Stairs)",
                    "pcs",
                    64,
                    18500.00,
                    {"masterformat": "03 41 00", "asaqs": "Concrete"},
                ),
                (
                    "D.08",
                    "High-yield reinforcement to superstructure, SANS 920 (Superstructure rebar)",
                    "t",
                    4850,
                    24500.00,
                    {"masterformat": "03 21 00", "asaqs": "Concrete"},
                ),
                (
                    "D.09",
                    "Bonded post-tensioning tendons, strand & anchorages (PT strand)",
                    "t",
                    215,
                    52000.00,
                    {"masterformat": "03 38 00", "asaqs": "Concrete"},
                ),
                (
                    "D.10",
                    "Formwork (shutter) to columns & walls (Vertical shutter)",
                    "m2",
                    28000,
                    415.00,
                    {"masterformat": "03 11 00", "asaqs": "Concrete"},
                ),
                (
                    "D.11",
                    "Formwork & propping to suspended slabs, table forms (Soffit shutter)",
                    "m2",
                    42000,
                    465.00,
                    {"masterformat": "03 11 13", "asaqs": "Concrete"},
                ),
                (
                    "D.12",
                    "Concrete curing, surface finishing & making good (Concrete finishing)",
                    "m2",
                    46000,
                    65.00,
                    {"masterformat": "03 39 00", "asaqs": "Concrete"},
                ),
            ],
        ),
        # ── E - Structural Steel & Metalwork (SANS 10162) ────────────────
        (
            "E",
            "E - Structural Steel & Metalwork",
            {"masterformat": "05", "asaqs": "Structural steel"},
            [
                (
                    "E.01",
                    "Structural steel to atrium roof & canopies, SANS 10162 (Structural steel)",
                    "t",
                    285,
                    42500.00,
                    {"masterformat": "05 12 00", "asaqs": "Structural steel"},
                ),
                (
                    "E.02",
                    "Steel fire escape stairs, galvanised (Steel stairs)",
                    "pcs",
                    8,
                    185000.00,
                    {"masterformat": "05 51 00", "asaqs": "Metalwork"},
                ),
                (
                    "E.03",
                    "Hot-dip galvanising & protective coatings to steel (Galvanising)",
                    "t",
                    285,
                    9800.00,
                    {"masterformat": "05 05 13", "asaqs": "Structural steel"},
                ),
                (
                    "E.04",
                    "Intumescent fire protection to structural steel (Fire protection to steel)",
                    "m2",
                    4200,
                    385.00,
                    {"masterformat": "05 05 23", "asaqs": "Structural steel"},
                ),
                (
                    "E.05",
                    "Steel balustrades & handrails to stairs, SANS 10400-M (Balustrades)",
                    "m",
                    1450,
                    1850.00,
                    {"masterformat": "05 52 00", "asaqs": "Metalwork"},
                ),
                (
                    "E.06",
                    "Sundry structural & architectural metalwork (Sundry metalwork)",
                    "lsum",
                    1,
                    1650000.00,
                    {"masterformat": "05 50 00", "asaqs": "Metalwork"},
                ),
            ],
        ),
        # ── F - Masonry & Brickwork (ASAQS Masonry) ──────────────────────
        (
            "F",
            "F - Masonry, Brickwork & Plaster",
            {"masterformat": "04", "asaqs": "Masonry"},
            [
                (
                    "F.01",
                    "Corobrik facebrick to external skin, NFP (Facebrick)",
                    "m2",
                    8600,
                    985.00,
                    {"masterformat": "04 21 13", "asaqs": "Masonry"},
                ),
                (
                    "F.02",
                    "Cement-brick infill walls, plastered both sides (Brick infill)",
                    "m2",
                    18500,
                    685.00,
                    {"masterformat": "04 22 00", "asaqs": "Masonry"},
                ),
                (
                    "F.03",
                    "Concrete-block walls to plant & service rooms (Blockwork)",
                    "m2",
                    4200,
                    745.00,
                    {"masterformat": "04 22 00", "asaqs": "Masonry"},
                ),
                (
                    "F.04",
                    "Fire-rated masonry to stair & lift shafts (Fire-rated masonry)",
                    "m2",
                    3600,
                    825.00,
                    {"masterformat": "04 22 00", "asaqs": "Masonry"},
                ),
                (
                    "F.05",
                    "Brickforce & wall reinforcement to bed joints (Brickforce)",
                    "m",
                    42000,
                    18.50,
                    {"masterformat": "04 05 23", "asaqs": "Masonry"},
                ),
                (
                    "F.06",
                    "Damp-proof course & damp-proof membrane (DPC/DPM)",
                    "m",
                    6800,
                    95.00,
                    {"masterformat": "07 26 00", "asaqs": "Waterproofing"},
                ),
                (
                    "F.07",
                    "Cement plaster to internal walls, steel-floated (Internal plaster)",
                    "m2",
                    62000,
                    245.00,
                    {"masterformat": "09 24 00", "asaqs": "Plaster"},
                ),
                (
                    "F.08",
                    "Cement plaster to external walls, rendered (External plaster)",
                    "m2",
                    9800,
                    285.00,
                    {"masterformat": "09 24 00", "asaqs": "Plaster"},
                ),
            ],
        ),
        # ── G - Waterproofing & Roofing (SANS 10400-L) ───────────────────
        (
            "G",
            "G - Waterproofing & Roofing",
            {"masterformat": "07", "asaqs": "Waterproofing"},
            [
                (
                    "G.01",
                    "Torch-on waterproofing membrane to flat roofs, 2-ply (Roof waterproofing)",
                    "m2",
                    4800,
                    425.00,
                    {"masterformat": "07 52 00", "asaqs": "Waterproofing"},
                ),
                (
                    "G.02",
                    "Thermal insulation to roof, extruded polystyrene 75mm (Roof insulation)",
                    "m2",
                    4800,
                    285.00,
                    {"masterformat": "07 22 00", "asaqs": "Waterproofing"},
                ),
                (
                    "G.03",
                    "Screed to falls on concrete roof slabs (Roof screed)",
                    "m2",
                    4800,
                    185.00,
                    {"masterformat": "03 53 00", "asaqs": "Concrete"},
                ),
                (
                    "G.04",
                    "Concrete roof tiles to residential pitched roof, SANS 542 (Roof tiles)",
                    "m2",
                    1800,
                    545.00,
                    {"masterformat": "07 31 13", "asaqs": "Roofing"},
                ),
                (
                    "G.05",
                    "Structural timber roof trusses, SANS 10243 (Roof trusses)",
                    "m2",
                    1800,
                    685.00,
                    {"masterformat": "06 17 53", "asaqs": "Carpentry"},
                ),
                (
                    "G.06",
                    "Aluminium box gutters, rainwater outlets & downpipes (Rainwater goods)",
                    "m",
                    980,
                    685.00,
                    {"masterformat": "07 71 23", "asaqs": "Roofing"},
                ),
                (
                    "G.07",
                    "Wet-area waterproofing to bathrooms & balconies (Wet-area waterproofing)",
                    "m2",
                    8200,
                    385.00,
                    {"masterformat": "07 14 00", "asaqs": "Waterproofing"},
                ),
                (
                    "G.08",
                    "Sealants, movement joints & firestopping to penetrations (Sealants)",
                    "lsum",
                    1,
                    1450000.00,
                    {"masterformat": "07 92 00", "asaqs": "Waterproofing"},
                ),
            ],
        ),
        # ── H - Facade, Glazing, Windows & Doors (SANS 613) ──────────────
        (
            "H",
            "H - Facade, Glazing, Windows & Doors",
            {"masterformat": "08", "asaqs": "Glazing"},
            [
                (
                    "H.01",
                    "Unitised curtain walling, solar-control double glazing (Curtain wall)",
                    "m2",
                    9800,
                    6850.00,
                    {"masterformat": "08 44 00", "asaqs": "Glazing"},
                ),
                (
                    "H.02",
                    "Aluminium composite panel cladding to podium (ACP cladding)",
                    "m2",
                    4200,
                    2850.00,
                    {"masterformat": "07 42 43", "asaqs": "Cladding"},
                ),
                (
                    "H.03",
                    "Aluminium shopfronts & feature entrance glazing (Shopfronts)",
                    "m2",
                    1450,
                    4250.00,
                    {"masterformat": "08 43 00", "asaqs": "Glazing"},
                ),
                (
                    "H.04",
                    "Aluminium windows to residential wing, double glazed (Aluminium windows)",
                    "m2",
                    3600,
                    2650.00,
                    {"masterformat": "08 51 13", "asaqs": "Glazing"},
                ),
                (
                    "H.05",
                    "Automatic sliding entrance doors, glazed (Auto entrance doors)",
                    "pcs",
                    6,
                    185000.00,
                    {"masterformat": "08 42 29", "asaqs": "Doors"},
                ),
                (
                    "H.06",
                    "Solid-core timber doors, frames & ironmongery (Timber doors)",
                    "pcs",
                    920,
                    6850.00,
                    {"masterformat": "08 14 16", "asaqs": "Doors"},
                ),
                (
                    "H.07",
                    "Fire-rated doors to escape routes, SANS 1253 (Fire doors)",
                    "pcs",
                    180,
                    12500.00,
                    {"masterformat": "08 14 16", "asaqs": "Doors"},
                ),
                (
                    "H.08",
                    "Steel doors & frames to plant & service rooms (Steel doors)",
                    "pcs",
                    145,
                    4850.00,
                    {"masterformat": "08 11 13", "asaqs": "Doors"},
                ),
                (
                    "H.09",
                    "Frameless glass balustrades to balconies & atrium (Glass balustrades)",
                    "m",
                    1850,
                    3850.00,
                    {"masterformat": "08 80 00", "asaqs": "Glazing"},
                ),
            ],
        ),
        # ── J - Internal Finishes (ASAQS Finishes) ───────────────────────
        (
            "J",
            "J - Internal Finishes (Floor, wall & ceiling)",
            {"masterformat": "09", "asaqs": "Finishes"},
            [
                (
                    "J.01",
                    "Cement-sand screed to floors, power-floated (Floor screed)",
                    "m2",
                    38000,
                    185.00,
                    {"masterformat": "03 53 00", "asaqs": "Finishes"},
                ),
                (
                    "J.02",
                    "Porcelain floor tiling to retail, lobbies & wet areas (Floor tiling)",
                    "m2",
                    16500,
                    985.00,
                    {"masterformat": "09 30 13", "asaqs": "Tiling"},
                ),
                (
                    "J.03",
                    "Natural granite flooring to main office lobby (Granite flooring)",
                    "m2",
                    1850,
                    3850.00,
                    {"masterformat": "09 63 40", "asaqs": "Tiling"},
                ),
                (
                    "J.04",
                    "Carpet tiles to office floors, commercial grade (Carpet tiles)",
                    "m2",
                    9800,
                    685.00,
                    {"masterformat": "09 68 13", "asaqs": "Finishes"},
                ),
                (
                    "J.05",
                    "Engineered timber & laminate flooring to apartments (Timber floor)",
                    "m2",
                    6800,
                    985.00,
                    {"masterformat": "09 64 00", "asaqs": "Finishes"},
                ),
                (
                    "J.06",
                    "Vinyl & SPC flooring to back-of-house & ablutions (Vinyl flooring)",
                    "m2",
                    4200,
                    545.00,
                    {"masterformat": "09 65 00", "asaqs": "Finishes"},
                ),
                (
                    "J.07",
                    "Ceramic wall tiling to bathrooms & kitchens (Wall tiling)",
                    "m2",
                    12500,
                    685.00,
                    {"masterformat": "09 30 00", "asaqs": "Tiling"},
                ),
                (
                    "J.08",
                    "Suspended grid & acoustic ceilings to offices (Suspended ceilings)",
                    "m2",
                    14500,
                    545.00,
                    {"masterformat": "09 51 00", "asaqs": "Ceilings"},
                ),
                (
                    "J.09",
                    "Gypsum plasterboard ceilings & bulkheads, SANS 266 (Gypsum ceilings)",
                    "m2",
                    18500,
                    425.00,
                    {"masterformat": "09 29 00", "asaqs": "Ceilings"},
                ),
                (
                    "J.10",
                    "Drywall partitions, steel stud & plasterboard (Drywall partitions)",
                    "m2",
                    16500,
                    685.00,
                    {"masterformat": "09 29 00", "asaqs": "Finishes"},
                ),
                (
                    "J.11",
                    "Acrylic PVA & enamel paint to walls & ceilings (Painting)",
                    "m2",
                    92000,
                    145.00,
                    {"masterformat": "09 91 00", "asaqs": "Painting"},
                ),
                (
                    "J.12",
                    "Epoxy floor coating to parkade & plant rooms (Epoxy coating)",
                    "m2",
                    18000,
                    285.00,
                    {"masterformat": "09 67 00", "asaqs": "Finishes"},
                ),
            ],
        ),
        # ── K - Joinery, Fittings & Equipment (ASAQS Joinery) ────────────
        (
            "K",
            "K - Joinery, Fittings & Equipment",
            {"masterformat": "11", "asaqs": "Joinery"},
            [
                (
                    "K.01",
                    "Fitted kitchens to apartments, BIC & stone tops (Apartment kitchens)",
                    "pcs",
                    88,
                    78500.00,
                    {"masterformat": "11 31 00", "asaqs": "Joinery"},
                ),
                (
                    "K.02",
                    "Built-in cupboards & wardrobes to apartments (Built-in cupboards)",
                    "pcs",
                    220,
                    18500.00,
                    {"masterformat": "12 35 30", "asaqs": "Joinery"},
                ),
                (
                    "K.03",
                    "Vanity units & bathroom joinery (Vanities)",
                    "pcs",
                    165,
                    14500.00,
                    {"masterformat": "12 35 70", "asaqs": "Joinery"},
                ),
                (
                    "K.04",
                    "Office & lobby reception joinery, FF&E (Reception joinery)",
                    "lsum",
                    1,
                    2850000.00,
                    {"masterformat": "12 50 00", "asaqs": "Joinery"},
                ),
                (
                    "K.05",
                    "Signage, wayfinding & statutory signage (Signage)",
                    "lsum",
                    1,
                    1450000.00,
                    {"masterformat": "10 14 00", "asaqs": "Fittings"},
                ),
                (
                    "K.06",
                    "Sanitaryware & taps, SANS 226 fittings (Sanitaryware)",
                    "pcs",
                    880,
                    8500.00,
                    {"masterformat": "22 40 00", "asaqs": "Plumbing"},
                ),
                (
                    "K.07",
                    "Toilet cubicles, partitions & accessories (Toilet cubicles)",
                    "pcs",
                    240,
                    6850.00,
                    {"masterformat": "10 21 13", "asaqs": "Fittings"},
                ),
            ],
        ),
        # ── L - Mechanical & HVAC (SANS 10400-O) ─────────────────────────
        (
            "L",
            "L - Mechanical Services & HVAC",
            {"masterformat": "23", "asaqs": "Mechanical"},
            [
                (
                    "L.01",
                    "Air-cooled water chillers & primary plant (Chillers)",
                    "pcs",
                    4,
                    2850000.00,
                    {"masterformat": "23 64 00", "asaqs": "Mechanical"},
                ),
                (
                    "L.02",
                    "Air-handling units to office floors (AHUs)",
                    "pcs",
                    28,
                    285000.00,
                    {"masterformat": "23 73 00", "asaqs": "Mechanical"},
                ),
                (
                    "L.03",
                    "Fan-coil units to offices & common areas (FCUs)",
                    "pcs",
                    420,
                    18500.00,
                    {"masterformat": "23 82 19", "asaqs": "Mechanical"},
                ),
                (
                    "L.04",
                    "Split-system air conditioning to apartments (Split units)",
                    "pcs",
                    176,
                    24500.00,
                    {"masterformat": "23 81 26", "asaqs": "Mechanical"},
                ),
                (
                    "L.05",
                    "Galvanised insulated ductwork & distribution (Ductwork)",
                    "kg",
                    145000,
                    145.00,
                    {"masterformat": "23 31 00", "asaqs": "Mechanical"},
                ),
                (
                    "L.06",
                    "Chilled-water & condenser piping, insulated (Chilled-water piping)",
                    "m",
                    6800,
                    685.00,
                    {"masterformat": "23 21 13", "asaqs": "Mechanical"},
                ),
                (
                    "L.07",
                    "Parkade impulse ventilation & smoke extraction (Parkade ventilation)",
                    "lsum",
                    1,
                    4850000.00,
                    {"masterformat": "23 34 00", "asaqs": "Mechanical"},
                ),
                (
                    "L.08",
                    "Stair pressurisation system, SANS 10400-T (Stair pressurisation)",
                    "pcs",
                    6,
                    285000.00,
                    {"masterformat": "23 34 23", "asaqs": "Mechanical"},
                ),
                (
                    "L.09",
                    "Building management system & HVAC controls (BMS)",
                    "lsum",
                    1,
                    3850000.00,
                    {"masterformat": "25 30 00", "asaqs": "Mechanical"},
                ),
            ],
        ),
        # ── M - Wet Services / Plumbing & Drainage (SANS 10252) ──────────
        (
            "M",
            "M - Wet Services, Plumbing & Drainage",
            {"masterformat": "22", "asaqs": "Plumbing"},
            [
                (
                    "M.01",
                    "Cold-water reticulation, HDPE & copper (Cold-water reticulation)",
                    "m",
                    9800,
                    545.00,
                    {"masterformat": "22 11 16", "asaqs": "Plumbing"},
                ),
                (
                    "M.02",
                    "Hot-water reticulation, insulated (Hot-water reticulation)",
                    "m",
                    5600,
                    685.00,
                    {"masterformat": "22 11 23", "asaqs": "Plumbing"},
                ),
                (
                    "M.03",
                    "Soil, waste & vent drainage, uPVC SANS 967 (Drainage)",
                    "m",
                    8400,
                    685.00,
                    {"masterformat": "22 13 16", "asaqs": "Plumbing"},
                ),
                (
                    "M.04",
                    "Heat-pump geysers & hot-water plant (Geysers)",
                    "pcs",
                    96,
                    32500.00,
                    {"masterformat": "22 33 00", "asaqs": "Plumbing"},
                ),
                (
                    "M.05",
                    "Borehole, pumps & water-storage tanks (Borehole & storage)",
                    "lsum",
                    1,
                    3850000.00,
                    {"masterformat": "33 21 00", "asaqs": "Plumbing"},
                ),
                (
                    "M.06",
                    "Rainwater harvesting tanks & reuse pumps (Rainwater harvesting)",
                    "lsum",
                    1,
                    1450000.00,
                    {"masterformat": "22 13 53", "asaqs": "Plumbing"},
                ),
                (
                    "M.07",
                    "Storm-water drainage, gullies & attenuation tank (Stormwater)",
                    "lsum",
                    1,
                    2850000.00,
                    {"masterformat": "33 40 00", "asaqs": "Plumbing"},
                ),
                (
                    "M.08",
                    "Municipal water & sewer connections, City of Joburg (Municipal connections)",
                    "lsum",
                    1,
                    1850000.00,
                    {"masterformat": "33 10 00", "asaqs": "Plumbing"},
                ),
            ],
        ),
        # ── N - Electrical & ICT (SANS 10142) ────────────────────────────
        (
            "N",
            "N - Electrical & ICT Services",
            {"masterformat": "26", "asaqs": "Electrical"},
            [
                (
                    "N.01",
                    "Miniature substation, MV switchgear & City Power connection (Substation)",
                    "lsum",
                    1,
                    6850000.00,
                    {"masterformat": "26 11 00", "asaqs": "Electrical"},
                ),
                (
                    "N.02",
                    "Main LV distribution boards & sub-mains, SANS 10142 (Main DBs)",
                    "pcs",
                    4,
                    685000.00,
                    {"masterformat": "26 24 13", "asaqs": "Electrical"},
                ),
                (
                    "N.03",
                    "Distribution boards per floor & per tenancy (Floor DBs)",
                    "pcs",
                    96,
                    42500.00,
                    {"masterformat": "26 24 16", "asaqs": "Electrical"},
                ),
                (
                    "N.04",
                    "Standby diesel generators 1500 kVA & changeover (Standby generators)",
                    "pcs",
                    2,
                    2850000.00,
                    {"masterformat": "26 32 13", "asaqs": "Electrical"},
                ),
                (
                    "N.05",
                    "Uninterruptible power supply to critical loads (UPS)",
                    "lsum",
                    1,
                    1850000.00,
                    {"masterformat": "26 33 53", "asaqs": "Electrical"},
                ),
                (
                    "N.06",
                    "Power & lighting reticulation, cable & containment (Reticulation)",
                    "m",
                    145000,
                    185.00,
                    {"masterformat": "26 05 19", "asaqs": "Electrical"},
                ),
                (
                    "N.07",
                    "LED luminaires, offices, common & external (LED luminaires)",
                    "pcs",
                    14500,
                    985.00,
                    {"masterformat": "26 51 00", "asaqs": "Electrical"},
                ),
                (
                    "N.08",
                    "Lightning protection & earthing, SANS 10313 (Lightning protection)",
                    "lsum",
                    1,
                    985000.00,
                    {"masterformat": "26 41 00", "asaqs": "Electrical"},
                ),
                (
                    "N.09",
                    "Rooftop solar PV 350 kWp with inverters (Solar PV)",
                    "lsum",
                    1,
                    6850000.00,
                    {"masterformat": "48 14 00", "asaqs": "Electrical"},
                ),
                (
                    "N.10",
                    "Structured cabling, data & telecoms backbone (Structured cabling)",
                    "lsum",
                    1,
                    4200000.00,
                    {"masterformat": "27 10 00", "asaqs": "Electrical"},
                ),
                (
                    "N.11",
                    "Electric-vehicle charging points to parkade, 22 kW (EV charging)",
                    "pcs",
                    48,
                    65000.00,
                    {"masterformat": "26 56 00", "asaqs": "Electrical"},
                ),
            ],
        ),
        # ── P - Fire, Life-Safety, Security & Lifts (SANS 10400-T) ───────
        (
            "P",
            "P - Fire, Life-Safety, Security & Vertical Transport",
            {"masterformat": "21", "asaqs": "Fire & lifts"},
            [
                (
                    "P.01",
                    "Automatic sprinkler installation, ASIB / SANS 10287 (Sprinklers)",
                    "m2",
                    24000,
                    285.00,
                    {"masterformat": "21 13 13", "asaqs": "Fire"},
                ),
                (
                    "P.02",
                    "Fire hydrants, hose reels & fire-water tank (Hydrants & hose reels)",
                    "lsum",
                    1,
                    1850000.00,
                    {"masterformat": "21 12 00", "asaqs": "Fire"},
                ),
                (
                    "P.03",
                    "Addressable fire detection & alarm, SANS 10139 (Fire detection)",
                    "m2",
                    24000,
                    165.00,
                    {"masterformat": "28 31 00", "asaqs": "Fire"},
                ),
                (
                    "P.04",
                    "Gas suppression to electrical & server rooms (Gas suppression)",
                    "lsum",
                    1,
                    985000.00,
                    {"masterformat": "21 22 00", "asaqs": "Fire"},
                ),
                (
                    "P.05",
                    "CCTV, access control & intruder detection (Security systems)",
                    "lsum",
                    1,
                    4850000.00,
                    {"masterformat": "28 20 00", "asaqs": "Security"},
                ),
                (
                    "P.06",
                    "High-speed passenger lifts to tower, 1600 kg (Passenger lifts)",
                    "pcs",
                    6,
                    2850000.00,
                    {"masterformat": "14 21 00", "asaqs": "Lifts"},
                ),
                (
                    "P.07",
                    "Goods & firefighting lift, 2000 kg (Goods lift)",
                    "pcs",
                    2,
                    3450000.00,
                    {"masterformat": "14 20 00", "asaqs": "Lifts"},
                ),
                (
                    "P.08",
                    "Passenger lifts to residential wing, 1000 kg (Residential lifts)",
                    "pcs",
                    3,
                    1850000.00,
                    {"masterformat": "14 21 00", "asaqs": "Lifts"},
                ),
            ],
        ),
        # ── Q - External Works & Landscaping (SANS 1200 M) ───────────────
        (
            "Q",
            "Q - External Works & Landscaping",
            {"masterformat": "32", "asaqs": "External works"},
            [
                (
                    "Q.01",
                    "Asphalt surfacing to access roads & ramps (Asphalt)",
                    "m2",
                    4200,
                    545.00,
                    {"masterformat": "32 12 16", "asaqs": "External works"},
                ),
                (
                    "Q.02",
                    "Interlocking concrete-block paving to forecourt (Paving)",
                    "m2",
                    3800,
                    485.00,
                    {"masterformat": "32 14 13", "asaqs": "External works"},
                ),
                (
                    "Q.03",
                    "Precast concrete kerbing & channels (Kerbing)",
                    "m",
                    1450,
                    385.00,
                    {"masterformat": "32 16 13", "asaqs": "External works"},
                ),
                (
                    "Q.04",
                    "Reinforced concrete boundary & retaining walls (Boundary walls)",
                    "m",
                    480,
                    4850.00,
                    {"masterformat": "32 31 00", "asaqs": "External works"},
                ),
                (
                    "Q.05",
                    "Palisade fencing, gates & guardhouse (Palisade fencing)",
                    "m",
                    320,
                    2850.00,
                    {"masterformat": "32 31 13", "asaqs": "External works"},
                ),
                (
                    "Q.06",
                    "Indigenous, water-wise landscaping & planting (Landscaping)",
                    "m2",
                    2400,
                    685.00,
                    {"masterformat": "32 90 00", "asaqs": "External works"},
                ),
                (
                    "Q.07",
                    "Automatic irrigation, borehole-fed (Irrigation)",
                    "m2",
                    2400,
                    185.00,
                    {"masterformat": "32 84 00", "asaqs": "External works"},
                ),
                (
                    "Q.08",
                    "External lighting, bollards & area floodlighting (External lighting)",
                    "pcs",
                    145,
                    12500.00,
                    {"masterformat": "26 56 00", "asaqs": "External works"},
                ),
                (
                    "Q.09",
                    "Site stormwater, manholes & subsoil drains (Site drainage)",
                    "m",
                    1850,
                    685.00,
                    {"masterformat": "33 40 00", "asaqs": "External works"},
                ),
            ],
        ),
    ],
    markups=[
        ("Preliminaries & General (P&Gs)", 11.0, "overhead", "direct_cost"),
        ("Contractor's Overheads & Profit", 8.0, "profit", "direct_cost"),
        ("Construction Contingency", 6.0, "contingency", "direct_cost"),
        ("Escalation (CPAP / contract price adjustment)", 4.5, "overhead", "direct_cost"),
        ("Value-Added Tax (VAT, SARS standard rate)", 15.0, "tax", "cumulative"),
    ],
    total_months=30,
    tender_name="Main Building Contract (Structure & Envelope)",
    tender_companies=[
        ("Halberd Construction", "tenders@halberd.example", 0.98),
        ("Vanderlyn & Kroft Buildings", "estimating@vanderlynkroft.example", 1.04),
        ("Vosterlan Brink Building", "tenders@vosterlan.example", 1.01),
    ],
    tender_packages=[
        (
            "Main Building Contract (Structure & Envelope)",
            "Substructure, piling, reinforced-concrete frame, post-tensioned slabs and facade.",
            "evaluating",
            [
                ("Halberd Construction", "tenders@halberd.example", 0.98),
                ("Vanderlyn & Kroft Buildings", "estimating@vanderlynkroft.example", 1.04),
                ("Vosterlan Brink Building", "tenders@vosterlan.example", 1.01),
            ],
        ),
        (
            "Building Services (Mechanical, Electrical & Wet Services)",
            "HVAC, electrical reticulation, standby power, solar PV, plumbing and fire services.",
            "issued",
            [
                ("Renbeck Projects (M&E)", "tenders@renbeck.example", 0.99),
                ("Vreelander & Partners", "bids@vreelander.example", 1.05),
                ("Halvardt Consulting Engineers", "estimating@halvardt.example", 1.02),
            ],
        ),
        (
            "Finishes & Fit-out Package",
            "Internal finishes, joinery, ceilings, partitions and tenant fit-out works.",
            "draft",
            [
                ("Tri-Vance Construction", "tenders@trivance.example", 0.97),
                ("Molefane Construction Group", "bids@molefane.example", 1.06),
                ("Grenvale Construction", "tenders@grenvale.example", 1.03),
            ],
        ),
    ],
    project_metadata={
        "address": "120 Rivonia Road, Sandton, Johannesburg 2196, South Africa",
        "client": "Cresslin Quarter Property Developments (Pty) Ltd",
        "architect": "Larkspire Architects",
        "quantity_surveyor": "MDQ Brakenhof Quantity Surveyors (ASAQS)",
        "structural_engineer": "Kelbright Engineers",
        "gfa_m2": 24000,
        "site_area_m2": 3200,
        "storeys": 14,
        "basement_levels": 2,
        "apartments": 88,
        "car_spaces": 620,
        "construction_standards": [
            "SANS 10100 The structural use of concrete",
            "SANS 10160 Basis of structural design and actions",
            "SANS 10162 The structural use of steel",
            "SANS 10142 The wiring of premises",
            "SANS 10252 Water supply and drainage installations",
            "SANS 10400 The application of the National Building Regulations",
            "SANS 204 / SANS 10400-XA Energy usage in buildings",
        ],
        "measurement_standard": "ASAQS Standard System of Measuring Building Work (latest edition)",
        "regulator": "City of Johannesburg Metropolitan Municipality (building plan approval, SANS 10400)",
        "cidb_grade": "9GB (General Building) - required contractor grading designation",
        "green_rating": "Green Star SA 4-Star (Office v1.1) target, GBCSA",
        "vat_note": "All BOQ rates are exclusive of VAT. South African VAT of 15% (SARS) is applied as a separate markup line.",
        "procurement": "JBCC Principal Building Agreement (Edition 6.2), lump-sum",
        "resilience_note": "Standby diesel generators and borehole/water-storage provided for Eskom load-shedding and municipal water-supply resilience.",
    },
)
