# DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
# Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
from __future__ import annotations

from app.core.demo_projects import DemoTemplate

# ---------------------------------------------------------------------------
# Partner pack: croatia-hr - Poslovna zgrada, Split
# ---------------------------------------------------------------------------
# The second Croatian demo and deliberately a different job from the Zagreb
# residential building: a mixed-use office building on the coast, where the
# bill carries what the Adriatic asks for. Concrete exposed to sea-salt air is
# specified to exposure class XS1 with stainless reinforcement at the exposed
# edges, fixings and downpipes are stainless A4, steelwork gets a C5 coating,
# and the south and west façades carry fixed and motorised shading because the
# cooling load, not the heating load, sizes the plant. Excavation is largely in
# limestone, which is why the rock line costs more than the soil line.
#
# Same troškovnik layout as the Zagreb bill: one chapter per trade, items
# numbered within the chapter, each line mapped to a DIN 276 cost group.
# Unit rates are all-in troškovnik prices. Prices are EUR excluding 25% PDV.
# ---------------------------------------------------------------------------

TEMPLATE = DemoTemplate(
    demo_id="office-split",
    project_name="Poslovna zgrada - Split, Poljička cesta (Office Building, Split)",
    project_description=(
        "Novogradnja poslovno-trgovačke zgrade u Splitu: Po+P+4, trgovački i "
        "ugostiteljski sadržaji u prizemlju, uredi na katovima, podzemna garaža "
        "s 42 parkirna mjesta. Bruto površina cca 6 600 m2. Armiranobetonski "
        "skelet, beton razreda izloženosti XS1 zbog morske soli, aluminijska "
        "fasadna stijena sa zaštitom od sunca, VRF grijanje i hlađenje. "
        "New-build mixed-use office building in Split: basement plus ground "
        "plus four storeys, retail and café at ground level, offices above, "
        "underground garage with 42 spaces. GFA approx. 6,600 m2. RC frame, "
        "XS1 concrete for sea-salt exposure, aluminium curtain wall with solar "
        "shading, VRF heating and cooling. Troškovnik total approx. 8,881,000 "
        "EUR excluding PDV (approx. 1,346 EUR/m2 GFA), priced at Split 2026 "
        "levels, before a 4% contingency."
    ),
    region="HR",
    classification_standard="din276",
    currency="EUR",
    locale="en",
    address={
        "street": "Poljička cesta 45",
        "city": "Split",
        "postcode": "21000",
        "country": "Croatia",
        "lat": 43.5086,
        "lng": 16.4631,
    },
    validation_rule_sets=["din276", "boq_quality"],
    boq_name="Troškovnik - Poslovna zgrada Split (Bill of Quantities)",
    boq_description=(
        "Troškovnik građevinskih, obrtničkih i instalaterskih radova za "
        "poslovnu zgradu u priobalnom okruženju. Jedinične cijene sadrže rad, "
        "materijal, strojeve, režiju i dobit. Cijene Split 2026 u EUR bez PDV-a. "
        "Tender bill for a coastal office building; all-in unit rates, Split "
        "2026 levels in EUR excluding PDV."
    ),
    boq_metadata={
        "standard": "Troškovnik / DIN 276",
        "phase": "Troškovnik za nadmetanje (Tender bill)",
        "base_date": "2026-Q1",
        "price_level": "Split 2026 (EUR, bez PDV-a)",
    },
    sections=[
        (
            "1",
            "1. Pripremni radovi (Preliminary works)",
            {"din276": "390"},
            [
                (
                    "1.01",
                    "Organizacija gradilišta, kontejneri i ograda (Site setup, cabins and hoarding)",
                    "lsum",
                    1,
                    70000,
                    {"din276": "391"},
                ),
                (
                    "1.02",
                    "Toranjska dizalica, najam i montaža (Tower crane hire and erection)",
                    "month",
                    11,
                    6800,
                    {"din276": "391"},
                ),
                (
                    "1.03",
                    "Iskolčenje i geodetsko praćenje (Setting out and survey)",
                    "lsum",
                    1,
                    15000,
                    {"din276": "391"},
                ),
                (
                    "1.04",
                    "Rušenje postojećeg skladišta i raščišćavanje (Demolition of existing warehouse)",
                    "m2",
                    1400,
                    22,
                    {"din276": "212"},
                ),
                (
                    "1.05",
                    "Fasadna skela sa zaštitnom mrežom (Façade scaffold with netting)",
                    "m2",
                    3600,
                    10,
                    {"din276": "392"},
                ),
                (
                    "1.06",
                    "Zaštita na radu i koordinator ZNR (Health and safety and coordinator)",
                    "month",
                    14,
                    2800,
                    {"din276": "391"},
                ),
                (
                    "1.07",
                    "Privremeni priključci vode i struje (Temporary water and power)",
                    "lsum",
                    1,
                    18000,
                    {"din276": "391"},
                ),
            ],
        ),
        (
            "2",
            "2. Zemljani radovi (Earthworks)",
            {"din276": "310"},
            [
                ("2.01", "Strojni iskop u tlu kat. C (Machine excavation in soil)", "m3", 1800, 12, {"din276": "311"}),
                (
                    "2.02",
                    "Iskop u vapnenačkoj stijeni hidrauličkim čekićem (Excavation in limestone, hydraulic breaker)",
                    "m3",
                    4200,
                    28,
                    {"din276": "311"},
                ),
                (
                    "2.03",
                    "Utovar i odvoz iskopa na deponiju (Loading and disposal off site)",
                    "m3",
                    6600,
                    10,
                    {"din276": "311"},
                ),
                (
                    "2.04",
                    "Zaštita pokosa, sidreni mlazni beton s mrežom (Anchored shotcrete slope support)",
                    "m2",
                    900,
                    145,
                    {"din276": "312"},
                ),
                (
                    "2.05",
                    "Tamponski sloj drobljenog kamena d=30 cm (Crushed stone sub-base 300 mm)",
                    "m3",
                    420,
                    34,
                    {"din276": "321"},
                ),
                ("2.06", "Zatrpavanje uz objekt s nabijanjem (Compacted backfill)", "m3", 700, 15, {"din276": "311"}),
            ],
        ),
        (
            "3",
            "3. Betonski i armiranobetonski radovi (Concrete and RC works)",
            {"din276": "300"},
            [
                ("3.01", "Podložni beton C12/15 d=10 cm (Blinding concrete C12/15)", "m3", 140, 120, {"din276": "322"}),
                (
                    "3.02",
                    "Temeljna ploča C35/45 XS1 d=50 cm (Raft foundation C35/45, exposure XS1)",
                    "m3",
                    700,
                    190,
                    {"din276": "322"},
                ),
                (
                    "3.03",
                    "AB zidovi podruma C35/45, vodonepropusni (Watertight basement walls C35/45)",
                    "m3",
                    300,
                    195,
                    {"din276": "331"},
                ),
                (
                    "3.04",
                    "AB jezgre i zidovi nadzemno C30/37 (RC cores and walls above ground)",
                    "m3",
                    420,
                    185,
                    {"din276": "341"},
                ),
                ("3.05", "AB stupovi C35/45 XS1 (RC columns C35/45, exposure XS1)", "m3", 150, 225, {"din276": "343"}),
                (
                    "3.06",
                    "AB ploče C30/37 d=25 cm, raspon 8,1 m (RC floor slabs 250 mm, 8.1 m span)",
                    "m3",
                    1400,
                    175,
                    {"din276": "351"},
                ),
                ("3.07", "AB grede i konzole (RC beams and cantilevers)", "m3", 160, 200, {"din276": "351"}),
                ("3.08", "AB stubišta i podesti (RC stairs and landings)", "m3", 50, 235, {"din276": "351"}),
                (
                    "3.09",
                    "Oplata temelja i zidova (Formwork to foundations and walls)",
                    "m2",
                    4600,
                    36,
                    {"din276": "331"},
                ),
                (
                    "3.10",
                    "Oplata ploča i greda s podupiranjem (Formwork to slabs and beams, propped)",
                    "m2",
                    5900,
                    40,
                    {"din276": "351"},
                ),
                (
                    "3.11",
                    "Armatura B500B, rezanje, savijanje i ugradnja (Reinforcement B500B)",
                    "t",
                    440,
                    1680,
                    {"din276": "351"},
                ),
                (
                    "3.12",
                    "Nehrđajuća armatura u izloženim rubovima (Stainless reinforcement to exposed edges)",
                    "t",
                    6,
                    7800,
                    {"din276": "351"},
                ),
            ],
        ),
        (
            "4",
            "4. Zidarski i suhomontažni radovi (Masonry and drywall)",
            {"din276": "340"},
            [
                (
                    "4.01",
                    "Vanjski zid od blok opeke d=25 cm (External clay block wall 250 mm)",
                    "m2",
                    1100,
                    54,
                    {"din276": "332"},
                ),
                (
                    "4.02",
                    "Gips-kartonske pregrade zajedničkih prostora (Plasterboard partitions to common areas)",
                    "m2",
                    1800,
                    42,
                    {"din276": "342"},
                ),
                (
                    "4.03",
                    "Unutarnja vapnenocementna žbuka (Internal lime-cement plaster)",
                    "m2",
                    5200,
                    15,
                    {"din276": "345"},
                ),
                ("4.04", "Cementni estrih d=6 cm (Cement screed 60 mm)", "m2", 4600, 22, {"din276": "352"}),
                (
                    "4.05",
                    "Obzidavanje instalacijskih vertikala (Enclosing service risers)",
                    "m2",
                    420,
                    44,
                    {"din276": "342"},
                ),
                (
                    "4.06",
                    "Pomoćni zidarski radovi za obrtnike i instalatere (Builder's work in connection)",
                    "lsum",
                    1,
                    32000,
                    {"din276": "349"},
                ),
            ],
        ),
        (
            "5",
            "5. Izolaterski radovi (Insulation and waterproofing)",
            {"din276": "320"},
            [
                (
                    "5.01",
                    "Hidroizolacija temeljne ploče, dva sloja bitumenske trake (Raft waterproofing, two-ply bitumen)",
                    "m2",
                    1450,
                    26,
                    {"din276": "325"},
                ),
                (
                    "5.02",
                    "Hidroizolacija podrumskih zidova sa zaštitom XPS (Basement wall waterproofing with XPS)",
                    "m2",
                    850,
                    40,
                    {"din276": "325"},
                ),
                (
                    "5.03",
                    "Toplinska izolacija ravnog krova XPS 20 cm (Flat roof insulation XPS 200 mm)",
                    "m2",
                    1150,
                    38,
                    {"din276": "363"},
                ),
                (
                    "5.04",
                    "Bijela reflektirajuća TPO membrana, hladni krov (White reflective TPO membrane, cool roof)",
                    "m2",
                    1150,
                    30,
                    {"din276": "363"},
                ),
                (
                    "5.05",
                    "Polimercementna hidroizolacija sanitarija (Liquid waterproofing to washrooms)",
                    "m2",
                    380,
                    17,
                    {"din276": "352"},
                ),
                (
                    "5.06",
                    "Zvučna izolacija poda EPS-T 3 cm (Impact sound insulation)",
                    "m2",
                    4600,
                    7,
                    {"din276": "352"},
                ),
                (
                    "5.07",
                    "Krovna terasa, kamene ploče na podmetačima (Roof terrace stone pavers on pedestals)",
                    "m2",
                    350,
                    85,
                    {"din276": "363"},
                ),
            ],
        ),
        (
            "6",
            "6. Krovopokrivački i limarski radovi (Roofing and sheet metal)",
            {"din276": "360"},
            [
                (
                    "6.01",
                    "Opšav atike, aluminijski plastificirani lim (Parapet capping, coated aluminium)",
                    "m",
                    320,
                    52,
                    {"din276": "363"},
                ),
                ("6.02", "Krovni slivnici (Roof outlets)", "pcs", 12, 320, {"din276": "363"}),
                (
                    "6.03",
                    "Vertikalni oluci, nehrđajući čelik (Stainless steel downpipes)",
                    "m",
                    160,
                    62,
                    {"din276": "335"},
                ),
                ("6.04", "Krovni izlaz s ljestvama (Roof access hatch with ladder)", "pcs", 2, 1900, {"din276": "362"}),
                (
                    "6.05",
                    "Sidrišta za zaštitu od pada, nehrđajući čelik A4 (Fall-arrest anchors, stainless A4)",
                    "pcs",
                    20,
                    190,
                    {"din276": "369"},
                ),
            ],
        ),
        (
            "7",
            "7. Stolarski i bravarski radovi (Joinery and metalwork)",
            {"din276": "330"},
            [
                (
                    "7.01",
                    "Aluminijska fasadna stijena, troslojno solarno zaštitno staklo, morska anodizacija (Aluminium curtain wall, triple solar-control glazing, marine-grade anodising)",
                    "m2",
                    1650,
                    780,
                    {"din276": "337"},
                ),
                (
                    "7.02",
                    "Aluminijski prozori u zonama ETICS fasade (Aluminium windows in ETICS areas)",
                    "m2",
                    380,
                    480,
                    {"din276": "334"},
                ),
                (
                    "7.03",
                    "Fiksne aluminijske lamele, južno i zapadno pročelje (Fixed aluminium brise-soleil, south and west)",
                    "m2",
                    620,
                    210,
                    {"din276": "338"},
                ),
                (
                    "7.04",
                    "Vanjske motorizirane žaluzine (Motorised external venetian blinds)",
                    "m2",
                    700,
                    185,
                    {"din276": "338"},
                ),
                (
                    "7.05",
                    "Automatska klizna ulazna vrata (Automatic sliding entrance doors)",
                    "pcs",
                    2,
                    14500,
                    {"din276": "334"},
                ),
                (
                    "7.06",
                    "Staklena izložbena stijena prizemlja (Ground-floor shopfront glazing)",
                    "m2",
                    240,
                    520,
                    {"din276": "337"},
                ),
                (
                    "7.07",
                    "Protupožarna vrata EI30 i EI60 (Fire doors EI30 and EI60)",
                    "pcs",
                    28,
                    1300,
                    {"din276": "344"},
                ),
                (
                    "7.08",
                    "Unutarnja vrata sanitarija i tehničkih prostora (Internal doors to washrooms and plant rooms)",
                    "pcs",
                    60,
                    380,
                    {"din276": "344"},
                ),
                (
                    "7.09",
                    "Staklene ograde terasa, nehrđajući čelik (Glass terrace balustrade, stainless steel)",
                    "m",
                    260,
                    320,
                    {"din276": "339"},
                ),
                (
                    "7.10",
                    "Stubišna ograda, bojani čelik (Painted steel stair balustrade)",
                    "m",
                    140,
                    170,
                    {"din276": "359"},
                ),
                (
                    "7.11",
                    "Segmentna garažna vrata s pogonom (Motorised sectional garage door)",
                    "pcs",
                    1,
                    9800,
                    {"din276": "334"},
                ),
            ],
        ),
        (
            "8",
            "8. Keramičarski i podopolagački radovi (Tiling and floor finishes)",
            {"din276": "350"},
            [
                (
                    "8.01",
                    "Podne keramičke pločice u sanitarijama (Floor tiles to washrooms)",
                    "m2",
                    380,
                    55,
                    {"din276": "352"},
                ),
                (
                    "8.02",
                    "Zidne keramičke pločice u sanitarijama (Wall tiles to washrooms)",
                    "m2",
                    900,
                    52,
                    {"din276": "345"},
                ),
                (
                    "8.03",
                    "Kamene ploče od domaćeg vapnenca u ulaznom holu (Local limestone to entrance lobby)",
                    "m2",
                    420,
                    145,
                    {"din276": "352"},
                ),
                (
                    "8.04",
                    "Tehnički podignuti pod u uredima (Raised access floor to offices)",
                    "m2",
                    3600,
                    58,
                    {"din276": "352"},
                ),
                (
                    "8.05",
                    "Tekstilne podne ploče u uredima (Carpet tiles to offices)",
                    "m2",
                    3600,
                    26,
                    {"din276": "352"},
                ),
                (
                    "8.06",
                    "Epoksidni premaz poda garaže (Epoxy coating to garage floor)",
                    "m2",
                    1300,
                    19,
                    {"din276": "352"},
                ),
                (
                    "8.07",
                    "Kamene obloge stubišta (Stone to stair treads and risers)",
                    "m2",
                    180,
                    110,
                    {"din276": "352"},
                ),
                (
                    "8.08",
                    "Uređenje recepcije i ulaznog hola (Reception and lobby fit-out)",
                    "lsum",
                    1,
                    85000,
                    {"din276": "371"},
                ),
                ("8.09", "Čajne kuhinje po katu (Tea points per floor)", "pcs", 4, 9500, {"din276": "371"}),
            ],
        ),
        (
            "9",
            "9. Soboslikarski i ličilački radovi (Painting and ceilings)",
            {"din276": "340"},
            [
                (
                    "9.01",
                    "Gletanje i bojanje zidova disperzijom, 2x (Skim coat and emulsion to walls)",
                    "m2",
                    7800,
                    8.5,
                    {"din276": "345"},
                ),
                (
                    "9.02",
                    "Modularni spušteni strop, mineralne ploče (Suspended mineral fibre ceiling to offices)",
                    "m2",
                    3600,
                    38,
                    {"din276": "353"},
                ),
                (
                    "9.03",
                    "Spušteni strop od gips-kartona, hodnici i sanitarije (Plasterboard ceilings to corridors and washrooms)",
                    "m2",
                    700,
                    36,
                    {"din276": "353"},
                ),
                (
                    "9.04",
                    "Bojanje garaže i tehničkih prostorija (Painting to garage and plant rooms)",
                    "m2",
                    2600,
                    6,
                    {"din276": "345"},
                ),
                (
                    "9.05",
                    "Antikorozivni sustav C5 za morsku sredinu (C5 marine anti-corrosion coating to steelwork)",
                    "m2",
                    380,
                    28,
                    {"din276": "339"},
                ),
            ],
        ),
        (
            "10",
            "10. Fasaderski radovi (ETICS façade)",
            {"din276": "330"},
            [
                (
                    "10.01",
                    "ETICS fasada, kamena vuna 12 cm (ETICS mineral wool 120 mm)",
                    "m2",
                    1250,
                    84,
                    {"din276": "335"},
                ),
                (
                    "10.02",
                    "Silikonska završna žbuka otporna na sol, doplata (Salt-resistant silicone render, extra over)",
                    "m2",
                    1250,
                    9,
                    {"din276": "335"},
                ),
                ("10.03", "Kamena obloga sokla (Stone plinth cladding)", "m2", 180, 140, {"din276": "335"}),
                (
                    "10.04",
                    "Toplinska izolacija špaleta i nadvoja (Reveal and head insulation)",
                    "m",
                    900,
                    15,
                    {"din276": "335"},
                ),
                (
                    "10.05",
                    "Pričvrsnice od nehrđajućeg čelika A4 za priobalje (Stainless A4 fixings for coastal exposure)",
                    "lsum",
                    1,
                    14000,
                    {"din276": "335"},
                ),
            ],
        ),
        (
            "11",
            "11. Instalacije (MEP: vodovod i odvodnja, strojarske, elektro)",
            {"din276": "400"},
            [
                (
                    "11.01",
                    "Vodovod i sanitarni uređaji, po sanitarnom čvoru (Plumbing and sanitaryware per washroom block)",
                    "pcs",
                    11,
                    19500,
                    {"din276": "412"},
                ),
                ("11.02", "Unutarnja kanalizacija PP i PVC (Internal drainage)", "lsum", 1, 58000, {"din276": "411"}),
                (
                    "11.03",
                    "Priključci na javni vodovod i kanalizaciju (Water and sewer connections)",
                    "lsum",
                    1,
                    42000,
                    {"din276": "411"},
                ),
                (
                    "11.04",
                    "VRF sustav grijanja i hlađenja s rekuperacijom (VRF heating and cooling with heat recovery)",
                    "m2",
                    4400,
                    135,
                    {"din276": "433"},
                ),
                (
                    "11.05",
                    "Klima komore s povratom topline (AHUs with heat recovery)",
                    "pcs",
                    2,
                    95000,
                    {"din276": "431"},
                ),
                (
                    "11.06",
                    "Kanalni razvod zraka, pocinčani lim (Galvanised ductwork distribution)",
                    "m2",
                    2600,
                    68,
                    {"din276": "431"},
                ),
                (
                    "11.07",
                    "Ventilacija garaže s detekcijom CO (Garage ventilation with CO detection)",
                    "lsum",
                    1,
                    62000,
                    {"din276": "431"},
                ),
                (
                    "11.08",
                    "Dizalica topline za potrošnu toplu vodu (Heat pump for domestic hot water)",
                    "lsum",
                    1,
                    22000,
                    {"din276": "421"},
                ),
                (
                    "11.09",
                    "Transformatorska stanica 10/0,4 kV, 630 kVA (Substation 10/0.4 kV, 630 kVA)",
                    "lsum",
                    1,
                    150000,
                    {"din276": "441"},
                ),
                (
                    "11.10",
                    "Glavni razvod i katni razdjelnici (Main LV distribution and floor boards)",
                    "lsum",
                    1,
                    175000,
                    {"din276": "444"},
                ),
                (
                    "11.11",
                    "LED rasvjeta ureda s DALI upravljanjem (LED office lighting with DALI control)",
                    "m2",
                    4400,
                    48,
                    {"din276": "445"},
                ),
                (
                    "11.12",
                    "Rasvjeta zajedničkih prostora i garaže (Lighting to common areas and garage)",
                    "m2",
                    2200,
                    20,
                    {"din276": "445"},
                ),
                (
                    "11.13",
                    "Gromobranska instalacija i uzemljenje (Lightning protection and earthing)",
                    "lsum",
                    1,
                    24000,
                    {"din276": "446"},
                ),
                ("11.14", "Sunčana elektrana na krovu 60 kW (Rooftop PV 60 kWp)", "lsum", 1, 66000, {"din276": "442"}),
                ("11.15", "Punionice za električna vozila (EV charging points)", "pcs", 10, 2600, {"din276": "444"}),
                ("11.16", "Strukturno kabliranje (Structured cabling)", "m2", 4400, 20, {"din276": "451"}),
                ("11.17", "Sustav vatrodojave (Fire detection and alarm)", "m2", 6600, 8, {"din276": "456"}),
                (
                    "11.18",
                    "Sprinkler sustav u garaži (Sprinkler installation to garage)",
                    "m2",
                    1350,
                    32,
                    {"din276": "474"},
                ),
                (
                    "11.19",
                    "Unutarnja hidrantska mreža (Internal fire hydrant main)",
                    "lsum",
                    1,
                    38000,
                    {"din276": "474"},
                ),
                (
                    "11.20",
                    "Kontrola pristupa i video nadzor (Access control and CCTV)",
                    "lsum",
                    1,
                    48000,
                    {"din276": "456"},
                ),
                (
                    "11.21",
                    "Centralni nadzorni sustav zgrade (Building management system)",
                    "lsum",
                    1,
                    120000,
                    {"din276": "481"},
                ),
                (
                    "11.22",
                    "Osobno dizalo 1000 kg, 6 stanica (Passenger lift 1000 kg, 6 stops)",
                    "pcs",
                    2,
                    78000,
                    {"din276": "461"},
                ),
            ],
        ),
        (
            "12",
            "12. Vanjsko uređenje (External works)",
            {"din276": "500"},
            [
                (
                    "12.01",
                    "Asfaltiranje pristupne prometnice i rampe (Asphalt access road and ramp)",
                    "m2",
                    500,
                    50,
                    {"din276": "520"},
                ),
                (
                    "12.02",
                    "Popločenje trga kamenim pločama (Stone paving to forecourt)",
                    "m2",
                    450,
                    75,
                    {"din276": "520"},
                ),
                (
                    "12.03",
                    "Mediteransko zelenilo s kap po kap navodnjavanjem (Mediterranean planting with drip irrigation)",
                    "m2",
                    480,
                    38,
                    {"din276": "530"},
                ),
                (
                    "12.04",
                    "Vanjska oborinska odvodnja sa separatorom (External stormwater drainage with separator)",
                    "lsum",
                    1,
                    42000,
                    {"din276": "541"},
                ),
                ("12.05", "Vanjska rasvjeta (External lighting)", "pcs", 12, 1500, {"din276": "550"}),
            ],
        ),
    ],
    markups=[
        ("Nepredviđeni radovi (Contingency)", 4.0, "contingency", "direct_cost"),
        ("PDV 25%", 25.0, "tax", "cumulative"),
    ],
    total_months=18,
    tender_name="Glavni izvođač - Poslovna zgrada Split",
    tender_companies=[
        ("Priobalna Gradnja d.o.o.", "ponude@priobalna-gradnja.example", 0.97),
        ("Srednjodalmatinski Graditelj d.d.", "nadmetanje@sdgraditelj.example", 1.01),
        ("Kaštelanska Izgradnja d.o.o.", "ponude@kastelanska-izgradnja.example", 1.06),
    ],
    project_metadata={
        "address": "Poljička cesta 45, 21000 Split, Croatia",
        "client": "Poljud Poslovni Prostori d.o.o.",
        "architect": "Studio Arhitekture Marjan d.o.o.",
        "structural_engineer": "Konstrukcije Žnjan d.o.o.",
        "qs": "Troškovnici Dalmacija d.o.o.",
        "gfa_m2": 6600,
        "storeys_above": 5,
        "storeys_below": 1,
        "parking_spaces": 42,
        "energy_class": "A",
        "exposure_note": "Beton izložen morskoj soli u razredu XS1, pričvrsnice A4, premazi C5.",
        "vat_note": "Sve jedinične cijene su bez PDV-a. PDV 25% obračunava se u rekapitulaciji.",
    },
)
