# DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
# Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
from __future__ import annotations

from app.core.demo_projects import DemoTemplate

# ---------------------------------------------------------------------------
# Partner pack: croatia-hr - Stambena zgrada, Zagreb Trešnjevka
# ---------------------------------------------------------------------------
# Croatian residential troškovnik, laid out chapter by chapter the way a
# Croatian tender bill is: one chapter per trade (pripremni, zemljani,
# betonski, zidarski ... instalacije), items numbered within the chapter.
# Every line is also mapped to a DIN 276 cost group, which is the platform's
# nearest supported hierarchy for Croatia.
#
# Unit rates are all-in troškovnik prices (labour, material, plant, site and
# head office overheads and profit included), so the recapitulation adds only
# a contingency and PDV. Prices are EUR excluding 25% PDV.
# ---------------------------------------------------------------------------

TEMPLATE = DemoTemplate(
    demo_id="residential-zagreb",
    project_name="Stambena zgrada - Zagreb Trešnjevka (Residential Building, Zagreb)",
    project_description=(
        "Novogradnja višestambene zgrade u Zagrebu, Trešnjevka: Po+P+5, "
        "54 stana, podzemna garaža sa 60 parkirnih mjesta. Bruto površina "
        "cca 7 600 m2. Armiranobetonski skelet s ispunom od blok opeke, "
        "ETICS fasada, ravni krov. Energetski razred A. New-build residential "
        "building in Zagreb Trešnjevka: basement plus ground plus five storeys, "
        "54 flats, underground garage with 60 spaces. GFA approx. 7,600 m2. "
        "RC frame with clay block infill, ETICS façade, flat roof. Troškovnik "
        "total approx. 8,992,000 EUR excluding PDV (approx. 1,183 EUR/m2 GFA), "
        "priced at Zagreb 2026 levels, before a 3% contingency."
    ),
    region="HR",
    classification_standard="din276",
    currency="EUR",
    locale="en",
    address={
        "street": "Ozaljska ulica 112",
        "city": "Zagreb",
        "postcode": "10000",
        "country": "Croatia",
        "lat": 45.8012,
        "lng": 15.9461,
    },
    validation_rule_sets=["din276", "boq_quality"],
    boq_name="Troškovnik - Stambena zgrada Trešnjevka (Bill of Quantities)",
    boq_description=(
        "Troškovnik građevinskih, obrtničkih i instalaterskih radova za "
        "višestambenu zgradu s 54 stana. Jedinične cijene sadrže rad, materijal, "
        "strojeve, režiju i dobit. Cijene Zagreb 2026 u EUR bez PDV-a. Tender "
        "bill for the building, construction, finishing and MEP works; all-in "
        "unit rates, Zagreb 2026 levels in EUR excluding PDV."
    ),
    boq_metadata={
        "standard": "Troškovnik / DIN 276",
        "phase": "Troškovnik za nadmetanje (Tender bill)",
        "base_date": "2026-Q1",
        "price_level": "Zagreb 2026 (EUR, bez PDV-a)",
    },
    sections=[
        (
            "1",
            "1. Pripremni radovi (Preliminary works)",
            {"din276": "390"},
            [
                (
                    "1.01",
                    "Organizacija gradilišta, kontejneri i ograda (Site setup, cabins and hoarding)",
                    "lsum",
                    1,
                    85000,
                    {"din276": "391"},
                ),
                (
                    "1.02",
                    "Toranjska dizalica, najam i montaža (Tower crane hire and erection)",
                    "month",
                    14,
                    6500,
                    {"din276": "391"},
                ),
                (
                    "1.03",
                    "Iskolčenje i geodetsko praćenje (Setting out and survey)",
                    "lsum",
                    1,
                    18000,
                    {"din276": "391"},
                ),
                (
                    "1.04",
                    "Uklanjanje postojećih objekata i raščišćavanje (Demolition and site clearance)",
                    "m2",
                    2600,
                    9,
                    {"din276": "212"},
                ),
                (
                    "1.05",
                    "Fasadna skela sa zaštitnom mrežom (Façade scaffold with netting)",
                    "m2",
                    5200,
                    9,
                    {"din276": "392"},
                ),
                (
                    "1.06",
                    "Zaštita na radu i koordinator ZNR (Health and safety and coordinator)",
                    "month",
                    18,
                    2800,
                    {"din276": "391"},
                ),
                (
                    "1.07",
                    "Privremeni priključci vode i struje (Temporary water and power)",
                    "lsum",
                    1,
                    22000,
                    {"din276": "391"},
                ),
            ],
        ),
        (
            "2",
            "2. Zemljani radovi (Earthworks)",
            {"din276": "310"},
            [
                ("2.01", "Skidanje humusa d=30 cm (Topsoil strip 300 mm)", "m2", 2600, 3, {"din276": "311"}),
                (
                    "2.02",
                    "Široki strojni iskop građevne jame, kat. B-C (Bulk machine excavation)",
                    "m3",
                    9800,
                    11,
                    {"din276": "311"},
                ),
                (
                    "2.03",
                    "Utovar i odvoz viška materijala na deponiju (Loading and disposal off site)",
                    "m3",
                    8900,
                    9.5,
                    {"din276": "311"},
                ),
                (
                    "2.04",
                    "Zaštita građevne jame, sidrena pilotna stijena (Anchored secant pile retaining wall)",
                    "m2",
                    1350,
                    210,
                    {"din276": "312"},
                ),
                (
                    "2.05",
                    "Crpljenje podzemne vode tijekom gradnje (Dewatering during construction)",
                    "month",
                    6,
                    4200,
                    {"din276": "313"},
                ),
                (
                    "2.06",
                    "Tamponski sloj drobljenog kamena d=30 cm (Crushed stone sub-base 300 mm)",
                    "m3",
                    620,
                    32,
                    {"din276": "321"},
                ),
                ("2.07", "Zatrpavanje uz objekt s nabijanjem (Compacted backfill)", "m3", 1400, 14, {"din276": "311"}),
            ],
        ),
        (
            "3",
            "3. Betonski i armiranobetonski radovi (Concrete and RC works)",
            {"din276": "300"},
            [
                ("3.01", "Podložni beton C12/15 d=10 cm (Blinding concrete C12/15)", "m3", 190, 115, {"din276": "322"}),
                ("3.02", "Temeljna ploča C30/37 d=60 cm (Raft foundation C30/37)", "m3", 1150, 165, {"din276": "322"}),
                (
                    "3.03",
                    "AB zidovi podruma C30/37, vodonepropusni d=30 cm (Watertight basement walls)",
                    "m3",
                    420,
                    185,
                    {"din276": "331"},
                ),
                (
                    "3.04",
                    "AB zidovi i jezgre nadzemno C30/37 d=20 cm (RC walls and cores above ground)",
                    "m3",
                    780,
                    180,
                    {"din276": "341"},
                ),
                ("3.05", "AB stupovi C30/37 (RC columns)", "m3", 95, 210, {"din276": "343"}),
                ("3.06", "AB međukatne ploče C30/37 d=22 cm (RC floor slabs)", "m3", 1700, 160, {"din276": "351"}),
                ("3.07", "AB grede i nadvoji C30/37 (RC beams and lintels)", "m3", 140, 195, {"din276": "351"}),
                ("3.08", "AB stubišta i podesti (RC stairs and landings)", "m3", 75, 230, {"din276": "351"}),
                (
                    "3.09",
                    "Balkonske ploče s elementima za prekid toplinskog mosta (Balcony slabs with thermal break)",
                    "m2",
                    780,
                    95,
                    {"din276": "351"},
                ),
                (
                    "3.10",
                    "Oplata temelja i zidova (Formwork to foundations and walls)",
                    "m2",
                    7600,
                    34,
                    {"din276": "331"},
                ),
                (
                    "3.11",
                    "Oplata ploča i greda s podupiranjem (Formwork to slabs and beams, propped)",
                    "m2",
                    7400,
                    38,
                    {"din276": "351"},
                ),
                (
                    "3.12",
                    "Armatura B500B, rezanje, savijanje i ugradnja (Reinforcement B500B)",
                    "t",
                    520,
                    1580,
                    {"din276": "351"},
                ),
            ],
        ),
        (
            "4",
            "4. Zidarski radovi (Masonry)",
            {"din276": "340"},
            [
                (
                    "4.01",
                    "Vanjski zid od blok opeke d=25 cm (External clay block wall 250 mm)",
                    "m2",
                    3100,
                    52,
                    {"din276": "332"},
                ),
                (
                    "4.02",
                    "Zidovi između stanova, akustični blok d=25 cm (Party walls, acoustic block)",
                    "m2",
                    2100,
                    58,
                    {"din276": "342"},
                ),
                (
                    "4.03",
                    "Pregradni zidovi od blok opeke d=10-12 cm (Internal block partitions)",
                    "m2",
                    4600,
                    36,
                    {"din276": "342"},
                ),
                (
                    "4.04",
                    "Unutarnja vapnenocementna žbuka (Internal lime-cement plaster)",
                    "m2",
                    19500,
                    14,
                    {"din276": "345"},
                ),
                (
                    "4.05",
                    "Cementni estrih d=6 cm, plivajući pod (Floating cement screed 60 mm)",
                    "m2",
                    5400,
                    21,
                    {"din276": "352"},
                ),
                (
                    "4.06",
                    "Pomoćni zidarski radovi za obrtnike i instalatere (Builder's work in connection)",
                    "lsum",
                    1,
                    38000,
                    {"din276": "349"},
                ),
                (
                    "4.07",
                    "Obzidavanje instalacijskih vertikala (Enclosing service risers)",
                    "m2",
                    620,
                    42,
                    {"din276": "342"},
                ),
            ],
        ),
        (
            "5",
            "5. Izolaterski radovi (Insulation and waterproofing)",
            {"din276": "320"},
            [
                (
                    "5.01",
                    "Hidroizolacija temeljne ploče, dva sloja bitumenske trake (Raft waterproofing, two-ply bitumen)",
                    "m2",
                    1950,
                    24,
                    {"din276": "325"},
                ),
                (
                    "5.02",
                    "Hidroizolacija podrumskih zidova sa zaštitom XPS (Basement wall waterproofing with XPS)",
                    "m2",
                    1100,
                    38,
                    {"din276": "325"},
                ),
                (
                    "5.03",
                    "Zvučna izolacija poda EPS-T 3 cm i PE folija (Impact sound insulation)",
                    "m2",
                    5400,
                    7.5,
                    {"din276": "352"},
                ),
                (
                    "5.04",
                    "Toplinska izolacija ravnog krova XPS 20 cm (Flat roof insulation XPS 200 mm)",
                    "m2",
                    980,
                    36,
                    {"din276": "363"},
                ),
                (
                    "5.05",
                    "Hidroizolacija ravnog krova, TPO membrana (Flat roof TPO membrane)",
                    "m2",
                    980,
                    28,
                    {"din276": "363"},
                ),
                (
                    "5.06",
                    "Polimercementna hidroizolacija kupaonica i balkona (Liquid waterproofing, bathrooms and balconies)",
                    "m2",
                    1650,
                    16,
                    {"din276": "352"},
                ),
                (
                    "5.07",
                    "Toplinska izolacija stropa garaže, kamena vuna 10 cm (Garage soffit insulation)",
                    "m2",
                    900,
                    32,
                    {"din276": "353"},
                ),
                ("5.08", "Ekstenzivni zeleni krov (Extensive green roof)", "m2", 350, 55, {"din276": "363"}),
            ],
        ),
        (
            "6",
            "6. Krovopokrivački i limarski radovi (Roofing and sheet metal)",
            {"din276": "360"},
            [
                (
                    "6.01",
                    "Opšav atike, aluminijski plastificirani lim (Parapet capping, coated aluminium)",
                    "m",
                    420,
                    48,
                    {"din276": "363"},
                ),
                ("6.02", "Krovni slivnici s grijačem (Heated roof outlets)", "pcs", 16, 280, {"din276": "363"}),
                ("6.03", "Vertikalni oluci, aluminij (Aluminium downpipes)", "m", 240, 38, {"din276": "335"}),
                (
                    "6.04",
                    "Podne ploče na podmetačima, krovne terase (Terrace pavers on pedestals)",
                    "m2",
                    420,
                    75,
                    {"din276": "363"},
                ),
                ("6.05", "Krovni izlaz s ljestvama (Roof access hatch with ladder)", "pcs", 2, 1850, {"din276": "362"}),
                ("6.06", "Sidrišta za zaštitu od pada (Roof fall-arrest anchors)", "pcs", 24, 180, {"din276": "369"}),
            ],
        ),
        (
            "7",
            "7. Stolarski i bravarski radovi (Joinery and metalwork)",
            {"din276": "330"},
            [
                (
                    "7.01",
                    "PVC prozori, troslojno staklo Uw<=0,9 (PVC windows, triple glazed)",
                    "m2",
                    1150,
                    420,
                    {"din276": "334"},
                ),
                (
                    "7.02",
                    "PVC balkonska vrata, troslojno staklo (PVC balcony doors, triple glazed)",
                    "m2",
                    520,
                    450,
                    {"din276": "334"},
                ),
                (
                    "7.03",
                    "Vanjske rolete s elektromotorom (Motorised external roller shutters)",
                    "m2",
                    1100,
                    145,
                    {"din276": "338"},
                ),
                (
                    "7.04",
                    "Ulazna vrata zgrade, aluminij (Aluminium building entrance doors)",
                    "pcs",
                    2,
                    7800,
                    {"din276": "334"},
                ),
                (
                    "7.05",
                    "Protuprovalna ulazna vrata stanova RC3 (Security flat entrance doors RC3)",
                    "pcs",
                    54,
                    1150,
                    {"din276": "344"},
                ),
                (
                    "7.06",
                    "Unutarnja sobna vrata s dovratnikom (Internal doors with frames)",
                    "pcs",
                    230,
                    330,
                    {"din276": "344"},
                ),
                (
                    "7.07",
                    "Protupožarna vrata EI30 i EI60 (Fire doors EI30 and EI60)",
                    "pcs",
                    22,
                    1250,
                    {"din276": "344"},
                ),
                (
                    "7.08",
                    "Segmentna garažna vrata s pogonom (Motorised sectional garage door)",
                    "pcs",
                    1,
                    9500,
                    {"din276": "334"},
                ),
                (
                    "7.09",
                    "Balkonske ograde, čelik i staklo (Balcony balustrades, steel and glass)",
                    "m",
                    640,
                    240,
                    {"din276": "339"},
                ),
                (
                    "7.10",
                    "Stubišna ograda, bojani čelik (Painted steel stair balustrade)",
                    "m",
                    190,
                    165,
                    {"din276": "359"},
                ),
                (
                    "7.11",
                    "Unutarnje i vanjske prozorske klupčice (Internal and external window sills)",
                    "m",
                    900,
                    32,
                    {"din276": "334"},
                ),
            ],
        ),
        (
            "8",
            "8. Keramičarski i podopolagački radovi (Tiling and floor finishes)",
            {"din276": "350"},
            [
                (
                    "8.01",
                    "Podne keramičke pločice, kupaonice i kuhinje (Floor tiles, bathrooms and kitchens)",
                    "m2",
                    1250,
                    52,
                    {"din276": "352"},
                ),
                (
                    "8.02",
                    "Zidne keramičke pločice u kupaonicama (Wall tiles to bathrooms)",
                    "m2",
                    2400,
                    50,
                    {"din276": "345"},
                ),
                (
                    "8.03",
                    "Višeslojni hrastov parket, lakiran (Engineered oak parquet, lacquered)",
                    "m2",
                    3300,
                    58,
                    {"din276": "352"},
                ),
                (
                    "8.04",
                    "Kamene ploče stubišta i ulaznog hola (Stone to stairs and entrance lobby)",
                    "m2",
                    520,
                    95,
                    {"din276": "352"},
                ),
                (
                    "8.05",
                    "Protuklizne mrazootporne pločice na balkonima (Frost-resistant tiles to balconies)",
                    "m2",
                    780,
                    55,
                    {"din276": "352"},
                ),
                (
                    "8.06",
                    "Epoksidni premaz poda garaže (Epoxy coating to garage floor)",
                    "m2",
                    1800,
                    18,
                    {"din276": "352"},
                ),
                ("8.07", "Sokl lajsne (Skirting)", "m", 5200, 7, {"din276": "352"}),
            ],
        ),
        (
            "9",
            "9. Soboslikarski i ličilački radovi (Painting)",
            {"din276": "340"},
            [
                (
                    "9.01",
                    "Gletanje i bojanje zidova disperzijom, 2x (Skim coat and emulsion to walls)",
                    "m2",
                    19500,
                    8,
                    {"din276": "345"},
                ),
                (
                    "9.02",
                    "Gletanje i bojanje stropova (Skim coat and emulsion to ceilings)",
                    "m2",
                    5600,
                    8.5,
                    {"din276": "353"},
                ),
                (
                    "9.03",
                    "Bojanje garaže i tehničkih prostorija (Painting to garage and plant rooms)",
                    "m2",
                    3400,
                    6,
                    {"din276": "345"},
                ),
                (
                    "9.04",
                    "Antikorozivni premaz bravarije (Anti-corrosion coating to steelwork)",
                    "m2",
                    420,
                    18,
                    {"din276": "339"},
                ),
                (
                    "9.05",
                    "Spušteni strop od gips-kartona u hodnicima (Plasterboard ceilings to corridors)",
                    "m2",
                    780,
                    34,
                    {"din276": "353"},
                ),
            ],
        ),
        (
            "10",
            "10. Fasaderski radovi (ETICS façade)",
            {"din276": "330"},
            [
                (
                    "10.01",
                    "ETICS fasada EPS 15 cm, tankoslojna silikatna žbuka (ETICS EPS 150 mm, silicate render)",
                    "m2",
                    3300,
                    72,
                    {"din276": "335"},
                ),
                (
                    "10.02",
                    "ETICS kamena vuna 15 cm, protupožarne barijere (ETICS mineral wool 150 mm, fire barriers)",
                    "m2",
                    650,
                    88,
                    {"din276": "335"},
                ),
                (
                    "10.03",
                    "Sokl XPS s dekorativnom mozaik žbukom (Plinth XPS with mosaic render)",
                    "m2",
                    280,
                    78,
                    {"din276": "335"},
                ),
                (
                    "10.04",
                    "Toplinska izolacija špaleta i nadvoja (Reveal and head insulation)",
                    "m",
                    2100,
                    14,
                    {"din276": "335"},
                ),
                (
                    "10.05",
                    "Ventilirana fasada HPL ploče u prizemlju (Ventilated HPL cladding at ground floor)",
                    "m2",
                    220,
                    145,
                    {"din276": "335"},
                ),
            ],
        ),
        (
            "11",
            "11. Instalacije (MEP: vodovod i odvodnja, strojarske, elektro)",
            {"din276": "400"},
            [
                (
                    "11.01",
                    "Vodovodna instalacija s vertikalama, po stanu (Water supply per flat)",
                    "pcs",
                    54,
                    3400,
                    {"din276": "412"},
                ),
                (
                    "11.02",
                    "Unutarnja kanalizacija PP i PVC, po stanu (Internal drainage per flat)",
                    "pcs",
                    54,
                    2100,
                    {"din276": "411"},
                ),
                (
                    "11.03",
                    "Sanitarni uređaji i armature, po stanu (Sanitaryware and fittings per flat)",
                    "pcs",
                    54,
                    3200,
                    {"din276": "412"},
                ),
                (
                    "11.04",
                    "Priključci na javni vodovod i kanalizaciju (Water and sewer connections)",
                    "lsum",
                    1,
                    45000,
                    {"din276": "411"},
                ),
                (
                    "11.05",
                    "Centralna dizalica topline zrak-voda (Central air-to-water heat pump)",
                    "lsum",
                    1,
                    185000,
                    {"din276": "421"},
                ),
                (
                    "11.06",
                    "Podno grijanje i hlađenje, po stanu (Underfloor heating and cooling per flat)",
                    "pcs",
                    54,
                    5200,
                    {"din276": "423"},
                ),
                (
                    "11.07",
                    "Split klima uređaji u dnevnim boravcima (Split AC units to living rooms)",
                    "pcs",
                    54,
                    1450,
                    {"din276": "433"},
                ),
                (
                    "11.08",
                    "Rekuperator s povratom topline, po stanu (MVHR unit per flat)",
                    "pcs",
                    54,
                    3100,
                    {"din276": "431"},
                ),
                (
                    "11.09",
                    "Ventilacija garaže s detekcijom CO (Garage ventilation with CO detection)",
                    "lsum",
                    1,
                    68000,
                    {"din276": "431"},
                ),
                (
                    "11.10",
                    "Elektroinstalacija jake i slabe struje, po stanu (Electrical installation per flat)",
                    "pcs",
                    54,
                    4600,
                    {"din276": "444"},
                ),
                (
                    "11.11",
                    "Glavni razvod, KPMO i razdjelnici (Main LV distribution and metering)",
                    "lsum",
                    1,
                    95000,
                    {"din276": "443"},
                ),
                (
                    "11.12",
                    "Rasvjeta zajedničkih prostora i garaže (Lighting to common areas and garage)",
                    "m2",
                    3200,
                    18,
                    {"din276": "445"},
                ),
                (
                    "11.13",
                    "Gromobranska instalacija i uzemljenje (Lightning protection and earthing)",
                    "lsum",
                    1,
                    26000,
                    {"din276": "446"},
                ),
                ("11.14", "Sunčana elektrana na krovu 30 kW (Rooftop PV 30 kWp)", "lsum", 1, 36000, {"din276": "442"}),
                ("11.15", "Punionice za električna vozila (EV charging points)", "pcs", 12, 2400, {"din276": "444"}),
                ("11.16", "Sustav vatrodojave (Fire detection and alarm)", "m2", 7600, 5.5, {"din276": "456"}),
                (
                    "11.17",
                    "Interfon, video i strukturno kabliranje, po stanu (Intercom and data cabling per flat)",
                    "pcs",
                    54,
                    950,
                    {"din276": "451"},
                ),
                (
                    "11.18",
                    "Osobno dizalo 630 kg, 7 stanica (Passenger lift 630 kg, 7 stops)",
                    "pcs",
                    2,
                    58000,
                    {"din276": "461"},
                ),
                (
                    "11.19",
                    "Unutarnja hidrantska mreža (Internal fire hydrant main)",
                    "lsum",
                    1,
                    42000,
                    {"din276": "474"},
                ),
            ],
        ),
        (
            "12",
            "12. Vanjsko uređenje (External works)",
            {"din276": "500"},
            [
                (
                    "12.01",
                    "Asfaltiranje pristupne rampe i prometnice (Asphalt access ramp and road)",
                    "m2",
                    650,
                    48,
                    {"din276": "520"},
                ),
                (
                    "12.02",
                    "Betonski opločnici pješačkih staza (Concrete block paving to footpaths)",
                    "m2",
                    520,
                    42,
                    {"din276": "520"},
                ),
                ("12.03", "Zelene površine i sadnja (Soft landscaping and planting)", "m2", 900, 22, {"din276": "530"}),
                (
                    "12.04",
                    "Vanjska oborinska odvodnja sa separatorom (External stormwater drainage with separator)",
                    "lsum",
                    1,
                    48000,
                    {"din276": "541"},
                ),
                ("12.05", "Dječje igralište (Playground)", "lsum", 1, 35000, {"din276": "530"}),
                ("12.06", "Vanjska rasvjeta (External lighting)", "pcs", 14, 1400, {"din276": "550"}),
            ],
        ),
    ],
    markups=[
        ("Nepredviđeni radovi (Contingency)", 3.0, "contingency", "direct_cost"),
        ("PDV 25%", 25.0, "tax", "cumulative"),
    ],
    total_months=20,
    tender_name="Glavni izvođač - Stambena zgrada Trešnjevka",
    tender_companies=[
        ("Savski Graditelji d.o.o.", "ponude@savski-graditelji.example", 0.98),
        ("Kajkavska Izgradnja d.d.", "nadmetanje@kajkavska-izgradnja.example", 1.02),
        ("Sjeverozapadni Građevinar d.o.o.", "ponude@szgradevinar.example", 1.05),
    ],
    project_metadata={
        "address": "Ozaljska ulica 112, 10000 Zagreb, Croatia",
        "client": "Trešnjevka Stanogradnja d.o.o.",
        "architect": "Arhitektonski Atelje Savica d.o.o.",
        "structural_engineer": "Statika Jarun d.o.o.",
        "qs": "Troškovnici Zagreb d.o.o.",
        "gfa_m2": 7600,
        "units": 54,
        "storeys_above": 6,
        "storeys_below": 1,
        "parking_spaces": 60,
        "energy_class": "A",
        "vat_note": "Sve jedinične cijene su bez PDV-a. PDV 25% obračunava se u rekapitulaciji.",
    },
)
