# DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
# Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
"""Public showcase demo: Lebensmittelmarkt Heidelberg / Retail Market Heidelberg.

Urban-infill single-storey food retail market with a structured car deck on a
constrained inner-city plot in the Pfaffengrund district of Heidelberg (DE).
Unlike the larger out-of-town Heilbronn store this is a tighter, smaller box
squeezed into a built-up commercial street: the logistics and site-setup cost
is higher (lane closures, crane provision, traffic management on a live road),
the facade is more demanding because the parcel sits inside a municipal design
board area (Gestaltungssatzung, a ceramic and brick-slip accent envelope), and
the PV array is smaller because the roof is partly shaded by the neighbouring
block. A self-contained showcase project that the partner-pack loader picks up
automatically; it shares the canonical 16-LV gewerk structure and the
VE.Abschnitt.Position OZ scheme with the other retail demos but is priced from
its own reconciled cost plan. All companies are fictional with descriptive
generic names; the only real entity is the public building authority.

Data layer
----------
The BOQ is assembled from two module-level tables so later passes only have to
touch the data, never the assembly logic:

* ``_VE_SECTIONS`` - the 16 priced procurement units (Vergabeeinheiten) that
  map 1:1 to LV sections (OZ scheme ``VE.subsection.position``). Their budgets
  sum to exactly 7,200,000.00 EUR net.
* ``_POSITIONS`` - the full LV grouped into thematic OZ subsections per Gewerk.
  Every section sums EXACTLY to its procurement-unit budget; the last lsum row
  in each section absorbs the rounding remainder so a careless rate edit can
  never silently drift a budget. ``_build_sections`` raises if any section
  drifts by a cent.

Money contract
--------------
Per LV section the position sum equals the procurement-unit budget to the cent,
and the 16 budgets sum to 7,200,000.00 EUR net. All money arithmetic runs
through ``Decimal`` so the emitted two-decimal floats are exact.

Geometry
--------
Quantities derive from the canonical building geometry of the smaller box:
footprint 60 x 36 m = 2,160 m2, work area 2,203 m2 (footprint x 1.02),
perimeter 192 m, 10 axes a 6.0 m -> 30 columns / 30 pocket foundations,
ground slab 432 m3 (2,160 x 0.20), envelope balance 980 + 320 + 110 + 39 m2
on roughly 192 x 6.6 m of skin, 520 PV modules a 440 Wp = 228.8 kWp, and a
compact car park of about 78 stalls.
"""

from __future__ import annotations

from decimal import Decimal

from app.core.demo_projects import DemoTemplate, SectionDef

__all__ = ["TEMPLATE"]

# (oz, description, unit, quantity, unit_rate_eur, din276_code)
_PositionRow = tuple[str, str, str, float, float, str]

# (section_ordinal, ve_id, section_title, primary_din276_kg, ve_budget_eur)
_VeSection = tuple[str, str, str, str, float]

_VE_SECTIONS: list[_VeSection] = [
    (
        "01",
        "VE-01",
        "LV 01 - Baustelleneinrichtung und Gemeinkosten (Site establishment and general items)",
        "390",
        210_000.00,
    ),
    ("02", "VE-02", "LV 02 - Erdbau und Erschließung (Earthworks and site servicing)", "310", 320_000.00),
    (
        "04",
        "VE-04",
        "LV 04 - Rohbau: Gründung, Bodenplatte, Industrieboden, Massivbau (Shell works)",
        "320",
        690_000.00,
    ),
    (
        "05",
        "VE-05",
        "LV 05 - Dach: Trapezblech, Dämmung, Abdichtung, RWA (Roof works incl. smoke vents)",
        "360",
        480_000.00,
    ),
    (
        "06",
        "VE-06",
        "LV 06 - Stahlbeton-Fertigteile und BSH-Binder (Precast RC frame and glulam binders)",
        "330",
        470_000.00,
    ),
    (
        "07",
        "VE-07",
        "LV 07 - Fassade: Keramik-Vorhangfassade, Ziegelriemchen, Sockel (Design-board facade)",
        "330",
        560_000.00,
    ),
    (
        "08",
        "VE-08",
        "LV 08 - Fenster, Türen, Tore, Pfosten-Riegel-Fassade (Windows, doors, gates, curtain wall)",
        "330",
        270_000.00,
    ),
    (
        "09",
        "VE-09",
        "LV 09 - Innenausbau: Trockenbau, Fliesen, Maler, Innentüren, Decken (Interior fit-out)",
        "340",
        260_000.00,
    ),
    (
        "14",
        "VE-14",
        "LV 14 - HLS: Sanitär, Wärmepumpe, Fußbodenheizung, RLT (Mechanical services)",
        "420",
        560_000.00,
    ),
    (
        "15",
        "VE-15",
        "LV 15 - Kältetechnik CO2-Verbund und Kühlmöbel (CO2 refrigeration and cabinets)",
        "470",
        770_000.00,
    ),
    (
        "16",
        "VE-16",
        "LV 16 - Elektrotechnik inkl. BMA und GLT (Electrical incl. fire alarm and automation)",
        "440",
        635_000.00,
    ),
    (
        "17",
        "VE-17",
        "LV 17 - PV 229 kWp, Batteriespeicher 110 kWh, Ladeinfrastruktur (PV, battery, EV charging)",
        "440",
        430_000.00,
    ),
    (
        "18",
        "VE-18",
        "LV 18 - Außenanlagen, Stellplätze, Entwässerung (External works, parking, drainage)",
        "520",
        800_000.00,
    ),
    (
        "19",
        "VE-19",
        "LV 19 - Werbepylon, Einkaufswagen-Boxen, Anfahrschutz (Pylon, cart shelters, protection)",
        "530",
        115_000.00,
    ),
    (
        "20",
        "VE-20",
        "LV 20 - Ladeneinrichtung, Kassenzone, Backstation (Store fit-out, checkout, bake-off)",
        "610",
        510_000.00,
    ),
    (
        "21",
        "VE-21",
        "LV 21 - Pfandraumtechnik und sonstige Ausstattung (Reverse-vending room and equipment)",
        "690",
        120_000.00,
    ),
]

# Full LV. Net unit rates, price level Heidelberg 2026. Quantities derive from
# the canonical geometry of the smaller urban-infill box (work area 2,203 m2,
# 30 pocket foundations, perimeter 192 m, slab 432 m3). Within each procurement
# unit the rows are grouped into thematic OZ subsections; the trailing lsum row
# in each section closes it exactly on the procurement-unit budget.
_POSITIONS: dict[str, list[_PositionRow]] = {
    # LV 01 (KG 390 = 210,000.00). Higher than a greenfield store: the plot
    # fronts a live commercial street, so traffic management, lane-closure
    # permits and crane provision dominate the general items.
    "VE-01": [
        (
            "01.01.0010",
            "Baustelle einrichten und räumen, innerstädtische Logistik, An- und Abtransport (Site establishment and clearance, inner-city logistics)",
            "lsum",
            1,
            36500.00,
            "390",
        ),
        (
            "01.01.0020",
            "Bauzaun mobil h = 2,0 m, beengte Straßenrandsicherung, Vorhaltung (Mobile site fence 2.0 m, constrained street-edge protection)",
            "m",
            360,
            23.50,
            "390",
        ),
        (
            "01.01.0030",
            "Bauzufahrt und Baustraße Schotter, herstellen und rückbauen (Gravel site access road, build and remove)",
            "m2",
            520,
            21.40,
            "390",
        ),
        (
            "01.01.0040",
            "Büro- und Sozialcontainer gestapelt, Vorhaltung (Stacked office and welfare containers, provision)",
            "pcs",
            6,
            2950.00,
            "390",
        ),
        (
            "01.01.0050",
            "Baustromversorgung inkl. Verteiler und Verbrauch (Site power supply incl. distribution and consumption)",
            "lsum",
            1,
            16800.00,
            "390",
        ),
        (
            "01.01.0060",
            "Bauwasseranschluss inkl. Verbrauch (Site water connection incl. consumption)",
            "lsum",
            1,
            6900.00,
            "390",
        ),
        (
            "01.01.0070",
            "Mobil- und Turmkranvorhaltung beengte Baustelle, Fremdgewerke (Mobile and tower crane provision, constrained site, other trades)",
            "lsum",
            1,
            18500.00,
            "390",
        ),
        (
            "01.01.0080",
            "Bauschild und bauzeitliche Verkehrssicherung Straße (Site sign and temporary road traffic safety measures)",
            "lsum",
            1,
            5400.00,
            "390",
        ),
        (
            "01.01.0090",
            "Baustellenbewachung und Kamerasystem (Site security and camera system)",
            "lsum",
            1,
            8600.00,
            "390",
        ),
        (
            "01.01.0100",
            "Bautrocknung und Winterbaumassnahmen (Construction drying and winter working measures)",
            "lsum",
            1,
            9800.00,
            "390",
        ),
        (
            "01.01.0110",
            "Baustellen-IT, Funk und Zutrittskontrolle (Site IT, radio and access control)",
            "lsum",
            1,
            4200.00,
            "390",
        ),
        ("01.01.0120", "Endreinigung und Übergabe (Final cleaning and handover)", "m2", 2250, 2.90, "390"),
        (
            "01.01.0130",
            "Verkehrslenkung, Spurensperrung und Anliegerkoordination Innenstadt (Traffic routing, lane closures and resident coordination, inner city)",
            "lsum",
            1,
            24600.00,
            "390",
        ),
        # Closing row: general site overheads, insurances and daily reports.
        (
            "01.01.0140",
            "Allgemeine Baustellengemeinkosten, Versicherungen, Bautagesberichte (General site overheads, insurances, daily reports)",
            "lsum",
            1,
            34887.00,
            "390",
        ),
    ],
    # LV 02 (KG 310 = 320,000.00 across clearance, servicing, earthworks and
    # sub-base on the constrained plot).
    "VE-02": [
        (
            "02.01.0010",
            "Baufeldfreimachung, Roden Bewuchs, Abbruch Kleinstrukturen (Site clearance, grubbing, removal of minor structures)",
            "lsum",
            1,
            12400.00,
            "310",
        ),
        (
            "02.01.0020",
            "Oberbodenabtrag Baufeld d = 25 cm, in Mieten lagern (Topsoil strip building field 25 cm, stockpile on site)",
            "m3",
            540,
            9.20,
            "310",
        ),
        (
            "02.01.0030",
            "Schnurgerüst, Absteckung und Feinabsteckung Gebäude (Batter boards, setting-out and fine staking)",
            "lsum",
            1,
            4400.00,
            "310",
        ),
        (
            "02.01.0040",
            "Kampfmittelsondierung und Freigabedokumentation Baufeld (UXO probing and clearance documentation)",
            "lsum",
            1,
            9800.00,
            "310",
        ),
        (
            "02.02.0010",
            "Hausanschluss Wasser DN 50 inkl. Graben und Wiederherstellung (Water service connection DN 50 incl. trench)",
            "m",
            32,
            152.00,
            "310",
        ),
        (
            "02.02.0020",
            "Hausanschluss Abwasser DN 200 bis Übergabeschacht (Sewer service connection DN 200 to transfer chamber)",
            "m",
            40,
            220.00,
            "310",
        ),
        (
            "02.02.0030",
            "Leerrohrtrasse Strom und Telekom, Trafostation bis NSHV (Conduit route power and telecom, substation to main LV board)",
            "m",
            95,
            102.00,
            "310",
        ),
        (
            "02.02.0040",
            "Übergabeschächte DN 1000 inkl. Abdeckung Kl. D (Transfer chambers DN 1000 incl. class D covers)",
            "pcs",
            2,
            3600.00,
            "310",
        ),
        (
            "02.02.0050",
            "Löschwasser- und Hydrantenleitung DN 100 auf dem Grundstück (Fire-water and hydrant main DN 100 on the plot)",
            "m",
            70,
            248.00,
            "310",
        ),
        (
            "02.02.0060",
            "Prüfung, Spülung, Desinfektion und Dokumentation Anschlüsse (Testing, flushing, disinfection and records)",
            "lsum",
            1,
            6500.00,
            "310",
        ),
        (
            "02.03.0010",
            "Erdaushub Planum Bauwerk und Anlieferrampe, Kl. 3-5 (Bulk excavation to formation, building and dock ramp)",
            "m3",
            1650,
            11.80,
            "310",
        ),
        (
            "02.03.0020",
            "Liefern und Einbau geprüfte Auffüllung, lagenweise verdichtet (Supply and place certified fill, compacted in layers)",
            "m3",
            1280,
            27.20,
            "310",
        ),
        (
            "02.03.0030",
            "Abfuhr und Entsorgung Überschussmassen Z1.1 (Haul-off and disposal of surplus soil, class Z1.1)",
            "m3",
            3900,
            19.40,
            "310",
        ),
        (
            "02.03.0040",
            "Offene Wasserhaltung, Vorhaltung 12 Wochen (Open dewatering, 12 weeks provision)",
            "lsum",
            1,
            9600.00,
            "310",
        ),
        (
            "02.03.0050",
            "Böschungen und Nachbarwand sichern, Folienabdeckung (Slope and party-wall protection, sheeting cover)",
            "m2",
            760,
            6.80,
            "310",
        ),
        (
            "02.03.0060",
            "Kalk-Zement-Stabilisierung Planum d = 30 cm (Lime-cement stabilisation of formation, 30 cm)",
            "m2",
            2203,
            17.40,
            "310",
        ),
        (
            "02.03.0070",
            "Baustraßen-Unterhaltung während Erdbau (Maintenance of site roads during earthworks)",
            "lsum",
            1,
            3200.00,
            "310",
        ),
        (
            "02.04.0010",
            "Kapillarbrechende Kiesschicht 0/32, d = 15 cm (Capillary-breaking gravel layer 0/32, 15 cm)",
            "m2",
            2203,
            12.80,
            "310",
        ),
        # Closing row: geotextile separation fleece and plate-load tests.
        (
            "02.04.0020",
            "Geotextil-Trennvlies GRK 4, Plattendruckversuche und Verdichtungsnachweise (Geotextile fleece GRK 4, plate-load tests and compaction records)",
            "lsum",
            1,
            19573.40,
            "310",
        ),
    ],
    # LV 04 - subsections: 04.01/04.02 Gruendung und Bodenplatte (KG 320),
    # 04.01.0140 RC shear walls (KG 330), 04.01.0150 masonry rooms (KG 340),
    # 04.03 plant mezzanine (KG 350). The trailing daywork row sits in KG 320.
    "VE-04": [
        (
            "04.01.0010",
            "Aushub Baugrube und Fundamente, Boden Kl. 3-5, seitlich lagern (Excavation pits and foundations, on-site storage)",
            "m3",
            2700,
            13.20,
            "310",
        ),
        (
            "04.01.0020",
            "Bodenaustausch / Tragschicht 0/45 unter Bodenplatte, d = 40 cm, verdichtet (Soil replacement / sub-base 0/45 under slab, 40 cm)",
            "m2",
            2203,
            14.60,
            "320",
        ),
        ("04.01.0030", "Sauberkeitsschicht C12/15, d = 5 cm (Blinding layer C12/15, 5 cm)", "m2", 2203, 9.60, "320"),
        (
            "04.01.0040",
            "Köcherfundamente 1,60 x 1,60 x 0,95 m, C25/30, inkl. Schalung und Aussparung (Pocket foundations 1.6 x 1.6 x 0.95 m C25/30)",
            "pcs",
            30,
            1520.00,
            "320",
        ),
        (
            "04.01.0050",
            "Frostschürze umlaufend, h = 80 cm, C25/30 (Perimeter frost skirt 80 cm C25/30)",
            "m",
            192,
            98.00,
            "320",
        ),
        (
            "04.01.0060",
            "Betonstahl B500B Fundamente und Frostschürze, liefern und verlegen (Rebar B500B foundations and skirt)",
            "t",
            31,
            1410.00,
            "320",
        ),
        (
            "04.01.0070",
            "PE-Folie Trennlage 2-lagig unter Bodenplatte (PE separation layer, 2-ply)",
            "m2",
            2203,
            2.20,
            "320",
        ),
        (
            "04.01.0080",
            "XPS-Dämmung 120 mm unter Bodenplatte, Heizzone, druckfest (XPS insulation 120 mm under slab, heated zone)",
            "m2",
            1380,
            29.50,
            "320",
        ),
        (
            "04.01.0090",
            "Bodenplatte C25/30 (RC-Beton), d = 20 cm, inkl. Einbau und Abziehen (Ground slab C25/30 recycled aggregate, 20 cm)",
            "m3",
            432,
            182.00,
            "320",
        ),
        (
            "04.01.0100",
            "Betonstahl B500B Bodenplatte inkl. Randzonenbewehrung (Rebar B500B ground slab incl. edge zones)",
            "t",
            39,
            1380.00,
            "320",
        ),
        (
            "04.01.0110",
            "Industrieboden: Hartstoffeinstreuung, monolithisch geglättet, Fugenschnitt und Verguss (Industrial floor: dry-shake topping, power-floated, joints)",
            "m2",
            1900,
            25.50,
            "320",
        ),
        (
            "04.01.0120",
            "Grundleitungen DN 100 - DN 150 unter Bodenplatte inkl. Dichtheitsprüfung DIN EN 1610 (Below-slab drainage DN100-150 incl. tightness test)",
            "m",
            320,
            90.00,
            "320",
        ),
        (
            "04.01.0130",
            "Bodeneinläufe, Pumpensumpf, Revisionsschächte komplett (Floor drains, sump, inspection chambers)",
            "lsum",
            1,
            16800.00,
            "320",
        ),
        (
            "04.01.0140",
            "Stahlbeton-Wandscheiben Aussteifung, C30/37, inkl. Schalung (RC shear walls C30/37 incl. formwork)",
            "m3",
            30,
            595.00,
            "330",
        ),
        (
            "04.01.0150",
            "Massivbau Sozialtrakt und Technikräume, komplett (Masonry/RC staff and plant rooms, complete)",
            "lsum",
            1,
            68900.00,
            "340",
        ),
        (
            "04.02.0010",
            "WU-Beton Rampenwände Anlieferung C25/30 inkl. Schalung (Watertight RC dock ramp walls C25/30 incl. formwork)",
            "m3",
            40,
            660.00,
            "320",
        ),
        (
            "04.02.0020",
            "Betonstahl B500B Rampenwände und Aufkantungen (Rebar B500B ramp walls and upstands)",
            "t",
            5,
            1450.00,
            "320",
        ),
        (
            "04.02.0030",
            "Grube Überladebrücke inkl. Randwinkel und Entwässerung (Dock leveller pit incl. edge angles and drainage)",
            "pcs",
            1,
            8600.00,
            "320",
        ),
        (
            "04.02.0040",
            "Randschalung Bodenplatte inkl. Höhenjustierung (Slab edge formwork incl. level adjustment)",
            "m",
            192,
            25.50,
            "320",
        ),
        (
            "04.02.0050",
            "Dehnfugenprofile Schwerlast einbauen (Heavy-duty expansion joint profiles, installed)",
            "m",
            100,
            88.00,
            "320",
        ),
        (
            "04.02.0060",
            "Fugenprofile Edelstahl Sichtbereiche (Stainless joint profiles in visible areas)",
            "m",
            50,
            66.00,
            "320",
        ),
        (
            "04.02.0070",
            "Sockel- und Perimeterabdichtung Bitumendickbeschichtung (Plinth and perimeter waterproofing, thick bitumen coating)",
            "m",
            192,
            33.50,
            "320",
        ),
        (
            "04.02.0080",
            "Aussparungen, Einbauteile, Leerrohre und Hülsen Bodenplatte (Recesses, cast-in items, conduits and sleeves in slab)",
            "lsum",
            1,
            9800.00,
            "320",
        ),
        (
            "04.02.0090",
            "Industrieboden Oberflächenhärtung und Versiegelung, Zulage (Industrial floor surface hardening and sealing, extra-over)",
            "m2",
            1900,
            3.40,
            "320",
        ),
        ("04.02.0100", "Betonnachbehandlung Bodenplatte (Concrete curing of ground slab)", "m2", 2160, 1.30, "320"),
        (
            "04.02.0110",
            "Gefälle- und Ausgleichsestrich Technik- und Nassbereiche (Sloped and levelling screed, plant and wet areas)",
            "m2",
            120,
            39.50,
            "320",
        ),
        (
            "04.03.0010",
            "Technik-Mezzanin 100 m2: Spannbeton-Hohldielen d = 20 cm inkl. Aufbeton (Plant mezzanine 100 m2: hollow-core slabs 20 cm incl. topping)",
            "m2",
            100,
            245.00,
            "350",
        ),
        # Closing row: shell daywork, core drilling and adaptations (KG 320).
        (
            "04.02.0120",
            "Stundenlohnarbeiten Rohbau, Kernbohrungen und Anpassarbeiten (Daywork shell, core drilling and adaptations)",
            "lsum",
            1,
            20134.80,
            "320",
        ),
    ],
    # LV 05 (KG 360). The trailing lightning-protection lsum closes the
    # section.
    "VE-05": [
        (
            "05.01.0010",
            "Stahltrapezprofil 160/250, t = 1,0 mm, als Dachtragschale inkl. Befestigung (Trapezoidal steel deck 160/250, 1.0 mm)",
            "m2",
            2203,
            32.50,
            "360",
        ),
        ("05.01.0020", "Dampfsperre bituminös, vollflächig (Bituminous vapour barrier)", "m2", 2203, 7.00, "360"),
        (
            "05.01.0030",
            "PIR-Gefälledämmung 200-260 mm, WLG 023 (PIR tapered insulation 200-260 mm)",
            "m2",
            2203,
            53.00,
            "360",
        ),
        (
            "05.01.0040",
            "FPO-Dachbahn, mechanisch befestigt, inkl. An- und Abschlüsse (FPO membrane, mechanically fixed)",
            "m2",
            2203,
            29.40,
            "360",
        ),
        (
            "05.01.0050",
            "Attika-Abdeckung Aluminium inkl. Unterkonstruktion (Aluminium parapet capping)",
            "m",
            192,
            70.00,
            "360",
        ),
        (
            "05.01.0060",
            "Lichtkuppeln 1,5 x 1,5 m als NRWG nach DIN 18232, elektrisch 24 V, inkl. Aufsetzkranz (Rooflights 1.5 x 1.5 m as smoke vents per DIN 18232)",
            "pcs",
            7,
            5100.00,
            "360",
        ),
        (
            "05.01.0070",
            "Dachgullys DN 100 beheizt und Notüberläufe (Heated roof drains DN100 and emergency overflows)",
            "pcs",
            18,
            760.00,
            "360",
        ),
        (
            "05.01.0080",
            "Durchdringungen und Einfassungen für RLT, Kälte, PV (Penetrations and flashings for HVAC, refrigeration, PV)",
            "lsum",
            1,
            11800.00,
            "360",
        ),
        (
            "05.01.0090",
            "Absturzsicherung Sekuranten umlaufend (Fall-arrest anchors along perimeter)",
            "pcs",
            24,
            300.00,
            "360",
        ),
        (
            "05.02.0010",
            "Vordach Eingang Stahlkonstruktion auskragend 20 x 3 m inkl. Abdichtung und Entwässerung (Entrance canopy, cantilevered steel 20 x 3 m incl. waterproofing and drainage)",
            "m2",
            60,
            590.00,
            "360",
        ),
        (
            "05.02.0020",
            "Attika-Aufkantung Dämmung und Holzwerkstoff inkl. Befestigung (Parapet upstand insulation and timber-based board incl. fixing)",
            "m",
            192,
            86.00,
            "360",
        ),
        (
            "05.02.0030",
            "Dachrand- und Anschlussbleche Titanzink (Roof edge and flashing sheets, titanium-zinc)",
            "m",
            192,
            39.50,
            "360",
        ),
        (
            "05.02.0040",
            "Windsogsicherung Verstärkung Rand- und Eckzonen, Zulage (Wind uplift reinforcement edge and corner zones, extra-over)",
            "m2",
            560,
            7.20,
            "360",
        ),
        (
            "05.02.0050",
            "Gefällekeile Kehlen und Grate, Zulage (Tapered crickets at valleys and ridges, extra-over)",
            "m",
            84,
            29.50,
            "360",
        ),
        (
            "05.02.0060",
            "Schaumglas-Dämmung druckfest Bereich Durchdringungen, Zulage (Compression-proof foam glass insulation at penetrations, extra-over)",
            "lsum",
            1,
            2600.00,
            "360",
        ),
        (
            "05.02.0070",
            "Wartungswege Plattenbelag begehbar (Walkable maintenance paths, paving slabs)",
            "m2",
            120,
            46.00,
            "360",
        ),
        (
            "05.02.0080",
            "RWA-Steuerzentrale 24 V, Wind- und Regensensorik, Verkabelung 7 NRWG (Smoke vent control 24 V, wind and rain sensors, wiring for 7 NRWG)",
            "lsum",
            1,
            13400.00,
            "360",
        ),
        (
            "05.02.0090",
            "Anschluss Aufsetzkränze Abdichtung, Zulage (Waterproofing connection to upstand kerbs, extra-over)",
            "pcs",
            7,
            390.00,
            "360",
        ),
        (
            "05.02.0100",
            "Durchsturzsicherung Lichtkuppeln, Gitter (Fall-through protection grids for rooflights)",
            "pcs",
            7,
            300.00,
            "360",
        ),
        # Closing row: lightning and earthing, plus temporary seals and records.
        (
            "05.01.0100",
            "Blitzschutz- und Erdungsanlage komplett, Notabdichtungen Bauphase und Dichtheitsprüfung (Lightning protection and earthing complete, temporary seals and leak test)",
            "lsum",
            1,
            37278.30,
            "360",
        ),
    ],
    # LV 06 - subsections: 06.01 Sockel und Gruendungsergaenzung (KG 320),
    # 06.02 Stuetzen und Attika-FT (KG 330), 06.03 Dachtragwerk (KG 360).
    "VE-06": [
        (
            "06.01.0010",
            "Stahlbeton-Sockelelemente FT h = 80 cm, tragend für Fassade, liefern und montieren (Precast RC socket panels 80 cm, load-bearing for facade, supply and erect)",
            "m",
            192,
            780.00,
            "320",
        ),
        (
            "06.01.0020",
            "Vergussmörtel Stützenfüße Köcher C60/75 (Grouting of column feet in pockets, C60/75)",
            "pcs",
            30,
            250.00,
            "320",
        ),
        (
            "06.01.0030",
            "Perimeterdämmung XPS d = 100 mm Sockelelemente (Perimeter insulation XPS 100 mm at socket panels)",
            "m",
            192,
            66.00,
            "320",
        ),
        (
            "06.01.0040",
            "Fugenabdichtung FT-Stöße dauerelastisch (Flexible joint sealing of precast element joints)",
            "m",
            380,
            13.00,
            "320",
        ),
        (
            "06.02.0010",
            "FT-Stützen C40/50, 40/40 cm, h = 6,2 m, in Köcher versetzt (Precast columns C40/50, 40/40 cm, h = 6.2 m, set in pockets)",
            "pcs",
            30,
            2750.00,
            "330",
        ),
        (
            "06.02.0020",
            "FT-Attikaelemente Portal Eingangsseite, h = 60 cm (Precast parapet elements at entrance portal, 60 cm)",
            "m",
            20,
            430.00,
            "330",
        ),
        (
            "06.02.0030",
            "Bemusterung Sichtoberflächen FT, Musterfläche (Sampling of fair-faced precast surfaces, mock-up panel)",
            "lsum",
            1,
            1900.00,
            "330",
        ),
        (
            "06.02.0040",
            "Fugenverguss, Anschlussbewehrung und Montagematerial FT-Stützen (Joint grouting, starter bars and erection material for columns)",
            "lsum",
            1,
            10800.00,
            "330",
        ),
        (
            "06.03.0010",
            "BSH-Binder GL24h, b/h = 20/110 cm, l = 21,8 m, liefern und montieren (Glulam binders GL24h 20/110 cm, l = 21.8 m, supply and erect)",
            "pcs",
            10,
            6900.00,
            "360",
        ),
        (
            "06.03.0020",
            "BSH-Binder GL24h, l = 15,0 m, liefern und montieren (Glulam binders GL24h, l = 15.0 m, supply and erect)",
            "pcs",
            10,
            5200.00,
            "360",
        ),
        ("06.03.0030", "BSH-Randträger und Wechsel (Glulam edge beams and trimmers)", "pcs", 18, 1180.00, "360"),
        (
            "06.03.0040",
            "Dachverband Zugstäbe Stahl inkl. Anschlussbleche (Steel rod roof bracing incl. connection plates)",
            "lsum",
            1,
            7900.00,
            "360",
        ),
        (
            "06.03.0050",
            "Schwertransporte und Telekran-Einsatz Binder 21,8 m, Sondergenehmigungen (Heavy haulage and crane operations for 21.8 m binders incl. permits)",
            "lsum",
            1,
            11500.00,
            "360",
        ),
        (
            "06.03.0060",
            "Elastomer-Auflagerlager und Verbindungsmittel, komplett (Elastomeric bearings and fasteners, complete)",
            "lsum",
            1,
            4800.00,
            "360",
        ),
        # Closing row: starter bars, cast-in items and insulation strips (KG 320).
        (
            "06.01.0050",
            "Anschlussbewehrung, Einbauteile und Dämmstreifen Sockelelemente (Starter bars, cast-in items and insulation strips, socket panels)",
            "lsum",
            1,
            24888.00,
            "320",
        ),
    ],
    # LV 07 (KG 330). Design-board envelope: ceramic rainscreen plus a
    # brick-slip accent band per the Gestaltungssatzung.
    "VE-07": [
        (
            "07.01.0010",
            "Keramik-Vorhangfassade hinterlüftet auf Alu-UK, gesatzungskonform (Ventilated ceramic rainscreen on aluminium subframe, design-board compliant)",
            "m2",
            980,
            312.00,
            "330",
        ),
        (
            "07.01.0020",
            "Sandwichpaneele MW-Kern 200 mm, U = 0,20, Anlieferseite, inkl. Befestigung (Sandwich panels mineral-wool core 200 mm, U = 0.20, delivery side, incl. fixing)",
            "m2",
            320,
            375.00,
            "330",
        ),
        (
            "07.01.0030",
            "Zulage Sonderformate und Farbton nach Bemusterung Gestaltungsbeirat (Extra-over for special formats and sampled colour, design board)",
            "m2",
            980,
            18.50,
            "330",
        ),
        (
            "07.01.0040",
            "Sockelblech- und Anschlussprofile, Eckausbildungen (Plinth flashings, connection profiles and corner details)",
            "m",
            192,
            58.00,
            "330",
        ),
        (
            "07.01.0050",
            "Öffnungen herstellen, Wechselrahmen für Tore, Türen und Fensterband (Forming openings, trimmer frames for gates, doors and window band)",
            "pcs",
            9,
            1250.00,
            "330",
        ),
        (
            "07.01.0060",
            "Fensterbankbleche und Leibungsverkleidungen (Sill flashings and reveal claddings)",
            "m",
            78,
            88.00,
            "330",
        ),
        (
            "07.01.0070",
            "Brandriegel und REI90-Anschlüsse an Brandwände (Fire barriers and REI90 connections to fire walls)",
            "lsum",
            1,
            12400.00,
            "330",
        ),
        ("07.01.0080", "Gerüstvorhaltung Fassade (Facade scaffolding provision)", "m2", 1260, 14.80, "330"),
        (
            "07.01.0090",
            "Mock-up- und Bemusterungsfläche Fassade 3 x 3 m für Gestaltungsbeirat (Facade mock-up and sampling area 3 x 3 m for the design board)",
            "lsum",
            1,
            9800.00,
            "330",
        ),
        (
            "07.01.0100",
            "Schutzfolien entfernen, Endreinigung Fassade (Removal of protective films, final facade cleaning)",
            "m2",
            980,
            3.20,
            "330",
        ),
        (
            "07.01.0120",
            "Ziegelriemchen-Akzentband im Eingangsbereich nach Gestaltungssatzung (Brick-slip accent band at the entrance per the design statute)",
            "lsum",
            1,
            25900.00,
            "330",
        ),
        # Closing row: erection allowances, sealing tapes, minor steel and fixings.
        (
            "07.01.0110",
            "Montagezugaben, Dichtbänder, Kleinstahl und Befestigungsmittel (Erection allowances, sealing tapes, minor steel and fixings)",
            "lsum",
            1,
            16976.00,
            "330",
        ),
    ],
    # LV 08 - subsections: 08.01 Fenster, Tueren, Tore (KG 330), 08.02
    # Verladetechnik und Einbauten (KG 370).
    "VE-08": [
        (
            "08.01.0010",
            "Pfosten-Riegel-Fassade Alu 22,0 x 5,0 m, Uw = 0,9, inkl. Verglasung (Aluminium curtain wall 22.0 x 5.0 m, Uw = 0.9, incl. glazing)",
            "m2",
            110,
            790.00,
            "330",
        ),
        (
            "08.01.0020",
            "Automatik-Schiebetüranlagen 2-flügelig im Windfang (Automatic bi-parting sliding doors in the entrance lobby)",
            "pcs",
            2,
            13400.00,
            "330",
        ),
        (
            "08.01.0030",
            "Fensterband Alu 26,0 x 1,5 m, festverglast (Aluminium window band 26.0 x 1.5 m, fixed glazing)",
            "m2",
            39,
            620.00,
            "330",
        ),
        (
            "08.01.0040",
            "Sektionaltor 3,5 x 4,0 m ebenerdig, elektrisch (Sectional gate 3.5 x 4.0 m at grade, electric)",
            "pcs",
            1,
            11200.00,
            "330",
        ),
        (
            "08.01.0050",
            "Dock-Tor 3,0 x 3,2 m an der Andockstelle (Dock gate 3.0 x 3.2 m at the loading dock)",
            "pcs",
            1,
            9400.00,
            "330",
        ),
        (
            "08.01.0060",
            "Stahltüren T30/RC2 einflügelig inkl. Beschläge (Steel doors T30/RC2 single-leaf incl. hardware)",
            "pcs",
            6,
            3450.00,
            "330",
        ),
        (
            "08.01.0070",
            "Fluchttürsteuerung, Panikschlösser und E-Öffner (Escape door control, panic locks and electric strikes)",
            "lsum",
            1,
            6200.00,
            "330",
        ),
        (
            "08.01.0080",
            "Beschläge-Komplettierung, mechanische Schließanlage (Hardware completion, mechanical master-key system)",
            "lsum",
            1,
            4400.00,
            "330",
        ),
        (
            "08.01.0090",
            "Glasreinigung und Einstellarbeiten zur Schlussabnahme (Glass cleaning and adjustment for final acceptance)",
            "lsum",
            1,
            2050.00,
            "330",
        ),
        (
            "08.02.0010",
            "Überladebrücke hydraulisch 2,00 x 2,75 m, Tragkraft 60 kN (Hydraulic dock leveller 2.00 x 2.75 m, 60 kN capacity)",
            "pcs",
            1,
            18800.00,
            "370",
        ),
        (
            "08.02.0020",
            "Torabdichtung aufblasbar inkl. Anfahrpuffer und Radführungen (Inflatable dock shelter incl. bumpers and wheel guides)",
            "pcs",
            1,
            8400.00,
            "370",
        ),
        (
            "08.02.0030",
            "Rammschutz innen Anlieferung und Lager, Stahlbügel verzinkt (Interior impact protection delivery and warehouse, galvanised steel hoops)",
            "pcs",
            24,
            300.00,
            "370",
        ),
        (
            "08.02.0040",
            "Stahltreppe Technik-Mezzanin inkl. Geländer (Steel stair to plant mezzanine incl. railing)",
            "pcs",
            1,
            14200.00,
            "370",
        ),
        (
            "08.02.0050",
            "Wartungsstege und Leiteranlagen Technikflächen (Maintenance walkways and ladder systems, plant areas)",
            "lsum",
            1,
            19600.00,
            "370",
        ),
        # Closing row: connection works, sealing and adjustment of facade elements.
        (
            "08.01.0100",
            "Anschlussarbeiten, Abdichtung und Einstellung Fassadenelemente (Connection works, sealing and adjustment of facade elements)",
            "lsum",
            1,
            9970.00,
            "330",
        ),
    ],
    # LV 09 - subsections: 09.01 Waende und Tueren (KG 340), 09.02 Boeden und
    # Decken (KG 350). The closing skirtings lsum sits in KG 350.
    "VE-09": [
        (
            "09.01.0010",
            "Trockenbauwände Sozialtrakt und Büros, doppelt beplankt, MW-Dämmung (Drywall partitions staff wing and offices, double-boarded, mineral wool)",
            "m2",
            560,
            98.00,
            "340",
        ),
        (
            "09.01.0020",
            "Brandwand REI90 Trennung Technikraum und Lager (Fire wall REI90 separating plant room and warehouse)",
            "m2",
            240,
            150.00,
            "340",
        ),
        (
            "09.01.0030",
            "Innentüren Holz mit Stahl-Umfassungszarge, teils Feuchtraum (Interior timber doors with steel frames, partly wet-room rated)",
            "pcs",
            16,
            1000.00,
            "340",
        ),
        (
            "09.01.0040",
            "T30-RS-Türen Technik- und LV-Raum (T30 smoke-control doors, plant and main LV room)",
            "pcs",
            4,
            2400.00,
            "340",
        ),
        (
            "09.01.0050",
            "Wandfliesen WC, Umkleiden und Backstation h = 2,0 m (Wall tiling WCs, changing rooms and bake-off, h = 2.0 m)",
            "m2",
            220,
            78.00,
            "340",
        ),
        (
            "09.01.0060",
            "Innenwandbekleidung Windfang und Kassenzone, HPL-Paneele (Interior wall cladding lobby and checkout zone, HPL panels)",
            "m2",
            85,
            165.00,
            "340",
        ),
        (
            "09.01.0070",
            "Vorsatzschalen und Installationswände Nassbereiche (Furring and installation walls in wet areas)",
            "m2",
            105,
            80.00,
            "340",
        ),
        (
            "09.01.0080",
            "Eckschutzschienen und Rammschutz-Sockelleisten Flure (Corner guards and impact-protection skirtings, corridors)",
            "m",
            80,
            37.00,
            "340",
        ),
        (
            "09.01.0090",
            "Malerarbeiten Wände Innenbereich, Dispersion (Painting of interior walls, emulsion)",
            "m2",
            1650,
            10.20,
            "340",
        ),
        (
            "09.02.0010",
            "Zementestrich schwimmend Sozialtrakt (Floating cement screed, staff wing)",
            "m2",
            260,
            39.50,
            "350",
        ),
        (
            "09.02.0020",
            "Bodenfliesen R10 Sozialräume und WC inkl. Abdichtung (Floor tiling R10 staff rooms and WCs incl. waterproofing)",
            "m2",
            88,
            98.00,
            "350",
        ),
        (
            "09.02.0030",
            "Sauberlaufzone Eingang inkl. Edelstahlrahmen (Entrance matting zone incl. stainless frame)",
            "m2",
            22,
            330.00,
            "350",
        ),
        (
            "09.02.0040",
            "Abgehängte Rasterdecke Sozialtrakt und Büros (Suspended grid ceiling, staff wing and offices)",
            "m2",
            200,
            66.00,
            "350",
        ),
        (
            "09.02.0050",
            "Akustikdecke Kassenzone und Windfang (Acoustic ceiling, checkout zone and lobby)",
            "m2",
            165,
            92.00,
            "350",
        ),
        ("09.02.0060", "Revisionsöffnungen Decke (Ceiling access openings)", "pcs", 11, 190.00, "350"),
        # Closing row: skirtings, transition profiles and finishing works.
        (
            "09.02.0070",
            "Sockelleisten, Übergangsprofile und Restarbeiten Bodenbeläge (Skirtings, transition profiles and finishing works, floor coverings)",
            "lsum",
            1,
            27521.00,
            "350",
        ),
    ],
    # LV 14 - subsections by KG: 14.01 plant (KG 410/420/430), 14.02 Sanitaer
    # (KG 410), 14.03 Heizung (KG 420), 14.04 Lueftung (KG 430). The closing
    # fire-stopping lsum sits in KG 410.
    "VE-14": [
        (
            "14.01.0010",
            "Luft/Wasser-Wärmepumpe R290, 52 kW heizen / 64 kW kühlen, inkl. hydraulischer Einbindung (Air/water heat pump R290 52/64 kW incl. hydraulics)",
            "pcs",
            1,
            58500.00,
            "420",
        ),
        (
            "14.01.0020",
            "Fußbodenheizung Vorlauf 35/28 Grad C inkl. Verteiler, gespeist aus Kälte-Abwärme (Underfloor heating 35/28 C incl. manifolds)",
            "m2",
            1450,
            31.50,
            "420",
        ),
        (
            "14.01.0030",
            "RLT-Gerät 9.500 m3/h, Rotations-WRG eta = 78 %, adiabate Kühlung, auf Technik-Mezzanin (AHU 9,500 m3/h rotary heat recovery, adiabatic cooling)",
            "pcs",
            1,
            64800.00,
            "430",
        ),
        (
            "14.01.0040",
            "Lüftungskanäle verzinkt inkl. Dämmung und Brandschotts (Galvanised ductwork incl. insulation and firestopping)",
            "m2",
            860,
            42.00,
            "430",
        ),
        (
            "14.01.0050",
            "Türluftschleier Eingang 9 kW, WRG-gespeist (Entrance air curtain 9 kW, heat-recovery fed)",
            "pcs",
            1,
            7100.00,
            "430",
        ),
        (
            "14.01.0060",
            "Sanitärinstallation komplett: WC-Anlagen, Sozialräume, TWW-Speicher 300 l (Plumbing complete: WCs, staff rooms, 300 l DHW tank)",
            "lsum",
            1,
            44800.00,
            "410",
        ),
        (
            "14.01.0070",
            "Regelung und GLT-Schnittstellen HLS, Einregulierung, Abnahme (Controls and BMS interfaces HVAC, balancing, acceptance)",
            "lsum",
            1,
            21600.00,
            "430",
        ),
        (
            "14.02.0010",
            "Schmutz- und Regenwasserleitungen im Gebäude, SML/PE, inkl. Dämmung (Foul and rainwater pipework inside the building, cast iron/PE, insulated)",
            "m",
            320,
            65.00,
            "410",
        ),
        (
            "14.02.0020",
            "Trinkwasser-Installation Edelstahl press inkl. Dämmung und Spülung (Potable water installation, pressed stainless, insulated and flushed)",
            "m",
            380,
            59.00,
            "410",
        ),
        (
            "14.02.0030",
            "Regenwasser-Fallleitungen innenliegend DN 100 inkl. Anschluss (Internal rainwater downpipes DN 100 incl. connection)",
            "pcs",
            9,
            1480.00,
            "410",
        ),
        (
            "14.02.0040",
            "Fettabscheider NS 4 Backstation inkl. Einbau (Grease separator NS 4 for bake-off incl. installation)",
            "pcs",
            1,
            8800.00,
            "410",
        ),
        (
            "14.02.0050",
            "Wandhydranten Typ S inkl. Leitungsnetz (Wall hydrants type S incl. pipe network)",
            "pcs",
            4,
            4000.00,
            "410",
        ),
        (
            "14.02.0060",
            "Wasserzähleranlage, Feinfilter und Druckminderer (Water metering assembly, fine filter and pressure reducer)",
            "lsum",
            1,
            6400.00,
            "410",
        ),
        (
            "14.03.0010",
            "Pufferspeicher 2.000 l WRG-Einbindung inkl. Armaturen (Buffer tank 2,000 l for heat-recovery integration incl. valves)",
            "pcs",
            1,
            12800.00,
            "420",
        ),
        (
            "14.03.0020",
            "Rohrnetz Heizung Verteilung Decke, Stahl/Verbundrohr (Heating distribution pipework at ceiling, steel/composite)",
            "m",
            340,
            73.00,
            "420",
        ),
        (
            "14.03.0030",
            "Dämmung Heizleitungen inkl. Armaturen (Insulation of heating pipework incl. valves)",
            "m",
            340,
            22.00,
            "420",
        ),
        (
            "14.03.0040",
            "Einbindung WRG Kälteanlage, Wärmetauscher und Regelventile (Integration of refrigeration heat recovery, exchangers and control valves)",
            "lsum",
            1,
            16400.00,
            "420",
        ),
        (
            "14.03.0060",
            "Aufstellung WP: Fundament, Schwingungsdämpfer, Schallschutzhaube (Heat pump installation: base, vibration dampers, acoustic hood)",
            "lsum",
            1,
            9800.00,
            "420",
        ),
        (
            "14.03.0070",
            "Heizkörper und Konvektoren Nebenräume (Radiators and convectors, ancillary rooms)",
            "pcs",
            12,
            660.00,
            "420",
        ),
        (
            "14.03.0080",
            "Einzelraumregelung FBH, Raumthermostate (Room-by-room underfloor heating control, thermostats)",
            "pcs",
            20,
            390.00,
            "420",
        ),
        (
            "14.03.0090",
            "Druckhaltung, MAG und Sicherheitsarmaturen (Pressurisation, expansion vessel and safety valves)",
            "lsum",
            1,
            6900.00,
            "420",
        ),
        (
            "14.04.0010",
            "Brandschutz- und Jalousieklappen inkl. Ansteuerung (Fire and louvre dampers incl. actuation)",
            "pcs",
            16,
            660.00,
            "430",
        ),
        (
            "14.04.0020",
            "Wickelfalzrohr-Netz Nebenräume inkl. Formteile (Spiral duct network ancillary rooms incl. fittings)",
            "m",
            220,
            53.00,
            "430",
        ),
        (
            "14.04.0030",
            "Luftdurchlässe und Weitwurfdüsen Verkaufsraum (Air diffusers and long-throw nozzles, sales area)",
            "pcs",
            38,
            290.00,
            "430",
        ),
        (
            "14.04.0040",
            "Abluftanlagen WC, Sozialräume und Backstation (Extract systems WCs, staff rooms and bake-off)",
            "lsum",
            1,
            13400.00,
            "430",
        ),
        (
            "14.04.0050",
            "Außenluft- und Fortluftgitter, Schalldämpfer (Outdoor and exhaust air louvres, attenuators)",
            "lsum",
            1,
            9400.00,
            "430",
        ),
        (
            "14.04.0060",
            "Splitgerät Kühlung LV- und Serverraum (Split cooling unit, main LV and server room)",
            "pcs",
            1,
            6800.00,
            "430",
        ),
        # Closing row: fire stopping, remaining insulation and instruction (KG 410).
        (
            "14.02.0070",
            "Brandschotts, Restdämmung, hydraulischer Abgleich und Einweisung HLS (Fire stopping, remaining insulation, hydraulic balancing and instruction)",
            "lsum",
            1,
            36905.00,
            "410",
        ),
    ],
    # LV 15 (KG 470). The closing CO2-charge lsum sits in KG 470.
    "VE-15": [
        (
            "15.01.0010",
            "Transkritische CO2-Booster-Verbundanlage mit Parallelverdichtung, NK 82 kW / TK 22 kW (Transcritical CO2 booster rack with parallel compression, MT 82 / LT 22 kW)",
            "lsum",
            1,
            138000.00,
            "470",
        ),
        (
            "15.01.0020",
            "Gaskühler Dachaufstellung inkl. Stahlrahmen und Schwingungsdämpfung (Gas cooler roof-mounted incl. steel frame)",
            "pcs",
            1,
            17600.00,
            "470",
        ),
        (
            "15.01.0030",
            "Wärmerückgewinnung 2-stufig (Enthitzer + Kondensator) bis 105 kW thermisch (Two-stage heat recovery, desuperheater plus condenser, up to 105 kW)",
            "lsum",
            1,
            24500.00,
            "470",
        ),
        (
            "15.01.0040",
            "CO2-Rohrleitungsnetz K65/Edelstahl inkl. Dämmung und Halterung (CO2 piping network K65/stainless incl. insulation)",
            "m",
            380,
            96.00,
            "470",
        ),
        (
            "15.01.0050",
            "NK-Kühlzelle +2 Grad C, ca. 40 m2, PU 100 mm, inkl. Tür (Chiller cell +2 C, ~40 m2, PU 100 mm incl. door)",
            "pcs",
            1,
            12400.00,
            "470",
        ),
        (
            "15.01.0060",
            "Obst/Gemüse-Kühlraum +8 Grad C, ca. 22 m2, PU 80 mm (Produce cool room +8 C, ~22 m2, PU 80 mm)",
            "pcs",
            1,
            7600.00,
            "470",
        ),
        (
            "15.01.0070",
            "TK-Zelle -22 Grad C, ca. 28 m2, PU 150 mm, inkl. Boden (Freezer room ~28 m2, PU 150 mm incl. floor)",
            "pcs",
            1,
            23500.00,
            "470",
        ),
        (
            "15.01.0080",
            "Luftkühler/Verdampfer CO2-geeignet, Zellen (CO2 unit coolers for cold rooms)",
            "pcs",
            5,
            2950.00,
            "470",
        ),
        (
            "15.01.0090",
            "Anbindung Verbund-Kühlmöbel (bauseits gestellt), Verrohrung und IBN (Connection of operator-supplied remote cabinets)",
            "pcs",
            12,
            1180.00,
            "470",
        ),
        (
            "15.01.0100",
            "CO2-Gaswarnanlage Maschinenraum/Verkaufsraum (CO2 gas detection system)",
            "lsum",
            1,
            7400.00,
            "470",
        ),
        (
            "15.01.0110",
            "MSR/Anlagenregelung Kälte, inkl. Fernüberwachung (Refrigeration controls incl. remote monitoring)",
            "lsum",
            1,
            13800.00,
            "470",
        ),
        (
            "15.01.0120",
            "Dichtheitsprüfung, Inbetriebnahme, Abnahme EN 378, Einweisung (Pressure test, commissioning, EN 378 acceptance)",
            "lsum",
            1,
            8900.00,
            "470",
        ),
        (
            "15.02.0010",
            "NK-Kühlregale steckerlos, Glastüren, H = 2,0 m, anschlussfertig an Verbund (Remote chilled multidecks, glass doors, H = 2.0 m, rack-ready)",
            "m",
            42,
            4980.00,
            "470",
        ),
        (
            "15.02.0020",
            "TK-Schrankmöbel Glastüren, Verbundanschluss (Remote glass-door freezer cabinets, rack-connected)",
            "m",
            18,
            6400.00,
            "470",
        ),
        (
            "15.02.0030",
            "Bedientheke Frische 6 lfm inkl. Anbindung Maschinensatz (Serve-over fresh counter 6 lm incl. rack connection)",
            "m",
            6,
            7950.00,
            "470",
        ),
        (
            "15.02.0040",
            "Kühlstellenregler, Fühler und Busverkabelung (Case controllers, sensors and bus wiring)",
            "pcs",
            24,
            485.00,
            "470",
        ),
        (
            "15.02.0050",
            "Abtau- und Tauwasserleitungen isoliert bis Grundleitung (Insulated defrost and condensate pipework to below-slab drainage)",
            "m",
            160,
            86.00,
            "470",
        ),
        (
            "15.02.0060",
            "Schallschutzmassnahmen und Aufstellrahmen Verbundanlage (Acoustic measures and mounting frame for the rack)",
            "lsum",
            1,
            8900.00,
            "470",
        ),
        (
            "15.02.0070",
            "Wartungsvertrag Jahr 1 inkl. 24h-Bereitschaft (Maintenance contract year 1 incl. 24h standby)",
            "lsum",
            1,
            6800.00,
            "470",
        ),
        # Closing row: initial CO2 charge, leak verification and 72 h trial run.
        (
            "15.02.0080",
            "CO2-Erstbefüllung, Dichtheitsnachweis und Probebetrieb 72 h (Initial CO2 charge, leak verification and 72 h trial run)",
            "lsum",
            1,
            37750.00,
            "470",
        ),
    ],
    # LV 16 - subsections: 16.01/16.02 Starkstrom (KG 440), 16.03 Sicherheit
    # und Kommunikation (KG 450), 16.04 Gebaeudeautomation (KG 480). The
    # closing measurements lsum sits in KG 440.
    "VE-16": [
        (
            "16.01.0010",
            "NSHV 1.000 A inkl. Messung und Zählerplatz (Main LV board 1,000 A incl. metering)",
            "pcs",
            1,
            36400.00,
            "440",
        ),
        (
            "16.01.0020",
            "Kabeltrassen und Leitungsnetz komplett (Cable trays and wiring complete)",
            "m",
            1620,
            24.50,
            "440",
        ),
        (
            "16.01.0030",
            "LED-Lichtbandsystem Verkaufsraum 800 lx, DALI mit Tageslicht-/Präsenzregelung (LED light-band system sales area 800 lx, DALI daylight/presence control)",
            "m",
            470,
            142.00,
            "440",
        ),
        (
            "16.01.0040",
            "Beleuchtung Lager/Nebenräume 300 lx und Sicherheitsbeleuchtung (Warehouse/ancillary lighting 300 lx and emergency lighting)",
            "lsum",
            1,
            26800.00,
            "440",
        ),
        (
            "16.01.0050",
            "Elektroinstallation Sozialtrakt, Unterverteilungen, Endgeräte (Electrical installation staff wing, sub-distribution boards)",
            "lsum",
            1,
            24040.00,
            "440",
        ),
        (
            "16.01.0060",
            "Brandmeldeanlage Kat. 2 mit Aufschaltung (Fire alarm system cat. 2 with monitoring link)",
            "lsum",
            1,
            24600.00,
            "450",
        ),
        (
            "16.01.0070",
            "Datennetz Cat 6A inkl. IT-Schrank und Patchfeld (Data network Cat 6A incl. IT cabinet)",
            "lsum",
            1,
            14800.00,
            "450",
        ),
        (
            "16.01.0080",
            "GLT/Gebäudeautomation: Feldgeräte, Aufschaltung, Energiemonitoring ISO 50001-fähig (BMS field devices, integration, ISO 50001-ready energy monitoring)",
            "lsum",
            1,
            18900.00,
            "480",
        ),
        (
            "16.02.0010",
            "Kompakt-Trafostation 630 kVA inkl. MS-Schaltanlage und IBN (Compact transformer station 630 kVA incl. MV switchgear and commissioning)",
            "pcs",
            1,
            112000.00,
            "440",
        ),
        (
            "16.02.0020",
            "Unterverteilungen Markt, Technik und Kasse (Sub-distribution boards sales, plant and checkout)",
            "pcs",
            6,
            7200.00,
            "440",
        ),
        (
            "16.02.0030",
            "Installationsgeräte, Schalter, Steckdosen und CEE-Anschlüsse (Wiring accessories, switches, sockets and CEE outlets)",
            "lsum",
            1,
            18600.00,
            "440",
        ),
        (
            "16.02.0040",
            "LED-Panels Nebenräume und Sozialtrakt inkl. Präsenzmelder (LED panels ancillary rooms and staff wing incl. presence detectors)",
            "pcs",
            58,
            285.00,
            "440",
        ),
        (
            "16.02.0050",
            "Anschluss Maschinen und Anlagen: RLT, WP, Kälte, Backöfen, Tore (Connection of plant: AHU, heat pump, refrigeration, ovens, gates)",
            "lsum",
            1,
            30400.00,
            "440",
        ),
        (
            "16.02.0060",
            "USV-Anlage 20 kVA Kassen- und IT-Versorgung (UPS 20 kVA for checkout and IT supply)",
            "pcs",
            1,
            23500.00,
            "440",
        ),
        (
            "16.02.0070",
            "Fassadenbeleuchtung und Anschluss Werbeanlagen (Facade lighting and connection of signage)",
            "lsum",
            1,
            12800.00,
            "440",
        ),
        (
            "16.02.0080",
            "Potentialausgleich, Erdung und Überspannungsschutz Typ 1+2 (Equipotential bonding, earthing and surge protection type 1+2)",
            "lsum",
            1,
            9800.00,
            "440",
        ),
        (
            "16.02.0090",
            "Fundament- und Ringerder inkl. Anschlussfahnen (Foundation and ring earth electrode incl. connection lugs)",
            "m",
            192,
            14.50,
            "440",
        ),
        (
            "16.02.0100",
            "Leerrohre und Bodentanks Kassenzone (Conduits and floor boxes, checkout zone)",
            "lsum",
            1,
            7600.00,
            "440",
        ),
        (
            "16.02.0110",
            "Torsteuerungen und Türkommunikation Anlieferung anschließen (Connection of gate controls and door intercom, delivery area)",
            "lsum",
            1,
            3400.00,
            "440",
        ),
        (
            "16.03.0010",
            "Videoüberwachung 14 IP-Kameras inkl. Aufzeichnung (Video surveillance, 14 IP cameras incl. recording)",
            "pcs",
            14,
            1450.00,
            "450",
        ),
        (
            "16.03.0020",
            "Einbruchmeldeanlage Außenhaut und Büros (Intruder alarm, building envelope and offices)",
            "lsum",
            1,
            13800.00,
            "450",
        ),
        (
            "16.03.0030",
            "ELA- und Durchsageanlage Verkaufsraum (Public address system, sales area)",
            "lsum",
            1,
            9600.00,
            "450",
        ),
        (
            "16.03.0040",
            "Elektronische Schließanlage und Zutrittskontrolle Personal (Electronic locking and staff access control)",
            "lsum",
            1,
            13200.00,
            "450",
        ),
        (
            "16.04.0010",
            "Energiezähler M-Bus, 12 Messstellen, Aufschaltung (M-Bus energy meters, 12 metering points, integration)",
            "pcs",
            12,
            685.00,
            "480",
        ),
        (
            "16.04.0020",
            "GLT-Visualisierung, Trendaufzeichnung, Fernzugriff und Einweisung (BMS visualisation, trending, remote access and instruction)",
            "lsum",
            1,
            11788.00,
            "480",
        ),
        # Closing row: measurements, DIN VDE testing, labelling and documentation.
        (
            "16.02.0120",
            "Messungen, Prüfungen DIN VDE, Beschriftung und Dokumentation (Measurements, DIN VDE testing, labelling and documentation)",
            "lsum",
            1,
            25508.00,
            "440",
        ),
    ],
    # LV 17 (KG 440, owner direct award). Smaller PV because the neighbouring
    # block shades part of the roof. The closing registration lsum sits here.
    "VE-17": [
        (
            "17.01.0010",
            "PV-Module 440 Wp, Ost-West-Aufständerung aerodynamisch (PV modules 440 Wp, aerodynamic east-west racking)",
            "pcs",
            520,
            285.00,
            "440",
        ),
        (
            "17.01.0020",
            "Unterkonstruktion und Ballastierung inkl. Bautenschutzmatten (Substructure and ballasting incl. protection mats)",
            "m2",
            1150,
            28.50,
            "440",
        ),
        (
            "17.01.0030",
            "Wechselrichter 25 kW inkl. DC-Überspannungsschutz (Inverters 25 kW incl. DC surge protection)",
            "pcs",
            8,
            4200.00,
            "440",
        ),
        (
            "17.01.0040",
            "DC-Verkabelung, Stringleitungen und Generatoranschlusskasten (DC cabling, string lines and generator junction box)",
            "lsum",
            1,
            11400.00,
            "440",
        ),
        (
            "17.01.0050",
            "Dachdurchführungen DC-Leitungen inkl. Abdichtungskoordination (Roof penetrations for DC cabling incl. waterproofing coordination)",
            "pcs",
            5,
            420.00,
            "440",
        ),
        (
            "17.01.0060",
            "Erstreinigung Module und Kennlinien-Abnahmemessung (Initial module cleaning and IV-curve acceptance measurement)",
            "lsum",
            1,
            3000.00,
            "440",
        ),
        (
            "17.02.0010",
            "Batteriespeicher 110 kWh inkl. BMS und Anbindung (Battery storage 110 kWh incl. BMS and integration)",
            "pcs",
            1,
            78500.00,
            "440",
        ),
        (
            "17.02.0020",
            "NA-Schutz, Zählerwesen und Direktvermarktungs-Gateway (Grid protection, metering and direct-marketing gateway)",
            "lsum",
            1,
            14800.00,
            "440",
        ),
        (
            "17.02.0030",
            "Dynamisches Lastmanagement für Ladeinfrastruktur (Dynamic load management for EV charging)",
            "lsum",
            1,
            9800.00,
            "440",
        ),
        (
            "17.03.0010",
            "DC-Schnellladestation 150 kW mit 2 Ladepunkten (DC fast charger 150 kW with 2 charge points)",
            "pcs",
            1,
            28400.00,
            "440",
        ),
        ("17.03.0020", "AC-Wallboxen 22 kW (AC wallboxes 22 kW)", "pcs", 4, 2850.00, "440"),
        (
            "17.03.0030",
            "Tiefbau und Fundamente Ladestationen inkl. Schutzbügel (Civils and foundations for chargers incl. protection hoops)",
            "lsum",
            1,
            15600.00,
            "440",
        ),
        (
            "17.03.0040",
            "Leerrohr- und Kabeltrasse GEIG, 26 Stellplätze vorgerüstet (Conduit and cable route per GEIG, 26 stalls pre-equipped)",
            "m",
            220,
            36.00,
            "440",
        ),
        # Closing row: registration, certificates, monitoring and records.
        (
            "17.03.0050",
            "Anmeldung, Zertifikate VDE-AR-N 4110, Monitoring und Dokumentation (Registration, VDE-AR-N 4110 certificates, monitoring and records)",
            "lsum",
            1,
            32505.00,
            "440",
        ),
    ],
    # LV 18 - subsections by KG: 18.01 mixed external works, 18.02 Erdbau
    # (KG 510), 18.03 Belaege (KG 520), 18.04 Entwaesserung (KG 540), 18.05
    # Begruenung (KG 550). The closing compaction-daywork lsum sits in KG 510.
    "VE-18": [
        (
            "18.01.0010",
            "Oberbodenabtrag und Erdarbeiten Außenanlagen (Topsoil strip and earthworks external areas)",
            "m3",
            1600,
            10.20,
            "510",
        ),
        (
            "18.01.0020",
            "Frostschutzschicht 0/45, d = 40 cm, für befestigte Flächen (Frost protection layer 0/45, 40 cm)",
            "m2",
            3400,
            13.80,
            "520",
        ),
        (
            "18.01.0030",
            "Asphalttrag- und Deckschicht Fahrgassen und Anlieferhof (Asphalt base and wearing course, lanes and delivery yard)",
            "m2",
            2300,
            43.50,
            "520",
        ),
        (
            "18.01.0040",
            "Drän-Betonpflaster Stellplätze, d = 10 cm, sickerfähig (Permeable concrete pavers parking stalls, 10 cm)",
            "m2",
            980,
            49.00,
            "520",
        ),
        ("18.01.0050", "Bordsteine und Einfassungen (Kerbs and edgings)", "m", 720, 29.50, "520"),
        (
            "18.01.0060",
            "Entwässerungsrinnen und Hofabläufe inkl. Anschluss (Drainage channels and yard gullies incl. connection)",
            "lsum",
            1,
            23800.00,
            "540",
        ),
        (
            "18.01.0070",
            "Rigole 150 m3 und Versickerungsmulden 280 m2 inkl. Drosselschacht 10 l/s (DWA-A 138) (Retention trench 150 m3 and infiltration swales 280 m2 incl. 10 l/s throttle)",
            "lsum",
            1,
            62500.00,
            "540",
        ),
        (
            "18.01.0080",
            "Zisterne 8 m3 inkl. Pumpentechnik für Bewässerung (Cistern 8 m3 incl. pump for irrigation)",
            "pcs",
            1,
            9400.00,
            "540",
        ),
        (
            "18.01.0090",
            "Fahrbahn- und Stellplatzmarkierung inkl. Sonderflächen (Lane and stall marking incl. special stalls)",
            "m",
            680,
            4.40,
            "520",
        ),
        (
            "18.01.0100",
            "Außenbeleuchtung 12 LED-Mastleuchten h = 6 m, 3000 K insektenfreundlich, inkl. Kabel und Fundamente (External lighting 12 LED masts 6 m incl. cabling and foundations)",
            "pcs",
            12,
            2450.00,
            "540",
        ),
        (
            "18.01.0110",
            "Hochstamm-Bäume pflanzen inkl. Substrat und Verankerung (Standard trees incl. substrate and anchoring)",
            "pcs",
            14,
            1020.00,
            "550",
        ),
        (
            "18.01.0120",
            "Strauch-/Rasenflächen und Fassadenbegrünung (Shrub/lawn areas and green facade)",
            "m2",
            1280,
            13.00,
            "550",
        ),
        (
            "18.02.0010",
            "Kofferaushub befestigte Flächen, d = 60 cm (Box excavation for paved areas, 60 cm)",
            "m3",
            2040,
            14.60,
            "510",
        ),
        (
            "18.02.0020",
            "Erdbau Profilierung Außenanlagen, Auf- und Abtrag, Feinplanum (Earthworks profiling external areas, cut and fill, fine grading)",
            "m3",
            2400,
            12.80,
            "510",
        ),
        (
            "18.02.0030",
            "Entsorgung Überschussmassen Außenanlagen Z1.1 (Disposal of surplus soil external works, class Z1.1)",
            "m3",
            1800,
            17.20,
            "510",
        ),
        (
            "18.02.0040",
            "Liefern und Einbau Füllboden und Frostschutzmaterial (Supply and place fill and frost-protection material)",
            "m3",
            1400,
            25.00,
            "510",
        ),
        (
            "18.02.0050",
            "Leitungsgräben Entwässerung und Beleuchtung inkl. Verfüllung (Service trenches drainage and lighting incl. backfill)",
            "m",
            540,
            29.00,
            "510",
        ),
        (
            "18.02.0060",
            "Erdplanum und Verdichtung Pflanz- und Muldenbereiche (Formation and compaction, planting and swale areas)",
            "m2",
            1700,
            3.60,
            "510",
        ),
        (
            "18.02.0070",
            "Baugruben Rigole und Zisterne ausheben und verfüllen (Excavation and backfill for retention trench and cistern)",
            "m3",
            520,
            18.80,
            "510",
        ),
        (
            "18.03.0010",
            "Geogitter-Bewehrung Unterbau befestigte Flächen (Geogrid reinforcement of paved-area sub-base)",
            "m2",
            3280,
            10.20,
            "520",
        ),
        (
            "18.03.0020",
            "Asphaltbinderschicht AC 16 BS, d = 6 cm (Asphalt binder course AC 16 BS, 6 cm)",
            "m2",
            2300,
            22.40,
            "520",
        ),
        (
            "18.03.0030",
            "Zulage PmB-Asphalt Anlieferhof Schwerlast (Extra-over polymer-modified asphalt, heavy-duty delivery yard)",
            "m2",
            620,
            19.20,
            "520",
        ),
        (
            "18.03.0040",
            "Gehwegplatten und Betonpflaster Gehwege, d = 8 cm (Paving slabs and concrete pavers, walkways, 8 cm)",
            "m2",
            180,
            56.00,
            "520",
        ),
        (
            "18.03.0050",
            "Tiefbord-Randeinfassung Pflasterflächen (Flush kerb edging of paved areas)",
            "m",
            300,
            25.00,
            "520",
        ),
        (
            "18.03.0060",
            "Bordrinnen und Muldensteine V-Profil (Kerb channels and V-profile dished channels)",
            "m",
            200,
            47.00,
            "520",
        ),
        (
            "18.03.0070",
            "Eingangspodest und Rampen Betonfertigteile, taktile Elemente (Entrance landing and ramps, precast concrete, tactile elements)",
            "lsum",
            1,
            9400.00,
            "520",
        ),
        (
            "18.03.0080",
            "Zulage Einkornbeton-Bettung und Splittfugen Drän-Pflaster (Extra-over no-fines concrete bedding and grit joints, permeable pavers)",
            "m2",
            980,
            10.20,
            "520",
        ),
        (
            "18.03.0090",
            "Markierung Sonderstellplätze: barrierefrei, Eltern-Kind, E-Laden (Marking of special stalls: accessible, parent-child, EV)",
            "pcs",
            18,
            96.00,
            "520",
        ),
        (
            "18.03.0100",
            "Beschilderung Parkplatz und Wegweisung (Car park signage and wayfinding)",
            "pcs",
            16,
            245.00,
            "520",
        ),
        (
            "18.03.0110",
            "Anschluss öffentliche Straße inkl. Bordabsenkung (Connection to the public road incl. dropped kerb)",
            "lsum",
            1,
            16800.00,
            "520",
        ),
        (
            "18.03.0120",
            "Anrampungen und Anpassung Bestandsgehweg Eppelheimer Straße (Ramping and adaptation of the existing footway, Eppelheimer Straße)",
            "lsum",
            1,
            18400.00,
            "520",
        ),
        (
            "18.03.0130",
            "Fugenverguss Asphaltanschlüsse und Abnahmebefahrung (Joint sealing of asphalt connections and acceptance drive-over)",
            "m",
            360,
            8.80,
            "520",
        ),
        (
            "18.04.0010",
            "Kontrollschächte DN 600 Rigolenanbindung (Inspection chambers DN 600 at retention trench connection)",
            "pcs",
            2,
            1480.00,
            "540",
        ),
        (
            "18.04.0020",
            "Anschlussleitung Dachentwässerung an Rigole DN 200 (Connection pipe, roof drainage to retention trench, DN 200)",
            "lsum",
            1,
            1600.00,
            "540",
        ),
        (
            "18.05.0010",
            "Baumscheiben, Unterpflanzung und Tropfbewässerung (Tree pits, underplanting and drip irrigation)",
            "pcs",
            14,
            430.00,
            "550",
        ),
        (
            "18.05.0020",
            "Rankhilfen Fassadenbegrünung, Edelstahlseile (Climbing aids for facade greening, stainless cables)",
            "m2",
            110,
            148.00,
            "550",
        ),
        (
            "18.05.0030",
            "Staudenpflanzung Eingangsbereich, Hochbeet (Perennial planting at the entrance, raised bed)",
            "m2",
            40,
            66.00,
            "550",
        ),
        (
            "18.05.0040",
            "Fertigstellungs- und Entwicklungspflege 2 Jahre (Completion and establishment maintenance, 2 years)",
            "lsum",
            1,
            14800.00,
            "550",
        ),
        # Closing row: compaction verification, fine grading and temporary
        # drainage (KG 510).
        (
            "18.02.0080",
            "Verdichtungsnachweise, Feinplanum Restflächen, bauzeitliche Entwässerung (Compaction verification, fine grading of remaining areas, temporary drainage)",
            "lsum",
            1,
            18846.00,
            "510",
        ),
    ],
    # LV 19 (KG 530). The closing foundations lsum sits here.
    "VE-19": [
        (
            "19.01.0010",
            "Werbepylon h = 6,5 m, Stahlkonstruktion, beleuchtet, höhenbegrenzt, inkl. Fundament (Advertising pylon 6.5 m, steel, illuminated, height-limited, incl. foundation)",
            "pcs",
            1,
            33500.00,
            "530",
        ),
        (
            "19.01.0020",
            "Einkaufswagen-Überdachungen 24 m2 mit Gründach (Cart shelters 24 m2 with green roofs)",
            "pcs",
            2,
            16800.00,
            "530",
        ),
        (
            "19.01.0030",
            "Fahrradüberdachung 28 Plätze und 4 Lastenrad-Plätze (Bike shelter 28 spaces plus 4 cargo-bike spaces)",
            "lsum",
            1,
            13400.00,
            "530",
        ),
        (
            "19.01.0040",
            "Fahrradanlehnbügel Edelstahl, nicht überdacht (Stainless bike hoops, uncovered)",
            "pcs",
            8,
            390.00,
            "530",
        ),
        (
            "19.01.0050",
            "Anfahrschutz Poller und Schutzbügel: Ladesäulen, Pylon, Gebäudeecken (Impact protection bollards and hoops: chargers, pylon, building corners)",
            "pcs",
            18,
            470.00,
            "530",
        ),
        (
            "19.01.0060",
            "Fahnenmasten h = 8 m inkl. Hülsenfundament (Flag poles 8 m incl. sleeve foundations)",
            "pcs",
            2,
            1950.00,
            "530",
        ),
        (
            "19.01.0070",
            "Beleuchtung Pylon-Logoblende, Anschluss und IBN (Pylon sign lighting, connection and commissioning)",
            "lsum",
            1,
            2400.00,
            "530",
        ),
        # Closing row: foundations, erection and ancillary works.
        (
            "19.01.0080",
            "Fundamente, Montage und Nebenleistungen Außenbauwerke (Foundations, erection and ancillary works, external structures)",
            "lsum",
            1,
            16620.00,
            "530",
        ),
    ],
    # LV 20 (KG 610, owner direct award). The closing erection lsum sits here.
    "VE-20": [
        (
            "20.01.0010",
            "Regalanlage Verkaufsraum 7 Gänge, Grund- und Anbaufelder, H = 2,2 m (Sales-area shelving 7 aisles, starter and add-on bays, H = 2.2 m)",
            "m",
            420,
            545.00,
            "610",
        ),
        ("20.01.0020", "Bandkassen-Arbeitsplätze (Belt checkout workstations)", "pcs", 2, 18400.00, "610"),
        (
            "20.01.0030",
            "Self-Checkout-Systeme inkl. Software-Inbetriebnahme (Self-checkout systems incl. software commissioning)",
            "pcs",
            4,
            21500.00,
            "610",
        ),
        (
            "20.01.0040",
            "Kassenzonen-Leitsystem, Warentrenner und Gondelköpfe (Checkout guidance system, dividers and gondola ends)",
            "lsum",
            1,
            14800.00,
            "610",
        ),
        (
            "20.01.0050",
            "Warensicherung Antennen Ein- und Ausgang (Article surveillance antennas, entrance and exit)",
            "pcs",
            2,
            4850.00,
            "610",
        ),
        (
            "20.01.0060",
            "Einkaufswagen inkl. Pfandschloss (Shopping carts incl. deposit locks)",
            "pcs",
            190,
            145.00,
            "610",
        ),
        (
            "20.01.0070",
            "Pfandbon-Drucker, IT-Halterungen und Kleinmontagen Kasse (Deposit-receipt printers, IT mounts and minor checkout fitting)",
            "lsum",
            1,
            2800.00,
            "610",
        ),
        (
            "20.02.0010",
            "Backstation 3 Öfen a 18 kW inkl. Beschickungs- und Ablufttechnik (Bake-off station, 3 ovens a 18 kW incl. loading and extract equipment)",
            "pcs",
            3,
            16900.00,
            "610",
        ),
        (
            "20.02.0020",
            "Brotregale und Präsentationsmöbel Backstation (Bread racks and display furniture, bake-off)",
            "lsum",
            1,
            6400.00,
            "610",
        ),
        (
            "20.02.0030",
            "Obst- und Gemüse-Präsentation, Kistenregale (Fruit and vegetable displays, crate racks)",
            "m",
            22,
            680.00,
            "610",
        ),
        (
            "20.02.0040",
            "Aktionsmöbel Gondelkopf und mobile Verkostungstheke (Promotional gondola-end units and mobile tasting counter)",
            "pcs",
            6,
            1450.00,
            "610",
        ),
        (
            "20.02.0050",
            "Büro- und Sozialraummöbel, Spinde 18 Personal (Office and staff-room furniture, lockers for 18 staff)",
            "pcs",
            18,
            485.00,
            "610",
        ),
        (
            "20.02.0060",
            "Innenbeschilderung, Deckenhänger und Regalstirn-Beschilderung (Interior signage, ceiling hangers and shelf-end signage)",
            "lsum",
            1,
            4400.00,
            "610",
        ),
        # Closing row: erection, alignment, initial-stocking logistics and instruction.
        (
            "20.02.0070",
            "Montage, Ausrichtung, Erstbestückungs-Logistik und Einweisung (Erection, alignment, initial-stocking logistics and instruction)",
            "lsum",
            1,
            9560.00,
            "610",
        ),
    ],
    # LV 21 (KG 690). The closing delivery/installation lsum sits here.
    "VE-21": [
        (
            "21.01.0010",
            "Leergut-Rücknahmeautomaten Doppelgerät mit Durchreiche (Reverse-vending machines, twin unit with pass-through)",
            "pcs",
            2,
            32500.00,
            "690",
        ),
        (
            "21.01.0020",
            "Leergut-Förder- und Sortieranlage Pfandraum, kompakt (Empties conveying and sorting system, deposit room, compact)",
            "lsum",
            1,
            14800.00,
            "690",
        ),
        ("21.01.0030", "Ballenpresse Kartonage 50 kN (Cardboard baler 50 kN)", "pcs", 1, 12400.00, "690"),
        ("21.01.0040", "Scheuersaugmaschine Reinigung (Scrubber-dryer cleaning machine)", "pcs", 1, 8900.00, "690"),
        (
            "21.01.0050",
            "Behältersystem Wertstoffe und Müllpress-Stellplatz (Recyclables container system and waste-press bay)",
            "lsum",
            1,
            6400.00,
            "690",
        ),
        (
            "21.01.0060",
            "Kleinausstattung: Feuerlöscher, Erste-Hilfe, Arbeitsschutz-Beschilderung (Minor equipment: extinguishers, first aid, safety signage)",
            "lsum",
            1,
            4200.00,
            "690",
        ),
        (
            "21.01.0070",
            "Ersatzteil- und Verschleisspaket RVM inkl. Personaleinweisung (Spare and wear-part package for the RVMs incl. staff instruction)",
            "lsum",
            1,
            2900.00,
            "690",
        ),
        # Closing row: delivery, assembly, commissioning and instruction.
        (
            "21.01.0080",
            "Anlieferung, Montage, IBN und Einweisung Betriebstechnik (Delivery, assembly, commissioning and instruction, operational equipment)",
            "lsum",
            1,
            5400.00,
            "690",
        ),
    ],
}


def _build_sections() -> list[SectionDef]:
    """Assemble the 16 LV sections, each summing exactly to its VE budget.

    Every section's positions must reproduce the procurement-unit budget to
    the cent. All money arithmetic runs through ``Decimal`` so the emitted
    two-decimal floats are exact and the LV grand total lands on
    7,200,000.00 EUR. A nonzero remainder is a data error and raises
    immediately, so a careless edit can never silently drift a budget.
    """
    sections: list[SectionDef] = []
    for ordinal, ve_id, title, kg, budget in _VE_SECTIONS:
        rows = _POSITIONS[ve_id]
        items: list[tuple[str, str, str, float, float, dict]] = [
            (oz, desc, unit, qty, rate, {"din276": code}) for oz, desc, unit, qty, rate, code in rows
        ]
        total = sum(
            (Decimal(str(qty)) * Decimal(str(rate)) for _, _, _, qty, rate, _ in rows),
            Decimal("0"),
        )
        remainder = Decimal(str(budget)) - total
        if remainder != 0:
            msg = f"{ve_id}: positions sum to {total}, budget is {budget} (off by {remainder})"
            raise ValueError(msg)
        sections.append((ordinal, title, {"din276": kg}, items))
    return sections


# Net LV grand total across the 16 priced procurement units (= sum of the VE
# budgets). install_demo_project prices bids as a factor of a share of this
# figure: with four tender packages each package gets an equal share
# (grand_total / 4) and each bid is priced as ``share * factor``. The factors
# below are authored as ``net_bid / _PKG_SHARE`` so every bid lands on its
# exact net amount regardless of the equal-share split.
_LV_GRAND_TOTAL = 7_200_000.00
_PKG_SHARE = _LV_GRAND_TOTAL / 4  # = 1,800,000.00

TEMPLATE = DemoTemplate(
    demo_id="retail-market-heidelberg",
    project_name="Lebensmittelmarkt Heidelberg",
    project_description=(
        "Neubau eines eingeschossigen Lebensmittelmarktes als innerstädtische "
        "Nachverdichtung im Stadtteil Pfaffengrund, Heidelberg (New-build food "
        "retail market as urban infill). Verkaufsfläche 1.450 m2, BGF 2.280 m2 "
        "(EG 2.160 + Technik-Mezzanin 100 + Galerie 20), BRI 15.300 m3, "
        "Grundstück 6.100 m2 in beengter Straßenrandlage. Tragwerk: 30 "
        "Stahlbeton-Fertigteilstützen 40/40 cm auf Köcherfundamenten, 20 "
        "BSH-Binder GL24h (Spannweiten 21,8 m + 15,0 m) auf 10 Achsen a 6,0 m, "
        "Bodenplatte d = 20 cm (432 m3 RC-Beton), Stahltrapezblech-Dach mit 7 "
        "RWA-Lichtkuppeln. Fassade nach Gestaltungssatzung: hinterlüftete "
        "Keramik-Vorhangfassade 980 m2 mit Ziegelriemchen-Akzentband, "
        "Pfosten-Riegel-Verglasung 110 m2. 100 % fossilfrei: transkritische "
        "CO2-Kälteanlage (NK 82 kW / TK 22 kW) mit 2-stufiger "
        "Wärmerückgewinnung und Fußbodenheizung, PV-Anlage 229 kWp "
        "(teilverschattet durch Nachbarbebauung) mit Batteriespeicher 110 kWh, "
        "9 E-Ladepunkte. 78 Pkw-Stellplätze, 40 Fahrradplätze, Rigole 150 m3 "
        "(DWA-A 138). KfW 299 (EG 40 + QNG-PLUS), DGNB Gold angestrebt. "
        "Genehmigtes Projektbudget 8,55 Mio EUR netto (KG 200-700 zzgl. Reserve)."
    ),
    region="DACH",
    classification_standard="din276",
    currency="EUR",
    locale="de",
    address={
        "street": "Eppelheimer Straße 78",
        "city": "Heidelberg",
        "postcode": "69123",
        "country": "Germany",
        "lat": 49.4015,
        "lng": 8.6492,
    },
    validation_rule_sets=["din276", "gaeb", "boq_quality"],
    boq_name="Kostenberechnung nach DIN 276",
    boq_description=(
        "Kostenberechnung gem. DIN 276:2018-12 auf Basis der Vergabeeinheiten: "
        "16 bepreiste LV-Abschnitte im OZ-Schema VE.Abschnitt.Position, Summe "
        "exakt 7.200.000 EUR netto. Jeder Abschnitt schließt centgenau auf "
        "sein VE-Budget; die abschließende Pauschalposition jedes Abschnitts "
        "nimmt die Rundungsdifferenz auf (full bill of quantities, every "
        "section closing exactly on its procurement-unit budget)."
    ),
    boq_metadata={
        "standard": "DIN 276:2018-12",
        "phase": "LP 3 Kostenberechnung, fortgeschrieben mit Vergabestand",
        "base_date": "2026-Q2",
        "price_level": "Heidelberg 2026",
        "oz_scheme": "VE.Abschnitt.Position",
        "project_code": "LM-HD-2026-01",
    },
    sections=_build_sections(),
    markups=[
        ("Baustellengemeinkosten (BGK / site overhead)", 9.0, "overhead", "direct_cost"),
        ("Mehrwertsteuer (MwSt. / VAT)", 19.0, "tax", "cumulative"),
    ],
    total_months=12,
    # Legacy single-package fields (required by DemoTemplate). They are
    # overridden by ``tender_packages`` below, but kept as the VP-07 award so
    # the descriptor still reads correctly if the multi-package path is ever
    # disabled.
    tender_name="VP-07 Kältetechnik CO2-Verbund und Kühlmöbel (CO2 refrigeration, owner direct award)",
    tender_companies=[
        ("Kurpfalz Kältetechnik GmbH", "vergabe@kurpfalz-kälte.de", 752_400 / _LV_GRAND_TOTAL),
        ("Rhein-Neckar Kühlanlagenbau GmbH", "angebote@rn-kühlanlagen.de", 781_900 / _LV_GRAND_TOTAL),
        ("Odenwald Kälte- und Klimatechnik GmbH", "ausschreibung@odenwald-kälte.de", 818_500 / _LV_GRAND_TOTAL),
    ],
    # Four procurement packages, each mapping to a procurement-unit budget.
    # Status reflects a mid-construction snapshot: VP-07 awarded, VP-09 out for
    # submission, VP-10 in negotiation, VP-11 in evaluation pending the grid
    # feed-in approval. The bid factor is ``net_bid / _PKG_SHARE`` so
    # install_demo_project (which prices each package off an equal
    # grand_total / 4 share) lands every bid on its exact net figure.
    tender_packages=[
        (
            "VP-07 Kältetechnik CO2-Verbund und Kühlmöbel (CO2 refrigeration and cabinets, KG 470)",
            "Bauherren-Direktvergabe, vergeben am 2026-05-08 an Kurpfalz Kältetechnik GmbH; 3 Angebote, Spread 8,8 %. Budget 770.000 EUR netto (VE-15).",
            "awarded",
            [
                # bids 752,400 / 781,900 / 818,500 EUR, spread 8.8 %
                ("Kurpfalz Kältetechnik GmbH", "vergabe@kurpfalz-kälte.de", 752_400 / _PKG_SHARE),
                ("Rhein-Neckar Kühlanlagenbau GmbH", "angebote@rn-kühlanlagen.de", 781_900 / _PKG_SHARE),
                ("Odenwald Kälte- und Klimatechnik GmbH", "ausschreibung@odenwald-kälte.de", 818_500 / _PKG_SHARE),
            ],
        ),
        (
            "VP-09 Außenanlagen, Stellplätze, Entwässerung (External works, parking, drainage, KG 510+520+540+550)",
            "Ausgeschrieben, Submission 2026-07-02; 3 indikative Angebote, Spread 12,7 %. Budget 800.000 EUR netto (VE-18).",
            "collecting",
            [
                # indicative bids 771,200 / 818,400 / 869,400 EUR, spread 12.7 %
                ("Galabau Neckartal GmbH", "angebot@galabau-neckartal.de", 771_200 / _PKG_SHARE),
                ("Tiefbau Bergstraße GmbH", "vergabe@tiefbau-bergstraße.de", 818_400 / _PKG_SHARE),
                ("Grünbau Kraichgau GmbH", "ausschreibung@grünbau-kraichgau.de", 869_400 / _PKG_SHARE),
            ],
        ),
        (
            "VP-10 Ladeneinrichtung, Regaltechnik, Kassenzone, Backstation (Store fit-out, KG 610)",
            "Bauherren-Direktvergabe, in Verhandlung, Zuschlag geplant 2026-07-15; 2 Angebote, Spread 6,1 %. Budget 510.000 EUR netto (VE-20).",
            "evaluating",
            [
                # bids 481,200 / 510,600 EUR, spread 6.1 %
                ("Ladenbau Wieslocher GmbH", "m.wieslocher@ladenbau-wieslocher.de", 481_200 / _PKG_SHARE),
                ("Objekteinrichtung Handschuh & Co. KG", "vergabe@handschuh-objekt.de", 510_600 / _PKG_SHARE),
            ],
        ),
        (
            "VP-11 PV 229 kWp, Batteriespeicher 110 kWh, Ladeinfrastruktur (PV, battery, EV charging, KG 440)",
            "Bauherren-Direktvergabe, in Wertung, Zuschlag nach Einspeisezusage (Risiko R06); 3 Angebote, Spread 11,9 %. Budget 430.000 EUR netto (VE-17).",
            "evaluating",
            [
                # bids 411,300 / 438,700 / 460,200 EUR, spread 11.9 %
                ("Sonnenkraft Kurpfalz GmbH", "angebot@sonnenkraft-kurpfalz.de", 411_300 / _PKG_SHARE),
                ("EnergieWerk Bergstraße GmbH", "vergabe@energiewerk-bergstraße.de", 438_700 / _PKG_SHARE),
                ("Elektro Wieblinger GmbH", "t.wieblinger@elektro-wieblinger.de", 460_200 / _PKG_SHARE),
            ],
        ),
    ],
    # 35 schedule activities anchored on the real calendar so the project reads
    # mid-construction (Mon 2026-02-16 start, opening Thu 2026-12-17).
    # install_demo_project derives a progress ramp from the activity order; the
    # SPI/CPI overrides below carry the "slightly behind on facade, on cost"
    # story driven by the design-board envelope.
    schedule_activities=[
        ("T01 Werk- und Montageplanung Fertigteile (precast shop and erection drawings)", "2026-02-16", "2026-03-20"),
        (
            "T02 Baustelleneinrichtung inkl. Verkehrslenkung und Anliegerkoordination (site setup incl. traffic routing)",
            "2026-02-16",
            "2026-02-27",
        ),
        (
            "T03 Erschließung Kanal, Wasser, Strom bis Grundstücksgrenze (utility connections to plot)",
            "2026-03-02",
            "2026-03-20",
        ),
        ("T04 Baufeldfreimachung und Oberbodenabtrag (site clearance and topsoil strip)", "2026-03-02", "2026-03-06"),
        ("T05 Erdaushub und Bodenaustausch (excavation and soil replacement)", "2026-03-09", "2026-03-27"),
        (
            "T06 Planumserstellung und Verdichtungsnachweis (subgrade formation and compaction)",
            "2026-03-30",
            "2026-04-03",
        ),
        ("T07 Köcher- und Streifenfundamente (pocket and strip foundations)", "2026-04-06", "2026-04-17"),
        ("T08 Grundleitungen unter Bodenplatte (below-slab drainage)", "2026-04-13", "2026-04-24"),
        (
            "T09 Bodenplatte: Dämmung, Bewehrung, Betonage (ground slab: insulation, rebar, pour)",
            "2026-04-20",
            "2026-05-08",
        ),
        ("T10 Fertigteilproduktion im Werk (precast production at plant)", "2026-03-23", "2026-05-08"),
        ("T11 Montage Stützen und BSH-Binder (erection of columns and glulam beams)", "2026-05-11", "2026-05-22"),
        ("T12 Montage Wand- und Sandwichelemente (erection of wall and sandwich panels)", "2026-05-18", "2026-05-29"),
        ("T13 Dachtragschale Trapezblech (roof deck trapezoidal sheeting)", "2026-05-25", "2026-06-05"),
        (
            "T14 Dachabdichtung, Dämmung, RWA und Lichtkuppeln (roof waterproofing, smoke vents, rooflights)",
            "2026-06-08",
            "2026-07-03",
        ),
        (
            "T15 Fassadenarbeiten: Keramik-Vorhangfassade, Ziegelriemchen, Sockel (design-board facade)",
            "2026-06-08",
            "2026-07-17",
        ),
        (
            "T16 Fenster, Pfosten-Riegel-Glasfront, Türen, Sektionaltore (windows, curtain wall, doors, gates)",
            "2026-06-29",
            "2026-07-24",
        ),
        ("T17 Heizung/Sanitär Rohinstallation (heating/plumbing rough-in)", "2026-06-15", "2026-07-24"),
        ("T18 Lüftungskanäle Montage (ventilation ductwork installation)", "2026-06-22", "2026-07-24"),
        (
            "T19 Elektro-Rohinstallation und Kabeltrassen (electrical rough-in and cable trays)",
            "2026-06-15",
            "2026-07-31",
        ),
        ("T20 CO2-Kälteleitungen Rohmontage (CO2 refrigerant piping rough-in)", "2026-07-13", "2026-08-07"),
        (
            "T21 Netzanschluss, Trafostation, NSHV (grid connection, transformer, main LV board)",
            "2026-06-29",
            "2026-08-07",
        ),
        ("T22 Trockenbau Sozial- und Nebenräume (drywall for staff and ancillary rooms)", "2026-07-20", "2026-08-21"),
        ("T23 Industrieboden Verkaufsraum (industrial flooring sales area)", "2026-07-27", "2026-08-07"),
        ("T24 Fliesen, Maler, Innentüren (tiling, painting, internal doors)", "2026-08-17", "2026-09-11"),
        ("T25 Akustikdecken und Beleuchtungsmontage (acoustic ceilings and lighting)", "2026-08-24", "2026-09-11"),
        (
            "T26 TGA-Endmontage: Wärmepumpe, RLT, Verteilungen, GLT (MEP completion incl. BMS)",
            "2026-08-24",
            "2026-09-25",
        ),
        (
            "T27 Außenanlagen: Unterbau, Entwässerung, Beläge, Pylon, Begrünung (external works)",
            "2026-08-24",
            "2026-10-30",
        ),
        (
            "T28 PV-Anlage, Batteriespeicher und Ladeinfrastruktur (PV, battery and EV charging)",
            "2026-09-07",
            "2026-10-02",
        ),
        ("T29 Kühlmöbel stellen und anbinden (set and connect refrigerated cabinets)", "2026-09-14", "2026-10-02"),
        (
            "T30 Kälteanlage: Druckprobe, Inbetriebnahme, Kühlstellen kalt (refrigeration commissioning)",
            "2026-10-05",
            "2026-10-16",
        ),
        (
            "T31 Ladeneinrichtung: Regale, Kassenzone, Backstation, Pfandraum (store fit-out)",
            "2026-10-12",
            "2026-11-06",
        ),
        (
            "T32 Sachverständigen- und behördliche Abnahmen (expert and authority acceptance tests)",
            "2026-11-02",
            "2026-11-13",
        ),
        (
            "T33 VOB-Abnahme GU und Mängelbeseitigung (VOB acceptance of GC works and snagging)",
            "2026-11-16",
            "2026-11-27",
        ),
        (
            "T34 Revisionsunterlagen, Einweisungen, Wartungsverträge (as-builts, briefings, maintenance)",
            "2026-11-16",
            "2026-12-04",
        ),
        (
            "T35 Warenerstbestückung, Personaleinarbeitung, Pre-Opening (initial stocking, training)",
            "2026-12-07",
            "2026-12-17",
        ),
    ],
    project_metadata={
        "name_en": "Retail Market Heidelberg",
        "long_name_de": "Neubau Lebensmittelmarkt als Nachverdichtung, Heidelberg-Pfaffengrund",
        "long_name_en": "New-build food retail market as urban infill, Heidelberg-Pfaffengrund",
        "address": "Eppelheimer Straße 78, 69123 Heidelberg",
        "client": "Kurpfalz Handelsimmobilien GmbH",
        "operator": "Rhein-Neckar Lebensmittelmärkte GmbH",
        "architect": "Architekturbüro Quartier Süd Architekten PartG mbB",
        "structural_engineer": "Wagenbach Ingenieure Tragwerksplanung GmbH",
        "mep_engineer": "Reichert & Partner TGA-Planung GmbH",
        "main_contractor": "Bohnenberger Bau GmbH & Co. KG",
        "gfa_m2": 2280,
        "bri_m3": 15300,
        "plot_m2": 6100,
        "footprint_m2": 2160,
        "sales_area_m2": 1450,
        "parking_stalls": 78,
        "bike_stalls": 40,
        "ev_charge_points": 9,
        "pv_kwp": 229,
        "battery_kwh": 110,
        "structure_system": "Precast RC columns 40/40 on pocket foundations, glulam binders GL24h, steel roof deck",
        "facade_system": "Ventilated ceramic rainscreen with brick-slip accent band, aluminium curtain wall entrance",
        "grid_m": "10 axes a 6.0, spans 21.8 + 15.0",
        "refrigeration": "Transcritical CO2 (R744) booster rack, MT 82 kW / LT 22 kW, 2-stage heat recovery",
        "energy_standard": "GEG 2024 / KfW 299 (EG 40 + QNG-PLUS)",
        "sustainability_target": "DGNB Gold (Neubau 2023)",
        "zoning": "Vorhabenbezogener B-Plan Pfaffengrund-Mitte - Nahversorgung (SO Nahversorgung, Gestaltungssatzung)",
        "permit_authority": "Stadt Heidelberg, Baurechtsamt (LBO BW, Sonderbau Verkaufsstätte)",
        "design_phase": "LP 3 Kostenberechnung, fortgeschrieben mit Vergabestand",
        "applicable_standards": [
            "DIN 276:2018-12",
            "VOB/B + VOB/C (DIN 18299 ff.)",
            "GAEB DA XML 3.3 (X83)",
            "GEG 2024",
            "GEIG",
            "KlimaG BW (PV-Pflicht)",
            "EN 378 (CO2-Kälteanlage)",
            "DWA-A 138 (Versickerung)",
        ],
        "cost_basis": "Net, price level Heidelberg 2026, reconciled DIN 276 cost frame",
        "budget": "8.55M EUR",
    },
    project_code="LM-HD-2026-01",
    # 5D tuning: ~32 % billed, slightly behind on the design-board facade
    # (SPI 0.96), on cost (CPI 1.01).
    planned_budget=8_550_000.0,
    actual_spend_ratio=0.32,
    spi_override=0.96,
    cpi_override=1.01,
)
