#!/usr/bin/env python3
"""
Add boq.import_preview.* keys to all required locale files.
29 keys, 42 locales.
"""
import re
import sys
from pathlib import Path

LOCALES_DIR = Path(__file__).parent.parent / "frontend" / "src" / "app" / "locales"

# English source keys (for interpolation token validation)
EN_KEYS = {
    "boq.import_preview.back": "Back",
    "boq.import_preview.cancel": "Cancel",
    "boq.import_preview.col_description": "Description",
    "boq.import_preview.col_ordinal": "Pos. / Code",
    "boq.import_preview.col_quantity": "Qty",
    "boq.import_preview.col_total": "Total",
    "boq.import_preview.col_unit": "Unit",
    "boq.import_preview.col_unit_rate": "Unit Rate",
    "boq.import_preview.confirm_button": "Import",
    "boq.import_preview.confirm_summary": "Import {{positions}} positions ({{sections}} sections) in {{currency}} from {{format}}?",
    "boq.import_preview.confirm_warnings": "{{count}} warning(s) were detected during parsing. The import will proceed.",
    "boq.import_preview.continue": "Continue",
    "boq.import_preview.drop_hint": "GAEB XML, Excel, PDF or CSV",
    "boq.import_preview.drop_zone": "Drop file here or click to browse",
    "boq.import_preview.errors_title": "{{count}} error(s)",
    "boq.import_preview.import_success": "Imported {{count}} positions",
    "boq.import_preview.import_timeout": "Server did not respond within 90 seconds.",
    "boq.import_preview.parse_timeout": "Server did not respond within 90 seconds. The file may be too large.",
    "boq.import_preview.parsing": "Parsing file...",
    "boq.import_preview.skipped_count": "{{count}} row(s) skipped (empty or unreadable)",
    "boq.import_preview.stats_currency": "Currency",
    "boq.import_preview.stats_format": "Format",
    "boq.import_preview.stats_positions": "Positions",
    "boq.import_preview.stats_sections": "Sections",
    "boq.import_preview.title": "Import preview",
    "boq.import_preview.truncated": "... and {{count}} more position(s)",
    "boq.import_preview.upload_hint": "Choose a file to preview before importing into this BOQ.",
    "boq.import_preview.warnings_title": "{{count}} warning(s)",
}

# Extract interpolation tokens from a string
def get_tokens(s):
    return set(re.findall(r'\{\{[^}]+\}\}', s))

# Translations: {locale: {key_suffix: value}}
# key_suffix is the part after "boq.import_preview."
TRANSLATIONS = {
    "ar": {
        "back": "رجوع",
        "cancel": "إلغاء",
        "col_description": "الوصف",
        "col_ordinal": "الرقم / الكود",
        "col_quantity": "الكمية",
        "col_total": "الإجمالي",
        "col_unit": "الوحدة",
        "col_unit_rate": "سعر الوحدة",
        "confirm_button": "استيراد",
        "confirm_summary": "استيراد {{positions}} بند ({{sections}} قسم) بعملة {{currency}} من {{format}}؟",
        "confirm_warnings": "تم اكتشاف {{count}} تحذير أثناء التحليل. سيستمر الاستيراد.",
        "continue": "متابعة",
        "drop_hint": "GAEB XML, Excel, PDF أو CSV",
        "drop_zone": "أسقط الملف هنا أو انقر للاستعراض",
        "errors_title": "{{count}} خطأ",
        "import_success": "تم استيراد {{count}} بند",
        "import_timeout": "لم يستجب الخادم خلال 90 ثانية.",
        "parse_timeout": "لم يستجب الخادم خلال 90 ثانية. قد يكون الملف كبيراً جداً.",
        "parsing": "جارٍ تحليل الملف...",
        "skipped_count": "تم تخطي {{count}} صف (فارغ أو غير قابل للقراءة)",
        "stats_currency": "العملة",
        "stats_format": "التنسيق",
        "stats_positions": "البنود",
        "stats_sections": "الأقسام",
        "title": "معاينة الاستيراد",
        "truncated": "... و{{count}} بند إضافي",
        "upload_hint": "اختر ملفاً للمعاينة قبل الاستيراد إلى قائمة الكميات.",
        "warnings_title": "{{count}} تحذير",
    },
    "bg": {
        "back": "Назад",
        "cancel": "Отказ",
        "col_description": "Описание",
        "col_ordinal": "Поз. / Код",
        "col_quantity": "Кол.",
        "col_total": "Общо",
        "col_unit": "Ед.",
        "col_unit_rate": "Ед. цена",
        "confirm_button": "Импортиране",
        "confirm_summary": "Импортиране на {{positions}} позиции ({{sections}} раздела) в {{currency}} от {{format}}?",
        "confirm_warnings": "При анализа са открити {{count}} предупреждение(я). Импортирането ще продължи.",
        "continue": "Продължи",
        "drop_hint": "GAEB XML, Excel, PDF или CSV",
        "drop_zone": "Пуснете файл тук или кликнете за избор",
        "errors_title": "{{count}} грешка(и)",
        "import_success": "Импортирани {{count}} позиции",
        "import_timeout": "Сървърът не отговори в рамките на 90 секунди.",
        "parse_timeout": "Сървърът не отговори в рамките на 90 секунди. Файлът може да е твърде голям.",
        "parsing": "Анализ на файла...",
        "skipped_count": "{{count}} ред(а) пропуснати (празни или нечетими)",
        "stats_currency": "Валута",
        "stats_format": "Формат",
        "stats_positions": "Позиции",
        "stats_sections": "Раздели",
        "title": "Преглед преди импорт",
        "truncated": "... и {{count}} позиция(и) повече",
        "upload_hint": "Изберете файл за преглед преди импортиране в тази КСС.",
        "warnings_title": "{{count}} предупреждение(я)",
    },
    "bn": {
        "back": "পেছনে",
        "cancel": "বাতিল",
        "col_description": "বিবরণ",
        "col_ordinal": "অবস্থান / কোড",
        "col_quantity": "পরিমাণ",
        "col_total": "মোট",
        "col_unit": "একক",
        "col_unit_rate": "একক মূল্য",
        "confirm_button": "আমদানি",
        "confirm_summary": "{{format}} থেকে {{currency}}-তে {{positions}}টি আইটেম ({{sections}}টি বিভাগ) আমদানি করবেন?",
        "confirm_warnings": "পার্সিংয়ের সময় {{count}}টি সতর্কতা পাওয়া গেছে। আমদানি চলবে।",
        "continue": "চালিয়ে যান",
        "drop_hint": "GAEB XML, Excel, PDF বা CSV",
        "drop_zone": "এখানে ফাইল ড্রপ করুন বা ব্রাউজ করতে ক্লিক করুন",
        "errors_title": "{{count}}টি ত্রুটি",
        "import_success": "{{count}}টি আইটেম আমদানি হয়েছে",
        "import_timeout": "সার্ভার ৯০ সেকেন্ডের মধ্যে সাড়া দেয়নি।",
        "parse_timeout": "সার্ভার ৯০ সেকেন্ডের মধ্যে সাড়া দেয়নি। ফাইলটি অনেক বড় হতে পারে।",
        "parsing": "ফাইল পার্স করা হচ্ছে...",
        "skipped_count": "{{count}}টি সারি এড়িয়ে গেছে (ফাঁকা বা পড়া যাচ্ছে না)",
        "stats_currency": "মুদ্রা",
        "stats_format": "ফরম্যাট",
        "stats_positions": "আইটেম",
        "stats_sections": "বিভাগ",
        "title": "আমদানির পূর্বরূপ",
        "truncated": "... এবং আরও {{count}}টি আইটেম",
        "upload_hint": "এই BOQ-তে আমদানির আগে পূর্বরূপ দেখতে একটি ফাইল বেছে নিন।",
        "warnings_title": "{{count}}টি সতর্কতা",
    },
    "cs": {
        "back": "Zpět",
        "cancel": "Zrušit",
        "col_description": "Popis",
        "col_ordinal": "Pol. / Kód",
        "col_quantity": "Mn.",
        "col_total": "Celkem",
        "col_unit": "Jedn.",
        "col_unit_rate": "Jedn. cena",
        "confirm_button": "Importovat",
        "confirm_summary": "Importovat {{positions}} položek ({{sections}} oddílů) v {{currency}} z {{format}}?",
        "confirm_warnings": "Při zpracování bylo zjištěno {{count}} upozornění. Import proběhne.",
        "continue": "Pokračovat",
        "drop_hint": "GAEB XML, Excel, PDF nebo CSV",
        "drop_zone": "Přetáhněte soubor sem nebo klikněte pro výběr",
        "errors_title": "{{count}} chyba(y)",
        "import_success": "Importováno {{count}} položek",
        "import_timeout": "Server nereagoval do 90 sekund.",
        "parse_timeout": "Server nereagoval do 90 sekund. Soubor může být příliš velký.",
        "parsing": "Zpracování souboru...",
        "skipped_count": "{{count}} řádek přeskočeno (prázdné nebo nečitelné)",
        "stats_currency": "Měna",
        "stats_format": "Formát",
        "stats_positions": "Položky",
        "stats_sections": "Oddíly",
        "title": "Náhled importu",
        "truncated": "... a {{count}} další položka(y)",
        "upload_hint": "Vyberte soubor pro náhled před importem do tohoto výkazu výměr.",
        "warnings_title": "{{count}} upozornění",
    },
    "da": {
        "back": "Tilbage",
        "cancel": "Annuller",
        "col_description": "Beskrivelse",
        "col_ordinal": "Pos. / Kode",
        "col_quantity": "Antal",
        "col_total": "Total",
        "col_unit": "Enhed",
        "col_unit_rate": "Enhedspris",
        "confirm_button": "Importer",
        "confirm_summary": "Importer {{positions}} poster ({{sections}} afsnit) i {{currency}} fra {{format}}?",
        "confirm_warnings": "Der blev fundet {{count}} advarsel(er) under parsing. Importen fortsætter.",
        "continue": "Fortsæt",
        "drop_hint": "GAEB XML, Excel, PDF eller CSV",
        "drop_zone": "Slip fil her eller klik for at gennemse",
        "errors_title": "{{count}} fejl",
        "import_success": "Importerede {{count}} poster",
        "import_timeout": "Serveren svarede ikke inden for 90 sekunder.",
        "parse_timeout": "Serveren svarede ikke inden for 90 sekunder. Filen kan være for stor.",
        "parsing": "Behandler fil...",
        "skipped_count": "{{count}} række(r) sprunget over (tomme eller ulæselige)",
        "stats_currency": "Valuta",
        "stats_format": "Format",
        "stats_positions": "Poster",
        "stats_sections": "Afsnit",
        "title": "Importforhåndsvisning",
        "truncated": "... og {{count}} post(er) til",
        "upload_hint": "Vælg en fil til forhåndsvisning inden import til dette tilbudsliste.",
        "warnings_title": "{{count}} advarsel(er)",
    },
    "de": {
        "back": "Zurück",
        "cancel": "Abbrechen",
        "col_description": "Bezeichnung",
        "col_ordinal": "Pos. / Code",
        "col_quantity": "Menge",
        "col_total": "Gesamt",
        "col_unit": "Einheit",
        "col_unit_rate": "Einheitspreis",
        "confirm_button": "Importieren",
        "confirm_summary": "{{positions}} Positionen ({{sections}} Abschnitte) in {{currency}} aus {{format}} importieren?",
        "confirm_warnings": "Beim Einlesen wurden {{count}} Warnung(en) festgestellt. Der Import wird fortgesetzt.",
        "continue": "Weiter",
        "drop_hint": "GAEB XML, Excel, PDF oder CSV",
        "drop_zone": "Datei hier ablegen oder zum Durchsuchen klicken",
        "errors_title": "{{count}} Fehler",
        "import_success": "{{count}} Positionen importiert",
        "import_timeout": "Der Server hat nicht innerhalb von 90 Sekunden geantwortet.",
        "parse_timeout": "Der Server hat nicht innerhalb von 90 Sekunden geantwortet. Die Datei ist möglicherweise zu groß.",
        "parsing": "Datei wird eingelesen...",
        "skipped_count": "{{count}} Zeile(n) übersprungen (leer oder nicht lesbar)",
        "stats_currency": "Währung",
        "stats_format": "Format",
        "stats_positions": "Positionen",
        "stats_sections": "Abschnitte",
        "title": "Importvorschau",
        "truncated": "... und {{count}} weitere Position(en)",
        "upload_hint": "Wählen Sie eine Datei zur Vorschau, bevor Sie sie in dieses LV importieren.",
        "warnings_title": "{{count}} Warnung(en)",
    },
    "el": {
        "back": "Πίσω",
        "cancel": "Ακύρωση",
        "col_description": "Περιγραφή",
        "col_ordinal": "Θέση / Κωδ.",
        "col_quantity": "Ποσ.",
        "col_total": "Σύνολο",
        "col_unit": "Μον.",
        "col_unit_rate": "Τιμή μον.",
        "confirm_button": "Εισαγωγή",
        "confirm_summary": "Εισαγωγή {{positions}} θέσεων ({{sections}} τμημάτων) σε {{currency}} από {{format}};",
        "confirm_warnings": "Κατά την ανάλυση εντοπίστηκαν {{count}} προειδοποίηση(εις). Η εισαγωγή θα συνεχιστεί.",
        "continue": "Συνέχεια",
        "drop_hint": "GAEB XML, Excel, PDF ή CSV",
        "drop_zone": "Αποθέστε το αρχείο εδώ ή κάντε κλικ για αναζήτηση",
        "errors_title": "{{count}} σφάλμα(τα)",
        "import_success": "Εισήχθησαν {{count}} θέσεις",
        "import_timeout": "Ο διακομιστής δεν απάντησε εντός 90 δευτερολέπτων.",
        "parse_timeout": "Ο διακομιστής δεν απάντησε εντός 90 δευτερολέπτων. Το αρχείο μπορεί να είναι πολύ μεγάλο.",
        "parsing": "Ανάλυση αρχείου...",
        "skipped_count": "{{count}} γραμμή(ές) παραλείφθηκε (κενές ή μη αναγνώσιμες)",
        "stats_currency": "Νόμισμα",
        "stats_format": "Μορφή",
        "stats_positions": "Θέσεις",
        "stats_sections": "Τμήματα",
        "title": "Προεπισκόπηση εισαγωγής",
        "truncated": "... και {{count}} ακόμη θέση(εις)",
        "upload_hint": "Επιλέξτε αρχείο για προεπισκόπηση πριν την εισαγωγή στον προϋπολογισμό.",
        "warnings_title": "{{count}} προειδοποίηση(εις)",
    },
    "es": {
        "back": "Atrás",
        "cancel": "Cancelar",
        "col_description": "Descripción",
        "col_ordinal": "Pos. / Código",
        "col_quantity": "Cant.",
        "col_total": "Total",
        "col_unit": "Unidad",
        "col_unit_rate": "Precio unit.",
        "confirm_button": "Importar",
        "confirm_summary": "¿Importar {{positions}} partidas ({{sections}} capítulos) en {{currency}} desde {{format}}?",
        "confirm_warnings": "Se detectaron {{count}} advertencia(s) durante el análisis. La importación continuará.",
        "continue": "Continuar",
        "drop_hint": "GAEB XML, Excel, PDF o CSV",
        "drop_zone": "Suelte el archivo aquí o haga clic para buscar",
        "errors_title": "{{count}} error(es)",
        "import_success": "{{count}} partidas importadas",
        "import_timeout": "El servidor no respondió en 90 segundos.",
        "parse_timeout": "El servidor no respondió en 90 segundos. El archivo puede ser demasiado grande.",
        "parsing": "Procesando archivo...",
        "skipped_count": "{{count}} fila(s) omitida(s) (vacías o ilegibles)",
        "stats_currency": "Moneda",
        "stats_format": "Formato",
        "stats_positions": "Partidas",
        "stats_sections": "Capítulos",
        "title": "Vista previa de importación",
        "truncated": "... y {{count}} partida(s) más",
        "upload_hint": "Seleccione un archivo para previsualizar antes de importarlo en este presupuesto.",
        "warnings_title": "{{count}} advertencia(s)",
    },
    "es-CL": {
        "back": "Atrás",
        "cancel": "Cancelar",
        "col_description": "Descripción",
        "col_ordinal": "Pos. / Código",
        "col_quantity": "Cant.",
        "col_total": "Total",
        "col_unit": "Unidad",
        "col_unit_rate": "Precio unit.",
        "confirm_button": "Importar",
        "confirm_summary": "¿Importar {{positions}} partidas ({{sections}} capítulos) en {{currency}} desde {{format}}?",
        "confirm_warnings": "Se detectaron {{count}} advertencia(s) durante el análisis. La importación continuará.",
        "continue": "Continuar",
        "drop_hint": "GAEB XML, Excel, PDF o CSV",
        "drop_zone": "Suelte el archivo aquí o haga clic para buscar",
        "errors_title": "{{count}} error(es)",
        "import_success": "{{count}} partidas importadas",
        "import_timeout": "El servidor no respondió en 90 segundos.",
        "parse_timeout": "El servidor no respondió en 90 segundos. El archivo puede ser demasiado grande.",
        "parsing": "Procesando archivo...",
        "skipped_count": "{{count}} fila(s) omitida(s) (vacías o ilegibles)",
        "stats_currency": "Moneda",
        "stats_format": "Formato",
        "stats_positions": "Partidas",
        "stats_sections": "Capítulos",
        "title": "Vista previa de importación",
        "truncated": "... y {{count}} partida(s) más",
        "upload_hint": "Seleccione un archivo para previsualizar antes de importarlo en este presupuesto.",
        "warnings_title": "{{count}} advertencia(s)",
    },
    "es-CO": {
        "back": "Atrás",
        "cancel": "Cancelar",
        "col_description": "Descripción",
        "col_ordinal": "Pos. / Código",
        "col_quantity": "Cant.",
        "col_total": "Total",
        "col_unit": "Unidad",
        "col_unit_rate": "Precio unit.",
        "confirm_button": "Importar",
        "confirm_summary": "¿Importar {{positions}} ítems ({{sections}} capítulos) en {{currency}} desde {{format}}?",
        "confirm_warnings": "Se detectaron {{count}} advertencia(s) durante el análisis. La importación continuará.",
        "continue": "Continuar",
        "drop_hint": "GAEB XML, Excel, PDF o CSV",
        "drop_zone": "Suelte el archivo aquí o haga clic para buscar",
        "errors_title": "{{count}} error(es)",
        "import_success": "{{count}} ítems importados",
        "import_timeout": "El servidor no respondió en 90 segundos.",
        "parse_timeout": "El servidor no respondió en 90 segundos. El archivo puede ser demasiado grande.",
        "parsing": "Procesando archivo...",
        "skipped_count": "{{count}} fila(s) omitida(s) (vacías o ilegibles)",
        "stats_currency": "Moneda",
        "stats_format": "Formato",
        "stats_positions": "Ítems",
        "stats_sections": "Capítulos",
        "title": "Vista previa de importación",
        "truncated": "... y {{count}} ítem(s) más",
        "upload_hint": "Seleccione un archivo para previsualizar antes de importarlo en este APU.",
        "warnings_title": "{{count}} advertencia(s)",
    },
    "es-MX": {
        "back": "Atrás",
        "cancel": "Cancelar",
        "col_description": "Descripción",
        "col_ordinal": "Pos. / Código",
        "col_quantity": "Cant.",
        "col_total": "Total",
        "col_unit": "Unidad",
        "col_unit_rate": "Precio unit.",
        "confirm_button": "Importar",
        "confirm_summary": "¿Importar {{positions}} conceptos ({{sections}} capítulos) en {{currency}} desde {{format}}?",
        "confirm_warnings": "Se detectaron {{count}} advertencia(s) durante el análisis. La importación continuará.",
        "continue": "Continuar",
        "drop_hint": "GAEB XML, Excel, PDF o CSV",
        "drop_zone": "Suelte el archivo aquí o haga clic para buscar",
        "errors_title": "{{count}} error(es)",
        "import_success": "{{count}} conceptos importados",
        "import_timeout": "El servidor no respondió en 90 segundos.",
        "parse_timeout": "El servidor no respondió en 90 segundos. El archivo puede ser demasiado grande.",
        "parsing": "Procesando archivo...",
        "skipped_count": "{{count}} fila(s) omitida(s) (vacías o ilegibles)",
        "stats_currency": "Moneda",
        "stats_format": "Formato",
        "stats_positions": "Conceptos",
        "stats_sections": "Capítulos",
        "title": "Vista previa de importación",
        "truncated": "... y {{count}} concepto(s) más",
        "upload_hint": "Seleccione un archivo para previsualizar antes de importarlo en este catálogo de conceptos.",
        "warnings_title": "{{count}} advertencia(s)",
    },
    "et": {
        "back": "Tagasi",
        "cancel": "Tühista",
        "col_description": "Kirjeldus",
        "col_ordinal": "Pos. / Kood",
        "col_quantity": "Kogus",
        "col_total": "Kokku",
        "col_unit": "Ühik",
        "col_unit_rate": "Ühiku hind",
        "confirm_button": "Impordi",
        "confirm_summary": "Importida {{positions}} rida ({{sections}} sektsiooni) valuutas {{currency}} failist {{format}}?",
        "confirm_warnings": "Töötlemisel leiti {{count}} hoiatus(t). Import jätkub.",
        "continue": "Jätka",
        "drop_hint": "GAEB XML, Excel, PDF või CSV",
        "drop_zone": "Lohista fail siia või klõpsa sirvimiseks",
        "errors_title": "{{count}} viga",
        "import_success": "Imporditud {{count}} rida",
        "import_timeout": "Server ei vastanud 90 sekundi jooksul.",
        "parse_timeout": "Server ei vastanud 90 sekundi jooksul. Fail võib olla liiga suur.",
        "parsing": "Faili töötlemine...",
        "skipped_count": "{{count}} rida vahele jäetud (tühi või loetamatu)",
        "stats_currency": "Valuuta",
        "stats_format": "Vorming",
        "stats_positions": "Read",
        "stats_sections": "Sektsioonid",
        "title": "Impordi eelvaade",
        "truncated": "... ja {{count}} rida veel",
        "upload_hint": "Valige fail eelvaatamiseks enne selle importimist sellesse mahuarvutusse.",
        "warnings_title": "{{count}} hoiatus(t)",
    },
    "fa": {
        "back": "بازگشت",
        "cancel": "لغو",
        "col_description": "شرح",
        "col_ordinal": "ردیف / کد",
        "col_quantity": "مقدار",
        "col_total": "جمع",
        "col_unit": "واحد",
        "col_unit_rate": "قیمت واحد",
        "confirm_button": "وارد کردن",
        "confirm_summary": "وارد کردن {{positions}} ردیف ({{sections}} بخش) به {{currency}} از {{format}}؟",
        "confirm_warnings": "در هنگام تجزیه {{count}} هشدار شناسایی شد. وارد کردن ادامه خواهد یافت.",
        "continue": "ادامه",
        "drop_hint": "GAEB XML, Excel, PDF یا CSV",
        "drop_zone": "فایل را اینجا رها کنید یا برای انتخاب کلیک کنید",
        "errors_title": "{{count}} خطا",
        "import_success": "{{count}} ردیف وارد شد",
        "import_timeout": "سرور در ۹۰ ثانیه پاسخ نداد.",
        "parse_timeout": "سرور در ۹۰ ثانیه پاسخ نداد. فایل ممکن است خیلی بزرگ باشد.",
        "parsing": "در حال تجزیه فایل...",
        "skipped_count": "{{count}} ردیف رد شد (خالی یا غیرقابل خواندن)",
        "stats_currency": "ارز",
        "stats_format": "فرمت",
        "stats_positions": "ردیف‌ها",
        "stats_sections": "بخش‌ها",
        "title": "پیش‌نمایش وارد کردن",
        "truncated": "... و {{count}} ردیف دیگر",
        "upload_hint": "برای پیش‌نمایش قبل از وارد کردن به این برآورد، یک فایل انتخاب کنید.",
        "warnings_title": "{{count}} هشدار",
    },
    "fi": {
        "back": "Takaisin",
        "cancel": "Peruuta",
        "col_description": "Kuvaus",
        "col_ordinal": "Pos. / Koodi",
        "col_quantity": "Määrä",
        "col_total": "Yhteensä",
        "col_unit": "Yksikkö",
        "col_unit_rate": "Yksikköhinta",
        "confirm_button": "Tuo",
        "confirm_summary": "Tuodaanko {{positions}} nimikettä ({{sections}} osaa) valuutassa {{currency}} tiedostosta {{format}}?",
        "confirm_warnings": "Jäsentämisen aikana havaittiin {{count}} varoitus(ta). Tuonti jatkuu.",
        "continue": "Jatka",
        "drop_hint": "GAEB XML, Excel, PDF tai CSV",
        "drop_zone": "Pudota tiedosto tähän tai selaa napsauttamalla",
        "errors_title": "{{count}} virhe(ttä)",
        "import_success": "Tuotu {{count}} nimikettä",
        "import_timeout": "Palvelin ei vastannut 90 sekunnin kuluessa.",
        "parse_timeout": "Palvelin ei vastannut 90 sekunnin kuluessa. Tiedosto saattaa olla liian suuri.",
        "parsing": "Käsitellään tiedostoa...",
        "skipped_count": "{{count}} rivi ohitettu (tyhjä tai lukukelvoton)",
        "stats_currency": "Valuutta",
        "stats_format": "Muoto",
        "stats_positions": "Nimikkeet",
        "stats_sections": "Osat",
        "title": "Tuonnin esikatselu",
        "truncated": "... ja {{count}} nimikettä lisää",
        "upload_hint": "Valitse tiedosto esikatselua varten ennen tuontia tähän määräluetteloon.",
        "warnings_title": "{{count}} varoitus(ta)",
    },
    "fil": {
        "back": "Bumalik",
        "cancel": "Kanselahin",
        "col_description": "Paglalarawan",
        "col_ordinal": "Pos. / Code",
        "col_quantity": "Dami",
        "col_total": "Kabuuan",
        "col_unit": "Yunit",
        "col_unit_rate": "Presyo sa yunit",
        "confirm_button": "I-import",
        "confirm_summary": "I-import ang {{positions}} na aytem ({{sections}} na seksyon) sa {{currency}} mula sa {{format}}?",
        "confirm_warnings": "{{count}} babala ang natukoy sa panahon ng pag-parse. Magpapatuloy ang pag-import.",
        "continue": "Magpatuloy",
        "drop_hint": "GAEB XML, Excel, PDF o CSV",
        "drop_zone": "I-drop ang file dito o mag-click para mag-browse",
        "errors_title": "{{count}} error",
        "import_success": "Na-import ang {{count}} na aytem",
        "import_timeout": "Hindi sumagot ang server sa loob ng 90 segundo.",
        "parse_timeout": "Hindi sumagot ang server sa loob ng 90 segundo. Maaaring masyadong malaki ang file.",
        "parsing": "Inaayos ang file...",
        "skipped_count": "{{count}} hanay ang nilaktawan (walang laman o hindi mabasa)",
        "stats_currency": "Pera",
        "stats_format": "Format",
        "stats_positions": "Mga aytem",
        "stats_sections": "Mga seksyon",
        "title": "Preview ng import",
        "truncated": "... at {{count}} pang aytem",
        "upload_hint": "Pumili ng file para sa preview bago i-import sa BOQ na ito.",
        "warnings_title": "{{count}} babala",
    },
    "fr": {
        "back": "Retour",
        "cancel": "Annuler",
        "col_description": "Désignation",
        "col_ordinal": "Pos. / Code",
        "col_quantity": "Qté",
        "col_total": "Montant",
        "col_unit": "Unité",
        "col_unit_rate": "P.U.",
        "confirm_button": "Importer",
        "confirm_summary": "Importer {{positions}} postes ({{sections}} lots) en {{currency}} depuis {{format}} ?",
        "confirm_warnings": "{{count}} avertissement(s) détecté(s) lors de l'analyse. L'import sera effectué.",
        "continue": "Continuer",
        "drop_hint": "GAEB XML, Excel, PDF ou CSV",
        "drop_zone": "Déposez le fichier ici ou cliquez pour parcourir",
        "errors_title": "{{count}} erreur(s)",
        "import_success": "{{count}} postes importés",
        "import_timeout": "Le serveur n'a pas répondu dans les 90 secondes.",
        "parse_timeout": "Le serveur n'a pas répondu dans les 90 secondes. Le fichier est peut-être trop volumineux.",
        "parsing": "Analyse du fichier en cours...",
        "skipped_count": "{{count}} ligne(s) ignorée(s) (vide(s) ou illisible(s))",
        "stats_currency": "Devise",
        "stats_format": "Format",
        "stats_positions": "Postes",
        "stats_sections": "Lots",
        "title": "Aperçu avant import",
        "truncated": "... et {{count}} poste(s) de plus",
        "upload_hint": "Choisissez un fichier pour le prévisualiser avant de l'importer dans ce DPGF.",
        "warnings_title": "{{count}} avertissement(s)",
    },
    "he": {
        "back": "חזרה",
        "cancel": "ביטול",
        "col_description": "תיאור",
        "col_ordinal": "סעיף / קוד",
        "col_quantity": "כמות",
        "col_total": "סה\"כ",
        "col_unit": "יחידה",
        "col_unit_rate": "מחיר יחידה",
        "confirm_button": "ייבוא",
        "confirm_summary": "לייבא {{positions}} סעיפים ({{sections}} פרקים) ב-{{currency}} מ-{{format}}?",
        "confirm_warnings": "{{count}} אזהרה/ות זוהו במהלך העיבוד. הייבוא יתבצע.",
        "continue": "המשך",
        "drop_hint": "GAEB XML, Excel, PDF או CSV",
        "drop_zone": "גרור קובץ לכאן או לחץ לבחירה",
        "errors_title": "{{count}} שגיאה/ות",
        "import_success": "יובאו {{count}} סעיפים",
        "import_timeout": "השרת לא הגיב תוך 90 שניות.",
        "parse_timeout": "השרת לא הגיב תוך 90 שניות. הקובץ עלול להיות גדול מדי.",
        "parsing": "מעבד קובץ...",
        "skipped_count": "{{count}} שורה/ות דולגה/ו (ריקה/ות או לא קריאה/ות)",
        "stats_currency": "מטבע",
        "stats_format": "פורמט",
        "stats_positions": "סעיפים",
        "stats_sections": "פרקים",
        "title": "תצוגה מקדימה של ייבוא",
        "truncated": "... ועוד {{count}} סעיף/ים",
        "upload_hint": "בחר קובץ לתצוגה מקדימה לפני ייבוא לכתב הכמויות.",
        "warnings_title": "{{count}} אזהרה/ות",
    },
    "hi": {
        "back": "वापस",
        "cancel": "रद्द करें",
        "col_description": "विवरण",
        "col_ordinal": "आइटम / कोड",
        "col_quantity": "मात्रा",
        "col_total": "कुल",
        "col_unit": "इकाई",
        "col_unit_rate": "इकाई दर",
        "confirm_button": "आयात करें",
        "confirm_summary": "{{format}} से {{currency}} में {{positions}} आइटम ({{sections}} खंड) आयात करें?",
        "confirm_warnings": "पार्सिंग के दौरान {{count}} चेतावनी मिली। आयात जारी रहेगा।",
        "continue": "जारी रखें",
        "drop_hint": "GAEB XML, Excel, PDF या CSV",
        "drop_zone": "यहाँ फ़ाइल छोड़ें या ब्राउज़ करने के लिए क्लिक करें",
        "errors_title": "{{count}} त्रुटि",
        "import_success": "{{count}} आइटम आयात हुए",
        "import_timeout": "सर्वर ने 90 सेकंड में जवाब नहीं दिया।",
        "parse_timeout": "सर्वर ने 90 सेकंड में जवाब नहीं दिया। फ़ाइल बहुत बड़ी हो सकती है।",
        "parsing": "फ़ाइल प्रोसेस हो रही है...",
        "skipped_count": "{{count}} पंक्ति छोड़ी गई (खाली या अपठनीय)",
        "stats_currency": "मुद्रा",
        "stats_format": "प्रारूप",
        "stats_positions": "आइटम",
        "stats_sections": "खंड",
        "title": "आयात पूर्वावलोकन",
        "truncated": "... और {{count}} आइटम",
        "upload_hint": "इस BOQ में आयात करने से पहले पूर्वावलोकन के लिए एक फ़ाइल चुनें।",
        "warnings_title": "{{count}} चेतावनी",
    },
    "hr": {
        "back": "Natrag",
        "cancel": "Odustani",
        "col_description": "Opis",
        "col_ordinal": "Pos. / Šifra",
        "col_quantity": "Kol.",
        "col_total": "Ukupno",
        "col_unit": "Jed.",
        "col_unit_rate": "Jed. cijena",
        "confirm_button": "Uvezi",
        "confirm_summary": "Uvesti {{positions}} stavki ({{sections}} poglavlja) u {{currency}} iz {{format}}?",
        "confirm_warnings": "Otkriveno je {{count}} upozorenje/a pri obradi. Uvoz će se nastaviti.",
        "continue": "Nastavi",
        "drop_hint": "GAEB XML, Excel, PDF ili CSV",
        "drop_zone": "Ispustite datoteku ovdje ili kliknite za pregled",
        "errors_title": "{{count}} greška/e",
        "import_success": "Uvezeno {{count}} stavki",
        "import_timeout": "Poslužitelj nije odgovorio u roku od 90 sekundi.",
        "parse_timeout": "Poslužitelj nije odgovorio u roku od 90 sekundi. Datoteka je možda prevelika.",
        "parsing": "Obrada datoteke...",
        "skipped_count": "{{count}} redak/ka preskočeno (prazno ili nečitljivo)",
        "stats_currency": "Valuta",
        "stats_format": "Format",
        "stats_positions": "Stavke",
        "stats_sections": "Poglavlja",
        "title": "Pregled uvoza",
        "truncated": "... i još {{count}} stavka/ki",
        "upload_hint": "Odaberite datoteku za pregled prije uvoza u ovaj troškovnik.",
        "warnings_title": "{{count}} upozorenje/a",
    },
    "hu": {
        "back": "Vissza",
        "cancel": "Mégse",
        "col_description": "Leírás",
        "col_ordinal": "Tétel / Kód",
        "col_quantity": "Menny.",
        "col_total": "Összesen",
        "col_unit": "Egység",
        "col_unit_rate": "Egységár",
        "confirm_button": "Importálás",
        "confirm_summary": "{{positions}} tétel ({{sections}} fejezet) importálása {{currency}} pénznemben, forrás: {{format}}?",
        "confirm_warnings": "Az elemzés során {{count}} figyelmeztetés érkezett. Az importálás folytatódik.",
        "continue": "Folytatás",
        "drop_hint": "GAEB XML, Excel, PDF vagy CSV",
        "drop_zone": "Húzza ide a fájlt, vagy kattintson a tallózáshoz",
        "errors_title": "{{count}} hiba",
        "import_success": "{{count}} tétel importálva",
        "import_timeout": "A szerver 90 másodpercen belül nem válaszolt.",
        "parse_timeout": "A szerver 90 másodpercen belül nem válaszolt. A fájl esetleg túl nagy.",
        "parsing": "Fájl feldolgozása...",
        "skipped_count": "{{count}} sor kihagyva (üres vagy olvashatatlan)",
        "stats_currency": "Pénznem",
        "stats_format": "Formátum",
        "stats_positions": "Tételek",
        "stats_sections": "Fejezetek",
        "title": "Importálás előnézete",
        "truncated": "... és még {{count}} tétel",
        "upload_hint": "Válasszon fájlt az előnézethez, mielőtt importálja ebbe a tételjegyzékbe.",
        "warnings_title": "{{count}} figyelmeztetés",
    },
    "id": {
        "back": "Kembali",
        "cancel": "Batal",
        "col_description": "Keterangan",
        "col_ordinal": "Pos. / Kode",
        "col_quantity": "Kuan.",
        "col_total": "Total",
        "col_unit": "Satuan",
        "col_unit_rate": "Harga satuan",
        "confirm_button": "Impor",
        "confirm_summary": "Impor {{positions}} item ({{sections}} bagian) dalam {{currency}} dari {{format}}?",
        "confirm_warnings": "{{count}} peringatan ditemukan saat parsing. Impor akan dilanjutkan.",
        "continue": "Lanjutkan",
        "drop_hint": "GAEB XML, Excel, PDF atau CSV",
        "drop_zone": "Letakkan file di sini atau klik untuk mencari",
        "errors_title": "{{count}} kesalahan",
        "import_success": "{{count}} item berhasil diimpor",
        "import_timeout": "Server tidak merespons dalam 90 detik.",
        "parse_timeout": "Server tidak merespons dalam 90 detik. File mungkin terlalu besar.",
        "parsing": "Memproses file...",
        "skipped_count": "{{count}} baris dilewati (kosong atau tidak terbaca)",
        "stats_currency": "Mata uang",
        "stats_format": "Format",
        "stats_positions": "Item",
        "stats_sections": "Bagian",
        "title": "Pratinjau impor",
        "truncated": "... dan {{count}} item lainnya",
        "upload_hint": "Pilih file untuk pratinjau sebelum mengimpor ke RAB ini.",
        "warnings_title": "{{count}} peringatan",
    },
    "it": {
        "back": "Indietro",
        "cancel": "Annulla",
        "col_description": "Descrizione",
        "col_ordinal": "Pos. / Codice",
        "col_quantity": "Q.tà",
        "col_total": "Totale",
        "col_unit": "U.M.",
        "col_unit_rate": "Prezzo unit.",
        "confirm_button": "Importa",
        "confirm_summary": "Importare {{positions}} voci ({{sections}} capitoli) in {{currency}} da {{format}}?",
        "confirm_warnings": "Durante l'analisi sono stati rilevati {{count}} avviso/i. L'importazione proseguirà.",
        "continue": "Continua",
        "drop_hint": "GAEB XML, Excel, PDF o CSV",
        "drop_zone": "Trascina il file qui o clicca per sfogliare",
        "errors_title": "{{count}} errore/i",
        "import_success": "{{count}} voci importate",
        "import_timeout": "Il server non ha risposto entro 90 secondi.",
        "parse_timeout": "Il server non ha risposto entro 90 secondi. Il file potrebbe essere troppo grande.",
        "parsing": "Elaborazione file in corso...",
        "skipped_count": "{{count}} riga/righe saltata/e (vuota/e o illeggibile/i)",
        "stats_currency": "Valuta",
        "stats_format": "Formato",
        "stats_positions": "Voci",
        "stats_sections": "Capitoli",
        "title": "Anteprima importazione",
        "truncated": "... e altre {{count}} voce/voci",
        "upload_hint": "Scegliere un file per l'anteprima prima di importarlo in questo computo metrico.",
        "warnings_title": "{{count}} avviso/i",
    },
    "ja": {
        "back": "戻る",
        "cancel": "キャンセル",
        "col_description": "項目名",
        "col_ordinal": "番号 / コード",
        "col_quantity": "数量",
        "col_total": "合計",
        "col_unit": "単位",
        "col_unit_rate": "単価",
        "confirm_button": "インポート",
        "confirm_summary": "{{format}} から {{currency}} 建てで {{positions}} 項目（{{sections}} 章）をインポートしますか？",
        "confirm_warnings": "解析中に {{count}} 件の警告が検出されました。インポートを続行します。",
        "continue": "続行",
        "drop_hint": "GAEB XML、Excel、PDF または CSV",
        "drop_zone": "ここにファイルをドロップするか、クリックして参照",
        "errors_title": "{{count}} 件のエラー",
        "import_success": "{{count}} 項目をインポートしました",
        "import_timeout": "サーバーが 90 秒以内に応答しませんでした。",
        "parse_timeout": "サーバーが 90 秒以内に応答しませんでした。ファイルが大きすぎる可能性があります。",
        "parsing": "ファイルを解析中...",
        "skipped_count": "{{count}} 行をスキップしました（空白または読み取り不可）",
        "stats_currency": "通貨",
        "stats_format": "フォーマット",
        "stats_positions": "項目数",
        "stats_sections": "章数",
        "title": "インポートプレビュー",
        "truncated": "... 他 {{count}} 項目",
        "upload_hint": "この工事費内訳書にインポートする前にファイルを選択してプレビューしてください。",
        "warnings_title": "{{count}} 件の警告",
    },
    "kk": {
        "back": "Артқа",
        "cancel": "Болдырмау",
        "col_description": "Сипаттама",
        "col_ordinal": "Поз. / Код",
        "col_quantity": "Сан",
        "col_total": "Барлығы",
        "col_unit": "Бірлік",
        "col_unit_rate": "Бірлік бағасы",
        "confirm_button": "Импорттау",
        "confirm_summary": "{{positions}} позицияны ({{sections}} бөлім) {{currency}} валютасымен {{format}} форматынан импорттау?",
        "confirm_warnings": "Талдау кезінде {{count}} ескерту анықталды. Импорт жалғасады.",
        "continue": "Жалғастыру",
        "drop_hint": "GAEB XML, Excel, PDF немесе CSV",
        "drop_zone": "Файлды осында сүйреңіз немесе шолу үшін басыңыз",
        "errors_title": "{{count}} қате",
        "import_success": "{{count}} позиция импортталды",
        "import_timeout": "Сервер 90 секунд ішінде жауап бермеді.",
        "parse_timeout": "Сервер 90 секунд ішінде жауап бермеді. Файл тым үлкен болуы мүмкін.",
        "parsing": "Файл талданып жатыр...",
        "skipped_count": "{{count}} жол өткізілді (бос немесе оқылмайды)",
        "stats_currency": "Валюта",
        "stats_format": "Формат",
        "stats_positions": "Позициялар",
        "stats_sections": "Бөлімдер",
        "title": "Импорт алдын ала қарау",
        "truncated": "... және тағы {{count}} позиция",
        "upload_hint": "Осы сметаға импорттамас бұрын алдын ала қарау үшін файл таңдаңыз.",
        "warnings_title": "{{count}} ескерту",
    },
    "ko": {
        "back": "뒤로",
        "cancel": "취소",
        "col_description": "항목명",
        "col_ordinal": "번호 / 코드",
        "col_quantity": "수량",
        "col_total": "합계",
        "col_unit": "단위",
        "col_unit_rate": "단가",
        "confirm_button": "가져오기",
        "confirm_summary": "{{format}}에서 {{currency}} 기준 {{positions}}개 항목({{sections}}개 장)을 가져오시겠습니까?",
        "confirm_warnings": "분석 중 {{count}}개의 경고가 발견되었습니다. 가져오기를 계속합니다.",
        "continue": "계속",
        "drop_hint": "GAEB XML, Excel, PDF 또는 CSV",
        "drop_zone": "여기에 파일을 놓거나 클릭하여 찾아보기",
        "errors_title": "{{count}}개 오류",
        "import_success": "{{count}}개 항목 가져오기 완료",
        "import_timeout": "서버가 90초 내에 응답하지 않았습니다.",
        "parse_timeout": "서버가 90초 내에 응답하지 않았습니다. 파일이 너무 클 수 있습니다.",
        "parsing": "파일 분석 중...",
        "skipped_count": "{{count}}개 행 건너뜀 (비어 있거나 읽을 수 없음)",
        "stats_currency": "통화",
        "stats_format": "형식",
        "stats_positions": "항목 수",
        "stats_sections": "장 수",
        "title": "가져오기 미리보기",
        "truncated": "... 외 {{count}}개 항목",
        "upload_hint": "이 BOQ로 가져오기 전에 미리 볼 파일을 선택하세요.",
        "warnings_title": "{{count}}개 경고",
    },
    "ky": {
        "back": "Артка",
        "cancel": "Жокко чыгаруу",
        "col_description": "Мүнөздөмө",
        "col_ordinal": "Поз. / Код",
        "col_quantity": "Сан",
        "col_total": "Жалпы",
        "col_unit": "Бирдик",
        "col_unit_rate": "Бирдик баасы",
        "confirm_button": "Импорттоо",
        "confirm_summary": "{{positions}} позицияны ({{sections}} бөлүм) {{currency}} валютасы менен {{format}} файлынан импорттоо?",
        "confirm_warnings": "Иштетүү учурунда {{count}} эскертүү табылды. Импорт уланат.",
        "continue": "Улантуу",
        "drop_hint": "GAEB XML, Excel, PDF же CSV",
        "drop_zone": "Файлды бул жерге таштаңыз же чалгын үчүн чыкылдатыңыз",
        "errors_title": "{{count}} ката",
        "import_success": "{{count}} позиция импортталды",
        "import_timeout": "Сервер 90 секунда ичинде жооп бербеди.",
        "parse_timeout": "Сервер 90 секунда ичинде жооп бербеди. Файл өтө чоң болушу мүмкүн.",
        "parsing": "Файл иштетилүүдө...",
        "skipped_count": "{{count}} саптар өткөрүп жиберилди (бош же окулбайт)",
        "stats_currency": "Валюта",
        "stats_format": "Формат",
        "stats_positions": "Позициялар",
        "stats_sections": "Бөлүмдөр",
        "title": "Импортту алдын ала кароо",
        "truncated": "... жана дагы {{count}} позиция",
        "upload_hint": "Бул сметага импорттоодон мурун алдын ала кароо үчүн файл тандаңыз.",
        "warnings_title": "{{count}} эскертүү",
    },
    "mn": {
        "back": "Буцах",
        "cancel": "Цуцлах",
        "col_description": "Тайлбар",
        "col_ordinal": "Поз. / Код",
        "col_quantity": "Тоо хэмжээ",
        "col_total": "Нийт",
        "col_unit": "Нэгж",
        "col_unit_rate": "Нэгжийн үнэ",
        "confirm_button": "Импортлох",
        "confirm_summary": "{{format}} файлаас {{currency}} валютаар {{positions}} ажлын нэр ({{sections}} хэсэг) импортлох уу?",
        "confirm_warnings": "Боловсруулалтын явцад {{count}} анхааруулга илэрсэн. Импортлолт үргэлжилнэ.",
        "continue": "Үргэлжлүүлэх",
        "drop_hint": "GAEB XML, Excel, PDF эсвэл CSV",
        "drop_zone": "Файлыг энд чирж оруулах эсвэл хайхын тулд дарна уу",
        "errors_title": "{{count}} алдаа",
        "import_success": "{{count}} ажлын нэр импортлогдлоо",
        "import_timeout": "Сервер 90 секундын дотор хариу өгсөнгүй.",
        "parse_timeout": "Сервер 90 секундын дотор хариу өгсөнгүй. Файл хэт том байж болзошгүй.",
        "parsing": "Файл боловсруулж байна...",
        "skipped_count": "{{count}} мөр алгасав (хоосон эсвэл унших боломжгүй)",
        "stats_currency": "Валют",
        "stats_format": "Формат",
        "stats_positions": "Ажлын нэрс",
        "stats_sections": "Хэсгүүд",
        "title": "Импортын урьдчилан харах",
        "truncated": "... болон {{count}} ажлын нэр дэлгэрэнгүй",
        "upload_hint": "Энэ тооцооны жагсаалтад импортлохын өмнө урьдчилан харах файл сонгоно уу.",
        "warnings_title": "{{count}} анхааруулга",
    },
    "nl": {
        "back": "Terug",
        "cancel": "Annuleren",
        "col_description": "Omschrijving",
        "col_ordinal": "Pos. / Code",
        "col_quantity": "Hoeveelh.",
        "col_total": "Totaal",
        "col_unit": "Eenheid",
        "col_unit_rate": "Eenheidsprijs",
        "confirm_button": "Importeren",
        "confirm_summary": "{{positions}} posten ({{sections}} hoofdstukken) in {{currency}} importeren vanuit {{format}}?",
        "confirm_warnings": "Er zijn {{count}} waarschuwing(en) gevonden tijdens het verwerken. De import wordt voortgezet.",
        "continue": "Doorgaan",
        "drop_hint": "GAEB XML, Excel, PDF of CSV",
        "drop_zone": "Sleep bestand hierheen of klik om te bladeren",
        "errors_title": "{{count}} fout(en)",
        "import_success": "{{count}} posten geïmporteerd",
        "import_timeout": "De server reageerde niet binnen 90 seconden.",
        "parse_timeout": "De server reageerde niet binnen 90 seconden. Het bestand is mogelijk te groot.",
        "parsing": "Bestand verwerken...",
        "skipped_count": "{{count}} rij(en) overgeslagen (leeg of onleesbaar)",
        "stats_currency": "Valuta",
        "stats_format": "Formaat",
        "stats_positions": "Posten",
        "stats_sections": "Hoofdstukken",
        "title": "Importvoorbeeld",
        "truncated": "... en {{count}} post(en) meer",
        "upload_hint": "Kies een bestand voor een voorbeeld voordat u het importeert in dit besteksboek.",
        "warnings_title": "{{count}} waarschuwing(en)",
    },
    "no": {
        "back": "Tilbake",
        "cancel": "Avbryt",
        "col_description": "Beskrivelse",
        "col_ordinal": "Pos. / Kode",
        "col_quantity": "Antall",
        "col_total": "Total",
        "col_unit": "Enhet",
        "col_unit_rate": "Enhetspris",
        "confirm_button": "Importer",
        "confirm_summary": "Importer {{positions}} poster ({{sections}} seksjoner) i {{currency}} fra {{format}}?",
        "confirm_warnings": "Det ble funnet {{count}} advarsel(er) under parsing. Importen vil fortsette.",
        "continue": "Fortsett",
        "drop_hint": "GAEB XML, Excel, PDF eller CSV",
        "drop_zone": "Slipp fil her eller klikk for å bla gjennom",
        "errors_title": "{{count}} feil",
        "import_success": "Importerte {{count}} poster",
        "import_timeout": "Serveren svarte ikke innen 90 sekunder.",
        "parse_timeout": "Serveren svarte ikke innen 90 sekunder. Filen kan være for stor.",
        "parsing": "Behandler fil...",
        "skipped_count": "{{count}} rad(er) hoppet over (tomme eller uleselige)",
        "stats_currency": "Valuta",
        "stats_format": "Format",
        "stats_positions": "Poster",
        "stats_sections": "Seksjoner",
        "title": "Forhåndsvisning av import",
        "truncated": "... og {{count}} post(er) til",
        "upload_hint": "Velg en fil for forhåndsvisning før import til denne mengdelisten.",
        "warnings_title": "{{count}} advarsel(er)",
    },
    "pl": {
        "back": "Wstecz",
        "cancel": "Anuluj",
        "col_description": "Opis",
        "col_ordinal": "Poz. / Kod",
        "col_quantity": "Ilość",
        "col_total": "Razem",
        "col_unit": "J.m.",
        "col_unit_rate": "Cena jedn.",
        "confirm_button": "Importuj",
        "confirm_summary": "Importować {{positions}} pozycji ({{sections}} rozdziałów) w {{currency}} z {{format}}?",
        "confirm_warnings": "Podczas przetwarzania wykryto {{count}} ostrzeżenie(ń). Import zostanie wykonany.",
        "continue": "Kontynuuj",
        "drop_hint": "GAEB XML, Excel, PDF lub CSV",
        "drop_zone": "Upuść plik tutaj lub kliknij, aby przeglądać",
        "errors_title": "{{count}} błąd(ów)",
        "import_success": "Zaimportowano {{count}} pozycji",
        "import_timeout": "Serwer nie odpowiedział w ciągu 90 sekund.",
        "parse_timeout": "Serwer nie odpowiedział w ciągu 90 sekund. Plik może być za duży.",
        "parsing": "Przetwarzanie pliku...",
        "skipped_count": "{{count}} wiersz(y) pominięto (puste lub nieczytelne)",
        "stats_currency": "Waluta",
        "stats_format": "Format",
        "stats_positions": "Pozycje",
        "stats_sections": "Rozdziały",
        "title": "Podgląd importu",
        "truncated": "... i {{count}} pozycja/e więcej",
        "upload_hint": "Wybierz plik do podglądu przed importem do tego przedmiaru robót.",
        "warnings_title": "{{count}} ostrzeżenie(ń)",
    },
    "pt": {
        "back": "Voltar",
        "cancel": "Cancelar",
        "col_description": "Descrição",
        "col_ordinal": "Pos. / Código",
        "col_quantity": "Qtd.",
        "col_total": "Total",
        "col_unit": "Unidade",
        "col_unit_rate": "Preço unit.",
        "confirm_button": "Importar",
        "confirm_summary": "Importar {{positions}} rubricas ({{sections}} capítulos) em {{currency}} de {{format}}?",
        "confirm_warnings": "Foram detetados {{count}} aviso(s) durante a análise. A importação prosseguirá.",
        "continue": "Continuar",
        "drop_hint": "GAEB XML, Excel, PDF ou CSV",
        "drop_zone": "Largue o ficheiro aqui ou clique para procurar",
        "errors_title": "{{count}} erro(s)",
        "import_success": "{{count}} rubricas importadas",
        "import_timeout": "O servidor não respondeu em 90 segundos.",
        "parse_timeout": "O servidor não respondeu em 90 segundos. O ficheiro pode ser demasiado grande.",
        "parsing": "A processar ficheiro...",
        "skipped_count": "{{count}} linha(s) ignorada(s) (vazia(s) ou ilegível/eis)",
        "stats_currency": "Moeda",
        "stats_format": "Formato",
        "stats_positions": "Rubricas",
        "stats_sections": "Capítulos",
        "title": "Pré-visualização da importação",
        "truncated": "... e mais {{count}} rubrica(s)",
        "upload_hint": "Escolha um ficheiro para pré-visualizar antes de importar para este mapa de quantidades.",
        "warnings_title": "{{count}} aviso(s)",
    },
    "pt-BR": {
        "back": "Voltar",
        "cancel": "Cancelar",
        "col_description": "Descrição",
        "col_ordinal": "Pos. / Código",
        "col_quantity": "Qtd.",
        "col_total": "Total",
        "col_unit": "Unidade",
        "col_unit_rate": "Preço unit.",
        "confirm_button": "Importar",
        "confirm_summary": "Importar {{positions}} itens ({{sections}} capítulos) em {{currency}} de {{format}}?",
        "confirm_warnings": "Foram detectados {{count}} aviso(s) durante a análise. A importação prosseguirá.",
        "continue": "Continuar",
        "drop_hint": "GAEB XML, Excel, PDF ou CSV",
        "drop_zone": "Solte o arquivo aqui ou clique para procurar",
        "errors_title": "{{count}} erro(s)",
        "import_success": "{{count}} itens importados",
        "import_timeout": "O servidor não respondeu em 90 segundos.",
        "parse_timeout": "O servidor não respondeu em 90 segundos. O arquivo pode ser muito grande.",
        "parsing": "Processando arquivo...",
        "skipped_count": "{{count}} linha(s) ignorada(s) (vazia(s) ou ilegível/eis)",
        "stats_currency": "Moeda",
        "stats_format": "Formato",
        "stats_positions": "Itens",
        "stats_sections": "Capítulos",
        "title": "Pré-visualização da importação",
        "truncated": "... e mais {{count}} item(ns)",
        "upload_hint": "Escolha um arquivo para pré-visualizar antes de importar para este orçamento.",
        "warnings_title": "{{count}} aviso(s)",
    },
    "ro": {
        "back": "Înapoi",
        "cancel": "Anulare",
        "col_description": "Descriere",
        "col_ordinal": "Poz. / Cod",
        "col_quantity": "Cant.",
        "col_total": "Total",
        "col_unit": "U.M.",
        "col_unit_rate": "Preț unitar",
        "confirm_button": "Importare",
        "confirm_summary": "Importare {{positions}} articole ({{sections}} capitole) în {{currency}} din {{format}}?",
        "confirm_warnings": "Au fost detectate {{count}} avertisment(e) în timpul analizei. Importul va continua.",
        "continue": "Continuare",
        "drop_hint": "GAEB XML, Excel, PDF sau CSV",
        "drop_zone": "Trageți fișierul aici sau faceți clic pentru a căuta",
        "errors_title": "{{count}} eroare/erori",
        "import_success": "{{count}} articole importate",
        "import_timeout": "Serverul nu a răspuns în 90 de secunde.",
        "parse_timeout": "Serverul nu a răspuns în 90 de secunde. Fișierul poate fi prea mare.",
        "parsing": "Se procesează fișierul...",
        "skipped_count": "{{count}} rând(uri) omis(e) (gol(e) sau ilizibil(e))",
        "stats_currency": "Monedă",
        "stats_format": "Format",
        "stats_positions": "Articole",
        "stats_sections": "Capitole",
        "title": "Previzualizare import",
        "truncated": "... și alte {{count}} articol(e)",
        "upload_hint": "Alegeți un fișier pentru previzualizare înainte de a-l importa în acest deviz.",
        "warnings_title": "{{count}} avertisment(e)",
    },
    "ru": {
        "back": "Назад",
        "cancel": "Отмена",
        "col_description": "Наименование",
        "col_ordinal": "Поз. / Код",
        "col_quantity": "Кол-во",
        "col_total": "Сумма",
        "col_unit": "Ед. изм.",
        "col_unit_rate": "Расценка",
        "confirm_button": "Импортировать",
        "confirm_summary": "Импортировать {{positions}} позиций ({{sections}} разделов) в {{currency}} из {{format}}?",
        "confirm_warnings": "При разборе обнаружено {{count}} предупреждение(-й). Импорт будет выполнен.",
        "continue": "Далее",
        "drop_hint": "GAEB XML, Excel, PDF или CSV",
        "drop_zone": "Перетащите файл сюда или нажмите для выбора",
        "errors_title": "{{count}} ошибка(-ок)",
        "import_success": "Импортировано {{count}} позиций",
        "import_timeout": "Сервер не ответил за 90 секунд.",
        "parse_timeout": "Сервер не ответил за 90 секунд. Возможно, файл слишком большой.",
        "parsing": "Разбор файла...",
        "skipped_count": "{{count}} строк(-а) пропущено (пустые или нечитаемые)",
        "stats_currency": "Валюта",
        "stats_format": "Формат",
        "stats_positions": "Позиции",
        "stats_sections": "Разделы",
        "title": "Предварительный просмотр импорта",
        "truncated": "... и ещё {{count}} позиция(-й)",
        "upload_hint": "Выберите файл для предварительного просмотра перед импортом в эту смету.",
        "warnings_title": "{{count}} предупреждение(-й)",
    },
    "sv": {
        "back": "Tillbaka",
        "cancel": "Avbryt",
        "col_description": "Beskrivning",
        "col_ordinal": "Pos. / Kod",
        "col_quantity": "Antal",
        "col_total": "Totalt",
        "col_unit": "Enhet",
        "col_unit_rate": "Enhetspris",
        "confirm_button": "Importera",
        "confirm_summary": "Importera {{positions}} poster ({{sections}} avsnitt) i {{currency}} från {{format}}?",
        "confirm_warnings": "{{count}} varning(ar) hittades vid tolkning. Importen fortsätter.",
        "continue": "Fortsätt",
        "drop_hint": "GAEB XML, Excel, PDF eller CSV",
        "drop_zone": "Släpp fil här eller klicka för att bläddra",
        "errors_title": "{{count}} fel",
        "import_success": "Importerade {{count}} poster",
        "import_timeout": "Servern svarade inte inom 90 sekunder.",
        "parse_timeout": "Servern svarade inte inom 90 sekunder. Filen kan vara för stor.",
        "parsing": "Bearbetar fil...",
        "skipped_count": "{{count}} rad(er) hoppades över (tomma eller oläsliga)",
        "stats_currency": "Valuta",
        "stats_format": "Format",
        "stats_positions": "Poster",
        "stats_sections": "Avsnitt",
        "title": "Importförhandsgranskning",
        "truncated": "... och {{count}} post(er) till",
        "upload_hint": "Välj en fil för förhandsgranskning innan import till denna mängdförteckning.",
        "warnings_title": "{{count}} varning(ar)",
    },
    "th": {
        "back": "ย้อนกลับ",
        "cancel": "ยกเลิก",
        "col_description": "รายละเอียด",
        "col_ordinal": "รายการ / รหัส",
        "col_quantity": "จำนวน",
        "col_total": "รวม",
        "col_unit": "หน่วย",
        "col_unit_rate": "ราคาต่อหน่วย",
        "confirm_button": "นำเข้า",
        "confirm_summary": "นำเข้า {{positions}} รายการ ({{sections}} หมวด) ในสกุลเงิน {{currency}} จาก {{format}}?",
        "confirm_warnings": "พบ {{count}} คำเตือนระหว่างการประมวลผล การนำเข้าจะดำเนินต่อไป",
        "continue": "ดำเนินการต่อ",
        "drop_hint": "GAEB XML, Excel, PDF หรือ CSV",
        "drop_zone": "วางไฟล์ที่นี่ หรือคลิกเพื่อเรียกดู",
        "errors_title": "{{count}} ข้อผิดพลาด",
        "import_success": "นำเข้า {{count}} รายการสำเร็จ",
        "import_timeout": "เซิร์ฟเวอร์ไม่ตอบสนองภายใน 90 วินาที",
        "parse_timeout": "เซิร์ฟเวอร์ไม่ตอบสนองภายใน 90 วินาที ไฟล์อาจมีขนาดใหญ่เกินไป",
        "parsing": "กำลังประมวลผลไฟล์...",
        "skipped_count": "ข้ามไป {{count}} แถว (ว่างเปล่าหรืออ่านไม่ได้)",
        "stats_currency": "สกุลเงิน",
        "stats_format": "รูปแบบ",
        "stats_positions": "รายการ",
        "stats_sections": "หมวด",
        "title": "ตัวอย่างก่อนนำเข้า",
        "truncated": "... และอีก {{count}} รายการ",
        "upload_hint": "เลือกไฟล์เพื่อดูตัวอย่างก่อนนำเข้าสู่ BOQ นี้",
        "warnings_title": "{{count}} คำเตือน",
    },
    "tr": {
        "back": "Geri",
        "cancel": "İptal",
        "col_description": "Açıklama",
        "col_ordinal": "Pos. / Kod",
        "col_quantity": "Miktar",
        "col_total": "Toplam",
        "col_unit": "Birim",
        "col_unit_rate": "Birim fiyat",
        "confirm_button": "İçe aktar",
        "confirm_summary": "{{format}} dosyasından {{currency}} cinsinden {{positions}} poz ({{sections}} bölüm) içe aktarılsın mı?",
        "confirm_warnings": "Ayrıştırma sırasında {{count}} uyarı tespit edildi. İçe aktarma devam edecek.",
        "continue": "Devam",
        "drop_hint": "GAEB XML, Excel, PDF veya CSV",
        "drop_zone": "Dosyayı buraya bırakın veya göz atmak için tıklayın",
        "errors_title": "{{count}} hata",
        "import_success": "{{count}} poz içe aktarıldı",
        "import_timeout": "Sunucu 90 saniye içinde yanıt vermedi.",
        "parse_timeout": "Sunucu 90 saniye içinde yanıt vermedi. Dosya çok büyük olabilir.",
        "parsing": "Dosya işleniyor...",
        "skipped_count": "{{count}} satır atlandı (boş veya okunamaz)",
        "stats_currency": "Para birimi",
        "stats_format": "Format",
        "stats_positions": "Pozlar",
        "stats_sections": "Bölümler",
        "title": "İçe aktarma önizlemesi",
        "truncated": "... ve {{count}} poz daha",
        "upload_hint": "Bu metrajlara aktarmadan önce önizlemek için bir dosya seçin.",
        "warnings_title": "{{count}} uyarı",
    },
    "uk": {
        "back": "Назад",
        "cancel": "Скасувати",
        "col_description": "Найменування",
        "col_ordinal": "Поз. / Код",
        "col_quantity": "К-сть",
        "col_total": "Сума",
        "col_unit": "Од. вим.",
        "col_unit_rate": "Розцінка",
        "confirm_button": "Імпортувати",
        "confirm_summary": "Імпортувати {{positions}} позицій ({{sections}} розділів) у {{currency}} з {{format}}?",
        "confirm_warnings": "Під час розбору виявлено {{count}} попередження(-нь). Імпорт буде виконано.",
        "continue": "Далі",
        "drop_hint": "GAEB XML, Excel, PDF або CSV",
        "drop_zone": "Перетягніть файл сюди або натисніть для вибору",
        "errors_title": "{{count}} помилка(-ок)",
        "import_success": "Імпортовано {{count}} позицій",
        "import_timeout": "Сервер не відповів протягом 90 секунд.",
        "parse_timeout": "Сервер не відповів протягом 90 секунд. Можливо, файл занадто великий.",
        "parsing": "Розбір файлу...",
        "skipped_count": "{{count}} рядок(-ків) пропущено (порожні або нечитабельні)",
        "stats_currency": "Валюта",
        "stats_format": "Формат",
        "stats_positions": "Позиції",
        "stats_sections": "Розділи",
        "title": "Попередній перегляд імпорту",
        "truncated": "... і ще {{count}} позиція(-й)",
        "upload_hint": "Виберіть файл для попереднього перегляду перед імпортом до цього кошторису.",
        "warnings_title": "{{count}} попередження(-нь)",
    },
    "ur": {
        "back": "واپس",
        "cancel": "منسوخ",
        "col_description": "تفصیل",
        "col_ordinal": "آئٹم / کوڈ",
        "col_quantity": "مقدار",
        "col_total": "کل",
        "col_unit": "اکائی",
        "col_unit_rate": "اکائی قیمت",
        "confirm_button": "درآمد کریں",
        "confirm_summary": "{{format}} سے {{currency}} میں {{positions}} آئٹم ({{sections}} حصے) درآمد کریں؟",
        "confirm_warnings": "پارسنگ کے دوران {{count}} انتباہ ملے۔ درآمد جاری رہے گی۔",
        "continue": "جاری رکھیں",
        "drop_hint": "GAEB XML, Excel, PDF یا CSV",
        "drop_zone": "فائل یہاں چھوڑیں یا براؤز کرنے کے لیے کلک کریں",
        "errors_title": "{{count}} خرابی",
        "import_success": "{{count}} آئٹم درآمد ہوئے",
        "import_timeout": "سرور نے 90 سیکنڈ میں جواب نہیں دیا۔",
        "parse_timeout": "سرور نے 90 سیکنڈ میں جواب نہیں دیا۔ فائل بہت بڑی ہو سکتی ہے۔",
        "parsing": "فائل پروسیس ہو رہی ہے...",
        "skipped_count": "{{count}} قطاریں چھوڑ دی گئیں (خالی یا ناقابل پڑھ)",
        "stats_currency": "کرنسی",
        "stats_format": "فارمیٹ",
        "stats_positions": "آئٹم",
        "stats_sections": "حصے",
        "title": "درآمد پیش نظارہ",
        "truncated": "... اور {{count}} مزید آئٹم",
        "upload_hint": "اس BOQ میں درآمد سے پہلے پیش نظارہ کے لیے ایک فائل منتخب کریں۔",
        "warnings_title": "{{count}} انتباہ",
    },
    "uz": {
        "back": "Orqaga",
        "cancel": "Bekor qilish",
        "col_description": "Tavsif",
        "col_ordinal": "Pos. / Kod",
        "col_quantity": "Miqdor",
        "col_total": "Jami",
        "col_unit": "O'lchov birligi",
        "col_unit_rate": "Birlik narxi",
        "confirm_button": "Import qilish",
        "confirm_summary": "{{format}} faylidan {{currency}} valyutasida {{positions}} ta pozitsiya ({{sections}} ta bo'lim) import qilinsinmi?",
        "confirm_warnings": "Tahlil davomida {{count}} ta ogohlantirish aniqlandi. Import davom etadi.",
        "continue": "Davom etish",
        "drop_hint": "GAEB XML, Excel, PDF yoki CSV",
        "drop_zone": "Faylni shu yerga tashlang yoki ko'rish uchun bosing",
        "errors_title": "{{count}} ta xato",
        "import_success": "{{count}} ta pozitsiya import qilindi",
        "import_timeout": "Server 90 soniya ichida javob bermadi.",
        "parse_timeout": "Server 90 soniya ichida javob bermadi. Fayl juda katta bo'lishi mumkin.",
        "parsing": "Fayl tahlil qilinmoqda...",
        "skipped_count": "{{count}} ta qator o'tkazib yuborildi (bo'sh yoki o'qib bo'lmaydi)",
        "stats_currency": "Valyuta",
        "stats_format": "Format",
        "stats_positions": "Pozitsiyalar",
        "stats_sections": "Bo'limlar",
        "title": "Import oldindan ko'rish",
        "truncated": "... va yana {{count}} ta pozitsiya",
        "upload_hint": "Ushbu smeta jadvaliga import qilishdan oldin oldindan ko'rish uchun fayl tanlang.",
        "warnings_title": "{{count}} ta ogohlantirish",
    },
    "vi": {
        "back": "Quay lại",
        "cancel": "Hủy",
        "col_description": "Mô tả",
        "col_ordinal": "Mục / Mã",
        "col_quantity": "Khối lượng",
        "col_total": "Thành tiền",
        "col_unit": "Đơn vị",
        "col_unit_rate": "Đơn giá",
        "confirm_button": "Nhập khẩu",
        "confirm_summary": "Nhập {{positions}} hạng mục ({{sections}} chương) bằng {{currency}} từ {{format}}?",
        "confirm_warnings": "Phát hiện {{count}} cảnh báo khi phân tích. Quá trình nhập khẩu sẽ tiếp tục.",
        "continue": "Tiếp tục",
        "drop_hint": "GAEB XML, Excel, PDF hoặc CSV",
        "drop_zone": "Thả tệp vào đây hoặc nhấp để duyệt",
        "errors_title": "{{count}} lỗi",
        "import_success": "Đã nhập {{count}} hạng mục",
        "import_timeout": "Máy chủ không phản hồi trong vòng 90 giây.",
        "parse_timeout": "Máy chủ không phản hồi trong vòng 90 giây. Tệp có thể quá lớn.",
        "parsing": "Đang phân tích tệp...",
        "skipped_count": "{{count}} hàng bị bỏ qua (trống hoặc không đọc được)",
        "stats_currency": "Tiền tệ",
        "stats_format": "Định dạng",
        "stats_positions": "Hạng mục",
        "stats_sections": "Chương",
        "title": "Xem trước nhập khẩu",
        "truncated": "... và {{count}} hạng mục khác",
        "upload_hint": "Chọn tệp để xem trước trước khi nhập vào dự toán này.",
        "warnings_title": "{{count}} cảnh báo",
    },
    "zh": {
        "back": "返回",
        "cancel": "取消",
        "col_description": "项目名称",
        "col_ordinal": "序号 / 编码",
        "col_quantity": "工程量",
        "col_total": "合价",
        "col_unit": "单位",
        "col_unit_rate": "综合单价",
        "confirm_button": "导入",
        "confirm_summary": "从 {{format}} 导入 {{positions}} 个清单项（{{sections}} 个章节），货币为 {{currency}}？",
        "confirm_warnings": "解析过程中发现 {{count}} 条警告，导入将继续执行。",
        "continue": "继续",
        "drop_hint": "GAEB XML、Excel、PDF 或 CSV",
        "drop_zone": "将文件拖放到此处，或点击浏览",
        "errors_title": "{{count}} 个错误",
        "import_success": "已导入 {{count}} 个清单项",
        "import_timeout": "服务器未在 90 秒内响应。",
        "parse_timeout": "服务器未在 90 秒内响应，文件可能过大。",
        "parsing": "正在解析文件...",
        "skipped_count": "已跳过 {{count}} 行（空行或无法读取）",
        "stats_currency": "货币",
        "stats_format": "格式",
        "stats_positions": "清单项数",
        "stats_sections": "章节数",
        "title": "导入预览",
        "truncated": "…以及另外 {{count}} 个清单项",
        "upload_hint": "请选择文件进行预览，再导入到本工程量清单。",
        "warnings_title": "{{count}} 条警告",
    },
    "en-GB": {
        "back": "Back",
        "cancel": "Cancel",
        "col_description": "Description",
        "col_ordinal": "Pos. / Code",
        "col_quantity": "Qty",
        "col_total": "Total",
        "col_unit": "Unit",
        "col_unit_rate": "Unit Rate",
        "confirm_button": "Import",
        "confirm_summary": "Import {{positions}} positions ({{sections}} sections) in {{currency}} from {{format}}?",
        "confirm_warnings": "{{count}} warning(s) were detected during parsing. The import will proceed.",
        "continue": "Continue",
        "drop_hint": "GAEB XML, Excel, PDF or CSV",
        "drop_zone": "Drop file here or click to browse",
        "errors_title": "{{count}} error(s)",
        "import_success": "Imported {{count}} positions",
        "import_timeout": "Server did not respond within 90 seconds.",
        "parse_timeout": "Server did not respond within 90 seconds. The file may be too large.",
        "parsing": "Parsing file...",
        "skipped_count": "{{count}} row(s) skipped (empty or unreadable)",
        "stats_currency": "Currency",
        "stats_format": "Format",
        "stats_positions": "Positions",
        "stats_sections": "Sections",
        "title": "Import preview",
        "truncated": "... and {{count}} more position(s)",
        "upload_hint": "Choose a file to preview before importing into this BOQ.",
        "warnings_title": "{{count}} warning(s)",
    },
}

KEY_SUFFIXES = list(EN_KEYS.keys())
# Remove the "boq.import_preview." prefix for lookup in TRANSLATIONS dict
SUFFIX_MAP = {k: k.replace("boq.import_preview.", "") for k in KEY_SUFFIXES}

def validate_tokens(locale, suffix, value):
    full_key = f"boq.import_preview.{suffix}"
    en_value = EN_KEYS[full_key]
    en_tokens = get_tokens(en_value)
    tr_tokens = get_tokens(value)
    if en_tokens != tr_tokens:
        print(f"  TOKEN MISMATCH [{locale}] {full_key}: EN={en_tokens} TR={tr_tokens}", file=sys.stderr)
        return False
    return True

def build_block(locale, trans):
    lines = []
    ok = True
    for full_key, suffix in SUFFIX_MAP.items():
        value = trans.get(suffix)
        if value is None:
            print(f"  MISSING KEY [{locale}] {suffix}", file=sys.stderr)
            ok = False
            continue
        if not validate_tokens(locale, suffix, value):
            ok = False
        # Escape double-quotes in value
        escaped = value.replace('"', '\\"')
        lines.append(f'    "{full_key}": "{escaped}",')
    return "\n".join(lines), ok

def process_locale(locale):
    filepath = LOCALES_DIR / f"{locale}.ts"
    if not filepath.exists():
        print(f"  FILE NOT FOUND: {filepath}", file=sys.stderr)
        return False

    trans = TRANSLATIONS.get(locale)
    if trans is None:
        print(f"  NO TRANSLATIONS DEFINED for locale: {locale}", file=sys.stderr)
        return False

    content = filepath.read_text(encoding="utf-8")

    # Check if already has these keys
    if '"boq.import_preview.back"' in content:
        print(f"  ALREADY HAS keys, skipping: {locale}")
        return True

    block, ok = build_block(locale, trans)
    if not ok:
        return False

    # Insertion point: just before the closing of the translation object
    # Pattern: the last occurrence of "\n  }\n} as { translation:"
    closing = "\n  }\n} as { translation: Record<string, string> };\n\nexport default resource;"
    if closing not in content:
        print(f"  CLOSING PATTERN NOT FOUND in {locale}.ts", file=sys.stderr)
        return False

    insertion = f"\n{block}{closing}"
    new_content = content.replace(closing, insertion, 1)

    filepath.write_text(new_content, encoding="utf-8")
    print(f"  OK: {locale} ({len(SUFFIX_MAP)} keys added)")
    return True

def main():
    locales = list(TRANSLATIONS.keys())
    print(f"Processing {len(locales)} locales...")
    errors = []
    for locale in locales:
        if not process_locale(locale):
            errors.append(locale)

    if errors:
        print(f"\nFAILED locales: {errors}", file=sys.stderr)
        sys.exit(1)
    else:
        print(f"\nDone. {len(locales)} locales updated.")

if __name__ == "__main__":
    main()
