#!/usr/bin/env python3
"""Insert 23 timeline keys after timeline.showing in all required locale files."""

import re
import sys
from pathlib import Path

LOCALES_DIR = Path(__file__).parent.parent / "frontend" / "src" / "app" / "locales"

# 23 keys, ordered as they appear in en.ts after timeline.showing
KEYS = [
    "timeline.total_events",
    "timeline.modules_active",
    "timeline.top_actions",
    "timeline.filters",
    "timeline.toggle_filters",
    "timeline.action_type",
    "timeline.all_actions",
    "timeline.since",
    "timeline.until",
    "timeline.apply_filters",
    "timeline.export_csv",
    "timeline.event_details",
    "timeline.detail_action",
    "timeline.detail_module",
    "timeline.detail_entity_type",
    "timeline.detail_entity_id",
    "timeline.detail_timestamp",
    "timeline.detail_actor",
    "timeline.detail_status_change",
    "timeline.detail_reason",
    "timeline.detail_metadata",
    "timeline.go_to_entity",
    "timeline.system",
]

# Translations per locale code.
# Order matches KEYS above.
TRANSLATIONS: dict[str, list[str]] = {
    "ar": [
        "إجمالي الأحداث",
        "الوحدات النشطة",
        "أبرز الإجراءات",
        "عوامل التصفية",
        "تبديل عوامل التصفية",
        "نوع الإجراء",
        "جميع الإجراءات",
        "من تاريخ",
        "إلى تاريخ",
        "تطبيق",
        "تصدير CSV",
        "تفاصيل الحدث",
        "الإجراء",
        "الوحدة",
        "نوع الكيان",
        "معرّف الكيان",
        "الطابع الزمني",
        "المنفّذ",
        "تغيير الحالة",
        "السبب",
        "البيانات الوصفية",
        "الانتقال إلى السجل",
        "النظام",
    ],
    "bg": [
        "Общо събития",
        "Активни модули",
        "Топ действия",
        "Филтри",
        "Превключване на филтри",
        "Тип действие",
        "Всички действия",
        "От дата",
        "До дата",
        "Приложи",
        "Експорт CSV",
        "Детайли на събитието",
        "Действие",
        "Модул",
        "Тип обект",
        "ID на обект",
        "Времева марка",
        "Изпълнител",
        "Промяна на статус",
        "Причина",
        "Метаданни",
        "Към записа",
        "Система",
    ],
    "bn": [
        "মোট ইভেন্ট",
        "সক্রিয় মডিউল",
        "শীর্ষ কার্যক্রম",
        "ফিল্টার",
        "ফিল্টার টগল করুন",
        "কার্যক্রমের ধরন",
        "সব কার্যক্রম",
        "শুরুর তারিখ",
        "শেষের তারিখ",
        "প্রয়োগ করুন",
        "CSV রপ্তানি",
        "ইভেন্টের বিবরণ",
        "কার্যক্রম",
        "মডিউল",
        "এন্টিটি ধরন",
        "এন্টিটি আইডি",
        "সময়চিহ্ন",
        "অভিনেতা",
        "স্ট্যাটাস পরিবর্তন",
        "কারণ",
        "মেটাডেটা",
        "রেকর্ডে যান",
        "সিস্টেম",
    ],
    "cs": [
        "Celkem událostí",
        "Aktivní moduly",
        "Nejčastější akce",
        "Filtry",
        "Přepnout filtry",
        "Typ akce",
        "Všechny akce",
        "Od data",
        "Do data",
        "Použít",
        "Exportovat CSV",
        "Detaily události",
        "Akce",
        "Modul",
        "Typ záznamu",
        "ID záznamu",
        "Časové razítko",
        "Provedl",
        "Změna stavu",
        "Důvod",
        "Metadata",
        "Přejít na záznam",
        "Systém",
    ],
    "da": [
        "Antal hændelser",
        "Aktive moduler",
        "Tophandlinger",
        "Filtre",
        "Slå filtre til/fra",
        "Handlingstype",
        "Alle handlinger",
        "Fra dato",
        "Til dato",
        "Anvend",
        "Eksporter CSV",
        "Hændelsesdetaljer",
        "Handling",
        "Modul",
        "Objekttype",
        "Objekt-id",
        "Tidsstempel",
        "Aktør",
        "Statusændring",
        "Årsag",
        "Metadata",
        "Gå til post",
        "System",
    ],
    "de": [
        "Ereignisse gesamt",
        "Aktive Module",
        "Top-Aktionen",
        "Filter",
        "Filter einblenden",
        "Aktionstyp",
        "Alle Aktionen",
        "Ab Datum",
        "Bis Datum",
        "Anwenden",
        "CSV exportieren",
        "Ereignisdetails",
        "Aktion",
        "Modul",
        "Objekttyp",
        "Objekt-ID",
        "Zeitstempel",
        "Ausführender",
        "Statusänderung",
        "Grund",
        "Metadaten",
        "Zum Datensatz",
        "System",
    ],
    "el": [
        "Σύνολο συμβάντων",
        "Ενεργά τμήματα",
        "Κορυφαίες ενέργειες",
        "Φίλτρα",
        "Εναλλαγή φίλτρων",
        "Τύπος ενέργειας",
        "Όλες οι ενέργειες",
        "Από ημερομηνία",
        "Έως ημερομηνία",
        "Εφαρμογή",
        "Εξαγωγή CSV",
        "Λεπτομέρειες συμβάντος",
        "Ενέργεια",
        "Τμήμα",
        "Τύπος εγγραφής",
        "ID εγγραφής",
        "Χρονική σφραγίδα",
        "Εκτελεστής",
        "Αλλαγή κατάστασης",
        "Λόγος",
        "Μεταδεδομένα",
        "Μετάβαση στην εγγραφή",
        "Σύστημα",
    ],
    "es": [
        "Total de eventos",
        "Módulos activos",
        "Acciones principales",
        "Filtros",
        "Mostrar u ocultar filtros",
        "Tipo de acción",
        "Todas las acciones",
        "Desde fecha",
        "Hasta fecha",
        "Aplicar",
        "Exportar CSV",
        "Detalles del evento",
        "Acción",
        "Módulo",
        "Tipo de registro",
        "ID de registro",
        "Marca de tiempo",
        "Ejecutor",
        "Cambio de estado",
        "Motivo",
        "Metadatos",
        "Ir al registro",
        "Sistema",
    ],
    "es-CL": [
        "Total de eventos",
        "Módulos activos",
        "Acciones principales",
        "Filtros",
        "Mostrar u ocultar filtros",
        "Tipo de acción",
        "Todas las acciones",
        "Desde fecha",
        "Hasta fecha",
        "Aplicar",
        "Exportar CSV",
        "Detalles del evento",
        "Acción",
        "Módulo",
        "Tipo de registro",
        "ID de registro",
        "Marca de tiempo",
        "Ejecutor",
        "Cambio de estado",
        "Motivo",
        "Metadatos",
        "Ir al registro",
        "Sistema",
    ],
    "es-CO": [
        "Total de eventos",
        "Módulos activos",
        "Acciones principales",
        "Filtros",
        "Mostrar u ocultar filtros",
        "Tipo de acción",
        "Todas las acciones",
        "Desde fecha",
        "Hasta fecha",
        "Aplicar",
        "Exportar CSV",
        "Detalles del evento",
        "Acción",
        "Módulo",
        "Tipo de registro",
        "ID de registro",
        "Marca de tiempo",
        "Ejecutor",
        "Cambio de estado",
        "Motivo",
        "Metadatos",
        "Ir al registro",
        "Sistema",
    ],
    "es-MX": [
        "Total de eventos",
        "Módulos activos",
        "Acciones principales",
        "Filtros",
        "Mostrar u ocultar filtros",
        "Tipo de acción",
        "Todas las acciones",
        "Desde fecha",
        "Hasta fecha",
        "Aplicar",
        "Exportar CSV",
        "Detalles del evento",
        "Acción",
        "Módulo",
        "Tipo de registro",
        "ID de registro",
        "Marca de tiempo",
        "Ejecutor",
        "Cambio de estado",
        "Motivo",
        "Metadatos",
        "Ir al registro",
        "Sistema",
    ],
    "et": [
        "Sündmusi kokku",
        "Aktiivsed moodulid",
        "Populaarseimad toimingud",
        "Filtrid",
        "Lülita filtrid",
        "Toimingu tüüp",
        "Kõik toimingud",
        "Alguskuupäev",
        "Lõppkuupäev",
        "Rakenda",
        "Ekspordi CSV",
        "Sündmuse üksikasjad",
        "Toiming",
        "Moodul",
        "Kirje tüüp",
        "Kirje ID",
        "Ajatempel",
        "Tegija",
        "Oleku muutus",
        "Põhjus",
        "Metaandmed",
        "Mine kirjele",
        "Süsteem",
    ],
    "fa": [
        "کل رویدادها",
        "ماژول‌های فعال",
        "برترین اقدامات",
        "فیلترها",
        "نمایش/پنهان فیلترها",
        "نوع اقدام",
        "همه اقدامات",
        "از تاریخ",
        "تا تاریخ",
        "اعمال",
        "خروجی CSV",
        "جزئیات رویداد",
        "اقدام",
        "ماژول",
        "نوع رکورد",
        "شناسه رکورد",
        "زمان‌نشان",
        "کاربر",
        "تغییر وضعیت",
        "دلیل",
        "فراداده",
        "رفتن به رکورد",
        "سیستم",
    ],
    "fi": [
        "Tapahtumia yhteensä",
        "Aktiiviset moduulit",
        "Suosituimmat toiminnot",
        "Suodattimet",
        "Näytä tai piilota suodattimet",
        "Toimintotyyppi",
        "Kaikki toiminnot",
        "Alkupäivä",
        "Loppupäivä",
        "Käytä",
        "Vie CSV",
        "Tapahtuman tiedot",
        "Toiminto",
        "Moduuli",
        "Tietueen tyyppi",
        "Tietueen tunnus",
        "Aikaleima",
        "Tekijä",
        "Tilamuutos",
        "Syy",
        "Metatiedot",
        "Siirry tietueeseen",
        "Järjestelmä",
    ],
    "fil": [
        "Kabuuang mga Kaganapan",
        "Mga Aktibong Module",
        "Nangungunang mga Aksyon",
        "Mga Filter",
        "I-toggle ang mga filter",
        "Uri ng Aksyon",
        "Lahat ng aksyon",
        "Mula sa Petsa",
        "Hanggang sa Petsa",
        "Ilapat",
        "I-export ang CSV",
        "Mga Detalye ng Kaganapan",
        "Aksyon",
        "Module",
        "Uri ng Record",
        "ID ng Record",
        "Timestamp",
        "Gumagawa",
        "Pagbabago ng Katayuan",
        "Dahilan",
        "Metadata",
        "Pumunta sa Record",
        "Sistema",
    ],
    "fr": [
        "Total des événements",
        "Modules actifs",
        "Principales actions",
        "Filtres",
        "Afficher ou masquer les filtres",
        "Type d'action",
        "Toutes les actions",
        "Depuis le",
        "Jusqu'au",
        "Appliquer",
        "Exporter CSV",
        "Détails de l'événement",
        "Action",
        "Module",
        "Type de fiche",
        "ID de la fiche",
        "Horodatage",
        "Intervenant",
        "Changement de statut",
        "Motif",
        "Métadonnées",
        "Aller à la fiche",
        "Système",
    ],
    "he": [
        "סך הכל אירועים",
        "מודולים פעילים",
        "פעולות מובילות",
        "מסננים",
        "הצג/הסתר מסננים",
        "סוג פעולה",
        "כל הפעולות",
        "מתאריך",
        "עד תאריך",
        "החל",
        "ייצוא CSV",
        "פרטי אירוע",
        "פעולה",
        "מודול",
        "סוג רשומה",
        "מזהה רשומה",
        "חותמת זמן",
        "מבצע",
        "שינוי סטטוס",
        "סיבה",
        "מטא-נתונים",
        "עבור לרשומה",
        "מערכת",
    ],
    "hi": [
        "कुल घटनाएँ",
        "सक्रिय मॉड्यूल",
        "शीर्ष क्रियाएँ",
        "फ़िल्टर",
        "फ़िल्टर चालू/बंद करें",
        "क्रिया प्रकार",
        "सभी क्रियाएँ",
        "प्रारंभ तिथि",
        "समाप्ति तिथि",
        "लागू करें",
        "CSV निर्यात करें",
        "घटना विवरण",
        "क्रिया",
        "मॉड्यूल",
        "रिकॉर्ड प्रकार",
        "रिकॉर्ड आईडी",
        "टाइमस्टैम्प",
        "निष्पादक",
        "स्थिति परिवर्तन",
        "कारण",
        "मेटाडेटा",
        "रिकॉर्ड पर जाएँ",
        "सिस्टम",
    ],
    "hr": [
        "Ukupno događaja",
        "Aktivni moduli",
        "Glavne radnje",
        "Filtri",
        "Prikaži/sakrij filtre",
        "Vrsta radnje",
        "Sve radnje",
        "Od datuma",
        "Do datuma",
        "Primijeni",
        "Izvezi CSV",
        "Detalji događaja",
        "Radnja",
        "Modul",
        "Vrsta zapisa",
        "ID zapisa",
        "Vremenski žig",
        "Izvršitelj",
        "Promjena statusa",
        "Razlog",
        "Metapodaci",
        "Idi na zapis",
        "Sustav",
    ],
    "hu": [
        "Összes esemény",
        "Aktív modulok",
        "Leggyakoribb műveletek",
        "Szűrők",
        "Szűrők be/ki",
        "Művelet típusa",
        "Összes művelet",
        "Kezdő dátum",
        "Záró dátum",
        "Alkalmaz",
        "CSV exportálása",
        "Esemény részletei",
        "Művelet",
        "Modul",
        "Rekord típusa",
        "Rekord azonosítója",
        "Időbélyeg",
        "Végrehajtó",
        "Állapotváltozás",
        "Ok",
        "Metaadatok",
        "Ugrás a rekordra",
        "Rendszer",
    ],
    "id": [
        "Total Peristiwa",
        "Modul Aktif",
        "Tindakan Utama",
        "Filter",
        "Tampilkan/sembunyikan filter",
        "Jenis Tindakan",
        "Semua tindakan",
        "Dari Tanggal",
        "Sampai Tanggal",
        "Terapkan",
        "Ekspor CSV",
        "Detail Peristiwa",
        "Tindakan",
        "Modul",
        "Jenis Rekam",
        "ID Rekam",
        "Cap Waktu",
        "Pelaksana",
        "Perubahan Status",
        "Alasan",
        "Metadata",
        "Ke Rekam",
        "Sistem",
    ],
    "it": [
        "Totale eventi",
        "Moduli attivi",
        "Azioni principali",
        "Filtri",
        "Mostra/nascondi filtri",
        "Tipo di azione",
        "Tutte le azioni",
        "Dal",
        "Al",
        "Applica",
        "Esporta CSV",
        "Dettagli evento",
        "Azione",
        "Modulo",
        "Tipo di voce",
        "ID voce",
        "Marca temporale",
        "Responsabile",
        "Cambio di stato",
        "Motivo",
        "Metadati",
        "Vai alla voce",
        "Sistema",
    ],
    "ja": [
        "総イベント数",
        "有効モジュール数",
        "主な操作",
        "フィルター",
        "フィルターの切替",
        "操作種別",
        "すべての操作",
        "開始日",
        "終了日",
        "適用",
        "CSVエクスポート",
        "イベント詳細",
        "操作",
        "モジュール",
        "レコード種別",
        "レコードID",
        "タイムスタンプ",
        "実行者",
        "ステータス変更",
        "理由",
        "メタデータ",
        "レコードへ移動",
        "システム",
    ],
    "kk": [
        "Барлық оқиғалар",
        "Белсенді модульдер",
        "Жиі орындалған әрекеттер",
        "Сүзгілер",
        "Сүзгілерді ашу/жабу",
        "Әрекет түрі",
        "Барлық әрекеттер",
        "Бастапқы күн",
        "Соңғы күн",
        "Қолдану",
        "CSV экспорты",
        "Оқиға мәліметтері",
        "Әрекет",
        "Модуль",
        "Жазба түрі",
        "Жазба идентификаторы",
        "Уақыт белгісі",
        "Орындаушы",
        "Күй өзгерісі",
        "Себеп",
        "Метадеректер",
        "Жазбаға өту",
        "Жүйе",
    ],
    "ko": [
        "전체 이벤트",
        "활성 모듈",
        "주요 작업",
        "필터",
        "필터 표시/숨기기",
        "작업 유형",
        "모든 작업",
        "시작 날짜",
        "종료 날짜",
        "적용",
        "CSV 내보내기",
        "이벤트 상세",
        "작업",
        "모듈",
        "레코드 유형",
        "레코드 ID",
        "타임스탬프",
        "실행자",
        "상태 변경",
        "사유",
        "메타데이터",
        "레코드로 이동",
        "시스템",
    ],
    "ky": [
        "Бардык окуялар",
        "Активдүү модулдар",
        "Эң көп аракеттер",
        "Чыпкалар",
        "Чыпкаларды ачуу/жабуу",
        "Аракет түрү",
        "Бардык аракеттер",
        "Баштоо датасы",
        "Аяктоо датасы",
        "Колдонуу",
        "CSV экспорту",
        "Окуянын чоо-жайы",
        "Аракет",
        "Модул",
        "Жазуу түрү",
        "Жазуунун идентификатору",
        "Убакыт белгиси",
        "Аткаруучу",
        "Абал өзгөрүүсү",
        "Себеп",
        "Метадеректер",
        "Жазууга өтүү",
        "Система",
    ],
    "mn": [
        "Нийт үйл явдал",
        "Идэвхтэй модулиуд",
        "Шилдэг үйлдлүүд",
        "Шүүлтүүр",
        "Шүүлтүүрийг нээх/хаах",
        "Үйлдлийн төрөл",
        "Бүх үйлдлүүд",
        "Эхлэх огноо",
        "Дуусах огноо",
        "Хэрэглэх",
        "CSV экспорт",
        "Үйл явдлын дэлгэрэнгүй",
        "Үйлдэл",
        "Модуль",
        "Бичлэгийн төрөл",
        "Бичлэгийн ID",
        "Цагийн тэмдэг",
        "Гүйцэтгэгч",
        "Төлвийн өөрчлөлт",
        "Шалтгаан",
        "Мета өгөгдөл",
        "Бичлэг рүү очих",
        "Систем",
    ],
    "nl": [
        "Totaal gebeurtenissen",
        "Actieve modules",
        "Meest voorkomende acties",
        "Filters",
        "Filters weergeven/verbergen",
        "Actietype",
        "Alle acties",
        "Vanaf datum",
        "Tot datum",
        "Toepassen",
        "CSV exporteren",
        "Gebeurtenisdetails",
        "Actie",
        "Module",
        "Recordtype",
        "Record-id",
        "Tijdstempel",
        "Uitvoerder",
        "Statuswijziging",
        "Reden",
        "Metadata",
        "Naar record",
        "Systeem",
    ],
    "no": [
        "Totalt antall hendelser",
        "Aktive moduler",
        "Vanligste handlinger",
        "Filtre",
        "Vis/skjul filtre",
        "Handlingstype",
        "Alle handlinger",
        "Fra dato",
        "Til dato",
        "Bruk",
        "Eksporter CSV",
        "Hendelsesdetaljer",
        "Handling",
        "Modul",
        "Oppføringstype",
        "Oppførings-id",
        "Tidsstempel",
        "Utfører",
        "Statusendring",
        "Årsak",
        "Metadata",
        "Gå til oppføring",
        "System",
    ],
    "pl": [
        "Łączna liczba zdarzeń",
        "Aktywne moduły",
        "Najczęstsze akcje",
        "Filtry",
        "Przełącz filtry",
        "Typ akcji",
        "Wszystkie akcje",
        "Od daty",
        "Do daty",
        "Zastosuj",
        "Eksportuj CSV",
        "Szczegóły zdarzenia",
        "Akcja",
        "Moduł",
        "Typ rekordu",
        "ID rekordu",
        "Znacznik czasu",
        "Wykonawca",
        "Zmiana statusu",
        "Powód",
        "Metadane",
        "Przejdź do rekordu",
        "System",
    ],
    "pt": [
        "Total de eventos",
        "Módulos ativos",
        "Principais ações",
        "Filtros",
        "Mostrar/ocultar filtros",
        "Tipo de ação",
        "Todas as ações",
        "Desde",
        "Até",
        "Aplicar",
        "Exportar CSV",
        "Detalhes do evento",
        "Ação",
        "Módulo",
        "Tipo de registo",
        "ID do registo",
        "Timestamp",
        "Responsável",
        "Mudança de estado",
        "Motivo",
        "Metadados",
        "Ir para o registo",
        "Sistema",
    ],
    "pt-BR": [
        "Total de eventos",
        "Módulos ativos",
        "Principais ações",
        "Filtros",
        "Mostrar/ocultar filtros",
        "Tipo de ação",
        "Todas as ações",
        "Desde",
        "Até",
        "Aplicar",
        "Exportar CSV",
        "Detalhes do evento",
        "Ação",
        "Módulo",
        "Tipo de registro",
        "ID do registro",
        "Timestamp",
        "Responsável",
        "Mudança de status",
        "Motivo",
        "Metadados",
        "Ir para o registro",
        "Sistema",
    ],
    "ro": [
        "Total evenimente",
        "Module active",
        "Acțiuni principale",
        "Filtre",
        "Arată/ascunde filtre",
        "Tip acțiune",
        "Toate acțiunile",
        "De la data",
        "Până la data",
        "Aplică",
        "Export CSV",
        "Detalii eveniment",
        "Acțiune",
        "Modul",
        "Tip înregistrare",
        "ID înregistrare",
        "Marcaj de timp",
        "Executor",
        "Schimbare de stare",
        "Motiv",
        "Metadate",
        "Mergi la înregistrare",
        "Sistem",
    ],
    "ru": [
        "Всего событий",
        "Активные модули",
        "Популярные действия",
        "Фильтры",
        "Показать/скрыть фильтры",
        "Тип действия",
        "Все действия",
        "С даты",
        "По дату",
        "Применить",
        "Экспорт CSV",
        "Детали события",
        "Действие",
        "Модуль",
        "Тип записи",
        "ID записи",
        "Метка времени",
        "Исполнитель",
        "Изменение статуса",
        "Причина",
        "Метаданные",
        "Перейти к записи",
        "Система",
    ],
    "sv": [
        "Totalt antal händelser",
        "Aktiva moduler",
        "Vanligaste åtgärder",
        "Filter",
        "Visa/dölj filter",
        "Åtgärdstyp",
        "Alla åtgärder",
        "Från datum",
        "Till datum",
        "Tillämpa",
        "Exportera CSV",
        "Händelsedetaljer",
        "Åtgärd",
        "Modul",
        "Posttyp",
        "Post-id",
        "Tidsstämpel",
        "Utförare",
        "Statusändring",
        "Orsak",
        "Metadata",
        "Gå till post",
        "System",
    ],
    "th": [
        "เหตุการณ์ทั้งหมด",
        "โมดูลที่ใช้งาน",
        "การกระทำยอดนิยม",
        "ตัวกรอง",
        "เปิด/ปิดตัวกรอง",
        "ประเภทการกระทำ",
        "การกระทำทั้งหมด",
        "ตั้งแต่วันที่",
        "ถึงวันที่",
        "นำไปใช้",
        "ส่งออก CSV",
        "รายละเอียดเหตุการณ์",
        "การกระทำ",
        "โมดูล",
        "ประเภทบันทึก",
        "ID บันทึก",
        "เวลาประทับ",
        "ผู้ดำเนินการ",
        "การเปลี่ยนสถานะ",
        "เหตุผล",
        "ข้อมูลเมตา",
        "ไปที่บันทึก",
        "ระบบ",
    ],
    "tr": [
        "Toplam Etkinlik",
        "Aktif Modüller",
        "En Çok Yapılan İşlemler",
        "Filtreler",
        "Filtreleri göster/gizle",
        "İşlem Türü",
        "Tüm işlemler",
        "Başlangıç Tarihi",
        "Bitiş Tarihi",
        "Uygula",
        "CSV İndir",
        "Etkinlik Ayrıntıları",
        "İşlem",
        "Modül",
        "Kayıt Türü",
        "Kayıt Kimliği",
        "Zaman Damgası",
        "Gerçekleştiren",
        "Durum Değişikliği",
        "Sebep",
        "Meta Veri",
        "Kayda Git",
        "Sistem",
    ],
    "uk": [
        "Усього подій",
        "Активні модулі",
        "Популярні дії",
        "Фільтри",
        "Показати/приховати фільтри",
        "Тип дії",
        "Всі дії",
        "З дати",
        "По дату",
        "Застосувати",
        "Експорт CSV",
        "Деталі події",
        "Дія",
        "Модуль",
        "Тип запису",
        "ID запису",
        "Мітка часу",
        "Виконавець",
        "Зміна статусу",
        "Причина",
        "Метадані",
        "Перейти до запису",
        "Система",
    ],
    "ur": [
        "کل واقعات",
        "فعال ماڈیولز",
        "اہم اقدامات",
        "فلٹر",
        "فلٹر دکھائیں/چھپائیں",
        "اقدام کی قسم",
        "تمام اقدامات",
        "شروع تاریخ",
        "اختتام تاریخ",
        "لاگو کریں",
        "CSV برآمد کریں",
        "واقعے کی تفصیلات",
        "اقدام",
        "ماڈیول",
        "ریکارڈ کی قسم",
        "ریکارڈ آئی ڈی",
        "ٹائم اسٹیمپ",
        "منتظم",
        "حیثیت میں تبدیلی",
        "وجہ",
        "میٹا ڈیٹا",
        "ریکارڈ پر جائیں",
        "سسٹم",
    ],
    "uz": [
        "Jami voqealar",
        "Faol modullar",
        "Eng ko'p bajariladigan harakatlar",
        "Filtrlar",
        "Filtrlarni ko'rsatish/yashirish",
        "Harakat turi",
        "Barcha harakatlar",
        "Boshlanish sanasi",
        "Tugash sanasi",
        "Qo'llash",
        "CSV eksport",
        "Voqea tafsilotlari",
        "Harakat",
        "Modul",
        "Yozuv turi",
        "Yozuv ID si",
        "Vaqt belgisi",
        "Ijrochi",
        "Holat o'zgarishi",
        "Sabab",
        "Metama'lumot",
        "Yozuvga o'tish",
        "Tizim",
    ],
    "vi": [
        "Tổng sự kiện",
        "Mô-đun đang hoạt động",
        "Hành động phổ biến nhất",
        "Bộ lọc",
        "Hiện/ẩn bộ lọc",
        "Loại hành động",
        "Tất cả hành động",
        "Từ ngày",
        "Đến ngày",
        "Áp dụng",
        "Xuất CSV",
        "Chi tiết sự kiện",
        "Hành động",
        "Mô-đun",
        "Loại bản ghi",
        "ID bản ghi",
        "Dấu thời gian",
        "Người thực hiện",
        "Thay đổi trạng thái",
        "Lý do",
        "Siêu dữ liệu",
        "Đến bản ghi",
        "Hệ thống",
    ],
    "zh": [
        "总事件数",
        "活跃模块数",
        "主要操作",
        "筛选",
        "显示/隐藏筛选",
        "操作类型",
        "全部操作",
        "开始日期",
        "结束日期",
        "应用",
        "导出 CSV",
        "事件详情",
        "操作",
        "模块",
        "记录类型",
        "记录 ID",
        "时间戳",
        "执行人",
        "状态变更",
        "原因",
        "元数据",
        "跳转至记录",
        "系统",
    ],
}


def build_insertion_lines(locale: str) -> str:
    """Build the block of 23 lines to insert."""
    values = TRANSLATIONS[locale]
    lines = []
    for key, value in zip(KEYS, values, strict=True):
        # Escape any single quotes in value by using double-quoted TS strings
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{key}": "{escaped}",')
    return "\n".join(lines)


def process_file(locale: str) -> tuple[bool, str]:
    """Insert the 23 keys after timeline.showing in the given locale file.
    Returns (changed, message)."""
    path = LOCALES_DIR / f"{locale}.ts"
    if not path.exists():
        return False, f"File not found: {path}"

    text = path.read_text(encoding="utf-8")

    # Check if already present (idempotent)
    if '"timeline.total_events"' in text:
        return False, f"{locale}: already has timeline.total_events, skipping"

    # Find the timeline.showing line
    pattern = re.compile(r'("timeline\.showing":[^\n]*\n)')
    match = pattern.search(text)
    if not match:
        return False, f"{locale}: timeline.showing not found"

    insertion = build_insertion_lines(locale)
    new_text = text[: match.end()] + insertion + "\n" + text[match.end() :]
    path.write_text(new_text, encoding="utf-8")
    return True, f"{locale}: inserted 23 keys"


def main() -> None:
    required = [
        "ar",
        "bg",
        "bn",
        "cs",
        "da",
        "de",
        "el",
        "es",
        "es-CL",
        "es-CO",
        "es-MX",
        "et",
        "fa",
        "fi",
        "fil",
        "fr",
        "he",
        "hi",
        "hr",
        "hu",
        "id",
        "it",
        "ja",
        "kk",
        "ko",
        "ky",
        "mn",
        "nl",
        "no",
        "pl",
        "pt",
        "pt-BR",
        "ro",
        "ru",
        "sv",
        "th",
        "tr",
        "uk",
        "ur",
        "uz",
        "vi",
        "zh",
    ]

    missing_translations = [loc for loc in required if loc not in TRANSLATIONS]
    if missing_translations:
        print(
            f"ERROR: no translations defined for: {missing_translations}",
            file=sys.stderr,
        )
        sys.exit(1)

    changed = 0
    for locale in required:
        ok, msg = process_file(locale)
        print(msg)
        if ok:
            changed += 1

    print(f"\nDone: {changed}/{len(required)} files updated.")


if __name__ == "__main__":
    main()
