// DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
// Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
//
// The honeycomb: the two hexagon clip paths the product draws with, and the
// geometry that lays cells out into an interlocking band.
//
// TWO SHAPES, NOT ONE. They are different hexagons and they are not
// interchangeable:
//
//   HEX_PORTRAIT_CLIP  points at the TOP and BOTTOM, flat left and right
//                      edges. This is the crop a person's photo is cut to on
//                      a case card. A portrait wants the tall axis vertical.
//
//   HEX_CELL_CLIP      points at the LEFT and RIGHT, flat top and bottom
//                      edges. This is the face of a module cell in the
//                      honeycomb. A label wants the wide axis horizontal, and
//                      this orientation is what the layout maths below tiles.
//
// Both used to be written out by hand at their call sites - the portrait one
// in three separate places, once as a bare inline literal with no name at all.
// Three copies of a polygon do not stay equal, and a cell that is a few
// percent off its neighbours reads as a rendering fault rather than as a
// design. They live here so there is one of each.
//
// The clip paths match the marketing site's honeycomb component character for
// character, so a case card and the public page for the same case cut to the
// same shape. Changing one here without changing it there splits them - which
// happened: the site was corrected to exact vertices after a reader called the
// old shape a stretched diamond, and this file went on carrying the inset one.
// The site's stylesheet is generated by marketing-site/scripts/put_case_face.py.

/**
 * Pointy-top hexagon: vertices at top and bottom centre, flat left and right
 * edges. Used to crop portraits on case cards and on the sign-in art.
 *
 * The vertices are exact. An inset version of this shape - 2% off the points,
 * 26% instead of 25% on the shoulders - shortens the two slanted sides against
 * the two vertical ones no matter what box it is given, so it cannot be made
 * regular by resizing. Pair it with {@link HEX_PORTRAIT_ASPECT}.
 */
export const HEX_PORTRAIT_CLIP =
  'polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%)';

/**
 * Width divided by height for a box a {@link HEX_PORTRAIT_CLIP} is regular in.
 *
 * A clip path cuts percentages of whatever box it is handed, so the polygon
 * alone cannot make a hexagon regular - the box decides the shape. Give this
 * one a taller box and the two slanted sides grow past the vertical ones and
 * it reads as a stretched diamond, which is exactly what shipped: the cards
 * cropped at `aspect-[7/8]` and the sign-in art at 88x100, so the slanted
 * sides ran 3.96% and 4.42% long.
 *
 * The rim on the case cards is the one place this is knowingly approximate.
 * A border cannot survive a clip path, so the rim is the wrapper's own
 * background showing through a few pixels of padding, and shrinking a box by
 * an equal number of pixels on every side is not the same operation as
 * offsetting a hexagon inward. The visible outline stays exactly regular; the
 * photo cut just inside it lands near 0.853, whose slanted sides are 1.14%
 * short - about half a pixel on a cell that size, under an edge nobody can
 * see past. Drawing a true inward offset would need a second polygon, which
 * is a larger change than the thing it would correct.
 *
 * Numerically this is {@link HEX_ASPECT}, and it is deliberately not the same
 * constant. That one is a flat-top cell's height over its width; this one is a
 * pointy-top portrait's width over its height. They agree today because a
 * regular hexagon turned on its side inverts the ratio, and a single constant
 * would hide which of the two a call site meant.
 */
export const HEX_PORTRAIT_ASPECT = 0.8660254;

/**
 * Flat-top hexagon: flat top and bottom edges, vertices at left and right.
 * The face of a module cell in a honeycomb, and the shape {@link hiveBand}
 * tiles. Its 6:1 width-to-inset ratio is what makes neighbouring columns
 * interlock at a 3/4 horizontal pitch.
 */
export const HEX_CELL_CLIP =
  'polygon(25% 0%, 75% 0%, 100% 50%, 75% 100%, 25% 100%, 0% 50%)';

/**
 * Height of a flat-top hex as a fraction of its width (sqrt(3)/2). A cell laid
 * out at any other ratio stops interlocking and leaves gaps between columns.
 */
export const HEX_ASPECT = 0.866;

/** Where one cell sits inside the stage, in pixels from its top-inline-start corner. */
export interface HivePlacement {
  /** Offset along the inline axis. Apply as `insetInlineStart`, NEVER as
   *  `left`: the app ships Arabic, Hebrew, Persian and Urdu, and a band
   *  anchored to the left edge reads backwards in all four. */
  inlineStart: number;
  /** Offset from the top of the stage. */
  top: number;
}

/** A laid-out honeycomb: where every cell goes, and how big the stage must be. */
export interface HiveLayout {
  /** One placement per cell, in the order the cells were given. */
  placements: HivePlacement[];
  /** Width of the box that contains every cell. */
  width: number;
  /** Height of the box that contains every cell. */
  height: number;
  /** Width of a single cell. */
  cellWidth: number;
  /** Height of a single cell (`cellWidth * HEX_ASPECT`, rounded). */
  cellHeight: number;
}

/**
 * Lay `count` flat-top cells out as a horizontal band `rows` cells deep.
 *
 * Cells fill a column top to bottom before moving to the next column, so two
 * consecutive cells are always neighbours in the comb. That matters because
 * the callers feed these in the order a case runs: step 1's module touches
 * step 2's module, and the eye should be able to follow that without hunting
 * across the band.
 *
 * Columns advance at 3/4 of a cell width and every other column drops by half
 * a cell height, which is what makes the hexagons interlock rather than sit in
 * a grid with gaps at the corners.
 *
 * Positions are computed once and baked into inline styles: the band renders
 * statically, with no measurement pass and nothing to recompute on resize.
 */
export function hiveBand(count: number, cellWidth: number, rows = 2): HiveLayout {
  const cellHeight = Math.round(cellWidth * HEX_ASPECT);
  const columnPitch = Math.round(cellWidth * 0.75);
  const safeRows = Math.max(1, rows);
  const placements: HivePlacement[] = [];
  for (let i = 0; i < Math.max(0, count); i += 1) {
    const column = Math.floor(i / safeRows);
    const rowInColumn = i % safeRows;
    placements.push({
      inlineStart: column * columnPitch,
      // Odd columns are pushed down half a cell. That is the interlock.
      top: rowInColumn * cellHeight + (column % 2) * Math.round(cellHeight / 2),
    });
  }
  // Measure the stage from the cells that are actually there. A band of three
  // is three cells wide, not the width of the row it could have filled.
  const width = placements.length
    ? Math.max(...placements.map((p) => p.inlineStart)) + cellWidth
    : 0;
  const height = placements.length
    ? Math.max(...placements.map((p) => p.top)) + cellHeight
    : 0;
  return { placements, width, height, cellWidth, cellHeight };
}

// ── A hub and the cells that touch it ───────────────────────────────────────
// `hiveBand` above lays cells out as a strip, which is the right drawing for a
// list. This is the other arrangement the comb affords: one cell in the middle
// and its neighbours around it, for when the middle cell is the SUBJECT and the
// ones around it are what the subject reaches.
//
// Six is not a design budget, it is the shape. A flat-top hexagon has exactly
// six neighbours, so a hub can hold six spokes and no more without starting a
// second ring. Measured over the case catalogue before this was written: the
// most modules any of the 202 cases walks through is six, and the distribution
// is 1:2, 2:33, 3:86, 4:38, 5:34, 6:9. Every case fits the first ring, so the
// second ring is not written, and if a future case reaches a seventh module the
// layout tables below will not silently drop it - `hiveRing` clamps and the
// caller is expected to say so.

/** The six neighbours of a flat-top hex, in cell widths and cell heights. */
const RING_SLOTS: readonly (readonly [number, number])[] = [
  [0, -1], // N
  [0.75, -0.5], // NE
  [0.75, 0.5], // SE
  [0, 1], // S
  [-0.75, 0.5], // SW
  [-0.75, -0.5], // NW
];

/**
 * Which of the six slots to fill for a given spoke count, chosen so the cluster
 * is balanced at every size rather than growing clockwise into a lopsided fan.
 * Three makes a triangle, four an X, five a fan open at the top.
 */
const RING_ORDER: readonly (readonly number[])[] = [
  [],
  [1],
  [1, 2],
  [0, 2, 4],
  [1, 2, 4, 5],
  [1, 2, 3, 4, 5],
  [0, 1, 2, 3, 4, 5],
];

/** A hub cell and the cells touching it, with the stage they need. */
export interface HiveRingLayout {
  /** Where the middle cell goes. */
  hub: HivePlacement;
  /** One placement per spoke, in the order the spokes were given. */
  spokes: HivePlacement[];
  /** Width of the box that contains the hub and every spoke. */
  width: number;
  /** Height of that box. */
  height: number;
  /** Width of a single cell. */
  cellWidth: number;
  /** Height of a single cell (`cellWidth * HEX_ASPECT`, rounded). */
  cellHeight: number;
}

/**
 * Place a hub cell and up to six cells that touch it.
 *
 * Offsets come back measured from the top-inline-start corner of the stage, so
 * a caller applies them as `insetInlineStart` and the whole cluster mirrors in
 * Arabic, Hebrew, Persian and Urdu the same way a band does. Anything past the
 * sixth spoke is dropped: there is no second ring, and returning a seventh
 * placement on top of one of the first six would draw two cells in one hole.
 */
export function hiveRing(count: number, cellWidth: number): HiveRingLayout {
  const cellHeight = Math.round(cellWidth * HEX_ASPECT);
  const wanted = Math.min(Math.max(count, 0), RING_SLOTS.length);
  const slots = (RING_ORDER[wanted] ?? RING_ORDER[RING_SLOTS.length]!).map((i) => RING_SLOTS[i]!);
  const xs = [0, ...slots.map(([dx]) => dx * cellWidth)];
  const ys = [0, ...slots.map(([, dy]) => dy * cellHeight)];
  const minX = Math.min(...xs);
  const minY = Math.min(...ys);
  const maxX = Math.max(...xs);
  const maxY = Math.max(...ys);
  return {
    hub: { inlineStart: Math.round(-minX), top: Math.round(-minY) },
    spokes: slots.map(([dx, dy]) => ({
      inlineStart: Math.round(dx * cellWidth - minX),
      top: Math.round(dy * cellHeight - minY),
    })),
    width: Math.round(maxX - minX) + cellWidth,
    height: Math.round(maxY - minY) + cellHeight,
    cellWidth,
    cellHeight,
  };
}
