// DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
// Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
//
// Case: "Attest the boletim de medicao and invoice the period" (BR).
//
// GENERATED. Do not edit this file by hand, the next compose run
// will overwrite it. The workflow lives once at
//   frontend/src/features/cases/intl/spines/f01-progress-payment.json
// and this country's words and step order live at
//   frontend/src/features/cases/intl/layers/f01-progress-payment/BR.json
//
// Brazil surfaces the measurement half plus the attestation that makes
// it payable. The distinctive step is not the arithmetic, it is that a
// public body cannot pay against a measurement nobody attested: the
// fiscal do contrato signs the boletim de medicao, the expense is
// liquidated, and only then does the nota fiscal have anything to
// attach to. So this layer surfaces register, measure, value, certify,
// invoice and reconcile, and leaves the clock steps to the regimes
// that count days rather than approvals.
//
// Rebuild with:
//   node frontend/scripts/compose-case-layers.mjs --family f01-progress-payment

import type { Playbook } from "../types";

const playbook: Playbook = {
  id: "attest-the-boletim-de-medicao-and-invoice-the-period",
  order: 1220,
  region: "BR",
  category: "commercial",
  companyTypes: ["general-contractor", "subcontractor", "developer-client"],
  roles: ["contract-administrator", "commercial-manager", "quantity-surveyor"],
  icon: "ClipboardCheck",
  titleKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.title",
  titleDefault: "Attest the boletim de medicao and invoice the period",
  descKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.desc",
  descDefault:
    "Measure the period against the planilha orcamentaria, price it at the contract rates, have the fiscal do contrato attest the boletim de medicao and raise the nota fiscal against the attested figure, so the expense can be liquidated instead of sitting in a queue nobody can explain.",
  longDescKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.longdesc",
  longDescDefault:
    "In a Brazilian contract the money does not move because the work was done, it moves because the work was measured, attested and liquidated in that order, and each of those is a document with a name and a signatory. A nota fiscal issued ahead of the boletim de medicao it should reference is the single most common reason a payment stalls, because there is nothing for the accounts to match it to and the person who could fix it is not the person holding the invoice. Measured against the planilha item by item, the attestation is a signature on a figure both sides have already seen rather than a negotiation that starts when the invoice arrives.",
  estMinutes: 12,
  steps: [
    {
      id: "register",
      icon: "FileSignature",
      inputs: [
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.register.in.contrato",
          label: "Signed contrato",
        },
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.register.in.planilha",
          label: "Planilha orcamentaria",
        },
      ],
      outputs: [
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.register.out.registered",
          label: "Contract on record",
        },
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.register.out.terms",
          label: "Measurement and payment terms attached",
        },
      ],
      titleKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.register.title",
      titleDefault: "Register the contract and its payment regime",
      whatKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.register.what",
      whatDefault:
        "Record the contract, its the contract payment terms under Lei 14.133 payment regime and the dates it turns on, so every later step reads the same terms instead of somebody's memory of them.",
      whyKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.register.why",
      whyDefault:
        "A payment regime that lives in a PDF nobody opens is a regime that gets applied differently by each person who applies it. Registered once, the deadlines below are computed rather than argued about.",
      moduleLabel: "Contracts",
      moduleLabelKey: "nav.contracts",
      to: "/projects/:projectId/contracts",
    },
    {
      id: "medicao",
      icon: "Ruler",
      inputs: [
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.medicao.in.planilha",
          label: "Planilha orcamentaria",
        },
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.medicao.in.executed",
          label: "Work executed this period",
        },
      ],
      outputs: [
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.medicao.out.percent",
          label: "Percent complete per item da planilha",
        },
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.medicao.out.quantities",
          label: "Measured quantities for the period",
        },
      ],
      titleKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.medicao.title",
      titleDefault: "Measure the period item da planilha by item da planilha",
      whatKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.medicao.what",
      whatDefault:
        "Record what was executed against each item da planilha for the period as a percentage of its contract quantity. The earned quantity follows from that percentage and the design quantity, and the earned amount from the same percentage and the position total, so one honest number per line produces the whole valuation.",
      whyKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.medicao.why",
      whyDefault:
        "A boletim de medicao built from a single project percentage cannot be checked and therefore cannot be approved without a conversation. Measured line by line, the disagreement is about one item da planilha rather than about the whole month, and the rest of the money moves while that one is settled.",
      moduleLabel: "Progress",
      moduleLabelKey: "nav.progress",
      to: "/progress",
    },
    {
      id: "value",
      icon: "Calculator",
      inputs: [
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.value.in.quantities",
          label: "Measured quantities for the period",
        },
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.value.in.rates",
          label: "Contract unit rates",
        },
      ],
      outputs: [
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.value.out.valuation",
          label: "Boletim de medicao for the period",
        },
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.value.out.aditivo",
          label: "Termo aditivo flagged",
        },
      ],
      titleKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.value.title",
      titleDefault: "Value it at the contract rates",
      whatKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.value.what",
      whatDefault:
        "Read the valuation back against the bill and check the rates it used are the contract rates. Where an item da planilha has been measured past the quantity the contract carries, deal with it as a change to the position with an order behind it rather than as a larger figure on the same line.",
      whyKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.value.why",
      whyDefault:
        "A termo aditivo certified quietly is one the client can refuse at the final account, months after the work was built and paid for down the chain. Raising it as a change while it is small is the only version of that conversation where you are not asking to be paid for work already done. Quantity measured beyond what the contract carries has to become a termo aditivo before it is measured, not after it is paid. A public body that pays for it the other way round is asking its own audit to find the difference.",
      moduleLabel: "BOQ",
      moduleLabelKey: "boq.title",
      to: "/projects/:projectId/boq",
    },
    {
      id: "atestar",
      icon: "Stamp",
      inputs: [
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.atestar.in.boletim",
          label: "Boletim de medicao for the period",
        },
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.atestar.in.fiscal",
          label: "Fiscal do contrato named for attestation",
        },
      ],
      outputs: [
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.atestar.out.attested",
          label: "Attested boletim de medicao",
        },
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.atestar.out.date",
          label: "Attestation date on record",
        },
      ],
      titleKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.atestar.title",
      titleDefault: "Get it approved by the people who have to approve it",
      whatKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.atestar.what",
      whatDefault:
        "Route the boletim de medicao to the fiscal do contrato, and to whoever the contract adds after them. Keep the approval date, because the nota fiscal follows the approval and the payment clock runs from there, so an approval that slips moves everything behind it.",
      whyKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.atestar.why",
      whyDefault:
        "Approval sitting in an inbox is the most common reason a payment is late, and it is invisible while it is happening because nobody has refused anything. A route with a date on each hop turns that into a question with an owner instead of a monthly complaint.",
      moduleLabel: "Approval routes",
      moduleLabelKey: "approvalRoutes.title",
      to: "/approval-routes",
    },
    {
      id: "notafiscal",
      icon: "ReceiptText",
      inputs: [
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.notafiscal.in.attested",
          label: "Attested boletim de medicao",
        },
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.notafiscal.in.retencao",
          label: "Retencao and deductions",
        },
      ],
      outputs: [
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.notafiscal.out.nf",
          label: "Nota fiscal issued",
        },
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.notafiscal.out.carried",
          label: "Amount carried into the accounts",
        },
      ],
      titleKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.notafiscal.title",
      titleDefault: "Issue the nota fiscal against the approved figure",
      whatKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.notafiscal.what",
      whatDefault:
        "Raise the nota fiscal against the approved boletim de medicao, carrying retencao contratual and any deduction the contract provides for, and reference the boletim de medicao on it. Reference the attested boletim on the nota fiscal itself. The accounts match the two by that reference, and an invoice carrying no reference is one a clerk has to chase somebody to explain.",
      whyKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.notafiscal.why",
      whyDefault:
        "A demand for a figure nobody approved is one that will be returned, and the clock does not start on a returned document. Matching it to the boletim de medicao also means the accounts and the valuation tell the same story at year end without anybody reconciling them by hand.",
      moduleLabel: "Finance",
      moduleLabelKey: "nav.finance",
      to: "/projects/:projectId/finance",
    },
    {
      id: "reconcile",
      icon: "Scale",
      inputs: [
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.reconcile.in.asked",
          label: "Amount invoiced",
        },
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.reconcile.in.attested",
          label: "Amount attested",
        },
      ],
      outputs: [
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.reconcile.out.difference",
          label: "Difference carried forward",
        },
        {
          labelKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.reconcile.out.aged",
          label: "Outstanding by age",
        },
      ],
      titleKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.reconcile.title",
      titleDefault: "Reconcile what was certified against what was asked",
      whatKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.reconcile.what",
      whatDefault:
        "Put the approved figure next to the figure you asked for and carry the difference forward. What is unpaid, and how long it has been unpaid, belongs in the accounts as a number rather than in a conversation.",
      whyKey: "cases.attest_the_boletim_de_medicao_and_invoice_the_period.step.reconcile.why",
      whyDefault:
        "The gap between applied and certified is the health of the commercial relationship expressed as money, and it is only visible if somebody puts the two numbers side by side every period. Cumulatively it is also the single best predictor of a final account fight.",
      moduleLabel: "Event Reconciliation",
      moduleLabelKey: "nav.reconciliation",
      to: "/projects/:projectId/reconciliation",
    },
  ],
};

export default playbook;
