// DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
// Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
//
// Case: "Authorise the estimacion and invoice it as a CFDI" (MX).
//
// GENERATED. Do not edit this file by hand, the next compose run
// will overwrite it. The workflow lives once at
//   frontend/src/features/cases/intl/spines/f01-progress-payment.json
// and this country's words and step order live at
//   frontend/src/features/cases/intl/layers/f01-progress-payment/MX.json
//
// Mexico surfaces the measurement half plus the authorisation and the
// fiscal document, because here the invoice is not a letter you write,
// it is a CFDI the tax authority stamps, and it has to agree with the
// estimacion it is raised against. The amortizacion del anticipo rides
// on the adjust step, which is what a spine slot for the money held
// back from each payment is for.
//
// Rebuild with:
//   node frontend/scripts/compose-case-layers.mjs --family f01-progress-payment

import type { Playbook } from "../types";

const playbook: Playbook = {
  id: "authorise-the-estimacion-and-invoice-it-as-a-cfdi",
  order: 1260,
  region: "MX",
  category: "commercial",
  companyTypes: ["general-contractor", "subcontractor", "developer-client"],
  roles: ["contract-administrator", "commercial-manager", "quantity-surveyor"],
  icon: "ReceiptText",
  titleKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.title",
  titleDefault: "Authorise the estimacion and invoice it as a CFDI",
  descKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.desc",
  descDefault:
    "Measure the period concepto by concepto, value it against the precios unitarios, amortise the anticipo and hold the fondo de garantia, get the residente de obra to authorise the estimacion and raise the CFDI against the authorised figure.",
  longDescKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.longdesc",
  longDescDefault:
    "An estimacion is not an invoice and the difference is the whole workflow. The estimacion is the measured, priced and authorised statement of the period; the CFDI is the fiscal document raised against it, and the tax authority will stamp a CFDI whose figures nobody authorised just as happily as one whose figures everybody agreed. That is how a contractor ends up holding a stamped invoice for an amount the client will not pay, with the correction living in a cancellation and a reissue rather than in a conversation. Authorised first and invoiced second, the two documents say the same number and the amortizacion del anticipo is visible on both.",
  estMinutes: 12,
  steps: [
    {
      id: "measure",
      icon: "Ruler",
      inputs: [
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.measure.in.catalogo",
          label: "Catalogo de conceptos",
        },
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.measure.in.executed",
          label: "Work executed this period",
        },
      ],
      outputs: [
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.measure.out.percent",
          label: "Percent complete per concepto",
        },
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.measure.out.volumenes",
          label: "Volumenes for the period",
        },
      ],
      titleKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.measure.title",
      titleDefault: "Measure the period concepto by concepto",
      whatKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.measure.what",
      whatDefault:
        "Record what was executed against each concepto for the period as a percentage of its contract quantity. The earned quantity follows from that percentage and the design quantity, and the earned amount from the same percentage and the position total, so one honest number per line produces the whole valuation.",
      whyKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.measure.why",
      whyDefault:
        "An estimacion built from a single project percentage cannot be checked and therefore cannot be approved without a conversation. Measured line by line, the disagreement is about one concepto rather than about the whole month, and the rest of the money moves while that one is settled.",
      moduleLabel: "Progress",
      moduleLabelKey: "nav.progress",
      to: "/progress",
    },
    {
      id: "value",
      icon: "Calculator",
      inputs: [
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.value.in.volumenes",
          label: "Volumenes for the period",
        },
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.value.in.precios",
          label: "Precios unitarios",
        },
      ],
      outputs: [
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.value.out.estimacion",
          label: "Estimacion for the period",
        },
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.value.out.extraordinarios",
          label: "Conceptos extraordinarios flagged",
        },
      ],
      titleKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.value.title",
      titleDefault: "Value it at the contract rates",
      whatKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.value.what",
      whatDefault:
        "Read the valuation back against the bill and check the rates it used are the contract rates. Where a concepto has been measured past the quantity the contract carries, deal with it as a change to the position with an order behind it rather than as a larger figure on the same line.",
      whyKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.value.why",
      whyDefault:
        "A concepto extraordinario certified quietly is one the client can refuse at the final account, months after the work was built and paid for down the chain. Raising it as a change while it is small is the only version of that conversation where you are not asking to be paid for work already done.",
      moduleLabel: "BOQ",
      moduleLabelKey: "boq.title",
      to: "/projects/:projectId/boq",
    },
    {
      id: "amortize",
      icon: "Percent",
      inputs: [
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.amortize.in.estimacion",
          label: "Cumulative estimacion",
        },
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.amortize.in.anticipo",
          label: "Anticipo outstanding",
        },
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.amortize.in.previous",
          label: "Previous payments",
        },
      ],
      outputs: [
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.amortize.out.amortizacion",
          label: "Amortizacion del anticipo",
        },
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.amortize.out.net",
          label: "Net due for the period",
        },
      ],
      titleKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.amortize.title",
      titleDefault: "Apply fondo de garantia and previous payments",
      whatKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.amortize.what",
      whatDefault:
        "Take the cumulative valuation, subtract what has already been certified, and apply fondo de garantia at the contract percentage. The figure that leaves this step is the one the CFDI is raised for, and the backup behind it is the measure that produced it. The anticipo is amortised on the same proportion the period earned, so an estimacion that measures more also repays more. Left to a fixed monthly figure it finishes the works still owing, and the last estimacion is the one that discovers it.",
      whyKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.amortize.why",
      whyDefault:
        "Interim payments are cumulative, so the month's money is a difference between two totals rather than a total of its own. Computing it from the cumulative figure is what stops a line being paid twice or dropped entirely when a period is re-measured.",
      moduleLabel: "Finance",
      moduleLabelKey: "nav.finance",
      to: "/projects/:projectId/finance",
    },
    {
      id: "autorizar",
      icon: "Stamp",
      inputs: [
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.autorizar.in.estimacion",
          label: "Estimacion for the period",
        },
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.autorizar.in.residente",
          label: "Residente de obra named for authorisation",
        },
      ],
      outputs: [
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.autorizar.out.authorised",
          label: "Authorised estimacion",
        },
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.autorizar.out.date",
          label: "Authorisation date on record",
        },
      ],
      titleKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.autorizar.title",
      titleDefault: "Get it approved by the people who have to approve it",
      whatKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.autorizar.what",
      whatDefault:
        "Route the estimacion to the residente de obra, and to whoever the contract adds after them. Keep the approval date, because the CFDI follows the approval and the payment clock runs from there, so an approval that slips moves everything behind it.",
      whyKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.autorizar.why",
      whyDefault:
        "Approval sitting in an inbox is the most common reason a payment is late, and it is invisible while it is happening because nobody has refused anything. A route with a date on each hop turns that into a question with an owner instead of a monthly complaint.",
      moduleLabel: "Approval routes",
      moduleLabelKey: "approvalRoutes.title",
      to: "/approval-routes",
    },
    {
      id: "cfdi",
      icon: "ReceiptText",
      inputs: [
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.cfdi.in.authorised",
          label: "Authorised estimacion",
        },
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.cfdi.in.retenciones",
          label: "Retenciones and deductions",
        },
      ],
      outputs: [
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.cfdi.out.cfdi",
          label: "CFDI issued and stamped",
        },
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.cfdi.out.carried",
          label: "Amount carried into the accounts",
        },
      ],
      titleKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.cfdi.title",
      titleDefault: "Issue the CFDI against the approved figure",
      whatKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.cfdi.what",
      whatDefault:
        "Raise the CFDI against the approved estimacion, carrying fondo de garantia and any deduction the contract provides for, and reference the estimacion on it. A stamped CFDI is corrected by cancelling it and issuing another, not by editing it, so the figure has to be right before it is stamped rather than after.",
      whyKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.cfdi.why",
      whyDefault:
        "A demand for a figure nobody approved is one that will be returned, and the clock does not start on a returned document. Matching it to the estimacion also means the accounts and the valuation tell the same story at year end without anybody reconciling them by hand.",
      moduleLabel: "Finance",
      moduleLabelKey: "nav.finance",
      to: "/projects/:projectId/finance",
    },
    {
      id: "openclock",
      icon: "Clock",
      inputs: [
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.openclock.in.cfdi",
          label: "CFDI and its date",
        },
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.openclock.in.authorised",
          label: "Authorisation date",
        },
      ],
      outputs: [
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.openclock.out.clock",
          label: "Open payment clock",
        },
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.openclock.out.due",
          label: "Due date computed",
        },
      ],
      titleKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.openclock.title",
      titleDefault: "Open the payment clock on the right day",
      whatKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.openclock.what",
      whatDefault:
        "Open a clock over the CFDI starting from the authorisation of the estimacion, under the public works payment rules. Payment falls due 20 days later, and the clock records that date rather than leaving it to be worked out when somebody asks.",
      whyKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.openclock.why",
      whyDefault:
        "The single most expensive mistake in interim payment is starting the count on the wrong event, because every deadline behind it inherits the error and none of them look wrong. Anchoring on the authorisation of the estimacion once makes the whole chain checkable.",
      moduleLabel: "Payment Clock",
      moduleLabelKey: "nav.payment_clock",
      to: "/payment-clock",
    },
    {
      id: "reconcile",
      icon: "Scale",
      inputs: [
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.reconcile.in.asked",
          label: "Amount invoiced",
        },
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.reconcile.in.authorised",
          label: "Amount authorised",
        },
      ],
      outputs: [
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.reconcile.out.difference",
          label: "Difference carried forward",
        },
        {
          labelKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.reconcile.out.aged",
          label: "Outstanding by age",
        },
      ],
      titleKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.reconcile.title",
      titleDefault: "Reconcile what was certified against what was asked",
      whatKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.reconcile.what",
      whatDefault:
        "Put the approved figure next to the figure you asked for and carry the difference forward. What is unpaid, and how long it has been unpaid, belongs in the accounts as a number rather than in a conversation.",
      whyKey: "cases.authorise_the_estimacion_and_invoice_it_as_a_cfdi.step.reconcile.why",
      whyDefault:
        "The gap between applied and certified is the health of the commercial relationship expressed as money, and it is only visible if somebody puts the two numbers side by side every period. Cumulatively it is also the single best predictor of a final account fight.",
      moduleLabel: "Event Reconciliation",
      moduleLabelKey: "nav.reconciliation",
      to: "/projects/:projectId/reconciliation",
    },
  ],
};

export default playbook;
