// DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
// Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
//
// Case: "Certify the interim payment and invoice the authority" (SA).
//
// GENERATED. Do not edit this file by hand, the next compose run
// will overwrite it. The workflow lives once at
//   frontend/src/features/cases/intl/spines/f01-progress-payment.json
// and this country's words and step order live at
//   frontend/src/features/cases/intl/layers/f01-progress-payment/SA.json
//
// Saudi Arabia surfaces the widest window in the family, register
// through clock, because a government works contract here carries the
// advance payment guarantee, the retention and the interim payment
// certificate in one arc and none of them is optional. The Engineer
// certifies, the authority pays against the certificate, and the
// invoice is the last document rather than the first.
//
// Rebuild with:
//   node frontend/scripts/compose-case-layers.mjs --family f01-progress-payment

import type { Playbook } from "../types";

const playbook: Playbook = {
  id: "certify-the-interim-payment-and-invoice-the-authority",
  order: 1320,
  region: "SA",
  category: "commercial",
  companyTypes: ["general-contractor", "subcontractor", "cost-consultant"],
  roles: ["contract-administrator", "commercial-manager", "quantity-surveyor"],
  icon: "Landmark",
  titleKey: "cases.certify_the_interim_payment_and_invoice_the_authority.title",
  titleDefault: "Certify the interim payment and invoice the authority",
  descKey: "cases.certify_the_interim_payment_and_invoice_the_authority.desc",
  descDefault:
    "Register the contract and its guarantees, measure the period against the bill, recover the advance payment and hold retention, get the Engineer to issue the interim payment certificate and invoice the authority against it under the procurement law's payment window.",
  longDescKey: "cases.certify_the_interim_payment_and_invoice_the_authority.longdesc",
  longDescDefault:
    "On a government works contract the interim payment certificate is the document everything else hangs from. The advance payment is recovered through it, the retention is held on it, and the invoice that follows is only as good as the certificate behind it. The failure this arc is built to prevent is quiet and expensive: an invoice submitted against a certificate the Engineer has not issued sits in the authority's queue looking exactly like an invoice that is being processed, and the payment window everybody is relying on has not started at all. Certificate first, invoice second, with both dates recorded, is what makes a late payment a question with an answer.",
  estMinutes: 13,
  steps: [
    {
      id: "register",
      icon: "FileSignature",
      inputs: [
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.register.in.contract",
          label: "Signed contract",
        },
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.register.in.guarantees",
          label: "Advance payment and performance guarantees",
        },
      ],
      outputs: [
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.register.out.registered",
          label: "Contract on record",
        },
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.register.out.terms",
          label: "Certification and payment terms attached",
        },
      ],
      titleKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.register.title",
      titleDefault: "Register the contract and its payment regime",
      whatKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.register.what",
      whatDefault:
        "Record the contract, its the government procurement payment rules payment regime and the dates it turns on, so every later step reads the same terms instead of somebody's memory of them.",
      whyKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.register.why",
      whyDefault:
        "A payment regime that lives in a PDF nobody opens is a regime that gets applied differently by each person who applies it. Registered once, the deadlines below are computed rather than argued about.",
      moduleLabel: "Contracts",
      moduleLabelKey: "nav.contracts",
      to: "/projects/:projectId/contracts",
    },
    {
      id: "measure",
      icon: "Ruler",
      inputs: [
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.measure.in.boq",
          label: "Contract bill of quantities",
        },
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.measure.in.works",
          label: "Work executed this period",
        },
      ],
      outputs: [
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.measure.out.percent",
          label: "Percent complete per BoQ item",
        },
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.measure.out.quantities",
          label: "Earned quantities for the period",
        },
      ],
      titleKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.measure.title",
      titleDefault: "Measure the period BoQ item by BoQ item",
      whatKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.measure.what",
      whatDefault:
        "Record what was executed against each BoQ item for the period as a percentage of its contract quantity. The earned quantity follows from that percentage and the design quantity, and the earned amount from the same percentage and the position total, so one honest number per line produces the whole valuation.",
      whyKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.measure.why",
      whyDefault:
        "An interim payment certificate built from a single project percentage cannot be checked and therefore cannot be approved without a conversation. Measured line by line, the disagreement is about one BoQ item rather than about the whole month, and the rest of the money moves while that one is settled.",
      moduleLabel: "Progress",
      moduleLabelKey: "nav.progress",
      to: "/progress",
    },
    {
      id: "value",
      icon: "Calculator",
      inputs: [
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.value.in.quantities",
          label: "Earned quantities for the period",
        },
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.value.in.rates",
          label: "Contract rates",
        },
      ],
      outputs: [
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.value.out.valuation",
          label: "Valuation for the period",
        },
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.value.out.variations",
          label: "Variation orders flagged",
        },
      ],
      titleKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.value.title",
      titleDefault: "Value it at the contract rates",
      whatKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.value.what",
      whatDefault:
        "Read the valuation back against the bill and check the rates it used are the contract rates. Where a BoQ item has been measured past the quantity the contract carries, deal with it as a change to the position with an order behind it rather than as a larger figure on the same line.",
      whyKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.value.why",
      whyDefault:
        "A variation order certified quietly is one the client can refuse at the final account, months after the work was built and paid for down the chain. Raising it as a change while it is small is the only version of that conversation where you are not asking to be paid for work already done.",
      moduleLabel: "BOQ",
      moduleLabelKey: "boq.title",
      to: "/projects/:projectId/boq",
    },
    {
      id: "recover",
      icon: "Percent",
      inputs: [
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.recover.in.cumulative",
          label: "Cumulative valuation",
        },
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.recover.in.advance",
          label: "Advance payment outstanding",
        },
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.recover.in.previous",
          label: "Previous payments and retention",
        },
      ],
      outputs: [
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.recover.out.recovery",
          label: "Advance payment recovered this period",
        },
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.recover.out.net",
          label: "Net due for the period",
        },
      ],
      titleKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.recover.title",
      titleDefault: "Apply retention and previous payments",
      whatKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.recover.what",
      whatDefault:
        "Take the cumulative valuation, subtract what has already been certified, and apply retention at the contract percentage. The figure that leaves this step is the one the invoice is raised for, and the backup behind it is the measure that produced it. The advance is recovered on the proportion the period earned and the guarantee is reduced as it is recovered, so the two figures are read together rather than tracked in separate places by separate people.",
      whyKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.recover.why",
      whyDefault:
        "Interim payments are cumulative, so the month's money is a difference between two totals rather than a total of its own. Computing it from the cumulative figure is what stops a line being paid twice or dropped entirely when a period is re-measured.",
      moduleLabel: "Finance",
      moduleLabelKey: "nav.finance",
      to: "/projects/:projectId/finance",
    },
    {
      id: "certify",
      icon: "Stamp",
      inputs: [
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.certify.in.valuation",
          label: "Valuation for the period",
        },
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.certify.in.engineer",
          label: "Engineer named for certification",
        },
      ],
      outputs: [
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.certify.out.ipc",
          label: "Interim payment certificate issued",
        },
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.certify.out.date",
          label: "Certification date on record",
        },
      ],
      titleKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.certify.title",
      titleDefault: "Get it approved by the people who have to approve it",
      whatKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.certify.what",
      whatDefault:
        "Route the interim payment certificate to the Engineer, and to whoever the contract adds after them. Keep the approval date, because the invoice follows the approval and the payment clock runs from there, so an approval that slips moves everything behind it.",
      whyKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.certify.why",
      whyDefault:
        "Approval sitting in an inbox is the most common reason a payment is late, and it is invisible while it is happening because nobody has refused anything. A route with a date on each hop turns that into a question with an owner instead of a monthly complaint.",
      moduleLabel: "Approval routes",
      moduleLabelKey: "approvalRoutes.title",
      to: "/approval-routes",
    },
    {
      id: "invoice",
      icon: "ReceiptText",
      inputs: [
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.invoice.in.ipc",
          label: "Interim payment certificate issued",
        },
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.invoice.in.retention",
          label: "Retention and deductions",
        },
      ],
      outputs: [
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.invoice.out.invoice",
          label: "Invoice submitted to the authority",
        },
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.invoice.out.carried",
          label: "Amount carried into the accounts",
        },
      ],
      titleKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.invoice.title",
      titleDefault: "Issue the invoice against the approved figure",
      whatKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.invoice.what",
      whatDefault:
        "Raise the invoice against the approved interim payment certificate, carrying retention and any deduction the contract provides for, and reference the interim payment certificate on it.",
      whyKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.invoice.why",
      whyDefault:
        "A demand for a figure nobody approved is one that will be returned, and the clock does not start on a returned document. Matching it to the interim payment certificate also means the accounts and the valuation tell the same story at year end without anybody reconciling them by hand.",
      moduleLabel: "Finance",
      moduleLabelKey: "nav.finance",
      to: "/projects/:projectId/finance",
    },
    {
      id: "openclock",
      icon: "Clock",
      inputs: [
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.openclock.in.invoice",
          label: "Invoice and its submission date",
        },
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.openclock.in.ipc",
          label: "Certificate date",
        },
      ],
      outputs: [
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.openclock.out.clock",
          label: "Open payment clock",
        },
        {
          labelKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.openclock.out.due",
          label: "Due date computed",
        },
      ],
      titleKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.openclock.title",
      titleDefault: "Open the payment clock on the right day",
      whatKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.openclock.what",
      whatDefault:
        "Open a clock over the invoice starting from the day the invoice is submitted against the issued certificate, under the government procurement payment rules. Payment falls due 30 days later, and the clock records that date rather than leaving it to be worked out when somebody asks.",
      whyKey: "cases.certify_the_interim_payment_and_invoice_the_authority.step.openclock.why",
      whyDefault:
        "The single most expensive mistake in interim payment is starting the count on the wrong event, because every deadline behind it inherits the error and none of them look wrong. Anchoring on the day the invoice is submitted against the issued certificate once makes the whole chain checkable. The window runs from a compliant submission, so an invoice returned for a missing attachment has not started anything even though it left your office. Recording what was submitted with it is what makes that visible on the day rather than at the end of the month.",
      moduleLabel: "Payment Clock",
      moduleLabelKey: "nav.payment_clock",
      to: "/payment-clock",
    },
  ],
};

export default playbook;
