// DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
// Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
//
// Case: "Close the month with a KS-2 act and a KS-3 certificate" (RU).
//
// GENERATED. Do not edit this file by hand, the next compose run
// will overwrite it. The workflow lives once at
//   frontend/src/features/cases/intl/spines/f01-progress-payment.json
// and this country's words and step order live at
//   frontend/src/features/cases/intl/layers/f01-progress-payment/RU.json
//
// Russia splits the period across two forms rather than one, and the
// split is the point: the KS-2 act records what was accepted and the
// KS-3 certificate records what it is worth cumulatively. That maps
// onto the spine without a new sentence because the spine already
// separates the document that states the value from the document that
// asks for the money.
//
// Rebuild with:
//   node frontend/scripts/compose-case-layers.mjs --family f01-progress-payment

import type { Playbook } from "../types";

const playbook: Playbook = {
  id: "close-the-month-with-a-ks-2-act-and-a-ks-3-certificate",
  order: 1300,
  region: "RU",
  category: "commercial",
  companyTypes: ["general-contractor", "subcontractor", "developer-client"],
  roles: ["contract-administrator", "commercial-manager", "quantity-surveyor"],
  icon: "FileCheck2",
  titleKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.title",
  titleDefault: "Close the month with a KS-2 act and a KS-3 certificate",
  descKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.desc",
  descDefault:
    "Measure the period against the smeta, expand the GESN norms into the resources they carry, get the KS-2 act signed by the client's technical supervisor and raise the KS-3 certificate against it, so the cumulative figure and the accepted figure never disagree.",
  longDescKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.longdesc",
  longDescDefault:
    "The KS-2 and the KS-3 answer two different questions and a great deal of month-end argument comes from treating them as one document in two copies. The KS-2 is the act of acceptance: it lists what was executed, position by position, at the rates the smeta carries, and it is signed by the party who accepted it. The KS-3 is cumulative: it states the value of the works from the beginning of the contract to this period, which is what the payment is calculated from. A KS-3 that does not follow from the KS-2 acts behind it is a reconciliation nobody can complete, and it surfaces at the worst moment, when the contract closes and the totals have to agree.",
  estMinutes: 12,
  steps: [
    {
      id: "measure",
      icon: "Ruler",
      inputs: [
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.measure.in.smeta",
          label: "Approved smeta",
        },
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.measure.in.executed",
          label: "Work executed this period",
        },
      ],
      outputs: [
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.measure.out.percent",
          label: "Percent complete per smeta position",
        },
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.measure.out.volumes",
          label: "Executed volumes for the period",
        },
      ],
      titleKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.measure.title",
      titleDefault: "Measure the period smeta position by smeta position",
      whatKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.measure.what",
      whatDefault:
        "Record what was executed against each smeta position for the period as a percentage of its contract quantity. The earned quantity follows from that percentage and the design quantity, and the earned amount from the same percentage and the position total, so one honest number per line produces the whole valuation.",
      whyKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.measure.why",
      whyDefault:
        "A KS-2 act built from a single project percentage cannot be checked and therefore cannot be approved without a conversation. Measured line by line, the disagreement is about one smeta position rather than about the whole month, and the rest of the money moves while that one is settled.",
      moduleLabel: "Progress",
      moduleLabelKey: "nav.progress",
      to: "/progress",
    },
    {
      id: "value",
      icon: "Calculator",
      inputs: [
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.value.in.volumes",
          label: "Executed volumes for the period",
        },
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.value.in.norms",
          label: "GESN norms and smeta rates",
        },
      ],
      outputs: [
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.value.out.act",
          label: "KS-2 act for the period",
        },
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.value.out.additional",
          label: "Additional works flagged",
        },
      ],
      titleKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.value.title",
      titleDefault: "Value it at the contract rates",
      whatKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.value.what",
      whatDefault:
        "Read the valuation back against the bill and check the rates it used are the contract rates. Where a smeta position has been measured past the quantity the contract carries, deal with it as a change to the position with an order behind it rather than as a larger figure on the same line. A norm-based rate carries the labour, machinery and materials behind it, so the act can be read back to the resources it claims rather than to a single figure. That is what makes a disagreement about one position a conversation about one norm.",
      whyKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.value.why",
      whyDefault:
        "An additional works agreement certified quietly is one the client can refuse at the final account, months after the work was built and paid for down the chain. Raising it as a change while it is small is the only version of that conversation where you are not asking to be paid for work already done.",
      moduleLabel: "BOQ",
      moduleLabelKey: "boq.title",
      to: "/projects/:projectId/boq",
    },
    {
      id: "sign",
      icon: "Stamp",
      inputs: [
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.sign.in.act",
          label: "KS-2 act for the period",
        },
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.sign.in.supervisor",
          label: "Technical supervisor named for acceptance",
        },
      ],
      outputs: [
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.sign.out.signed",
          label: "Signed KS-2 act",
        },
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.sign.out.date",
          label: "Acceptance date on record",
        },
      ],
      titleKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.sign.title",
      titleDefault: "Get it approved by the people who have to approve it",
      whatKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.sign.what",
      whatDefault:
        "Route the KS-2 act to the client's technical supervisor, and to whoever the contract adds after them. Keep the approval date, because the KS-3 certificate follows the approval and the payment clock runs from there, so an approval that slips moves everything behind it.",
      whyKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.sign.why",
      whyDefault:
        "Approval sitting in an inbox is the most common reason a payment is late, and it is invisible while it is happening because nobody has refused anything. A route with a date on each hop turns that into a question with an owner instead of a monthly complaint.",
      moduleLabel: "Approval routes",
      moduleLabelKey: "approvalRoutes.title",
      to: "/approval-routes",
    },
    {
      id: "cumulative",
      icon: "Percent",
      inputs: [
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.cumulative.in.signed",
          label: "Signed KS-2 acts to date",
        },
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.cumulative.in.previous",
          label: "Previous payments and guarantee retention",
        },
      ],
      outputs: [
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.cumulative.out.cumulative",
          label: "Cumulative value of works",
        },
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.cumulative.out.net",
          label: "Net due for the period",
        },
      ],
      titleKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.cumulative.title",
      titleDefault: "Apply guarantee retention and previous payments",
      whatKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.cumulative.what",
      whatDefault:
        "Take the cumulative valuation, subtract what has already been certified, and apply guarantee retention at the contract percentage. The figure that leaves this step is the one the KS-3 certificate is raised for, and the backup behind it is the measure that produced it.",
      whyKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.cumulative.why",
      whyDefault:
        "Interim payments are cumulative, so the month's money is a difference between two totals rather than a total of its own. Computing it from the cumulative figure is what stops a line being paid twice or dropped entirely when a period is re-measured.",
      moduleLabel: "Finance",
      moduleLabelKey: "nav.finance",
      to: "/projects/:projectId/finance",
    },
    {
      id: "ks3",
      icon: "ReceiptText",
      inputs: [
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.ks3.in.cumulative",
          label: "Cumulative value of works",
        },
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.ks3.in.retention",
          label: "Guarantee retention and deductions",
        },
      ],
      outputs: [
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.ks3.out.ks3",
          label: "KS-3 certificate issued",
        },
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.ks3.out.carried",
          label: "Amount carried into the accounts",
        },
      ],
      titleKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.ks3.title",
      titleDefault: "Issue the KS-3 certificate against the approved figure",
      whatKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.ks3.what",
      whatDefault:
        "Raise the KS-3 certificate against the approved KS-2 act, carrying guarantee retention and any deduction the contract provides for, and reference the KS-2 act on it.",
      whyKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.ks3.why",
      whyDefault:
        "A demand for a figure nobody approved is one that will be returned, and the clock does not start on a returned document. Matching it to the KS-2 act also means the accounts and the valuation tell the same story at year end without anybody reconciling them by hand.",
      moduleLabel: "Finance",
      moduleLabelKey: "nav.finance",
      to: "/projects/:projectId/finance",
    },
    {
      id: "reconcile",
      icon: "Scale",
      inputs: [
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.reconcile.in.asked",
          label: "Amount certified on the KS-3",
        },
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.reconcile.in.accepted",
          label: "Amount accepted on the KS-2 acts",
        },
      ],
      outputs: [
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.reconcile.out.difference",
          label: "Difference carried forward",
        },
        {
          labelKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.reconcile.out.aged",
          label: "Outstanding by age",
        },
      ],
      titleKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.reconcile.title",
      titleDefault: "Reconcile what was certified against what was asked",
      whatKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.reconcile.what",
      whatDefault:
        "Put the approved figure next to the figure you asked for and carry the difference forward. What is unpaid, and how long it has been unpaid, belongs in the accounts as a number rather than in a conversation.",
      whyKey: "cases.close_the_month_with_a_ks_2_act_and_a_ks_3_certificate.step.reconcile.why",
      whyDefault:
        "The gap between applied and certified is the health of the commercial relationship expressed as money, and it is only visible if somebody puts the two numbers side by side every period. Cumulatively it is also the single best predictor of a final account fight. The two forms are reconciled at contract close whether or not anybody reconciled them monthly, and a year of small differences is not a month of arithmetic. Doing it every period is the same work spread over the time when it is still cheap to correct.",
      moduleLabel: "Event Reconciliation",
      moduleLabelKey: "nav.reconciliation",
      to: "/projects/:projectId/reconciliation",
    },
  ],
};

export default playbook;
