// DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
// Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
//
// Case: "Get the teljesitesigazolas signed and invoice the period" (HU).
//
// GENERATED. Do not edit this file by hand, the next compose run
// will overwrite it. The workflow lives once at
//   frontend/src/features/cases/intl/spines/f01-progress-payment.json
// and this country's words and step order live at
//   frontend/src/features/cases/intl/layers/f01-progress-payment/HU.json
//
// Hungary hangs the whole period on one document: without a signed
// teljesitesigazolas there is no lawful invoice, and the dispute that
// follows a refused one has its own forum rather than the courts. So
// this layer surfaces register, measure, certify, invoice, clock,
// deadlines and escalate, and the escalation slot names the expert
// body rather than a letter.
//
// Rebuild with:
//   node frontend/scripts/compose-case-layers.mjs --family f01-progress-payment

import type { Playbook } from "../types";

const playbook: Playbook = {
  id: "get-the-teljesitesigazolas-signed-and-invoice-the-period",
  order: 1240,
  region: "HU",
  category: "commercial",
  companyTypes: ["general-contractor", "subcontractor", "cost-consultant"],
  roles: ["contract-administrator", "commercial-manager", "quantity-surveyor"],
  icon: "FileCheck2",
  titleKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.title",
  titleDefault: "Get the teljesitesigazolas signed and invoice the period",
  descKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.desc",
  descDefault:
    "Register the contract, measure the period tetel by tetel, get the muszaki ellenor to sign the teljesitesigazolas, raise the szamla against it and let the module count the days the payment rules allow, so a refusal to certify is a dated fact with a forum rather than a stalemate.",
  longDescKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.longdesc",
  longDescDefault:
    "Hungarian construction payment turns on the teljesitesigazolas, and the reason it matters is that the contractor cannot lawfully invoice without one. That gives the certifying party a great deal of leverage and creates the failure everybody in the chain recognises: work is finished, nobody disputes it was finished, and the certificate does not arrive. The law answers that with a dedicated expert body rather than a lawsuit, but the answer is only available to a contractor who can show what was submitted, when, and what came back. Kept as the period runs, that record is a filing. Reconstructed afterwards it is an argument.",
  estMinutes: 12,
  steps: [
    {
      id: "register",
      icon: "FileSignature",
      inputs: [
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.register.in.szerzodes",
          label: "Signed vallalkozasi szerzodes",
        },
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.register.in.koltsegvetes",
          label: "Priced koltsegvetes",
        },
      ],
      outputs: [
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.register.out.registered",
          label: "Contract on record",
        },
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.register.out.terms",
          label: "Certification and payment terms attached",
        },
      ],
      titleKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.register.title",
      titleDefault: "Register the contract and its payment regime",
      whatKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.register.what",
      whatDefault:
        "Record the contract, its the Ptk. Payment rules payment regime and the dates it turns on, so every later step reads the same terms instead of somebody's memory of them.",
      whyKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.register.why",
      whyDefault:
        "A payment regime that lives in a PDF nobody opens is a regime that gets applied differently by each person who applies it. Registered once, the deadlines below are computed rather than argued about.",
      moduleLabel: "Contracts",
      moduleLabelKey: "nav.contracts",
      to: "/projects/:projectId/contracts",
    },
    {
      id: "measure",
      icon: "Ruler",
      inputs: [
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.measure.in.koltsegvetes",
          label: "Priced koltsegvetes",
        },
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.measure.in.executed",
          label: "Work executed this period",
        },
      ],
      outputs: [
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.measure.out.percent",
          label: "Percent complete per tetel",
        },
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.measure.out.quantities",
          label: "Earned quantities for the period",
        },
      ],
      titleKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.measure.title",
      titleDefault: "Measure the period tetel by tetel",
      whatKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.measure.what",
      whatDefault:
        "Record what was executed against each tetel for the period as a percentage of its contract quantity. The earned quantity follows from that percentage and the design quantity, and the earned amount from the same percentage and the position total, so one honest number per line produces the whole valuation. Keep potmunka on its own tetel rather than inside an existing one. A certifier who has to decide the whole period in order to decide the extra will decide neither.",
      whyKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.measure.why",
      whyDefault:
        "A teljesitesigazolas built from a single project percentage cannot be checked and therefore cannot be approved without a conversation. Measured line by line, the disagreement is about one tetel rather than about the whole month, and the rest of the money moves while that one is settled.",
      moduleLabel: "Progress",
      moduleLabelKey: "nav.progress",
      to: "/progress",
    },
    {
      id: "igazolas",
      icon: "Stamp",
      inputs: [
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.igazolas.in.valuation",
          label: "Valuation for the period",
        },
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.igazolas.in.ellenor",
          label: "Muszaki ellenor named for certification",
        },
      ],
      outputs: [
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.igazolas.out.signed",
          label: "Signed teljesitesigazolas",
        },
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.igazolas.out.date",
          label: "Certification date on record",
        },
      ],
      titleKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.igazolas.title",
      titleDefault: "Get it approved by the people who have to approve it",
      whatKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.igazolas.what",
      whatDefault:
        "Route the teljesitesigazolas to the muszaki ellenor, and to whoever the contract adds after them. Keep the approval date, because the szamla follows the approval and the payment clock runs from there, so an approval that slips moves everything behind it.",
      whyKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.igazolas.why",
      whyDefault:
        "Approval sitting in an inbox is the most common reason a payment is late, and it is invisible while it is happening because nobody has refused anything. A route with a date on each hop turns that into a question with an owner instead of a monthly complaint. A certificate that is refused and a certificate that has simply not arrived look identical from the contractor's side, and the remedies for them are different. Recording the submission date is what tells the two apart.",
      moduleLabel: "Approval routes",
      moduleLabelKey: "approvalRoutes.title",
      to: "/approval-routes",
    },
    {
      id: "szamla",
      icon: "ReceiptText",
      inputs: [
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.szamla.in.signed",
          label: "Signed teljesitesigazolas",
        },
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.szamla.in.visszatartas",
          label: "Visszatartas and deductions",
        },
      ],
      outputs: [
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.szamla.out.szamla",
          label: "Szamla issued",
        },
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.szamla.out.carried",
          label: "Amount carried into the accounts",
        },
      ],
      titleKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.szamla.title",
      titleDefault: "Issue the szamla against the approved figure",
      whatKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.szamla.what",
      whatDefault:
        "Raise the szamla against the approved teljesitesigazolas, carrying visszatartas and any deduction the contract provides for, and reference the teljesitesigazolas on it. Between businesses the domestic reverse charge usually applies to construction work, so the szamla carries the note and the customer accounts for the tax rather than the rate appearing on the invoice.",
      whyKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.szamla.why",
      whyDefault:
        "A demand for a figure nobody approved is one that will be returned, and the clock does not start on a returned document. Matching it to the teljesitesigazolas also means the accounts and the valuation tell the same story at year end without anybody reconciling them by hand.",
      moduleLabel: "Finance",
      moduleLabelKey: "nav.finance",
      to: "/projects/:projectId/finance",
    },
    {
      id: "openclock",
      icon: "Clock",
      inputs: [
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.openclock.in.szamla",
          label: "Szamla and its date",
        },
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.openclock.in.terms",
          label: "Contract payment terms",
        },
      ],
      outputs: [
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.openclock.out.clock",
          label: "Open payment clock",
        },
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.openclock.out.due",
          label: "Due date computed",
        },
      ],
      titleKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.openclock.title",
      titleDefault: "Open the payment clock on the right day",
      whatKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.openclock.what",
      whatDefault:
        "Open a clock over the szamla starting from the day the szamla is received, under the Ptk. Payment rules. Payment falls due 30 days later, and the clock records that date rather than leaving it to be worked out when somebody asks.",
      whyKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.openclock.why",
      whyDefault:
        "The single most expensive mistake in interim payment is starting the count on the wrong event, because every deadline behind it inherits the error and none of them look wrong. Anchoring on the day the szamla is received once makes the whole chain checkable.",
      moduleLabel: "Payment Clock",
      moduleLabelKey: "nav.payment_clock",
      to: "/payment-clock",
    },
    {
      id: "dates",
      icon: "CalendarClock",
      inputs: [
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.dates.in.clock",
          label: "Open payment clock",
        },
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.dates.in.regime",
          label: "Chosen regime",
        },
      ],
      outputs: [
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.dates.out.due",
          label: "Due date",
        },
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.dates.out.derivation",
          label: "Derivation you can quote",
        },
      ],
      titleKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.dates.title",
      titleDefault: "Read the dates the regime computes",
      whatKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.dates.what",
      whatDefault:
        "Read back the dates the Ptk. Payment rules produces from the day the szamla is received. The sum payable leads, the due date and the final date for payment sit under it, and the derivation spells out each date against the provision it came from, so every one of them can be quoted rather than asserted.",
      whyKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.dates.why",
      whyDefault:
        "Deadlines that are typed in are deadlines that are typed in wrong, and a payment regime has more of them than anyone holds in their head. A derivation you can read out loud is what turns a phone call about a late payment into a quotable line.",
      moduleLabel: "Payment Clock",
      moduleLabelKey: "nav.payment_clock",
      to: "/payment-clock",
    },
    {
      id: "escalate",
      icon: "Gavel",
      inputs: [
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.escalate.in.passed",
          label: "Passed deadlines",
        },
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.escalate.in.record",
          label: "Submissions and certification dates",
        },
      ],
      outputs: [
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.escalate.out.filing",
          label: "Expert body filing",
        },
        {
          labelKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.escalate.out.entitlement",
          label: "Entitlement preserved",
        },
      ],
      titleKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.escalate.title",
      titleDefault: "Escalate with the record already assembled",
      whatKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.escalate.what",
      whatDefault:
        "When the clock has run out, take it to the Teljesitesigazolasi Szakertoi Szerv and preserve the claim. The record the steps above produced, dates, approvals and the documents themselves, is the case, and it is assembled already rather than reconstructed under time pressure.",
      whyKey: "cases.get_the_teljesitesigazolas_signed_and_invoice_the_period.step.escalate.why",
      whyDefault:
        "The difference between a claim that is paid and one that is argued about is almost never the merits. It is whether the dates and the documents were kept as the work happened, because reconstructing them afterwards is expensive and looks exactly like inventing them.",
      moduleLabel: "Documents",
      moduleLabelKey: "nav.documents",
      to: "/projects/:projectId/files",
    },
  ],
};

export default playbook;
