// DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
// Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
//
// Case: "Issue the interim payment certificate and get paid on it" (ZA).
//
// GENERATED. Do not edit this file by hand, the next compose run
// will overwrite it. The workflow lives once at
//   frontend/src/features/cases/intl/spines/f01-progress-payment.json
// and this country's words and step order live at
//   frontend/src/features/cases/intl/layers/f01-progress-payment/ZA.json
//
// South Africa runs the shortest payment window in the family, which
// is why this layer surfaces the deadlines and the watch steps rather
// than stopping at the invoice. Seven calendar days from the
// certificate leaves no room for a certificate that was issued and not
// read, so the clock is opened on the certificate date rather than on
// the invoice date.
//
// Rebuild with:
//   node frontend/scripts/compose-case-layers.mjs --family f01-progress-payment

import type { Playbook } from "../types";

const playbook: Playbook = {
  id: "issue-the-interim-payment-certificate-and-get-paid-on-it",
  order: 1340,
  region: "ZA",
  category: "commercial",
  companyTypes: ["general-contractor", "subcontractor", "cost-consultant"],
  roles: ["contract-administrator", "commercial-manager", "quantity-surveyor"],
  icon: "CalendarClock",
  titleKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.title",
  titleDefault: "Issue the interim payment certificate and get paid on it",
  descKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.desc",
  descDefault:
    "Measure the period against the bill, value it at the contract rates, hold retention, get the principal agent to issue the interim payment certificate and open the clock on the certificate date, because the window that follows it is measured in days rather than weeks.",
  longDescKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.longdesc",
  longDescDefault:
    "The distinctive thing about this payment regime is how little time it leaves. The principal agent issues an interim payment certificate and the employer pays within a handful of calendar days of the certificate date, which means the certificate is the event that matters and the invoice is administration behind it. Firms that run the clock from their own invoice date consistently discover they were already late, because the days were counting while the paperwork moved internally. Opening the clock on the certificate, and watching it rather than filing it, is the whole difference between a payment that arrives and a default the contract has a remedy for.",
  estMinutes: 12,
  steps: [
    {
      id: "measure",
      icon: "Ruler",
      inputs: [
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.measure.in.bill",
          label: "Contract bill of quantities",
        },
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.measure.in.works",
          label: "Work executed this period",
        },
      ],
      outputs: [
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.measure.out.percent",
          label: "Percent complete per bill item",
        },
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.measure.out.quantities",
          label: "Earned quantities for the period",
        },
      ],
      titleKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.measure.title",
      titleDefault: "Measure the period bill item by bill item",
      whatKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.measure.what",
      whatDefault:
        "Record what was executed against each bill item for the period as a percentage of its contract quantity. The earned quantity follows from that percentage and the design quantity, and the earned amount from the same percentage and the position total, so one honest number per line produces the whole valuation.",
      whyKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.measure.why",
      whyDefault:
        "An interim payment certificate built from a single project percentage cannot be checked and therefore cannot be approved without a conversation. Measured line by line, the disagreement is about one bill item rather than about the whole month, and the rest of the money moves while that one is settled.",
      moduleLabel: "Progress",
      moduleLabelKey: "nav.progress",
      to: "/progress",
    },
    {
      id: "value",
      icon: "Calculator",
      inputs: [
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.value.in.quantities",
          label: "Earned quantities for the period",
        },
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.value.in.rates",
          label: "Contract rates",
        },
      ],
      outputs: [
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.value.out.valuation",
          label: "Valuation for the period",
        },
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.value.out.instructions",
          label: "Contract instructions flagged",
        },
      ],
      titleKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.value.title",
      titleDefault: "Value it at the contract rates",
      whatKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.value.what",
      whatDefault:
        "Read the valuation back against the bill and check the rates it used are the contract rates. Where a bill item has been measured past the quantity the contract carries, deal with it as a change to the position with an order behind it rather than as a larger figure on the same line.",
      whyKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.value.why",
      whyDefault:
        "A contract instruction certified quietly is one the client can refuse at the final account, months after the work was built and paid for down the chain. Raising it as a change while it is small is the only version of that conversation where you are not asking to be paid for work already done.",
      moduleLabel: "BOQ",
      moduleLabelKey: "boq.title",
      to: "/projects/:projectId/boq",
    },
    {
      id: "retention",
      icon: "Percent",
      inputs: [
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.retention.in.cumulative",
          label: "Cumulative valuation",
        },
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.retention.in.previous",
          label: "Previous payments and retention",
        },
      ],
      outputs: [
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.retention.out.held",
          label: "Retention held to date",
        },
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.retention.out.net",
          label: "Net due for the period",
        },
      ],
      titleKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.retention.title",
      titleDefault: "Apply retention and previous payments",
      whatKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.retention.what",
      whatDefault:
        "Take the cumulative valuation, subtract what has already been certified, and apply retention at the contract percentage. The figure that leaves this step is the one the tax invoice is raised for, and the backup behind it is the measure that produced it.",
      whyKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.retention.why",
      whyDefault:
        "Interim payments are cumulative, so the month's money is a difference between two totals rather than a total of its own. Computing it from the cumulative figure is what stops a line being paid twice or dropped entirely when a period is re-measured.",
      moduleLabel: "Finance",
      moduleLabelKey: "nav.finance",
      to: "/projects/:projectId/finance",
    },
    {
      id: "certify",
      icon: "Stamp",
      inputs: [
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.certify.in.valuation",
          label: "Valuation for the period",
        },
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.certify.in.agent",
          label: "Principal agent named for certification",
        },
      ],
      outputs: [
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.certify.out.certificate",
          label: "Interim payment certificate issued",
        },
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.certify.out.date",
          label: "Certificate date on record",
        },
      ],
      titleKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.certify.title",
      titleDefault: "Get it approved by the people who have to approve it",
      whatKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.certify.what",
      whatDefault:
        "Route the interim payment certificate to the principal agent, and to whoever the contract adds after them. Keep the approval date, because the tax invoice follows the approval and the payment clock runs from there, so an approval that slips moves everything behind it.",
      whyKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.certify.why",
      whyDefault:
        "Approval sitting in an inbox is the most common reason a payment is late, and it is invisible while it is happening because nobody has refused anything. A route with a date on each hop turns that into a question with an owner instead of a monthly complaint.",
      moduleLabel: "Approval routes",
      moduleLabelKey: "approvalRoutes.title",
      to: "/approval-routes",
    },
    {
      id: "invoice",
      icon: "ReceiptText",
      inputs: [
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.invoice.in.certificate",
          label: "Interim payment certificate issued",
        },
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.invoice.in.retention",
          label: "Retention and deductions",
        },
      ],
      outputs: [
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.invoice.out.invoice",
          label: "Tax invoice issued",
        },
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.invoice.out.carried",
          label: "Amount carried into the accounts",
        },
      ],
      titleKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.invoice.title",
      titleDefault: "Issue the tax invoice against the approved figure",
      whatKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.invoice.what",
      whatDefault:
        "Raise the tax invoice against the approved interim payment certificate, carrying retention and any deduction the contract provides for, and reference the interim payment certificate on it.",
      whyKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.invoice.why",
      whyDefault:
        "A demand for a figure nobody approved is one that will be returned, and the clock does not start on a returned document. Matching it to the interim payment certificate also means the accounts and the valuation tell the same story at year end without anybody reconciling them by hand.",
      moduleLabel: "Finance",
      moduleLabelKey: "nav.finance",
      to: "/projects/:projectId/finance",
    },
    {
      id: "openclock",
      icon: "Clock",
      inputs: [
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.openclock.in.certificate",
          label: "Certificate and its date",
        },
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.openclock.in.amount",
          label: "Certified amount",
        },
      ],
      outputs: [
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.openclock.out.clock",
          label: "Open payment clock",
        },
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.openclock.out.due",
          label: "Due date computed",
        },
      ],
      titleKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.openclock.title",
      titleDefault: "Open the payment clock on the right day",
      whatKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.openclock.what",
      whatDefault:
        "Open a clock over the tax invoice starting from the date of the interim payment certificate, under the contract payment provisions. Payment falls due 7 days later, and the clock records that date rather than leaving it to be worked out when somebody asks.",
      whyKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.openclock.why",
      whyDefault:
        "The single most expensive mistake in interim payment is starting the count on the wrong event, because every deadline behind it inherits the error and none of them look wrong. Anchoring on the date of the interim payment certificate once makes the whole chain checkable. Opening it on your own invoice date rather than on the certificate date moves every deadline later and does it silently, which is the version of this mistake that never gets caught, because nothing looks overdue until the remedy has already expired.",
      moduleLabel: "Payment Clock",
      moduleLabelKey: "nav.payment_clock",
      to: "/payment-clock",
    },
    {
      id: "dates",
      icon: "CalendarClock",
      inputs: [
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.dates.in.clock",
          label: "Open payment clock",
        },
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.dates.in.regime",
          label: "Chosen regime",
        },
      ],
      outputs: [
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.dates.out.due",
          label: "Due date",
        },
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.dates.out.derivation",
          label: "Derivation you can quote",
        },
      ],
      titleKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.dates.title",
      titleDefault: "Read the dates the regime computes",
      whatKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.dates.what",
      whatDefault:
        "Read back the dates the contract payment provisions produces from the date of the interim payment certificate. The sum payable leads, the due date and the final date for payment sit under it, and the derivation spells out each date against the provision it came from, so every one of them can be quoted rather than asserted.",
      whyKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.dates.why",
      whyDefault:
        "Deadlines that are typed in are deadlines that are typed in wrong, and a payment regime has more of them than anyone holds in their head. A derivation you can read out loud is what turns a phone call about a late payment into a quotable line.",
      moduleLabel: "Payment Clock",
      moduleLabelKey: "nav.payment_clock",
      to: "/payment-clock",
    },
    {
      id: "watch",
      icon: "AlertTriangle",
      inputs: [
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.watch.in.clocks",
          label: "Open clocks on the project",
        },
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.watch.in.finaldates",
          label: "Final dates for payment",
        },
      ],
      outputs: [
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.watch.out.overdue",
          label: "Overdue certificates flagged",
        },
        {
          labelKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.watch.out.register",
          label: "Breach register rows",
        },
      ],
      titleKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.watch.title",
      titleDefault: "Watch the clock count each deadline down",
      whatKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.watch.what",
      whatDefault:
        "Come back to the list as the month runs. It says how many clocks the project carries and how many are past their final date, badges the overdue ones and fills the breach register underneath. Open an overdue one and the findings name the sum outstanding, the days it has run past the final date and the rate interest runs at.",
      whyKey: "cases.issue_the_interim_payment_certificate_and_get_paid_on_it.step.watch.why",
      whyDefault:
        "Reading a clock is what writes its register, so a quiet register on a project nobody opens is telling you about the reading and not about the payments. Nobody misses a deadline on purpose; they miss it because the day it mattered looked like every other day.",
      moduleLabel: "Payment Clock",
      moduleLabelKey: "nav.payment_clock",
      to: "/payment-clock",
    },
  ],
};

export default playbook;
