// DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
// Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
//
// Case: "Prepare an interim payment application".
//
// GENERATED. Do not edit this file by hand, the next compose run
// will overwrite it. The workflow lives once at
//   frontend/src/features/cases/intl/spines/f01-progress-payment.json
// and this country's words and step order live at
//   frontend/src/features/cases/intl/layers/f01-progress-payment/XX.json
//
// The country-neutral member of the family. It fills the same slots
// with the vocabulary a reader in no particular country would use,
// which is what makes it a layer rather than a special case.
//
// Rebuild with:
//   node frontend/scripts/compose-case-layers.mjs --family f01-progress-payment

import type { Playbook } from "../types";

const playbook: Playbook = {
  id: "prepare-an-interim-payment-application",
  order: 267,
  category: "commercial",
  companyTypes: ["general-contractor", "subcontractor", "cost-consultant"],
  roles: ["commercial-manager", "quantity-surveyor"],
  icon: "ReceiptText",
  titleKey: "cases.prepare_an_interim_payment_application.title",
  titleDefault: "Prepare an interim payment application",
  descKey: "cases.prepare_an_interim_payment_application.desc",
  descDefault:
    "Build the monthly interim application: measure the work done to date, value it against the contract sum plus agreed variations, apply retention, and issue the application with its backup so it certifies in full.",
  estMinutes: 10,
  steps: [
    {
      id: "measure",
      icon: "Ruler",
      inputs: [
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.measure.in.boq",
          label: "BOQ lines",
        },
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.measure.in.works",
          label: "Work in place",
        },
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.measure.in.cutoff",
          label: "Cut-off date",
        },
      ],
      outputs: [
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.measure.out.percent",
          label: "Percentage complete",
        },
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.measure.out.measured",
          label: "Measured quantities",
        },
      ],
      titleKey: "cases.prepare_an_interim_payment_application.step.measure.title",
      titleDefault: "Measure the period bill item by bill item",
      whatKey: "cases.prepare_an_interim_payment_application.step.measure.what",
      whatDefault:
        "Record what was executed against each bill item for the period as a percentage of its contract quantity. The earned quantity follows from that percentage and the design quantity, and the earned amount from the same percentage and the position total, so one honest number per line produces the whole valuation.",
      whyKey: "cases.prepare_an_interim_payment_application.step.measure.why",
      whyDefault:
        "An interim valuation built from a single project percentage cannot be checked and therefore cannot be approved without a conversation. Measured line by line, the disagreement is about one bill item rather than about the whole month, and the rest of the money moves while that one is settled.",
      moduleLabel: "BOQ",
      moduleLabelKey: "boq.title",
      to: "/projects/:projectId/boq",
    },
    {
      id: "value",
      icon: "TrendingUp",
      inputs: [
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.value.in.measured",
          label: "Measured work",
        },
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.value.in.sum",
          label: "Contract sum",
        },
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.value.in.variations",
          label: "Agreed variations",
        },
      ],
      outputs: [
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.value.out.gross",
          label: "Gross value earned",
        },
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.value.out.breakdown",
          label: "Value breakdown",
        },
      ],
      titleKey: "cases.prepare_an_interim_payment_application.step.value.title",
      titleDefault: "Value it at the contract rates",
      whatKey: "cases.prepare_an_interim_payment_application.step.value.what",
      whatDefault:
        "Read the valuation back against the bill and check the rates it used are the contract rates. Where a bill item has been measured past the quantity the contract carries, deal with it as a change to the position with an order behind it rather than as a larger figure on the same line.",
      whyKey: "cases.prepare_an_interim_payment_application.step.value.why",
      whyDefault:
        "A variation certified quietly is one the client can refuse at the final account, months after the work was built and paid for down the chain. Raising it as a change while it is small is the only version of that conversation where you are not asking to be paid for work already done.",
      moduleLabel: "Value Realized",
      moduleLabelKey: "nav.value",
      to: "/projects/:projectId/value",
    },
    {
      id: "retention",
      icon: "Calculator",
      inputs: [
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.retention.in.gross",
          label: "Gross value earned",
        },
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.retention.in.rate",
          label: "Retention rate",
        },
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.retention.in.previous",
          label: "Previous payments",
        },
      ],
      outputs: [
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.retention.out.retention",
          label: "Retention held",
        },
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.retention.out.net",
          label: "Net sum due",
        },
      ],
      titleKey: "cases.prepare_an_interim_payment_application.step.retention.title",
      titleDefault: "Apply retention and previous payments",
      whatKey: "cases.prepare_an_interim_payment_application.step.retention.what",
      whatDefault:
        "Take the cumulative valuation, subtract what has already been certified, and apply retention at the contract percentage. The figure that leaves this step is the one the interim application is raised for, and the backup behind it is the measure that produced it.",
      whyKey: "cases.prepare_an_interim_payment_application.step.retention.why",
      whyDefault:
        "Interim payments are cumulative, so the month's money is a difference between two totals rather than a total of its own. Computing it from the cumulative figure is what stops a line being paid twice or dropped entirely when a period is re-measured.",
      moduleLabel: "Finance",
      moduleLabelKey: "nav.finance",
      to: "/projects/:projectId/finance",
    },
    {
      id: "issue",
      icon: "ReceiptText",
      inputs: [
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.issue.in.net",
          label: "Net sum due",
        },
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.issue.in.breakdown",
          label: "Measured breakdown",
        },
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.issue.in.retention",
          label: "Retention calculation",
        },
      ],
      outputs: [
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.issue.out.application",
          label: "Submitted application",
        },
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.issue.out.backup",
          label: "Backup pack",
        },
      ],
      titleKey: "cases.prepare_an_interim_payment_application.step.issue.title",
      titleDefault: "Issue the interim application against the approved figure",
      whatKey: "cases.prepare_an_interim_payment_application.step.issue.what",
      whatDefault:
        "Raise the interim application against the approved interim valuation, carrying retention and any deduction the contract provides for, and reference the interim valuation on it.",
      whyKey: "cases.prepare_an_interim_payment_application.step.issue.why",
      whyDefault:
        "A demand for a figure nobody approved is one that will be returned, and the clock does not start on a returned document. Matching it to the interim valuation also means the accounts and the valuation tell the same story at year end without anybody reconciling them by hand.",
      moduleLabel: "Reports",
      moduleLabelKey: "nav.reports",
      to: "/reports",
    },
    {
      id: "reconcile",
      icon: "Scale",
      inputs: [
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.reconcile.in.applied",
          label: "Submitted application",
        },
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.reconcile.in.certificate",
          label: "Payment certificate",
        },
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.reconcile.in.backup",
          label: "Measure and backup",
        },
      ],
      outputs: [
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.reconcile.out.reconciliation",
          label: "Reconciliation statement",
        },
        {
          labelKey: "cases.prepare_an_interim_payment_application.step.reconcile.out.cuts",
          label: "Cut-back lines",
        },
      ],
      titleKey: "cases.prepare_an_interim_payment_application.step.reconcile.title",
      titleDefault: "Reconcile what was certified against what was asked",
      whatKey: "cases.prepare_an_interim_payment_application.step.reconcile.what",
      whatDefault:
        "Put the approved figure next to the figure you asked for and carry the difference forward. What is unpaid, and how long it has been unpaid, belongs in the accounts as a number rather than in a conversation.",
      whyKey: "cases.prepare_an_interim_payment_application.step.reconcile.why",
      whyDefault:
        "The gap between applied and certified is the health of the commercial relationship expressed as money, and it is only visible if somebody puts the two numbers side by side every period. Cumulatively it is also the single best predictor of a final account fight.",
      moduleLabel: "Event Reconciliation",
      moduleLabelKey: "nav.reconciliation",
      to: "/projects/:projectId/reconciliation",
    },
  ],
};

export default playbook;
