// DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
// Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
//
// Case: "Run the security of payment clock on a progress claim" (AU).
//
// GENERATED. Do not edit this file by hand, the next compose run
// will overwrite it. The workflow lives once at
//   frontend/src/features/cases/intl/spines/f01-progress-payment.json
// and this country's words and step order live at
//   frontend/src/features/cases/intl/layers/f01-progress-payment/AU.json
//
// Australia surfaces the whole arc from measurement to adjudication,
// because the statutory regime here attaches to the claim rather than
// to the certificate: serving the payment claim is what starts the
// clock, and the Superintendent's certificate sits inside that window
// rather than in front of it. The Act counts business days, so payDays
// carries the word and the sentence reads correctly without the spine
// knowing that some regimes count calendar days and some do not.
//
// Rebuild with:
//   node frontend/scripts/compose-case-layers.mjs --family f01-progress-payment

import type { Playbook } from "../types";

const playbook: Playbook = {
  id: "run-the-security-of-payment-clock-on-a-progress-claim",
  order: 1200,
  region: "AU",
  category: "commercial",
  companyTypes: ["general-contractor", "subcontractor", "cost-consultant"],
  roles: ["contract-administrator", "commercial-manager", "quantity-surveyor"],
  icon: "CalendarClock",
  titleKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.title",
  titleDefault: "Run the security of payment clock on a progress claim",
  descKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.desc",
  descDefault:
    "Measure the period against the contract schedule, submit the progress claim to the Superintendent, serve it as a payment claim under the Security of Payment Act and let the module count the business days the respondent has, so a late payment is a dated record rather than a phone call.",
  longDescKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.longdesc",
  longDescDefault:
    "The Australian security of payment regime is fast and it is unforgiving of the claimant who cannot say what was served and when. A payment claim starts a clock the respondent answers with a payment schedule; if no schedule comes, the claimed amount becomes the amount payable, and if a schedule comes short the difference goes to adjudication on a timetable measured in business days. All of that turns on dates, and dates are exactly what nobody can reconstruct three months later. Measured line by line, served on a recorded date and watched as it counts down, the claim is either paid or it is an adjudication application with its evidence already assembled.",
  estMinutes: 12,
  steps: [
    {
      id: "measure",
      icon: "Ruler",
      inputs: [
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.measure.in.schedule",
          label: "Contract schedule of rates",
        },
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.measure.in.works",
          label: "Work executed this period",
        },
      ],
      outputs: [
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.measure.out.percent",
          label: "Percent complete per claim item",
        },
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.measure.out.quantities",
          label: "Earned quantities for the period",
        },
      ],
      titleKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.measure.title",
      titleDefault: "Measure the period claim item by claim item",
      whatKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.measure.what",
      whatDefault:
        "Record what was executed against each claim item for the period as a percentage of its contract quantity. The earned quantity follows from that percentage and the design quantity, and the earned amount from the same percentage and the position total, so one honest number per line produces the whole valuation.",
      whyKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.measure.why",
      whyDefault:
        "A progress claim built from a single project percentage cannot be checked and therefore cannot be approved without a conversation. Measured line by line, the disagreement is about one claim item rather than about the whole month, and the rest of the money moves while that one is settled.",
      moduleLabel: "Progress",
      moduleLabelKey: "nav.progress",
      to: "/progress",
    },
    {
      id: "value",
      icon: "Calculator",
      inputs: [
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.value.in.quantities",
          label: "Earned quantities for the period",
        },
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.value.in.rates",
          label: "Contract rates",
        },
      ],
      outputs: [
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.value.out.valuation",
          label: "Valuation for the period",
        },
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.value.out.variations",
          label: "Variations flagged",
        },
      ],
      titleKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.value.title",
      titleDefault: "Value it at the contract rates",
      whatKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.value.what",
      whatDefault:
        "Read the valuation back against the bill and check the rates it used are the contract rates. Where a claim item has been measured past the quantity the contract carries, deal with it as a change to the position with an order behind it rather than as a larger figure on the same line.",
      whyKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.value.why",
      whyDefault:
        "A variation certified quietly is one the client can refuse at the final account, months after the work was built and paid for down the chain. Raising it as a change while it is small is the only version of that conversation where you are not asking to be paid for work already done.",
      moduleLabel: "BOQ",
      moduleLabelKey: "boq.title",
      to: "/projects/:projectId/boq",
    },
    {
      id: "certify",
      icon: "Stamp",
      inputs: [
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.certify.in.valuation",
          label: "Valuation for the period",
        },
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.certify.in.superintendent",
          label: "Superintendent named for certification",
        },
      ],
      outputs: [
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.certify.out.certificate",
          label: "Progress certificate",
        },
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.certify.out.date",
          label: "Certification date on record",
        },
      ],
      titleKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.certify.title",
      titleDefault: "Get it approved by the people who have to approve it",
      whatKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.certify.what",
      whatDefault:
        "Route the progress claim to the Superintendent, and to whoever the contract adds after them. Keep the approval date, because the payment claim follows the approval and the payment clock runs from there, so an approval that slips moves everything behind it.",
      whyKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.certify.why",
      whyDefault:
        "Approval sitting in an inbox is the most common reason a payment is late, and it is invisible while it is happening because nobody has refused anything. A route with a date on each hop turns that into a question with an owner instead of a monthly complaint. The Superintendent certifies under the contract and the Act runs on its own timetable regardless, so a certificate that arrives late does not move the statutory dates. Recording both is what lets you see the two regimes disagree while there is still time to act on it.",
      moduleLabel: "Approval routes",
      moduleLabelKey: "approvalRoutes.title",
      to: "/approval-routes",
    },
    {
      id: "serve",
      icon: "ReceiptText",
      inputs: [
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.serve.in.certificate",
          label: "Progress certificate",
        },
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.serve.in.retention",
          label: "Retention and deductions",
        },
      ],
      outputs: [
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.serve.out.claim",
          label: "Payment claim served",
        },
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.serve.out.reference",
          label: "Reference to the Act on the claim",
        },
      ],
      titleKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.serve.title",
      titleDefault: "Issue the payment claim against the approved figure",
      whatKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.serve.what",
      whatDefault:
        "Raise the payment claim against the approved progress claim, carrying retention and any deduction the contract provides for, and reference the progress claim on it. The claim must say on its face that it is made under the Act, because a document that does not is not a payment claim and starts no clock at all.",
      whyKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.serve.why",
      whyDefault:
        "A demand for a figure nobody approved is one that will be returned, and the clock does not start on a returned document. Matching it to the progress claim also means the accounts and the valuation tell the same story at year end without anybody reconciling them by hand.",
      moduleLabel: "Finance",
      moduleLabelKey: "nav.finance",
      to: "/projects/:projectId/finance",
    },
    {
      id: "openclock",
      icon: "Clock",
      inputs: [
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.openclock.in.claim",
          label: "Payment claim served",
        },
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.openclock.in.served",
          label: "Date of service",
        },
      ],
      outputs: [
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.openclock.out.clock",
          label: "Open payment clock",
        },
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.openclock.out.due",
          label: "Due date computed",
        },
      ],
      titleKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.openclock.title",
      titleDefault: "Open the payment clock on the right day",
      whatKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.openclock.what",
      whatDefault:
        "Open a clock over the payment claim starting from the day the payment claim is served, under the Security of Payment Act. Payment falls due 15 business days later, and the clock records that date rather than leaving it to be worked out when somebody asks.",
      whyKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.openclock.why",
      whyDefault:
        "The single most expensive mistake in interim payment is starting the count on the wrong event, because every deadline behind it inherits the error and none of them look wrong. Anchoring on the day the payment claim is served once makes the whole chain checkable. Business days are not calendar days, and the state's public holidays move the answer. Counting them by hand is how a claimant arrives at adjudication one day out of time with a case that was otherwise good.",
      moduleLabel: "Payment Clock",
      moduleLabelKey: "nav.payment_clock",
      to: "/payment-clock",
    },
    {
      id: "dates",
      icon: "CalendarClock",
      inputs: [
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.dates.in.clock",
          label: "Open payment clock",
        },
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.dates.in.regime",
          label: "Statutory regime on record",
        },
      ],
      outputs: [
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.dates.out.schedule",
          label: "Date a payment schedule is due",
        },
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.dates.out.final",
          label: "Final date for payment",
        },
      ],
      titleKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.dates.title",
      titleDefault: "Read the dates the regime computes",
      whatKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.dates.what",
      whatDefault:
        "Read back the dates the Security of Payment Act produces from the day the payment claim is served. The sum payable leads, the due date and the final date for payment sit under it, and the derivation spells out each date against the provision it came from, so every one of them can be quoted rather than asserted. Two dates matter here and only one of them is about money: the date a payment schedule is due, and the date payment is due. A respondent who lets the first pass without a schedule has agreed to the claimed amount.",
      whyKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.dates.why",
      whyDefault:
        "Deadlines that are typed in are deadlines that are typed in wrong, and a payment regime has more of them than anyone holds in their head. A derivation you can read out loud is what turns a phone call about a late payment into a quotable line.",
      moduleLabel: "Payment Clock",
      moduleLabelKey: "nav.payment_clock",
      to: "/payment-clock",
    },
    {
      id: "adjudicate",
      icon: "Gavel",
      inputs: [
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.adjudicate.in.dates",
          label: "Passed deadlines",
        },
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.adjudicate.in.record",
          label: "Claim, schedule and service dates",
        },
      ],
      outputs: [
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.adjudicate.out.application",
          label: "Adjudication application",
        },
        {
          labelKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.adjudicate.out.entitlement",
          label: "Entitlement preserved",
        },
      ],
      titleKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.adjudicate.title",
      titleDefault: "Escalate with the record already assembled",
      whatKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.adjudicate.what",
      whatDefault:
        "When the clock has run out, lodge an adjudication application under the Security of Payment Act. The record the steps above produced, dates, approvals and the documents themselves, is the case, and it is assembled already rather than reconstructed under time pressure.",
      whyKey: "cases.run_the_security_of_payment_clock_on_a_progress_claim.step.adjudicate.why",
      whyDefault:
        "The difference between a claim that is paid and one that is argued about is almost never the merits. It is whether the dates and the documents were kept as the work happened, because reconstructing them afterwards is expensive and looks exactly like inventing them.",
      moduleLabel: "Documents",
      moduleLabelKey: "nav.documents",
      to: "/projects/:projectId/files",
    },
  ],
};

export default playbook;
