// DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
// Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
//
// Case: "Run the VOB/B payment clock" (DE).
//
// GENERATED. Do not edit this file by hand, the next compose run
// will overwrite it. The workflow lives once at
//   frontend/src/features/cases/intl/spines/f01-progress-payment.json
// and this country's words and step order live at
//   frontend/src/features/cases/intl/layers/f01-progress-payment/DE.json
//
// Germany surfaces the clock half of the same arc: it starts where the
// invoice is raised and follows the money out. It shares invoice,
// clock and reconcile with the other layers and adds register,
// deadlines, watch and escalate, which is what a spine covering the
// whole arc is for. The 21-day interim window under paragraph 16 VOB/B
// is a slot value, not a different sentence.
//
// Rebuild with:
//   node frontend/scripts/compose-case-layers.mjs --family f01-progress-payment

import type { Playbook } from "../types";

const playbook: Playbook = {
  id: "run-the-vob-payment-clock",
  order: 1053,
  region: "DE",
  category: "commercial",
  companyTypes: ["general-contractor", "subcontractor", "cost-consultant"],
  roles: ["contract-administrator", "commercial-manager", "quantity-surveyor"],
  icon: "CalendarClock",
  titleKey: "cases.run_the_vob_payment_clock.title",
  titleDefault: "Run the VOB/B payment clock",
  descKey: "cases.run_the_vob_payment_clock.desc",
  descDefault:
    "Register the contract, raise each Abschlagsrechnung against it, open a payment clock over the invoice and let the module count the days paragraph 16 VOB/B gives the client, so an overdue payment is a dated record rather than a feeling.",
  longDescKey: "cases.run_the_vob_payment_clock.longdesc",
  longDescDefault:
    "Money has a clock under VOB/B. An interim invoice falls due within 21 calendar days of the client receiving the verifiable statement of work, and the final invoice runs on its own longer window of 30 days, which the module carries as a second regime because they are two different clocks. A firm that does not track the chain - invoice out, period running, due, in default - is lending its client money at no charge and finds out months later, when the dates it would need are scattered across three inboxes.",
  estMinutes: 12,
  steps: [
    {
      id: "contract",
      icon: "FileSignature",
      inputs: [
        {
          labelKey: "cases.run_the_vob_payment_clock.step.contract.in.bauvertrag",
          label: "Signed Bauvertrag",
        },
        {
          labelKey: "cases.run_the_vob_payment_clock.step.contract.in.schedule",
          label: "Priced LV",
        },
      ],
      outputs: [
        {
          labelKey: "cases.run_the_vob_payment_clock.step.contract.out.registered",
          label: "Registered contract",
        },
        {
          labelKey: "cases.run_the_vob_payment_clock.step.contract.out.retention",
          label: "Sicherheitseinbehalt terms on record",
        },
      ],
      titleKey: "cases.run_the_vob_payment_clock.step.contract.title",
      titleDefault: "Register the contract and its payment regime",
      whatKey: "cases.run_the_vob_payment_clock.step.contract.what",
      whatDefault:
        "Record the contract, its paragraph 16 VOB/B payment regime and the dates it turns on, so every later step reads the same terms instead of somebody's memory of them.",
      whyKey: "cases.run_the_vob_payment_clock.step.contract.why",
      whyDefault:
        "A payment regime that lives in a PDF nobody opens is a regime that gets applied differently by each person who applies it. Registered once, the deadlines below are computed rather than argued about.",
      moduleLabel: "Contracts",
      moduleLabelKey: "nav.contracts",
      to: "/projects/:projectId/contracts",
    },
    {
      id: "claim",
      icon: "Calculator",
      inputs: [
        {
          labelKey: "cases.run_the_vob_payment_clock.step.claim.in.contract",
          label: "Registered contract",
        },
        {
          labelKey: "cases.run_the_vob_payment_clock.step.claim.in.measured",
          label: "Aufmass for the period",
        },
      ],
      outputs: [
        {
          labelKey: "cases.run_the_vob_payment_clock.step.claim.out.invoice",
          label: "Abschlagsrechnung",
        },
        {
          labelKey: "cases.run_the_vob_payment_clock.step.claim.out.net",
          label: "Net sum applied for",
        },
      ],
      titleKey: "cases.run_the_vob_payment_clock.step.claim.title",
      titleDefault: "Issue the Abschlagsrechnung against the Aufmass behind it",
      whatKey: "cases.run_the_vob_payment_clock.step.claim.what",
      whatDefault:
        "Raise the Abschlagsrechnung against the Aufmass behind it, carrying Sicherheitseinbehalt and any deduction the contract provides for, and reference the Aufmass on it. Take the Aufmass jointly with the client's site supervision wherever you can, as paragraph 14 (2) VOB/B provides, and attach it as the pruefbare Aufstellung, the verifiable statement of work an Abschlagsrechnung has to carry under paragraph 16 (1) VOB/B. Where the client is itself a construction business and holds a USt 1 TG certificate, the tax is accounted for by the client under paragraph 13b UStG, so the invoice carries the reverse-charge note and no tax rate.",
      whyKey: "cases.run_the_vob_payment_clock.step.claim.why",
      whyDefault:
        "Any Abschlagsrechnung the other side cannot check against the measure behind it comes back, and the clock does not start on a returned document. Matching it to the Aufmass also means the accounts and the valuation tell the same story at year end without anybody reconciling them by hand.",
      moduleLabel: "Contracts",
      moduleLabelKey: "nav.contracts",
      to: "/projects/:projectId/contracts",
    },
    {
      id: "openclock",
      icon: "Scale",
      inputs: [
        {
          labelKey: "cases.run_the_vob_payment_clock.step.openclock.in.invoice",
          label: "Abschlagsrechnung",
        },
        {
          labelKey: "cases.run_the_vob_payment_clock.step.openclock.in.receipt",
          label: "Day the client received the Aufstellung",
        },
        {
          labelKey: "cases.run_the_vob_payment_clock.step.openclock.in.amount",
          label: "Sum applied for",
        },
      ],
      outputs: [
        {
          labelKey: "cases.run_the_vob_payment_clock.step.openclock.out.clock",
          label: "Open payment clock",
        },
        {
          labelKey: "cases.run_the_vob_payment_clock.step.openclock.out.regime",
          label: "Statutory regime on record",
        },
      ],
      titleKey: "cases.run_the_vob_payment_clock.step.openclock.title",
      titleDefault: "Open the payment clock on the right day",
      whatKey: "cases.run_the_vob_payment_clock.step.openclock.what",
      whatDefault:
        "Open a clock over the Abschlagsrechnung starting from the client receiving the pruefbare Aufstellung, under paragraph 16 VOB/B. Payment falls due 21 days later, and the clock records that date rather than leaving it to be worked out when somebody asks.",
      whyKey: "cases.run_the_vob_payment_clock.step.openclock.why",
      whyDefault:
        "The single most expensive mistake in interim payment is starting the count on the wrong event, because every deadline behind it inherits the error and none of them look wrong. Anchoring on the client receiving the pruefbare Aufstellung once makes the whole chain checkable. The period runs from receipt, not from the day you printed the invoice. Entering the posting date moves every deadline in your own favour and leaves you holding a date you cannot prove on the one occasion it has to be proved.",
      moduleLabel: "Payment Clock",
      moduleLabelKey: "nav.payment_clock",
      to: "/payment-clock",
    },
    {
      id: "dates",
      icon: "CalendarClock",
      inputs: [
        {
          labelKey: "cases.run_the_vob_payment_clock.step.dates.in.clock",
          label: "Open payment clock",
        },
        {
          labelKey: "cases.run_the_vob_payment_clock.step.dates.in.regime",
          label: "Chosen regime",
        },
      ],
      outputs: [
        {
          labelKey: "cases.run_the_vob_payment_clock.step.dates.out.due",
          label: "Due date",
        },
        {
          labelKey: "cases.run_the_vob_payment_clock.step.dates.out.final",
          label: "Final date for payment",
        },
        {
          labelKey: "cases.run_the_vob_payment_clock.step.dates.out.derivation",
          label: "Derivation you can quote",
        },
      ],
      titleKey: "cases.run_the_vob_payment_clock.step.dates.title",
      titleDefault: "Read the dates the regime computes",
      whatKey: "cases.run_the_vob_payment_clock.step.dates.what",
      whatDefault:
        "Read back the dates paragraph 16 VOB/B produces from the client receiving the pruefbare Aufstellung. The sum payable leads, the due date and the final date for payment sit under it, and the derivation spells out each date against the provision it came from, so every one of them can be quoted rather than asserted. On this regime the day the client received the Aufstellung stands as the due date and the twenty-first day after it as the final date for payment, which is the Faelligkeit of paragraph 16 (1) VOB/B. The Nachfrist you set after that day is not computed here and has to be minded by hand.",
      whyKey: "cases.run_the_vob_payment_clock.step.dates.why",
      whyDefault:
        "Deadlines that are typed in are deadlines that are typed in wrong, and a payment regime has more of them than anyone holds in their head. A derivation you can read out loud is what turns a phone call about a late payment into a quotable line. On a VOB/B clock the two notice rows stay empty, because VOB/B sets no payment notice and no pay-less notice, so there is nothing to serve and nothing to chase, only the money and the date it stops being on time.",
      moduleLabel: "Payment Clock",
      moduleLabelKey: "nav.payment_clock",
      to: "/payment-clock",
    },
    {
      id: "watch",
      icon: "AlertTriangle",
      inputs: [
        {
          labelKey: "cases.run_the_vob_payment_clock.step.watch.in.clocks",
          label: "Open clocks on the project",
        },
        {
          labelKey: "cases.run_the_vob_payment_clock.step.watch.in.finaldates",
          label: "Final dates for payment",
        },
      ],
      outputs: [
        {
          labelKey: "cases.run_the_vob_payment_clock.step.watch.out.overdue",
          label: "Overdue invoices flagged",
        },
        {
          labelKey: "cases.run_the_vob_payment_clock.step.watch.out.register",
          label: "Breach register rows",
        },
      ],
      titleKey: "cases.run_the_vob_payment_clock.step.watch.title",
      titleDefault: "Watch the clock count each deadline down",
      whatKey: "cases.run_the_vob_payment_clock.step.watch.what",
      whatDefault:
        "Come back to the list as the month runs. It says how many clocks the project carries and how many are past their final date, badges the overdue ones and fills the breach register underneath. Open an overdue one and the findings name the sum outstanding, the days it has run past the final date and the rate interest runs at.",
      whyKey: "cases.run_the_vob_payment_clock.step.watch.why",
      whyDefault:
        "Reading a clock is what writes its register, so a quiet register on a project nobody opens is telling you about the reading and not about the payments. Nobody misses a deadline on purpose; they miss it because the day it mattered looked like every other day. Under VOB/B the interest does not start by itself on the twenty-first day. It runs from the end of a Nachfrist you set in writing, or at the latest from the thirtieth day after the client received the invoice and its Aufstellung, when paragraph 16 (5) VOB/B puts the client in default without any reminder. The clock reading is what tells you which of those two days you are on.",
      moduleLabel: "Payment Clock",
      moduleLabelKey: "nav.payment_clock",
      to: "/payment-clock",
    },
    {
      id: "receivable",
      icon: "Banknote",
      inputs: [
        {
          labelKey: "cases.run_the_vob_payment_clock.step.receivable.in.claim",
          label: "Checked Abschlagsrechnung",
        },
        {
          labelKey: "cases.run_the_vob_payment_clock.step.receivable.in.overdue",
          label: "Overdue clocks",
        },
      ],
      outputs: [
        {
          labelKey: "cases.run_the_vob_payment_clock.step.receivable.out.invoice",
          label: "Receivable on the books",
        },
        {
          labelKey: "cases.run_the_vob_payment_clock.step.receivable.out.total",
          label: "Overdue total in the cash picture",
        },
      ],
      titleKey: "cases.run_the_vob_payment_clock.step.receivable.title",
      titleDefault: "Reconcile what was certified against what was asked",
      whatKey: "cases.run_the_vob_payment_clock.step.receivable.what",
      whatDefault:
        "Put the approved figure next to the figure you asked for and carry the difference forward. What is unpaid, and how long it has been unpaid, belongs in the accounts as a number rather than in a conversation.",
      whyKey: "cases.run_the_vob_payment_clock.step.receivable.why",
      whyDefault:
        "The gap between applied and certified is the health of the commercial relationship expressed as money, and it is only visible if somebody puts the two numbers side by side every period. Cumulatively it is also the single best predictor of a final account fight.",
      moduleLabel: "Finance",
      moduleLabelKey: "finance.title",
      to: "/projects/:projectId/finance",
    },
    {
      id: "escalate",
      icon: "Send",
      inputs: [
        {
          labelKey: "cases.run_the_vob_payment_clock.step.escalate.in.reading",
          label: "Clock reading",
        },
        {
          labelKey: "cases.run_the_vob_payment_clock.step.escalate.in.invoice",
          label: "Abschlagsrechnung",
        },
      ],
      outputs: [
        {
          labelKey: "cases.run_the_vob_payment_clock.step.escalate.out.letter",
          label: "Nachfrist letter on file",
        },
        {
          labelKey: "cases.run_the_vob_payment_clock.step.escalate.out.record",
          label: "Escalation record",
        },
      ],
      titleKey: "cases.run_the_vob_payment_clock.step.escalate.title",
      titleDefault: "Escalate with the record already assembled",
      whatKey: "cases.run_the_vob_payment_clock.step.escalate.what",
      whatDefault:
        "When the clock has run out, set the client a written Nachfrist under paragraph 16 (5) VOB/B, after which default interest runs at the paragraph 288 (2) BGB rate and you may suspend the works until you are paid. The record the steps above produced, dates, approvals and the documents themselves, is the case, and it is assembled already rather than reconstructed under time pressure.",
      whyKey: "cases.run_the_vob_payment_clock.step.escalate.why",
      whyDefault:
        "The difference between a claim that is paid and one that is argued about is almost never the merits. It is whether the dates and the documents were kept as the work happened, because reconstructing them afterwards is expensive and looks exactly like inventing them.",
      moduleLabel: "Documents",
      moduleLabelKey: "nav.documents",
      to: "/projects/:projectId/files",
    },
  ],
};

export default playbook;
