// DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
// Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
//
// Case: "Serve a payment claim under the Construction Contracts Act" (NZ).
//
// GENERATED. Do not edit this file by hand, the next compose run
// will overwrite it. The workflow lives once at
//   frontend/src/features/cases/intl/spines/f01-progress-payment.json
// and this country's words and step order live at
//   frontend/src/features/cases/intl/layers/f01-progress-payment/NZ.json
//
// New Zealand is the clearest case in the family for why the document
// that states the value and the document that asks for the money are
// two slots and not one. The progress valuation is what the period is
// worth; the payment claim is the statutory document served under the
// Act, and serving it is what starts the clock. Naming the tax invoice
// as the payment document instead composed a true sentence about the
// wrong document, because the Act attaches to the claim and the
// invoice only follows it for GST.
//
// Rebuild with:
//   node frontend/scripts/compose-case-layers.mjs --family f01-progress-payment

import type { Playbook } from "../types";

const playbook: Playbook = {
  id: "serve-a-payment-claim-under-the-construction-contracts-act",
  order: 1280,
  region: "NZ",
  category: "commercial",
  companyTypes: ["general-contractor", "subcontractor", "cost-consultant"],
  roles: ["contract-administrator", "commercial-manager", "quantity-surveyor"],
  icon: "Clock",
  titleKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.title",
  titleDefault: "Serve a payment claim under the Construction Contracts Act",
  descKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.desc",
  descDefault:
    "Measure the period against the schedule, serve the payment claim, watch the working days the payer has to answer with a payment schedule, raise the tax invoice for the scheduled amount and keep retentions where the Act requires them to be kept.",
  longDescKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.longdesc",
  longDescDefault:
    "The Construction Contracts Act gives a payer a fixed number of working days to answer a payment claim with a payment schedule, and the consequence of not answering is not a penalty, it is that the claimed amount becomes payable. That is a strong remedy and it is available only to a claimant who can show the claim complied and when it was served. The second half of the regime is retentions: money withheld on a commercial construction contract is held on trust and has to be accounted for separately, which is a records question long before it is a cash question. Both halves are the same discipline, which is knowing what was served, when, and what came back.",
  estMinutes: 12,
  steps: [
    {
      id: "measure",
      icon: "Ruler",
      inputs: [
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.measure.in.schedule",
          label: "Contract schedule",
        },
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.measure.in.works",
          label: "Work executed this period",
        },
      ],
      outputs: [
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.measure.out.percent",
          label: "Percent complete per schedule item",
        },
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.measure.out.quantities",
          label: "Earned quantities for the period",
        },
      ],
      titleKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.measure.title",
      titleDefault: "Measure the period schedule item by schedule item",
      whatKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.measure.what",
      whatDefault:
        "Record what was executed against each schedule item for the period as a percentage of its contract quantity. The earned quantity follows from that percentage and the design quantity, and the earned amount from the same percentage and the position total, so one honest number per line produces the whole valuation.",
      whyKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.measure.why",
      whyDefault:
        "A progress valuation built from a single project percentage cannot be checked and therefore cannot be approved without a conversation. Measured line by line, the disagreement is about one schedule item rather than about the whole month, and the rest of the money moves while that one is settled.",
      moduleLabel: "Progress",
      moduleLabelKey: "nav.progress",
      to: "/progress",
    },
    {
      id: "value",
      icon: "Calculator",
      inputs: [
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.value.in.quantities",
          label: "Earned quantities for the period",
        },
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.value.in.rates",
          label: "Contract rates",
        },
      ],
      outputs: [
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.value.out.claim",
          label: "Progress valuation for the period",
        },
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.value.out.variations",
          label: "Variations flagged",
        },
      ],
      titleKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.value.title",
      titleDefault: "Value it at the contract rates",
      whatKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.value.what",
      whatDefault:
        "Read the valuation back against the bill and check the rates it used are the contract rates. Where a schedule item has been measured past the quantity the contract carries, deal with it as a change to the position with an order behind it rather than as a larger figure on the same line.",
      whyKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.value.why",
      whyDefault:
        "A variation certified quietly is one the client can refuse at the final account, months after the work was built and paid for down the chain. Raising it as a change while it is small is the only version of that conversation where you are not asking to be paid for work already done.",
      moduleLabel: "BOQ",
      moduleLabelKey: "boq.title",
      to: "/projects/:projectId/boq",
    },
    {
      id: "retentions",
      icon: "Percent",
      inputs: [
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.retentions.in.cumulative",
          label: "Cumulative progress valuation",
        },
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.retentions.in.previous",
          label: "Previous payments and retentions",
        },
      ],
      outputs: [
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.retentions.out.held",
          label: "Retentions held to date",
        },
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.retentions.out.net",
          label: "Net due for the period",
        },
      ],
      titleKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.retentions.title",
      titleDefault: "Apply retentions and previous payments",
      whatKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.retentions.what",
      whatDefault:
        "Take the cumulative valuation, subtract what has already been certified, and apply retentions at the contract percentage. The figure that leaves this step is the one the payment claim is raised for, and the backup behind it is the measure that produced it.",
      whyKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.retentions.why",
      whyDefault:
        "Interim payments are cumulative, so the month's money is a difference between two totals rather than a total of its own. Computing it from the cumulative figure is what stops a line being paid twice or dropped entirely when a period is re-measured. Retention money on a commercial construction contract is held on trust and has to be identifiable as such. A figure that exists only as a deduction line on a claim is not identifiable, and the party who needs it to be is the one who is not holding it.",
      moduleLabel: "Finance",
      moduleLabelKey: "nav.finance",
      to: "/projects/:projectId/finance",
    },
    {
      id: "serve",
      icon: "ReceiptText",
      inputs: [
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.serve.in.claim",
          label: "Progress valuation for the period",
        },
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.serve.in.net",
          label: "Net due for the period",
        },
      ],
      outputs: [
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.serve.out.served",
          label: "Payment claim served",
        },
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.serve.out.invoice",
          label: "Tax invoice issued",
        },
      ],
      titleKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.serve.title",
      titleDefault: "Issue the payment claim against the approved figure",
      whatKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.serve.what",
      whatDefault:
        "Raise the payment claim against the approved progress valuation, carrying retentions and any deduction the contract provides for, and reference the progress valuation on it. The claim has to state that it is made under the Act and say how the amount was calculated. A claim that does neither is a request for money rather than a payment claim, and it carries none of the Act's consequences for ignoring it. The tax invoice follows for GST and is not the document the Act counts from.",
      whyKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.serve.why",
      whyDefault:
        "A demand for a figure nobody approved is one that will be returned, and the clock does not start on a returned document. Matching it to the progress valuation also means the accounts and the valuation tell the same story at year end without anybody reconciling them by hand.",
      moduleLabel: "Finance",
      moduleLabelKey: "nav.finance",
      to: "/projects/:projectId/finance",
    },
    {
      id: "openclock",
      icon: "Clock",
      inputs: [
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.openclock.in.served",
          label: "Payment claim served",
        },
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.openclock.in.date",
          label: "Date of service",
        },
      ],
      outputs: [
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.openclock.out.clock",
          label: "Open payment clock",
        },
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.openclock.out.due",
          label: "Due date computed",
        },
      ],
      titleKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.openclock.title",
      titleDefault: "Open the payment clock on the right day",
      whatKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.openclock.what",
      whatDefault:
        "Open a clock over the payment claim starting from the day the payment claim is served, under the Construction Contracts Act. Payment falls due 20 working days later, and the clock records that date rather than leaving it to be worked out when somebody asks.",
      whyKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.openclock.why",
      whyDefault:
        "The single most expensive mistake in interim payment is starting the count on the wrong event, because every deadline behind it inherits the error and none of them look wrong. Anchoring on the day the payment claim is served once makes the whole chain checkable.",
      moduleLabel: "Payment Clock",
      moduleLabelKey: "nav.payment_clock",
      to: "/payment-clock",
    },
    {
      id: "dates",
      icon: "CalendarClock",
      inputs: [
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.dates.in.clock",
          label: "Open payment clock",
        },
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.dates.in.regime",
          label: "Statutory regime on record",
        },
      ],
      outputs: [
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.dates.out.schedule",
          label: "Date a payment schedule is due",
        },
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.dates.out.final",
          label: "Final date for payment",
        },
      ],
      titleKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.dates.title",
      titleDefault: "Read the dates the regime computes",
      whatKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.dates.what",
      whatDefault:
        "Read back the dates the Construction Contracts Act produces from the day the payment claim is served. The sum payable leads, the due date and the final date for payment sit under it, and the derivation spells out each date against the provision it came from, so every one of them can be quoted rather than asserted. Working days exclude weekends, public holidays and the year-end closedown the Act sets out, which is why a December claim does not answer on the same arithmetic as a June one.",
      whyKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.dates.why",
      whyDefault:
        "Deadlines that are typed in are deadlines that are typed in wrong, and a payment regime has more of them than anyone holds in their head. A derivation you can read out loud is what turns a phone call about a late payment into a quotable line.",
      moduleLabel: "Payment Clock",
      moduleLabelKey: "nav.payment_clock",
      to: "/payment-clock",
    },
    {
      id: "watch",
      icon: "AlertTriangle",
      inputs: [
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.watch.in.clocks",
          label: "Open clocks on the project",
        },
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.watch.in.finaldates",
          label: "Final dates for payment",
        },
      ],
      outputs: [
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.watch.out.unanswered",
          label: "Claims answered by no payment schedule",
        },
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.watch.out.register",
          label: "Breach register rows",
        },
      ],
      titleKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.watch.title",
      titleDefault: "Watch the clock count each deadline down",
      whatKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.watch.what",
      whatDefault:
        "Come back to the list as the month runs. It says how many clocks the project carries and how many are past their final date, badges the overdue ones and fills the breach register underneath. Open an overdue one and the findings name the sum outstanding, the days it has run past the final date and the rate interest runs at.",
      whyKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.watch.why",
      whyDefault:
        "Reading a clock is what writes its register, so a quiet register on a project nobody opens is telling you about the reading and not about the payments. Nobody misses a deadline on purpose; they miss it because the day it mattered looked like every other day. A claim nobody answered is worth more than a claim answered badly, and it looks like nothing at all until somebody counts the days. That is the one reading on this screen that turns silence into an amount payable.",
      moduleLabel: "Payment Clock",
      moduleLabelKey: "nav.payment_clock",
      to: "/payment-clock",
    },
    {
      id: "escalate",
      icon: "Gavel",
      inputs: [
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.escalate.in.passed",
          label: "Passed deadlines",
        },
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.escalate.in.record",
          label: "Claims, schedules and service dates",
        },
      ],
      outputs: [
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.escalate.out.notice",
          label: "Notice of intention to suspend",
        },
        {
          labelKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.escalate.out.entitlement",
          label: "Entitlement preserved",
        },
      ],
      titleKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.escalate.title",
      titleDefault: "Escalate with the record already assembled",
      whatKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.escalate.what",
      whatDefault:
        "When the clock has run out, give notice of intention to suspend and refer it to adjudication. The record the steps above produced, dates, approvals and the documents themselves, is the case, and it is assembled already rather than reconstructed under time pressure.",
      whyKey: "cases.serve_a_payment_claim_under_the_construction_contracts_act.step.escalate.why",
      whyDefault:
        "The difference between a claim that is paid and one that is argued about is almost never the merits. It is whether the dates and the documents were kept as the work happened, because reconstructing them afterwards is expensive and looks exactly like inventing them.",
      moduleLabel: "Documents",
      moduleLabelKey: "nav.documents",
      to: "/projects/:projectId/files",
    },
  ],
};

export default playbook;
