# DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
# Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
"""NCR ORM models.

Tables:
    oe_ncr_ncr - non-conformance reports with root cause analysis and corrective actions
"""

import uuid
from decimal import Decimal

from sqlalchemy import JSON, ForeignKey, Integer, Numeric, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from app.database import GUID, Base


class NCR(Base):
    """A Non-Conformance Report with root cause analysis and corrective/preventive actions."""

    __tablename__ = "oe_ncr_ncr"
    # Per-project uniqueness of the human-facing NCR-NNN number. The number is
    # generated by MAX(suffix)+1, which races under concurrent creates; this
    # constraint is the backstop that forces a retry instead of a duplicate.
    __table_args__ = (UniqueConstraint("project_id", "ncr_number", name="uq_oe_ncr_ncr_project_number"),)

    project_id: Mapped[uuid.UUID] = mapped_column(
        GUID(),
        ForeignKey("oe_projects_project.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    ncr_number: Mapped[str] = mapped_column(String(20), nullable=False)
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    ncr_type: Mapped[str] = mapped_column(String(50), nullable=False)
    severity: Mapped[str] = mapped_column(String(20), nullable=False)
    root_cause: Mapped[str | None] = mapped_column(Text, nullable=True)
    root_cause_category: Mapped[str | None] = mapped_column(String(100), nullable=True)
    corrective_action: Mapped[str | None] = mapped_column(Text, nullable=True)
    preventive_action: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="identified", index=True)
    cost_impact: Mapped[str | None] = mapped_column(String(50), nullable=True)
    schedule_impact_days: Mapped[int | None] = mapped_column(Integer, nullable=True)
    location_description: Mapped[str | None] = mapped_column(String(500), nullable=True)
    # Where the non-conformity actually is, in WGS84. ``location_description``
    # has always been able to say "grid B4, level 2", which reads well in a
    # report and cannot be drawn on a map. These three are nullable on purpose:
    # NULL means nobody recorded a position, which is honestly different from
    # 0/0 (a real position in the Gulf of Guinea) and is what every row that
    # predates this column carries. Same Numeric(10, 7) as ``GeoAnchor`` so a
    # pin and an anchor round-trip at the same precision.
    location_lat: Mapped[Decimal | None] = mapped_column(Numeric(10, 7), nullable=True)
    location_lon: Mapped[Decimal | None] = mapped_column(Numeric(10, 7), nullable=True)
    # Horizontal accuracy in metres, as reported by whatever took the fix -
    # a phone GPS is tens of metres, a survey instrument is centimetres.
    # NULL means the accuracy was not reported, not that it was perfect.
    location_accuracy_m: Mapped[Decimal | None] = mapped_column(Numeric(6, 2), nullable=True)
    linked_inspection_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    change_order_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    # When an NCR is auto-raised from a critical clash, this carries the
    # originating ``ClashResult.id`` so the rows stay traceable and the
    # auto-creation is idempotent on the same clash. Nullable + no
    # server_default: absent means "not clash-sourced".
    clash_result_id: Mapped[str | None] = mapped_column(String(36), nullable=True, index=True)
    created_by: Mapped[str | None] = mapped_column(String(36), nullable=True)
    metadata_: Mapped[dict] = mapped_column(  # type: ignore[assignment]
        "metadata",
        JSON,
        nullable=False,
        default=dict,
        server_default="{}",
    )

    def __repr__(self) -> str:
        return f"<NCR {self.ncr_number} - {self.title[:40]} ({self.status})>"
